import { ToolRegistry, type Tool, type ToolContext } from "../services/tools/toolRegistry.js";
import { CloudAndroidOrchestrator } from "./orchestrator.service.js";
import { CloudAndroidUiActionSchema } from "@windels/shared/cloudAndroid";

function actor(context: ToolContext) {
  if (!context.organizationId || !context.userId || !context.agentId) throw new Error("Cloud Android tools require authenticated organization, user, and agent context");
  return { organizationId: context.organizationId, userId: context.userId, agentId: context.agentId };
}
function tool(name: string, description: string, parameters: any, required: string[], execute: Tool["execute"], sideEffects = true): Tool {
  return { definition: { name, description, category: "cloud-android", parameters, required, hasSideEffects: sideEffects, timeoutMs: 130_000 }, execute };
}
const tools: Tool[] = [
  tool("cloud_android_device_list", "List Cloud Android devices visible to the agent's organization.", {}, [], async (_p, c) => ({ success: true, data: await CloudAndroidOrchestrator.listDevices(actor(c)) }), false),
  tool("cloud_android_device_get", "Get one Cloud Android device and its current control/session state.", { deviceId: { type: "string", description: "WINDELS device ID" } }, ["deviceId"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.getDevice(actor(c), p.deviceId) }), false),
  tool("cloud_android_screen_inspect", "Observe the Android screenshot, semantic elements, accessibility tree, app, window, and device state.", { deviceId: { type: "string", description: "WINDELS device ID" } }, ["deviceId"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.observe(actor(c), p.deviceId) }), false),
  tool("cloud_android_ui_tap", "Prepare, policy-check, execute, re-observe and verify a semantic or coordinate tap. Sensitive effects pause for human approval.", { deviceId: { type: "string", description: "Device ID" }, sessionId: { type: "string", description: "Active AI/collaborative session ID" }, elementId: { type: "string", description: "Preferred semantic element ID" }, x: { type: "number", description: "Fallback x coordinate" }, y: { type: "number", description: "Fallback y coordinate" }, intendedAction: { type: "string", description: "Expected effect" } }, ["deviceId", "sessionId"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.executeUiAction(actor(c), p.deviceId, p.sessionId, CloudAndroidUiActionSchema.parse({ type: "tap", elementId: p.elementId, x: p.x, y: p.y, intendedAction: p.intendedAction })) })),
  tool("cloud_android_ui_type", "Type into an approved Android UI target and verify the resulting screen state.", { deviceId: { type: "string", description: "Device ID" }, sessionId: { type: "string", description: "Session ID" }, elementId: { type: "string", description: "Editable semantic element" }, text: { type: "string", description: "Text to enter" }, replace: { type: "boolean", description: "Replace existing text" } }, ["deviceId", "sessionId", "text"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.executeUiAction(actor(c), p.deviceId, p.sessionId, CloudAndroidUiActionSchema.parse({ type: "type", elementId: p.elementId, text: p.text, replace: !!p.replace })) })),
  tool("cloud_android_ui_swipe", "Swipe on Android through an active agent control session and verify the result.", { deviceId: { type: "string", description: "Device ID" }, sessionId: { type: "string", description: "Session ID" }, startX: { type: "number", description: "Start x" }, startY: { type: "number", description: "Start y" }, endX: { type: "number", description: "End x" }, endY: { type: "number", description: "End y" } }, ["deviceId", "sessionId", "startX", "startY", "endX", "endY"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.executeUiAction(actor(c), p.deviceId, p.sessionId, CloudAndroidUiActionSchema.parse({ type: "swipe", startX: p.startX, startY: p.startY, endX: p.endX, endY: p.endY, durationMs: 300 })) })),
  tool("cloud_android_app_launch", "Launch an installed Android application through the prepared-action policy gate.", { deviceId: { type: "string", description: "Device ID" }, sessionId: { type: "string", description: "Session ID" }, packageName: { type: "string", description: "Android package name" } }, ["deviceId", "sessionId", "packageName"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.executeManagedAction(actor(c), p.deviceId, p.sessionId, "app.launch", { packageName: p.packageName }) })),
  tool("cloud_android_session_start", "Start an AI control session after confirming the agent has a device grant.", { deviceId: { type: "string", description: "Device ID" }, mode: { type: "string", description: "AI or COLLABORATIVE", enum: ["AI", "COLLABORATIVE"] } }, ["deviceId", "mode"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.startSession(actor(c), p.deviceId, { mode: p.mode, agentId: c.agentId }) })),
  tool("cloud_android_session_end", "End the current Cloud Android session, release the device lock, and meter actual runtime.", { sessionId: { type: "string", description: "Session ID" } }, ["sessionId"], async (p, c) => ({ success: true, data: await CloudAndroidOrchestrator.endSession(actor(c), p.sessionId, { completedBy: "agent" }) })),
];
for (const registered of tools) ToolRegistry.register(registered);
export const CLOUD_ANDROID_TOOL_NAMES = tools.map((item) => item.definition.name);
