/**
 * Session 144 — Politics seed (part 4): ideologies (§13), movements (§14),
 * international organizations (§16), government forms (§12), and policy
 * records (§21/§22/§23/§24/§28).
 */
import type {
  GovernmentFormRecord,
  IdeologyRecord,
  InternationalOrgRecord,
  MovementRecord,
} from "@windels/shared";
import {
  buildForm,
  buildIdeology,
  buildMovement,
  buildOrg,
  SRC_ACADEMIC,
  SRC_ARCHIVE,
  SRC_GOVT,
  SRC_UN,
} from "./politics.catalog.js";

/* ════════════════════════════════════════════════════════════════════════════
 * §13 — Political ideologies (taught academically, never advocated)
 * ════════════════════════════════════════════════════════════════════════════ */

export const IDEOLOGIES: IdeologyRecord[] = [
  buildIdeology({
    id: "pol.ideo.liberalism",
    name: "Liberalism",
    family: "Modern political ideologies",
    definition: "A political philosophy centered on individual liberty, equality before the law, constitutional government, and (in its modern forms) free markets and human rights.",
    origins: "The Enlightenment and the English, American and French revolutions; Locke, Montesquieu, Smith and Mill are foundational thinkers.",
    coreIdeas: "Individual rights, the rule of law, limited government, consent of the governed, free expression, and (in social liberalism) a role for the state in ensuring opportunity.",
    keyThinkers: ["John Locke", "Adam Smith", "John Stuart Mill", "Isaiah Berlin"],
    historicalRole: "The ideology of the democratic revolutions and of modern constitutional democracy; liberalism's varieties (classical vs social) frame much of Western politics.",
    variants: "Classical liberalism, social liberalism, neoliberalism, liberal internationalism.",
    criticism: "Critics on the left argue liberalism tolerates inequality; critics on the right argue it erodes tradition and community.",
    summary: "Liberalism is the political philosophy of individual liberty, rights and constitutional government.",
    simple: "Liberalism is the idea that people should be free and equal, with a government that protects their rights.",
  }),
  buildIdeology({
    id: "pol.ideo.conservatism",
    name: "Conservatism",
    family: "Modern political ideologies",
    definition: "A political philosophy valuing tradition, order, established institutions, and gradual change over radical reform.",
    origins: "Developed as a response to the French Revolution (Burke's Reflections, 1790); evolved through the 19th–20th centuries.",
    coreIdeas: "Respect for established institutions (family, religion, nation), skepticism of utopian schemes, the importance of order and authority, and (in modern forms) free markets and traditional values.",
    keyThinkers: ["Edmund Burke", "Joseph de Maistre", "Michael Oakeshott"],
    historicalRole: "The governing ideology of most 19th–20th-century European and American right-of-center parties.",
    variants: "Traditionalist, liberal-conservative, social-conservative, national-conservative.",
    criticism: "Critics argue conservatism defends privilege and resists necessary change.",
    summary: "Conservatism values tradition, order and gradual change, and is typically the ideology of right-of-center parties.",
    simple: "Conservatism is the idea that society should keep its traditions and change slowly and carefully.",
  }),
  buildIdeology({
    id: "pol.ideo.socialism",
    name: "Socialism",
    family: "Modern political ideologies",
    definition: "A family of economic and political ideas holding that the means of production should be owned or controlled by the community or the state, to reduce inequality and serve social needs.",
    origins: "19th-century Europe, in response to industrialization; the term's first uses were in the 1820s–30s.",
    coreIdeas: "Collective or public ownership, equality, solidarity, and the critique of capitalism's inequalities.",
    keyThinkers: ["Karl Marx", "Friedrich Engels", "Eduard Bernstein", "Rosa Luxemburg"],
    historicalRole: "Shaped the labor movement, social democracy, and the communist states of the 20th century.",
    variants: "Democratic socialism, social democracy, revolutionary socialism, market socialism, African socialism.",
    criticism: "Critics argue state control reduces efficiency and liberty; socialists reply that inequality and exploitation are worse.",
    summary: "Socialism is the family of ideas holding that economic life should serve social needs through collective or public control.",
    simple: "Socialism says that important things like factories and banks should belong to everyone together, not just a few owners.",
  }),
  buildIdeology({
    id: "pol.ideo.social-democracy",
    name: "Social democracy",
    family: "Modern political ideologies",
    definition: "A reformist current of socialism that works within democracy and markets, using the welfare state, regulation and collective bargaining to reduce inequality.",
    origins: "Late 19th-century European socialism; consolidated after 1945 in Western Europe.",
    coreIdeas: "Democratic reform rather than revolution, universal welfare, strong labor rights, and a regulated market economy.",
    keyThinkers: ["Eduard Bernstein", "Karl Kautsky", "Olof Palme"],
    historicalRole: "Built the post-war European welfare states (the Nordic model, the German SPD, the British Labour left).",
    variants: "Nordic social democracy, Third Way (centrist adaptations).",
    criticism: "Marxists call it a compromise with capitalism; the right argues it taxes and regulates too much.",
    summary: "Social democracy uses democracy and markets with a strong welfare state to reduce inequality.",
    simple: "Social democracy is the idea that capitalism can be made fairer with taxes, welfare and workers' rights.",
  }),
  buildIdeology({
    id: "pol.ideo.communism",
    name: "Communism",
    family: "Modern political ideologies",
    definition: "A revolutionary ideology aiming at a classless, stateless society in which the means of production are communally owned; in practice, the ideology of 20th-century one-party states.",
    origins: "Marx and Engels' Communist Manifesto (1848); the Bolshevik seizure of power (1917) made it a state ideology.",
    coreIdeas: "Historical materialism, class struggle, the abolition of private ownership of the means of production, and the dictatorship of the proletariat (in Leninist practice).",
    keyThinkers: ["Karl Marx", "Friedrich Engels", "Vladimir Lenin", "Mao Zedong"],
    historicalRole: "Governed the Soviet Union, China, and other states; shaped the Cold War's ideological divide.",
    variants: "Marxism-Leninism, Maoism, Stalinism, Eurocommunism, Trotskyism.",
    criticism: "Liberal and conservative critics document the authoritarianism, famine and repression of communist states; communists respond that these were distortions.",
    summary: "Communism is the revolutionary ideology of a classless society, which in the 20th century became the ideology of one-party states from the USSR to China.",
    simple: "Communism is a radical idea that everyone should own things together and there should be no rich or poor classes. Communist parties ruled the Soviet Union and China.",
  }),
  buildIdeology({
    id: "pol.ideo.marxism",
    name: "Marxism",
    family: "Socialist traditions",
    definition: "The social theory of Karl Marx: history is driven by class struggle, capitalism contains internal contradictions, and socialism is its predicted successor.",
    origins: "Marx's writings of the 1840s–1880s.",
    coreIdeas: "Historical materialism, the labor theory of value, class conflict, and revolution as the engine of historical change.",
    keyThinkers: ["Karl Marx", "Friedrich Engels"],
    historicalRole: "The intellectual foundation of communist parties and much of 20th-century social science.",
    variants: "Orthodox Marxism, Western Marxism, analytical Marxism, Marxian economics.",
    criticism: "Critics argue its predictions failed and its economics is flawed; Marxists dispute the readings.",
    summary: "Marxism is Marx's theory of history and capitalism — the foundation of modern socialism's revolutionary wing.",
    simple: "Marxism is the theory of Karl Marx that history is driven by rich versus poor, and that capitalism will be replaced.",
  }),
  buildIdeology({
    id: "pol.ideo.leninism",
    name: "Leninism",
    family: "Socialist traditions",
    definition: "Vladimir Lenin's adaptation of Marxism for the 20th century: a disciplined vanguard party, the seizure of power, and the 'dictatorship of the proletariat'.",
    origins: "Lenin's writings of 1902–1924; realized in the 1917 Russian Revolution.",
    coreIdeas: "The vanguard party, democratic centralism, imperialism as the highest stage of capitalism, and the revolutionary state.",
    keyThinkers: ["Vladimir Lenin"],
    historicalRole: "The operating ideology of the Soviet state and of communist parties worldwide.",
    variants: "Marxism-Leninism (the Stalin-era synthesis), Maoism.",
    criticism: "Critics document its one-party authoritarianism; Leninists see it as the science of revolution.",
    summary: "Leninism is Lenin's theory of the vanguard party and revolutionary state — the basis of 20th-century communism's practice.",
    simple: "Leninism is Lenin's version of Marxism: a small, strict party leads the revolution and then the state.",
  }),
  buildIdeology({
    id: "pol.ideo.marxism-leninism",
    name: "Marxism-Leninism",
    family: "Socialist traditions",
    definition: "The official ideology of the Soviet Union and its allied states: Marxism as codified by Lenin and Stalin into a state doctrine of one-party rule and planned economy.",
    origins: "Codified in the 1920s–30s after Lenin's death; the official ideology of the USSR and the Comintern.",
    coreIdeas: "The vanguard party's monopoly of power, the planned economy, and the leading role of the party in every sphere.",
    keyThinkers: ["Vladimir Lenin", "Joseph Stalin"],
    historicalRole: "Governing ideology of the Soviet bloc and of China's Maoist era.",
    criticism: "Documented criticisms include totalitarianism, the gulag, and economic inefficiency.",
    summary: "Marxism-Leninism was the Soviet bloc's official ideology of one-party rule and the planned economy.",
    simple: "Marxism-Leninism was the official belief system of the Soviet Union — one party running everything.",
  }),
  buildIdeology({
    id: "pol.ideo.anarchism",
    name: "Anarchism",
    family: "Modern political ideologies",
    definition: "A political philosophy that rejects the state and all coercive hierarchy, advocating voluntary, self-governing association.",
    origins: "19th-century Europe (Proudhon, Bakunin, Kropotkin); the term's first political use was Proudhon's 1840 claim that 'property is theft'.",
    coreIdeas: "Statelessness, voluntary association, mutual aid, direct action, and opposition to concentrated power.",
    keyThinkers: ["Pierre-Joseph Proudhon", "Mikhail Bakunin", "Peter Kropotkin", "Emma Goldman"],
    historicalRole: "A persistent radical current within labor and anti-authoritarian movements (Spanish anarchism, contemporary anarcho-syndicalism).",
    variants: "Anarcho-communism, anarcho-syndicalism, mutualism, anarcho-capitalism (a market variant most anarchists reject).",
    criticism: "Critics argue anarchism offers no workable order; anarchists reply that hierarchy is the source of the problem.",
    summary: "Anarchism rejects the state and hierarchy in favor of voluntary self-government.",
    simple: "Anarchism is the belief that governments are unnecessary and people can organize freely without them.",
  }),
  buildIdeology({
    id: "pol.ideo.libertarianism",
    name: "Libertarianism",
    family: "Modern political ideologies",
    definition: "A political philosophy maximizing individual liberty and minimizing the state, especially in economic life: strong property rights, free markets, and a minimal state.",
    origins: "19th-century classical liberalism, revived by 20th-century thinkers (Hayek, Friedman, Nozick, Rothbard).",
    coreIdeas: "Self-ownership, the non-aggression principle, free markets, and opposition to taxation and regulation.",
    keyThinkers: ["Friedrich Hayek", "Milton Friedman", "Robert Nozick", "Murray Rothbard"],
    historicalRole: "Influenced the late-20th-century wave of deregulation and the modern right's economic program.",
    variants: "Minarchism, anarcho-capitalism, left-libertarianism.",
    criticism: "Critics argue it ignores market failures and inequality; libertarians reply that state intervention causes them.",
    summary: "Libertarianism maximizes individual liberty and minimizes the state, especially in economic life.",
    simple: "Libertarianism says the government should be as small as possible and people should be free to make their own choices.",
  }),
  buildIdeology({
    id: "pol.ideo.nationalism",
    name: "Nationalism",
    family: "Modern political ideologies",
    definition: "The doctrine that the nation is the natural unit of political community, and that the nation should have its own state and self-determination.",
    origins: "18th–19th-century Europe and the Americas; spread worldwide with decolonization.",
    coreIdeas: "National identity, self-determination, sovereignty, and (in civic forms) shared citizenship rather than ethnicity.",
    keyThinkers: ["Johann Gottlieb Fichte", "Giuseppe Mazzini", "Ernest Renan"],
    historicalRole: "Built the modern nation-state, drove unification (Italy, Germany), decolonization, and also ethnic conflict.",
    variants: "Civic nationalism, ethnic nationalism, liberal nationalism, expansionist nationalism.",
    criticism: "Critics document nationalism's role in war and exclusion; defenders see it as the basis of democracy and self-rule.",
    summary: "Nationalism holds that nations should govern themselves — the force behind both modern democracy and modern conflict.",
    simple: "Nationalism is the belief that each nation of people should have its own country and govern itself.",
  }),
  buildIdeology({
    id: "pol.ideo.pan-africanism",
    name: "Pan-Africanism",
    family: "African political philosophies",
    definition: "The movement and ideology of African unity and solidarity: the belief that African peoples, on the continent and in the diaspora, share a common destiny and should unite politically, culturally and economically.",
    origins: "Late 19th-century diaspora thinkers (Crummell, Blyden); the 1900 London conference; the 1945 Manchester Congress; the OAU's founding (1963).",
    coreIdeas: "African self-determination, the end of colonialism and racism, continental unity, and the revaluation of African culture and history.",
    keyThinkers: ["W.E.B. Du Bois", "Marcus Garvey", "Kwame Nkrumah", "Julius Nyerere", "George Padmore"],
    historicalRole: "Ideological engine of decolonization; founded the OAU (1963) and its successor, the African Union (2002).",
    variants: "Continental unionism, regional integration (ECOWAS, AU Agenda 2063), diaspora pan-Africanism.",
    criticism: "Critics note the gap between unity rhetoric and the reality of 54 separate states; supporters point to the AU's institutions.",
    summary: "Pan-Africanism is the ideology of African unity and self-determination that powered decolonization and founded the African Union.",
    simple: "Pan-Africanism is the idea that all African people, at home and abroad, should work together for freedom and unity.",
  }),
  buildIdeology({
    id: "pol.ideo.environmentalism",
    name: "Environmentalism / Green politics",
    family: "Modern political ideologies",
    definition: "A political movement and ideology prioritizing environmental protection, sustainability, and (in party form) Green politics with ecological and social-justice goals.",
    origins: "The 1960s–70s environmental movement (Silent Spring, 1962; the first Earth Day, 1970); Green parties from the 1970s–80s.",
    coreIdeas: "Ecological limits, sustainability, intergenerational justice, and the precautionary principle.",
    keyThinkers: ["Rachel Carson", "Arne Naess", "Gro Harlem Brundtland"],
    historicalRole: "Produced environmental law, the climate regime (the Paris Agreement), and Green parties in dozens of countries.",
    variants: "Deep ecology, eco-socialism, eco-feminism, liberal environmentalism, Green conservatism.",
    criticism: "Critics argue strong environmentalism burdens growth; Greens reply that ecological collapse is the greater cost.",
    summary: "Environmentalism prioritizes protecting the natural world — from a reformist movement to the Green parties of today.",
    simple: "Environmentalism is the movement to protect nature, fight pollution and stop climate change.",
  }),
  buildIdeology({
    id: "pol.ideo.feminism",
    name: "Feminist political theory",
    family: "Modern political ideologies",
    definition: "The body of political thought analyzing gender inequality and advocating women's rights, representation and liberation.",
    origins: "The 18th-century Enlightenment (Wollstonecraft, 1792); the suffrage movements; the 20th-century women's liberation movement.",
    coreIdeas: "Equal rights and citizenship, reproductive freedom, the critique of patriarchy, and intersectionality (in modern theory).",
    keyThinkers: ["Mary Wollstonecraft", "Simone de Beauvoir", "bell hooks", "Chimamanda Ngozi Adichie"],
    historicalRole: "Won suffrage, legal equality and representation; reshaped labor, family and political life worldwide.",
    variants: "Liberal feminism, radical feminism, socialist feminism, intersectional feminism, African feminism.",
    criticism: "Conservative critics argue it disrupts family and tradition; internal debates concern strategy and inclusion.",
    summary: "Feminist political theory analyzes and challenges gender inequality — from suffrage to modern intersectional theory.",
    simple: "Feminism is the movement for equal rights and opportunities for women.",
  }),
  buildIdeology({
    id: "pol.ideo.populism",
    name: "Populism",
    family: "Modern political ideologies",
    definition: "A political style and thin-centered ideology that pits 'the people' against a corrupt or self-serving 'elite', claiming to speak for the common person against the establishment.",
    origins: "19th-century American and Russian agrarian movements; recurrent waves in the 20th–21st centuries.",
    coreIdeas: "The pure people vs the corrupt elite, anti-establishment rhetoric, direct connection with the leader, and majoritarian claims.",
    keyThinkers: ["No single canon; theorists of populism: Ernesto Laclau, Cas Mudde, Jan-Werner Müller"],
    historicalRole: "Appears across left and right (e.g. Peronism, Trumpism, European right-populism) and across democracies and autocracies.",
    variants: "Left populism, right populism, technocratic populism.",
    criticism: "Critics argue populism endangers liberal institutions; populists reply that elites have failed the people.",
    summary: "Populism pits 'the people' against 'the elite' — a recurring style across left and right, democracies and autocracies.",
    simple: "Populism is a style of politics that says ordinary people versus the powerful elite — used by many different leaders.",
  }),
  buildIdeology({
    id: "pol.ideo.monarchism",
    name: "Monarchism",
    family: "Traditional political doctrines",
    definition: "The doctrine that monarchy — rule by a king, queen, emperor or similar hereditary or dynastic head of state — is a legitimate or preferable form of government.",
    origins: "As old as the state itself; modern monarchism responded to the republican revolutions.",
    coreIdeas: "Continuity, tradition, and the unifying role of a head of state above partisan politics.",
    keyThinkers: ["Joseph de Maistre", "Robert Filmer"],
    historicalRole: "The default form of government until the modern era; today it survives as constitutional monarchy in many democracies.",
    variants: "Absolute monarchy, constitutional monarchy, elective monarchy.",
    criticism: "Republicans argue hereditary rule contradicts equality and democracy.",
    summary: "Monarchism is the doctrine favoring monarchy; today it survives mainly as constitutional monarchy.",
    simple: "Monarchism is the belief that a king or queen should rule. Some countries still have kings and queens.",
  }),
  buildIdeology({
    id: "pol.ideo.republicanism",
    name: "Republicanism",
    family: "Modern political ideologies",
    definition: "The political tradition holding that legitimate government rests on the people and their representatives, not on a monarch — centered on civic virtue, the rule of law and the common good.",
    origins: "Classical Rome (res publica), the Italian Renaissance city-states, and the American and French revolutions.",
    coreIdeas: "Popular sovereignty, representation, civic virtue, the separation of powers, and opposition to hereditary rule.",
    keyThinkers: ["Machiavelli (the Discourses)", "James Harrington", "Montesquieu", "James Madison"],
    historicalRole: "The intellectual foundation of modern democratic republics.",
    variants: "Classical republicanism, civic republicanism, constitutional republicanism.",
    criticism: "Critics argue republicanism's civic-virtue demands are unrealistic; defenders see it as democracy's foundation.",
    summary: "Republicanism holds that government belongs to the people and their representatives, not a monarch.",
    simple: "Republicanism is the idea that a country should be run by its people and their elected leaders, not a king.",
  }),
  buildIdeology({
    id: "pol.ideo.fascism",
    name: "Fascism",
    family: "Modern political ideologies",
    definition: "An authoritarian, ultranationalist ideology that subordinates the individual to a totalitarian state or party, glorifies the leader and violence, and rejects democracy and liberalism.",
    origins: "Italy under Mussolini (the Fasci, 1919–22); Nazism in Germany; other 20th-century movements.",
    coreIdeas: "Ultranationalism, the leader principle, militarism, the suppression of opposition, and the myth of national rebirth.",
    keyThinkers: ["Benito Mussolini", "Giovanni Gentile", "Adolf Hitler (National Socialism)"],
    historicalRole: "Governed Italy (1922–43), Germany (1933–45) and allied regimes; responsible for World War II and the Holocaust.",
    variants: "Italian Fascism, German National Socialism, Falangism, contemporary neo-fascism.",
    criticism: "Universally condemned in post-war scholarship for its crimes; the term is also used loosely and contested.",
    summary: "Fascism is the authoritarian, ultranationalist ideology of Mussolini's Italy and Hitler's Germany — responsible for World War II and the Holocaust.",
    simple: "Fascism was the extreme nationalist ideology of Mussolini and Hitler, with one all-powerful leader and no opposition allowed.",
  }),
  buildIdeology({
    id: "pol.ideo.african-socialism",
    name: "African socialism",
    family: "African political philosophies",
    definition: "A family of post-independence African ideologies combining socialist economics with African communal traditions (ujamaa, harambee, négritude).",
    origins: "The independence era (1950s–60s); Nkrumah, Nyerere, Senghor, Kaunda.",
    coreIdeas: "Communal ownership and mutual aid rooted in African tradition, development without capitalist exploitation, and national self-reliance.",
    keyThinkers: ["Kwame Nkrumah", "Julius Nyerere", "Léopold Sédar Senghor", "Kenneth Kaunda"],
    historicalRole: "Guiding ideology of several post-independence states (Tanzania's ujamaa, Zambia's humanism, Senegal's African socialism).",
    variants: "Ujamaa, African humanism, consciencism.",
    criticism: "Economic outcomes were mixed and are debated; supporters note the constraints of the post-colonial world economy.",
    summary: "African socialism blended socialist economics with African communal traditions in the post-independence era.",
    simple: "African socialism was the idea that African countries could build socialism using their own traditions of sharing and community.",
  }),
  buildIdeology({
    id: "pol.ideo.anticolonial",
    name: "Anti-colonial political thought",
    family: "African & global political philosophies",
    definition: "The body of political thought developed in resistance to colonialism: the critique of empire, the demand for self-determination, and the theory of liberation.",
    origins: "The colonial encounter itself; systematic theory from the late 19th century through the 1960s.",
    coreIdeas: "Self-determination, the critique of racial hierarchy, cultural revaluation, and the analysis of colonial economy and psychology.",
    keyThinkers: ["Frantz Fanon", "Aimé Césaire", "Mahatma Gandhi", "Amílcar Cabral", "Edward Said"],
    historicalRole: "The intellectual engine of decolonization and of post-colonial studies.",
    variants: "Négritude, national liberation theory, post-colonialism.",
    criticism: "Debates concern the use of violence in liberation (Fanon vs Gandhi) and the persistence of colonial structures after independence.",
    summary: "Anti-colonial thought is the theory of resistance to empire — from Fanon's critique to Gandhi's nonviolence.",
    simple: "Anti-colonial thinkers studied how empires oppressed people and argued for freedom and self-rule.",
  }),
  buildIdeology({
    id: "pol.ideo.indigenous-politics",
    name: "Indigenous political philosophies",
    family: "Global political philosophies",
    definition: "The political thought of Indigenous peoples: sovereignty, treaty rights, self-determination, relationality with land, and the critique of settler colonialism.",
    origins: "As old as the peoples themselves; modern movements from the 1960s–70s (the Red Power movement, the 2007 UN Declaration).",
    coreIdeas: "Inherent sovereignty, the nation-to-nation relationship, stewardship of land, and the intergenerational transmission of governance traditions.",
    keyThinkers: ["Vine Deloria Jr.", "Taiaiake Alfred", "Aileen Moreton-Robinson", "the leaders of the land-rights movements"],
    historicalRole: "Won land rights, treaty recognition and the UN Declaration on the Rights of Indigenous Peoples (2007).",
    variants: "Sovereignty movements, land-rights movements, treaty federalism.",
    criticism: "States have often resisted sovereignty claims; the field debates the terms of coexistence.",
    summary: "Indigenous political philosophy centers sovereignty, land and treaty rights — the thought behind modern Indigenous movements worldwide.",
    simple: "Indigenous political ideas are about the rights of native peoples to their land, their self-government and their treaties.",
  }),
  buildIdeology({
    id: "pol.ideo.religious-political",
    name: "Religious political movements",
    family: "Global political philosophies",
    definition: "Political movements that draw their program from religious tradition — including Christian democracy, political Islam (Islamism), Hindu nationalism, and Jewish religious Zionism.",
    origins: "Modern responses to secularization, colonialism and the nation-state (19th–20th centuries).",
    coreIdeas: "The application of religious law or values to public life, the defense of religious community, and (in many variants) the critique of secular liberalism.",
    keyThinkers: ["Sayyid Qutb", "Ruhollah Khomeini", "V.D. Savarkar", "Abraham Kuyper"],
    historicalRole: "Governed or shaped states (Iran 1979, the Christian-democratic parties of Europe), and mobilized millions.",
    variants: "Christian democracy, Islamism, Hindu nationalism, religious Zionism.",
    criticism: "Secularists argue religious politics threatens pluralism; religious movements reply that values must shape public life.",
    summary: "Religious political movements bring religious tradition into public life — from Christian democracy to Islamism and Hindu nationalism.",
    simple: "Some political movements are based on religion, saying that faith should guide how the country is run.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §14 — Political movements
 * ════════════════════════════════════════════════════════════════════════════ */

export const MOVEMENTS: MovementRecord[] = [
  buildMovement({
    id: "pol.mov.nigeria-independence",
    name: "Nigerian independence movement",
    countryIds: ["pol.country.nigeria"],
    origin: "1920s–1940s Lagos and the nationalists; the Nigerian Youth Movement (1934) and the NCNC (1944).",
    leaders: ["Herbert Macaulay", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello", "Abubakar Tafawa Balewa"],
    goals: "Self-government and independence from Britain.",
    historicalContext: "British colonial rule since 1861; indirect rule and the 1914 amalgamation.",
    majorEvents: "The 1945 general strike, the 1946–1958 constitutional conferences, the 1951–59 elections, independence (1960).",
    governmentResponse: "Gradual constitutional reform under British supervision.",
    outcome: "Independence on 1 October 1960.",
    impact: "Created the Nigerian state and its federal structure.",
    summary: "The Nigerian independence movement, led by Macaulay, Azikiwe and Awolowo, won independence in 1960.",
    simple: "Nigerian leaders like Azikiwe and Awolowo campaigned peacefully for years until Britain granted independence in 1960.",
  }),
  buildMovement({
    id: "pol.mov.us-civil-rights",
    name: "American civil rights movement",
    countryIds: ["pol.country.united-states"],
    origin: "The long struggle against Jim Crow; the modern phase from the 1950s (Brown v. Board, 1954; the Montgomery bus boycott, 1955).",
    leaders: ["Martin Luther King Jr.", "Rosa Parks", "John Lewis", "Malcolm X", "Fannie Lou Hamer"],
    goals: "End legal segregation and secure voting and civil rights for African Americans.",
    historicalContext: "Reconstruction's reversal, Jim Crow laws, and the Great Migration.",
    majorEvents: "The 1963 Birmingham campaign, the March on Washington, the 1964 Civil Rights Act, the 1965 Voting Rights Act, the Selma marches.",
    governmentResponse: "From resistance (Bull Connor) to the federal enforcement of civil rights laws.",
    outcome: "The Civil Rights Act (1964) and Voting Rights Act (1965).",
    impact: "Ended legal segregation and inspired movements worldwide.",
    summary: "The American civil rights movement ended legal segregation through nonviolent protest and federal law.",
    simple: "In the 1950s and 60s, Martin Luther King Jr. and others protested peacefully until the laws treating Black Americans unfairly were changed.",
  }),
  buildMovement({
    id: "pol.mov.anti-apartheid",
    name: "Anti-apartheid movement (South Africa)",
    countryIds: ["pol.country.south-africa"],
    origin: "The African National Congress (1912) and the resistance to apartheid after 1948.",
    leaders: ["Nelson Mandela", "Albert Luthuli", "Oliver Tambo", "Steve Biko", "Desmond Tutu"],
    goals: "End apartheid and establish majority-rule democracy.",
    historicalContext: "White-minority rule since 1910; apartheid's legalized segregation from 1948.",
    majorEvents: "The Defiance Campaign (1952), the Freedom Charter (1955), Sharpeville (1960), the Soweto uprising (1976), the release of Mandela (1990), the 1994 election.",
    governmentResponse: "Bans, detention, Sharpeville and the states of emergency.",
    outcome: "The negotiated transition and the 1994 democratic election.",
    impact: "Ended institutionalized racism and inspired global movements.",
    summary: "The anti-apartheid movement, led by the ANC and Mandela, ended white-minority rule and won democracy in 1994.",
    simple: "For decades, South Africans and people around the world protested against apartheid until it ended and Mandela became president.",
  }),
  buildMovement({
    id: "pol.mov.labor",
    name: "Labor movement",
    countryIds: ["pol.country.united-kingdom", "pol.country.united-states", "pol.country.nigeria"],
    origin: "The industrial revolution's working class; trade unions from the 19th century.",
    leaders: ["The union founders and leaders of each country (e.g. the TUC, AFL-CIO, NLC)"],
    goals: "Better wages, working conditions, the eight-hour day, and political representation of workers.",
    historicalContext: "Industrialization, child labor, and the absence of labor rights.",
    majorEvents: "The 1889 London dock strike, the 1930s CIO organizing, the 1945 Nigerian general strike, the formation of labor parties.",
    governmentResponse: "From suppression to legal recognition and collective-bargaining law.",
    outcome: "The eight-hour day, labor law, welfare states, and labor parties.",
    impact: "Created the modern welfare state and the political left's institutional base.",
    summary: "The labor movement won workers' rights — the eight-hour day, unions and labor parties — across the industrial world.",
    simple: "Workers organized unions to win fair pay and shorter hours — that is how the weekend and labor laws came to be.",
  }),
  buildMovement({
    id: "pol.mov.womens-suffrage",
    name: "Women's suffrage movement",
    countryIds: ["pol.country.united-kingdom", "pol.country.united-states", "pol.country.nigeria"],
    origin: "The 19th-century women's rights movement (Seneca Falls, 1848; the suffragettes).",
    leaders: ["Susan B. Anthony", "Emmeline Pankhurst", "Funnilayo Ransome-Kuti (Nigerian women's rights)"],
    goals: "The right to vote and full citizenship for women.",
    historicalContext: "Women's legal subordination and exclusion from the franchise.",
    majorEvents: "The suffragette campaigns, the 1918 UK Representation of the People Act, the 1920 US 19th Amendment, Nigerian women's franchise at independence (1960).",
    governmentResponse: "Arrests and force-feeding in Britain; gradual concession elsewhere.",
    outcome: "Universal women's suffrage across the world by the mid-20th century.",
    impact: "Doubled the electorate and transformed democratic politics.",
    summary: "The women's suffrage movement won women the vote — one of democracy's defining expansions.",
    simple: "Women fought for decades to be allowed to vote. Today, in most countries, women and men vote equally.",
  }),
  buildMovement({
    id: "pol.mov.pro-democracy",
    name: "Pro-democracy movements",
    countryIds: ["pol.country.nigeria", "pol.country.kenya", "pol.country.ghana"],
    origin: "Recurrent movements against military rule and one-party systems in Africa and worldwide.",
    leaders: ["The June 12 movement in Nigeria", "the Second Liberation in Ghana", "the 1990s Kenyan reform movements"],
    goals: "Multi-party elections, constitutional government, and the end of military or one-party rule.",
    historicalContext: "The post-independence wave of coups and one-party states.",
    majorEvents: "The June 12 crisis (Nigeria, 1993), the 1992–93 Ghanaian transition, the 1991 Kenyan repeal of section 2A, the 1999 Nigerian transition.",
    governmentResponse: "Ranged from repression to managed transitions.",
    outcome: "The African democratic wave of the 1990s.",
    impact: "Established the multi-party systems most African states have today.",
    summary: "Africa's pro-democracy movements ended military and one-party rule in the 1990s, from Nigeria's June 12 struggle to Ghana's and Kenya's transitions.",
    simple: "In the 1990s, people across Africa protested for the right to choose their leaders, and many countries became democracies.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §16 — International organizations
 * ════════════════════════════════════════════════════════════════════════════ */

export const INTERNATIONAL_ORGS: InternationalOrgRecord[] = [
  buildOrg({
    id: "org.un",
    name: "United Nations",
    altNames: ["UN"],
    founded: "1945 (Charter in force 24 October 1945)",
    headquarters: "New York City",
    membership: "193 member states",
    purpose: "To maintain international peace and security, develop friendly relations among nations, and cooperate on economic, social and humanitarian problems.",
    structure: "The General Assembly (all members), the Security Council (15, with five permanent veto-wielding members), the Secretariat, the International Court of Justice, and the specialized agencies (WHO, UNESCO, UNICEF and others).",
    majorActivities: "Peacekeeping, humanitarian relief, the SDGs, human-rights monitoring, and the framework of international law.",
    achievements: "Decolonization's framework, the UDHR (1948), peacekeeping operations, and the global development agenda.",
    criticisms: "Documented criticisms: Security Council veto paralysis, and the gap between its principles and member-state behavior.",
    memberExamples: ["Nigeria", "United States", "Kenya", "India", "Brazil"],
    summary: "The United Nations, founded in 1945, is the world's central intergovernmental organization for peace, rights and development.",
    simple: "The United Nations is where almost all countries meet to discuss peace, human rights and helping people.",
  }),
  buildOrg({
    id: "org.african-union",
    name: "African Union",
    altNames: ["AU"],
    founded: "2002 (successor to the OAU, 1963)",
    headquarters: "Addis Ababa",
    membership: "55 member states",
    purpose: "African unity and integration, peace and security, and the continent's development agenda (Agenda 2063).",
    structure: "The Assembly of Heads of State, the Commission, the Pan-African Parliament, the Peace and Security Council, and the African Court on Human and Peoples' Rights.",
    majorActivities: "Peacekeeping (AMISOM/AUSSOM), the African Continental Free Trade Area (AfCFTA), election observation, and mediation.",
    achievements: "The AfCFTA (2019), the AU's peace operations, and the promotion of democratic transitions.",
    criticisms: "Documented criticisms: the 'coup epidemic' responses, funding dependence, and the gap between decisions and implementation.",
    memberExamples: ["Nigeria", "Kenya", "Ghana", "South Africa", "Ethiopia"],
    summary: "The African Union (2002–) drives African integration, peace and development as the OAU's successor.",
    simple: "The African Union is the organization of all African countries, working for peace and cooperation.",
  }),
  buildOrg({
    id: "org.eu",
    name: "European Union",
    altNames: ["EU"],
    founded: "1957 (Treaty of Rome); the EU's current name and structure from the 1993 Maastricht Treaty",
    headquarters: "Brussels",
    membership: "27 member states",
    purpose: "European economic and political integration: a single market, common institutions, and shared law across member states.",
    structure: "The European Commission (executive), the European Parliament (elected), the Council of the EU (member states), and the Court of Justice.",
    majorActivities: "The single market, the euro (20 members), common trade policy, the Erasmus program, and regulation spanning most policy areas.",
    achievements: "Decades of peace and prosperity in Western Europe, enlargement, and the world's largest trading bloc.",
    criticisms: "Documented criticisms: the democratic deficit, bureaucracy, and the strains shown by Brexit (the UK left in 2020).",
    memberExamples: ["France", "Germany", "Italy", "Spain", "Poland"],
    summary: "The European Union is the world's deepest experiment in regional integration — 27 states sharing a market, law and institutions.",
    simple: "The European Union is a club of European countries that share a market, laws and, for many, the same money (the euro).",
  }),
  buildOrg({
    id: "org.nato",
    name: "NATO",
    altNames: ["North Atlantic Treaty Organization"],
    founded: "1949",
    headquarters: "Brussels",
    membership: "32 members (as of 2024, with Finland and Sweden)",
    purpose: "Collective defense: an attack on one member is an attack on all (Article 5).",
    structure: "The North Atlantic Council and the military command structure under a Secretary-General and a Supreme Allied Commander.",
    majorActivities: "Collective defense, exercises, crisis management (Kosovo, Afghanistan, Libya), and support for Ukraine since 2022.",
    achievements: "Deterred the Soviet Union during the Cold War and has maintained the transatlantic security community.",
    criticisms: "Documented criticisms: cost-sharing disputes and the effects of enlargement on relations with Russia.",
    memberExamples: ["United States", "United Kingdom", "France", "Germany", "Turkey"],
    summary: "NATO is the transatlantic military alliance founded in 1949 on the principle that an attack on one member is an attack on all.",
    simple: "NATO is a military alliance of North American and European countries that promise to defend each other if attacked.",
  }),
  buildOrg({
    id: "org.asean",
    name: "ASEAN",
    altNames: ["Association of Southeast Asian Nations"],
    founded: "1967 (Bangkok Declaration)",
    headquarters: "Jakarta",
    membership: "10 member states",
    purpose: "Economic growth, regional stability and cooperation in Southeast Asia.",
    structure: "The ASEAN Summit, the Secretariat, and the ASEAN Economic Community.",
    majorActivities: "The ASEAN Economic Community, regional security dialogues, and the ASEAN Way of consensus diplomacy.",
    achievements: "Brought stability and integration to a once-conflicted region.",
    criticisms: "Documented criticisms: the consensus requirement slows decision-making, and the Myanmar crisis has exposed its limits.",
    memberExamples: ["Indonesia", "Thailand", "Vietnam", "Philippines", "Malaysia"],
    summary: "ASEAN unites ten Southeast Asian states in a consensus-driven community for economic and regional cooperation.",
    simple: "ASEAN is a group of ten countries in Southeast Asia that cooperate on trade and regional peace.",
  }),
  buildOrg({
    id: "org.arab-league",
    name: "Arab League",
    altNames: ["League of Arab States"],
    founded: "1945",
    headquarters: "Cairo",
    membership: "22 members",
    purpose: "Coordination among Arab states on political, economic and cultural matters.",
    structure: "The Council, the Secretary-General, and specialized agencies.",
    majorActivities: "Joint positions on regional issues (Palestine, Libya, Syria), economic cooperation, and Arab League summits.",
    achievements: "A forum for Arab coordination for 80 years.",
    criticisms: "Documented criticisms: divisions (Syria's suspension and return) and its limited enforcement power.",
    memberExamples: ["Egypt", "Saudi Arabia", "United Arab Emirates", "Iraq", "Morocco"],
    summary: "The Arab League coordinates political and economic cooperation among 22 Arab states.",
    simple: "The Arab League is a group of Arab countries that meet to coordinate their positions.",
  }),
  buildOrg({
    id: "org.commonwealth",
    name: "Commonwealth of Nations",
    altNames: ["the Commonwealth"],
    founded: "1949 (the modern Commonwealth; the British Commonwealth from 1931)",
    headquarters: "London",
    membership: "56 member states",
    purpose: "A voluntary association of states, mostly former British territories, cooperating on democracy, development and law.",
    structure: "The Commonwealth Secretariat, the biennial Commonwealth Heads of Government Meeting (CHOGM), and the Commonwealth Games.",
    majorActivities: "Election observation, the Commonwealth Charter (2012), trade and education programs, and the Games.",
    achievements: "A global network spanning every continent; 15 members retain the King as head of state.",
    criticisms: "Documented criticisms: the legacy of empire, and its limited political teeth (e.g. on human-rights violations).",
    memberExamples: ["Nigeria", "United Kingdom", "Kenya", "Ghana", "India", "Canada", "Australia", "South Africa"],
    summary: "The Commonwealth is a 56-state association, mostly former British territories, cooperating on democracy and development.",
    simple: "The Commonwealth is a group of countries, most of them once ruled by Britain, that work together on democracy and development.",
  }),
  buildOrg({
    id: "org.ecowas",
    name: "ECOWAS",
    altNames: ["Economic Community of West African States"],
    founded: "1975 (Treaty of Lagos)",
    headquarters: "Abuja",
    membership: "15 member states (three under suspension/withdrawal notices as of the Last Verified date: Mali, Burkina Faso, Niger)",
    purpose: "West African economic integration, free movement, and peace and security.",
    structure: "The Authority of Heads of State, the Commission, the ECOWAS Parliament, and the ECOWAS Court of Justice.",
    majorActivities: "The ECOWAS free-trade area and free movement, election observation, and peacekeeping (ECOMOG; interventions in Liberia, Sierra Leone, The Gambia; mediation in Niger and elsewhere).",
    achievements: "Kept West Africa's integration alive through decades of crises.",
    criticisms: "Documented criticisms: sanctions' effectiveness, and the 2023–24 challenges from the Alliance of Sahel States' exit.",
    memberExamples: ["Nigeria", "Ghana", "Senegal", "Côte d'Ivoire", "Benin"],
    summary: "ECOWAS is West Africa's regional bloc — economic integration, free movement and peacekeeping since 1975.",
    simple: "ECOWAS is the club of West African countries that trade together and try to keep the region peaceful.",
  }),
  buildOrg({
    id: "org.sadc",
    name: "SADC",
    altNames: ["Southern African Development Community"],
    founded: "1980 (as SADCC); the SADC in 1992",
    headquarters: "Gaborone",
    membership: "16 member states",
    purpose: "Southern African cooperation in development, security and regional integration.",
    structure: "The Summit of Heads of State, the Council of Ministers, and the Secretariat.",
    majorActivities: "The SADC Free Trade Area, regional infrastructure, election observation, and the SADC Mission in Mozambique (SAMIM).",
    achievements: "Supported the anti-apartheid struggle and post-apartheid integration.",
    criticisms: "Documented criticisms: slow integration and mixed responses to members' political crises (e.g. Zimbabwe, eSwatini).",
    memberExamples: ["South Africa", "Tanzania", "Zambia", "Zimbabwe", "Mozambique"],
    summary: "SADC is the Southern African bloc for development and security cooperation among 16 states.",
    simple: "SADC is a group of countries in southern Africa that cooperate on trade and security.",
  }),
  buildOrg({
    id: "org.eac",
    name: "EAC",
    altNames: ["East African Community"],
    founded: "1999 (revived; the original EAC existed 1967–1977)",
    headquarters: "Arusha",
    membership: "8 member states (with Somalia joining in 2024)",
    purpose: "East African integration: a customs union, common market and monetary-union plans.",
    structure: "The Summit, the Council of Ministers, the East African Legislative Assembly, and the East African Court of Justice.",
    majorActivities: "The customs union, the single-tourist-visa, infrastructure projects, and regional peace efforts (e.g. in the DRC).",
    achievements: "Deep integration among its core members (Kenya, Tanzania, Uganda, Rwanda, Burundi).",
    criticisms: "Documented criticisms: the DRC's withdrawal notice (2025) and recurring political tensions among members.",
    memberExamples: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Burundi", "DR Congo", "South Sudan", "Somalia"],
    summary: "The EAC is East Africa's integration community — a customs union and common market of eight states.",
    simple: "The EAC is a group of East African countries that trade together and share a customs union.",
  }),
  buildOrg({
    id: "org.igad",
    name: "IGAD",
    altNames: ["Intergovernmental Authority on Development"],
    founded: "1986 (as IGADD); the IGAD in 1996",
    headquarters: "Djibouti",
    membership: "8 member states",
    purpose: "Drought and development cooperation in the Horn of Africa, extended to peace and security.",
    structure: "The Assembly of Heads of State, the Council of Ministers, and the Secretariat.",
    majorActivities: "Mediation in Sudan and Somalia, the IGAD Centre for Pastoral Areas, and regional early warning.",
    achievements: "Mediation in the Sudans and Somalia's stabilization.",
    criticisms: "Documented criticisms: capacity limits and uneven success in mediation.",
    memberExamples: ["Kenya", "Ethiopia", "Djibouti", "Somalia", "Sudan", "South Sudan", "Uganda", "Eritrea"],
    summary: "IGAD is the Horn of Africa's regional body for development, drought and peace mediation.",
    simple: "IGAD is a group of Horn of Africa countries that cooperate on development and peace.",
  }),
  buildOrg({
    id: "org.g20",
    name: "G20",
    altNames: ["Group of Twenty"],
    founded: "1999 (leaders' summits from 2008)",
    headquarters: "No permanent secretariat (rotating presidency)",
    membership: "19 countries plus the EU and AU",
    purpose: "Global economic coordination among the world's largest economies.",
    structure: "Annual leaders' summits, finance ministers' meetings, and the rotating presidency.",
    majorActivities: "Crisis coordination (2008, COVID-19), debt relief, the global tax deal (2021), and climate finance.",
    achievements: "The 2008 crisis response and the global minimum tax agreement.",
    criticisms: "Documented criticisms: the non-binding nature of its communiqués and the AU's late inclusion (2023).",
    memberExamples: ["Nigeria is not a member; members include the United States, China, India, Brazil, South Africa"],
    summary: "The G20 coordinates the world's largest economies on finance, trade and global crises.",
    simple: "The G20 is a meeting of the world's biggest economies to coordinate on money and global problems.",
  }),
  buildOrg({
    id: "org.g7",
    name: "G7",
    altNames: ["Group of Seven"],
    founded: "1975 (as the G6; Canada joined 1976)",
    headquarters: "Rotating presidency",
    membership: "7 members: the US, UK, France, Germany, Italy, Japan, Canada (+ the EU)",
    purpose: "Coordination among the major advanced democracies.",
    structure: "Annual summits and ministerial meetings.",
    majorActivities: "Economic policy, sanctions coordination, climate and development commitments.",
    achievements: "Decades of democratic coordination; the Ukraine support framework.",
    criticisms: "Documented criticisms: its exclusion of rising powers and declining share of world GDP.",
    memberExamples: ["United States", "United Kingdom", "France", "Germany", "Italy", "Japan", "Canada"],
    summary: "The G7 is the summit of the world's major advanced democracies.",
    simple: "The G7 is an annual meeting of seven rich democratic countries.",
  }),
  buildOrg({
    id: "org.brics",
    name: "BRICS",
    altNames: ["BRICS+ (after 2024 expansion)"],
    founded: "2009 (first summit; the acronym coined 2001)",
    headquarters: "Rotating presidency; the New Development Bank in Shanghai",
    membership: "9 full members after the 2024 expansion (Brazil, Russia, India, China, South Africa, Iran, Egypt, Ethiopia, UAE)",
    purpose: "Cooperation among major emerging economies and an alternative pole in global governance.",
    structure: "Annual summits, the New Development Bank, and the Contingent Reserve Arrangement.",
    majorActivities: "The New Development Bank, de-dollarization discussions, and the expansion summits.",
    achievements: "Created the New Development Bank (2014) and grew from 5 to 9+ members.",
    criticisms: "Documented criticisms: the members' divergent interests and Russia's war complicating its image.",
    memberExamples: ["Brazil", "Russia", "India", "China", "South Africa", "Egypt", "Ethiopia", "Iran", "UAE"],
    summary: "BRICS groups the major emerging economies, with a development bank and an expanding membership since 2024.",
    simple: "BRICS is a group of big emerging economies like China, India and Brazil that cooperate on development.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §12 — Government forms (educational)
 * ════════════════════════════════════════════════════════════════════════════ */

export const GOVERNMENT_FORMS_RECORDS: GovernmentFormRecord[] = [
  buildForm({
    id: "pol.form.presidential-republic",
    name: "Presidential republic",
    definition: "A republic in which a directly elected president is both head of state and head of government, independent of the legislature.",
    howItWorks: "The president is elected separately from the legislature; the cabinet answers to the president; the legislature cannot easily remove the president except through impeachment.",
    examples: ["United States", "Nigeria", "Kenya", "Brazil", "Ghana"],
    strengths: "Clear executive accountability, stability of tenure, and a direct popular mandate.",
    weaknesses: "Possible gridlock between the presidency and legislature, and the concentration of power in one office.",
    summary: "In a presidential republic, one directly elected president is both head of state and head of government.",
    simple: "In a presidential republic, the people elect a president who runs the country and is separate from the parliament.",
  }),
  buildForm({
    id: "pol.form.parliamentary-republic",
    name: "Parliamentary republic",
    definition: "A republic in which the government is drawn from and accountable to the legislature; a president (often ceremonial) is head of state, while a prime minister is head of government.",
    howItWorks: "Voters elect the legislature; the majority (or coalition) forms the government; the prime minister and cabinet hold office while they command the legislature's confidence.",
    examples: ["Germany", "India", "South Africa", "Ethiopia"],
    strengths: "Fusion of powers allows quick legislation and easy removal of failed governments.",
    weaknesses: "Coalition instability and the prime minister's dependence on the legislature.",
    summary: "In a parliamentary republic, the prime minister and cabinet govern by commanding a legislative majority.",
    simple: "In a parliamentary republic, people vote for parliament, and parliament chooses the prime minister who runs the country.",
  }),
  buildForm({
    id: "pol.form.semi-presidential",
    name: "Semi-presidential republic",
    definition: "A republic with both a directly elected president and a prime minister accountable to parliament, sharing executive power.",
    howItWorks: "The president usually controls foreign policy and defense; the prime minister runs domestic government; 'cohabitation' occurs when they come from different parties.",
    examples: ["France", "Russia", "Egypt"],
    strengths: "Combines a direct mandate with parliamentary accountability.",
    weaknesses: "Ambiguous responsibility and possible executive conflict.",
    summary: "A semi-presidential republic shares executive power between a president and a parliament-dependent prime minister.",
    simple: "In a semi-presidential system, there is both a president and a prime minister who share the work of running the country.",
  }),
  buildForm({
    id: "pol.form.constitutional-monarchy",
    name: "Constitutional monarchy",
    definition: "A monarchy in which the monarch's powers are limited by a constitution; in parliamentary monarchies the monarch is ceremonial and the prime minister governs.",
    howItWorks: "The monarch is head of state within constitutional limits; elected government exercises real power.",
    examples: ["United Kingdom", "Canada", "Australia", "Japan"],
    strengths: "Continuity and a non-partisan head of state.",
    weaknesses: "Hereditary office sits uneasily with democratic equality.",
    summary: "A constitutional monarchy limits the monarch by law; in most such systems, elected government rules.",
    simple: "In a constitutional monarchy, the king or queen is the head of state but the elected government really runs the country.",
  }),
  buildForm({
    id: "pol.form.absolute-monarchy",
    name: "Absolute monarchy",
    definition: "A monarchy in which the monarch holds supreme power without constitutional limitation.",
    howItWorks: "The monarch rules by decree; parliaments, where they exist, are advisory.",
    examples: ["Saudi Arabia", "Oman", "Brunei"],
    strengths: "Decisive rule and stability (per its advocates).",
    weaknesses: "No institutionalized accountability or succession contest.",
    summary: "An absolute monarchy concentrates power in a monarch without constitutional limits.",
    simple: "In an absolute monarchy, the king or ruler has all the power and no parliament can overrule him.",
  }),
  buildForm({
    id: "pol.form.federal-republic",
    name: "Federal republic",
    definition: "A republic whose territory is divided into self-governing states or provinces sharing sovereignty with the national government.",
    howItWorks: "A written constitution divides powers between the federal government and the states; both levels usually have their own executives and legislatures.",
    examples: ["United States", "Nigeria", "Brazil", "India", "Germany"],
    strengths: "Accommodates diversity and checks centralized power.",
    weaknesses: "Duplication, coordination problems, and recurring center-state disputes.",
    summary: "A federal republic divides power between a national government and self-governing states.",
    simple: "In a federal republic like Nigeria or the US, the country is made of states that share power with the central government.",
  }),
  buildForm({
    id: "pol.form.unitary-republic",
    name: "Unitary republic",
    definition: "A republic in which sovereignty is concentrated in the central government; sub-national units exercise only delegated powers.",
    howItWorks: "Local governments exist but their powers derive from the center, which can reorganize them.",
    examples: ["France", "Kenya", "Ghana", "Japan"],
    strengths: "Uniform policy and clear hierarchy.",
    weaknesses: "Possible over-centralization and neglect of local diversity.",
    summary: "A unitary republic concentrates sovereignty in the central government.",
    simple: "In a unitary republic, the central government is in charge, and local areas only have the powers it gives them.",
  }),
  buildForm({
    id: "pol.form.one-party",
    name: "One-party system",
    definition: "A system in which a single party holds a legal or effective monopoly on political power.",
    howItWorks: "Other parties are banned, co-opted or marginalized; the ruling party controls the state.",
    examples: ["China (CCP)", "historically the USSR, and post-independence African one-party states"],
    strengths: "Stability and rapid mobilization (per its advocates).",
    weaknesses: "No electoral accountability and the suppression of opposition.",
    summary: "A one-party system concentrates power in a single ruling party.",
    simple: "In a one-party system, only one political party is allowed to rule.",
  }),
  buildForm({
    id: "pol.form.military-government",
    name: "Military government",
    definition: "Government by the armed forces, usually after a coup, ruling by decree.",
    howItWorks: "A junta or military head of state suspends the constitution and rules through decrees until (often) a managed transition.",
    examples: ["Nigeria 1966–1999 (intermittently)", "Brazil 1964–1985", "Myanmar 2021–"],
    strengths: "Order and decisive action (per its defenders).",
    weaknesses: "No mandate, suppression of rights, and often poor governance outcomes.",
    summary: "A military government rules by decree after a coup, suspending constitutional government.",
    simple: "A military government is when soldiers take over the country and rule without elections.",
  }),
  buildForm({
    id: "pol.form.transitional",
    name: "Transitional government",
    definition: "A temporary government established to steer a country from crisis or conflict to constitutional rule.",
    howItWorks: "Often power-sharing arrangements among factions; charged with writing a constitution and organizing elections.",
    examples: ["South Africa 1990–1994", "Nigeria's Interim National Government 1993", "various UN-brokered transitions"],
    strengths: "A bridge from conflict to constitutional order.",
    weaknesses: "Instability and the risk of overstaying.",
    summary: "A transitional government temporarily steers a country from crisis toward constitutional elections.",
    simple: "A transitional government is a temporary one that prepares a country for real elections.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * Policy records (§21/§22/§23/§24/§28)
 * ════════════════════════════════════════════════════════════════════════════ */

export const POLICY_RECORDS: GovernmentFormRecord[] = [
  (() => { const r = buildForm({
    id: "pol.policy.neutrality",
    name: "How WINDELS teaches politics",
    altNames: ["political neutrality policy", "INFORM, NOT MANIPULATE"],
    definition: "WINDELS presents political information accurately, neutrally and transparently: it does not secretly favor any party, candidate, government, opposition, ideology, country or movement (§24).",
    howItWorks: "When controversies exist, WINDELS explains the competing positions and identifies what is established versus disputed. Political labels are presented with context — what a party calls itself vs how scholars classify it. Factual claims carry sources; opinions are labelled as opinions.",
    examples: ["Nigeria's 2023 election: WINDELS presents INEC's results and the opposition's legal challenges, noting the Supreme Court's affirmance."],
    strengths: "Trustworthy educational reference.",
    weaknesses: "Neutrality can read as blandness to partisans.",
    summary: "WINDELS teaches politics neutrally: INFORM, NOT MANIPULATE.",
    simple: "WINDELS tells you what is fact, what is opinion, and what each side says — without choosing a side.",
  }); r.kind = "policy" as any; return r; })(),
  (() => { const r = buildForm({
    id: "pol.policy.current-info",
    name: "How WINDELS handles current political information",
    altNames: ["current politics policy", "Last Verified"],
    definition: "Current political information (office-holders, recent results, ongoing crises) changes daily and is separated from stable historical knowledge (§21).",
    howItWorks: "Current records carry a 'Last Verified' timestamp and `current_as_of` verification. WINDELS marks them as subject to change and supports the update engine (§28) — which never overwrites history: a change creates a change-log entry and preserves the previous record.",
    examples: ["The Nigerian president record carries asOfDate 2026-08-08 and lastVerified 2026-08-08."],
    strengths: "Honest about the difference between history and news.",
    weaknesses: "Requires continuous verification to stay current.",
    summary: "Current political facts are labelled with Last Verified timestamps and are never treated as permanent.",
    simple: "Things that change — like who is president — are marked with the date they were last checked.",
  }); r.kind = "policy" as any; return r; })(),
];
