/**
 * Session 144 — Politics seed (part 1): deep Nigeria coverage (§26's example
 * country). Leaders (§4/§5), parties (§9), elections (§10), ministries (§8),
 * governors (§6), constitutions (§11), events (§15).
 *
 * Current office-holders carry `current_as_of` verification with a Last
 * Verified timestamp (§21); historical records are stable.
 */
import type {
  ConstitutionRecord,
  ElectionRecord,
  LeaderRecord,
  MinistryRecord,
  OfficeHolderRecord,
  PartyRecord,
  PoliticalEventRecord,
} from "@windels/shared";
import {
  buildConstitution,
  buildElection,
  buildEvent,
  buildLeader,
  buildMinistry,
  buildOfficeHolder,
  buildParty,
  SRC_ACADEMIC,
  SRC_ARCHIVE,
  SRC_CONSTITUTION,
  SRC_GOVT,
  SRC_INEC,
  SRC_JOURNALISM,
  SRC_PARLIAMENT,
} from "./politics.catalog.js";

const NIG = "pol.country.nigeria";

/* ════════════════════════════════════════════════════════════════════════════
 * §4/§5 — Nigeria's heads of state & heads of government
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_LEADERS: LeaderRecord[] = [
  buildLeader({
    id: "pol.leader.nigeria.azikiwe",
    name: "Nnamdi Azikiwe",
    altNames: ["Zik"],
    countryId: NIG,
    title: "Governor-General (1960–63) then President (1963–66)",
    titleKind: "head_of_state_ceremonial",
    role: "head_of_state",
    party: "NCNC",
    born: "1904 (Zungeru) – 1996",
    officeStart: "1 October 1960",
    officeEnd: "15 January 1966",
    predecessor: "Sir James Robertson (as colonial Governor-General)",
    successor: "Johnson Aguiyi-Ironsi (as Military Head of State)",
    cameToOffice: "First Governor-General of independent Nigeria; became ceremonial President when Nigeria became a republic in 1963.",
    ordinal: 1,
    majorPolicies: "Promoted African nationalism and 'Zikism'; championed education, including the University of Nigeria, Nsukka (founded 1960).",
    achievements: "First President of Nigeria; a leading figure of the independence movement and pan-African thought.",
    controversies: "His presidency was largely ceremonial; the 1962–63 Western Region crisis and the census disputes of 1962–63 marked the First Republic.",
    majorEvents: "Independence (1960), the republic (1963), the 1964–65 federal election crisis, the January 1966 coup that ended the First Republic.",
    constitutionalRole: "Under the 1960 and 1963 constitutions, the President was the ceremonial head of state; executive power lay with the Prime Minister.",
    historicalSignificance: "One of the founders of Nigerian nationalism and pan-Africanism; his life spans colonial rule, independence and the First Republic.",
    summary: "Nnamdi Azikiwe was Nigeria's first President (ceremonial, 1963–66), a founding figure of Nigerian nationalism and pan-Africanism.",
    simple: "Nnamdi Azikiwe, called 'Zik', was one of the leaders who won Nigeria's independence and became its first president.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.ironsi",
    name: "Johnson Aguiyi-Ironsi",
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1924 – 1966",
    officeStart: "16 January 1966",
    officeEnd: "29 July 1966",
    predecessor: "Nnamdi Azikiwe (President of the First Republic)",
    successor: "Yakubu Gowon",
    cameToOffice: "Took power after the January 1966 coup; the first military head of state.",
    ordinal: 2,
    majorPolicies: "Decreed the Unification Decree No. 34 of 1966, abolishing the federal structure in favor of a unitary system — highly controversial.",
    achievements: "Restored order after the January 1966 coup; his regime was brief.",
    controversies: "The unitary decree and perceptions of regional bias fueled tensions that led to his overthrow; he was killed in the July 1966 counter-coup.",
    majorEvents: "The January 1966 coup (the 'Young Majors'), the pogroms against Igbo people in the north, the July 1966 counter-coup.",
    constitutionalRole: "Ruled by decree as Military Head of State; suspended the 1963 constitution.",
    historicalSignificance: "His brief regime marks the end of the First Republic and the beginning of military rule in Nigeria.",
    summary: "Johnson Aguiyi-Ironsi was Nigeria's first military head of state (January–July 1966), overthrown and killed in the counter-coup.",
    simple: "Ironsi was the soldier who took over Nigeria after the first coup in 1966, but he was overthrown and killed months later.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.gowon",
    name: "Yakubu Gowon",
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1934 –",
    officeStart: "1 August 1966",
    officeEnd: "29 July 1975",
    predecessor: "Johnson Aguiyi-Ironsi",
    successor: "Murtala Mohammed",
    cameToOffice: "Assumed power after the July 1966 counter-coup.",
    ordinal: 3,
    majorPolicies: "Led Nigeria through the civil war (1967–70) with the slogan 'no victor, no vanquished'; pursued reconstruction and reconciliation; created 12 states (1967).",
    achievements: "Kept Nigeria one country through the Biafran war; led post-war reconstruction and the oil boom years.",
    controversies: "The civil war's conduct and the 1975 coup that removed him while he was abroad; later controversies over his wartime role are debated by historians.",
    majorEvents: "The creation of states (1967), the Nigerian Civil War (1967–70), the oil boom, the 1975 coup.",
    constitutionalRole: "Ruled by decree; announced a transition program that his successors continued.",
    historicalSignificance: "Nigeria's longest-serving military head of state; his reconciliation policy shaped the post-war federation.",
    summary: "Yakubu Gowon led Nigeria through the 1967–70 civil war and kept the federation united, ruling from 1966 to 1975.",
    simple: "Gowon was Nigeria's leader during the civil war. He kept the country together and said after the war: 'no victor, no vanquished'.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.murtala",
    name: "Murtala Mohammed",
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1938 – 1976",
    officeStart: "29 July 1975",
    officeEnd: "13 February 1976",
    predecessor: "Yakubu Gowon",
    successor: "Olusegun Obasanjo",
    cameToOffice: "Seized power in the July 1975 coup.",
    ordinal: 4,
    majorPolicies: "Launched sweeping reforms: purged the public service, created seven more states (19 total), moved the capital to Abuja (1976), and announced a transition to civilian rule by 1979.",
    achievements: "Restored public confidence; the transition program and the 1979 constitution are his legacy.",
    controversies: "Assassinated in the February 1976 coup attempt led by Buka Suka Dimka.",
    majorEvents: "The 1975 reforms, the creation of states, the announcement of the capital move to Abuja, the 1976 coup attempt.",
    constitutionalRole: "Ruled by decree; his transition timetable produced the Second Republic.",
    historicalSignificance: "Remembered for decisive reform and for his assassination; the Murtala Muhammed International Airport in Lagos bears his name.",
    summary: "Murtala Mohammed ruled Nigeria from July 1975 until his assassination in February 1976, launching major reforms and the transition to civilian rule.",
    simple: "Murtala Mohammed made big changes in Nigeria — new states, moving the capital to Abuja — but was killed in a coup attempt in 1976.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.obasanjo",
    name: "Olusegun Obasanjo",
    countryId: NIG,
    title: "Military Head of State (1976–79); President (1999–2007)",
    titleKind: "president",
    role: "both",
    party: "PDP (civilian terms)",
    born: "1937 –",
    officeStart: "13 February 1976",
    officeEnd: "29 May 2007",
    predecessor: "Murtala Mohammed; (civilian) Abdulsalami Abubakar",
    successor: "Shehu Shagari (1979); Umaru Musa Yar'Adua (2007)",
    cameToOffice: "Succeeded the assassinated Murtala Mohammed; later elected president in 1999 and re-elected in 2003.",
    ordinal: 5,
    majorPolicies: "Military term: handed power to civilians in 1979. Civilian terms: economic reforms (privatization, banking consolidation), anti-corruption agencies (EFCC, ICPC), debt relief (2005), return to democratic rule.",
    achievements: "Nigeria's first military ruler to hand over voluntarily; led the 1999 transition that ended military rule; won debt relief.",
    controversies: "Third-term attempt (2006, rejected by the Senate); human-rights record as military ruler (e.g. the 1977 'Dimka' trials); corruption allegations around his administration are documented by journalists and contested by supporters.",
    majorEvents: "The 1999 transition, the 2000 sharia adoption in northern states, the 2003 and 2007 elections, the debt-relief deal (2005), the 2006 third-term debate.",
    constitutionalRole: "Executive President under the 1999 constitution; two four-year terms.",
    historicalSignificance: "The dominant figure of Nigeria's return to democracy; the only Nigerian leader to serve as both military head of state and elected president.",
    summary: "Olusegun Obasanjo was military head of state (1976–79) and later Nigeria's first elected president of the Fourth Republic (1999–2007).",
    simple: "Obasanjo ruled Nigeria as a soldier, then handed power to civilians. Years later he was elected president and led Nigeria's new democracy.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.shagari",
    name: "Shehu Shagari",
    countryId: NIG,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "NPN",
    born: "1925 – 2018",
    officeStart: "1 October 1979",
    officeEnd: "31 December 1983",
    predecessor: "Olusegun Obasanjo (military)",
    successor: "Muhammadu Buhari (military)",
    cameToOffice: "Elected in the 1979 presidential election (the first of the Second Republic), re-elected in 1983.",
    ordinal: 6,
    majorPolicies: "The Green Revolution (agriculture), free education and health programs, the 'austerity' measures of 1982.",
    achievements: "First executive president of the Second Republic; the 1979–83 civilian interlude.",
    controversies: "The 1983 election was widely disputed; his government was overthrown on 31 December 1983 amid economic crisis and corruption allegations.",
    majorEvents: "The 1979 and 1983 elections, the oil-price collapse of the early 1980s, the 1982–83 austerity, the December 1983 coup.",
    constitutionalRole: "Executive President under the 1979 constitution (US-style separation of powers).",
    historicalSignificance: "The Second Republic's only president; his overthrow began a new round of military rule.",
    summary: "Shehu Shagari was the elected president of Nigeria's Second Republic (1979–83), overthrown by the military in December 1983.",
    simple: "Shagari was Nigeria's elected president in the Second Republic, but the army took over again at the end of 1983.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.buhari",
    name: "Muhammadu Buhari",
    countryId: NIG,
    title: "Military Head of State (1983–85); President (2015–2023)",
    titleKind: "president",
    role: "both",
    party: "APC (civilian terms)",
    born: "1942 –",
    officeStart: "31 December 1983",
    officeEnd: "29 May 2023",
    predecessor: "Shehu Shagari; (civilian) Goodluck Jonathan",
    successor: "Ibrahim Babangida (1985); Bola Tinubu (2023)",
    cameToOffice: "Seized power in the December 1983 coup; later won the 2015 and 2019 presidential elections.",
    ordinal: 7,
    majorPolicies: "Military term: 'War Against Indiscipline', austerity and anti-corruption campaigns. Civilian terms: anti-corruption (Buhari's EFCC-era), fight against Boko Haram, border closure (2019), economic reforms and the COVID-19 response.",
    achievements: "First opposition candidate to defeat an incumbent president (2015) — a landmark in Nigerian democracy; oversaw the end of the 2011–2016 insurgency's territorial phase.",
    controversies: "The 1984–85 military era's human-rights record (e.g. the 1984 drug-related executions, detentions); civilian-term issues include naira redesign disputes, fuel subsidy removal (2023), and documented security and economic challenges.",
    majorEvents: "The 1984–85 'War Against Indiscipline', the August 1985 coup; the 2015 defeat of Goodluck Jonathan, the 2019 re-election, the 2016 recession, the 2023 general elections.",
    constitutionalRole: "Military ruler by decree (1983–85); executive president under the 1999 constitution (2015–2023, two terms).",
    historicalSignificance: "The only Nigerian to rule as military head of state and later win two democratic elections; his 2015 victory is a milestone of African democratic transitions.",
    summary: "Muhammadu Buhari was Nigeria's military head of state (1983–85) and later president (2015–2023), defeating an incumbent in 2015.",
    simple: "Buhari first ruled Nigeria as a soldier in the 1980s. In 2015 he made history by winning an election against the sitting president.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.babangida",
    name: "Ibrahim Babangida",
    altNames: ["IBB"],
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1941 –",
    officeStart: "27 August 1985",
    officeEnd: "26 August 1993",
    predecessor: "Muhammadu Buhari",
    successor: "Ernest Shonekan (interim)",
    cameToOffice: "Seized power in the August 1985 coup.",
    ordinal: 8,
    majorPolicies: "Structural Adjustment Program (1986), creation of more states (21 → 30), the transition program to civilian rule, admission to the OIC debate, the annulment of the June 12 1993 election.",
    achievements: "Presided over economic liberalization and a long transition program; the 1993 election was regarded as free and fair by observers.",
    controversies: "The annulment of the June 12, 1993 presidential election (widely believed won by MKO Abiola) — one of the most consequential political crises in Nigerian history; the death of Dele Giwa (1986, letter bomb) is an unresolved documented controversy.",
    majorEvents: "SAP (1986), the creation of states, the two-party experiment (SDP/NRC), the June 12 1993 election and its annulment, the 1993 'handover' to an interim government.",
    constitutionalRole: "Ruled by decree; his transition produced the aborted Third Republic.",
    historicalSignificance: "His annulment of June 12 defined Nigerian politics for a decade and is still a reference point in Nigerian political discourse.",
    summary: "Ibrahim Babangida ruled Nigeria from 1985 to 1993; his annulment of the June 12, 1993 election remains one of the most consequential events in Nigerian political history.",
    simple: "Babangida was a military ruler who promised to return Nigeria to democracy, then cancelled the 1993 election many people believed was won by MKO Abiola.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.shonekan",
    name: "Ernest Shonekan",
    countryId: NIG,
    title: "Interim Head of State",
    titleKind: "transitional_leader",
    role: "head_of_state",
    born: "1936 – 2022",
    officeStart: "26 August 1993",
    officeEnd: "17 November 1993",
    predecessor: "Ibrahim Babangida",
    successor: "Sani Abacha",
    cameToOffice: "Appointed by Babangida as head of the Interim National Government after the June 12 annulment.",
    ordinal: 9,
    majorPolicies: "Attempted to stabilize the economy and organize fresh elections.",
    achievements: "Briefly headed the Interim National Government.",
    controversies: "His government was widely seen as illegitimate following the annulment; he was pushed out by Sani Abacha after about three months.",
    majorEvents: "The Interim National Government (August–November 1993), the political crisis over June 12, Abacha's takeover.",
    constitutionalRole: "Interim leader under the suspended transition; no elected mandate.",
    historicalSignificance: "A symbol of the botched transition after June 12.",
    summary: "Ernest Shonekan headed Nigeria's short-lived Interim National Government (August–November 1993) after the June 12 annulment.",
    simple: "After Babangida cancelled the 1993 election, Shonekan led a temporary government for a few months before Abacha took over.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.abacha",
    name: "Sani Abacha",
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1943 – 1998",
    officeStart: "17 November 1993",
    officeEnd: "8 June 1998",
    predecessor: "Ernest Shonekan",
    successor: "Abdulsalami Abubakar",
    cameToOffice: "Seized power in November 1993, forcing out the interim government.",
    ordinal: 10,
    majorPolicies: "Ruled by decree; launched a 'transition' program of his own design with a five-party system; pursued economic reforms under the IMF's shadow.",
    achievements: "Kept the federation intact and ran a managed transition (never completed in his lifetime).",
    controversies: "His regime is documented for the execution of Ken Saro-Wiwa and the Ogoni Nine (1995), the detention of MKO Abiola (who died in custody in 1998), suppression of the press and opposition, and vast corruption (the 'Abacha loot', later recovered in part).",
    majorEvents: "The 1995 executions, Nigeria's suspension from the Commonwealth, the 1998 death of Abiola and Abacha's own death in June 1998.",
    constitutionalRole: "Ruled by decree; the 1979 constitution remained suspended.",
    historicalSignificance: "His death in 1998 opened the path to the 1999 transition to democracy.",
    summary: "Sani Abacha ruled Nigeria from 1993 until his death in 1998 — a regime documented for human-rights abuses, corruption and the 1995 execution of Ken Saro-Wiwa.",
    simple: "Abacha was a military ruler known for harsh rule. When he died in 1998, Nigeria began its journey back to democracy.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.abdulsalami",
    name: "Abdulsalami Abubakar",
    countryId: NIG,
    title: "Military Head of State",
    titleKind: "military_ruler",
    role: "head_of_state",
    born: "1942 –",
    officeStart: "9 June 1998",
    officeEnd: "29 May 1999",
    predecessor: "Sani Abacha",
    successor: "Olusegun Obasanjo (elected president)",
    cameToOffice: "Assumed power after Abacha's death.",
    ordinal: 11,
    majorPolicies: "Restored the transition to democracy: released political prisoners, freed the press, and organized the 1999 elections.",
    achievements: "Handed power to an elected government in May 1999 — Nigeria's return to democracy.",
    controversies: "Generally credited for the smooth transition; the 1999 election had documented irregularities but was accepted.",
    majorEvents: "The 1998–99 transition, the new 1999 constitution, the February 1999 presidential election.",
    constitutionalRole: "Oversaw the restoration of constitutional government.",
    historicalSignificance: "The military ruler who returned Nigeria to democracy.",
    summary: "Abdulsalami Abubakar ruled Nigeria from 1998 to 1999 and organized the transition that returned the country to democratic government.",
    simple: "After Abacha died, Abdulsalami Abubakar led Nigeria for a year and organized the elections that brought back democracy.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.yaradua",
    name: "Umaru Musa Yar'Adua",
    countryId: NIG,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "PDP",
    born: "1951 – 2010",
    officeStart: "29 May 2007",
    officeEnd: "5 May 2010",
    predecessor: "Olusegun Obasanjo",
    successor: "Goodluck Jonathan",
    cameToOffice: "Elected in the 2007 presidential election (the first civilian-to-civilian transfer in Nigeria's history).",
    ordinal: 12,
    majorPolicies: "The Seven-Point Agenda (power, food security, education, Niger Delta amnesty); began the amnesty program for Niger Delta militants (2009); the 'doctrine of necessity' controversy over his health.",
    achievements: "The Niger Delta amnesty (2009) sharply reduced conflict in the oil region.",
    controversies: "The 2007 election was widely criticized; his long illness and absence from office (November 2009 – February 2010) created a constitutional crisis resolved by the 'doctrine of necessity' that made Jonathan acting president.",
    majorEvents: "The 2007 election, the amnesty (2009), the illness crisis and the doctrine of necessity (2010), his death on 5 May 2010.",
    constitutionalRole: "Executive President; his illness tested the 1999 constitution's succession rules.",
    historicalSignificance: "First civilian-to-civilian transfer; his death triggered the first vice-presidential succession under the 1999 constitution.",
    summary: "Umaru Musa Yar'Adua was Nigeria's president from 2007 until his death in 2010; his illness created the 'doctrine of necessity' crisis.",
    simple: "Yar'Adua became president in 2007. He was often ill, and when he died in 2010 his deputy Jonathan took over.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.jonathan",
    name: "Goodluck Jonathan",
    countryId: NIG,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "PDP",
    born: "1957 –",
    officeStart: "5 May 2010",
    officeEnd: "29 May 2015",
    predecessor: "Umaru Musa Yar'Adua",
    successor: "Muhammadu Buhari",
    cameToOffice: "Succeeded Yar'Adua (acting president from February 2010); won the 2011 presidential election.",
    ordinal: 13,
    majorPolicies: "Transformation Agenda, power-sector privatization, the 2011 fuel subsidy removal (reversed after protests), the state of emergency in the northeast, and the 2015 elections.",
    achievements: "Conceded defeat in the 2015 election — the first incumbent in Nigeria to lose and concede peacefully, a milestone for African democracy.",
    controversies: "The 2011 post-election violence (documented, with official reports), the 2014 Chibok schoolgirls kidnapping and the government's response, corruption allegations against his administration (he has denied them), and the 2015 campaign's security challenges.",
    majorEvents: "The 2011 election, the Occupy Nigeria protests (2012), the 2013 state of emergency, the Chibok kidnapping (2014), the 2015 election and his concession.",
    constitutionalRole: "Executive President under the 1999 constitution.",
    historicalSignificance: "His peaceful concession in 2015 is one of the defining moments of Nigerian and African democratic history.",
    summary: "Goodluck Jonathan was Nigeria's president (2010–2015) and made history by conceding defeat in the 2015 election.",
    simple: "Jonathan became president in 2010 and won again in 2011. In 2015 he lost the election and peacefully handed over — a big moment for democracy.",
  }),
  buildLeader({
    id: "pol.leader.nigeria.tinubu",
    name: "Bola Tinubu",
    countryId: NIG,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "APC",
    born: "1952 –",
    officeStart: "29 May 2023",
    officeEnd: "",
    predecessor: "Muhammadu Buhari",
    successor: "",
    cameToOffice: "Won the 2023 presidential election; INEC declared him winner with 36.6% of the vote. The Supreme Court affirmed the result in October 2023 after opposition challenges.",
    ordinal: 14,
    majorPolicies: "The 'Renewed Hope' agenda; fuel-subsidy removal (May 2023), exchange-rate unification, tax and economic reforms, student-loan scheme, and the 2023–24 cost-of-living crisis response.",
    achievements: "The first president to complete a full transition from the Buhari era; his reforms (subsidy removal, FX unification) are supported by some economists and criticized by others.",
    controversies: "The 2023 election was disputed by the opposition (challenges dismissed by tribunals and the Supreme Court); the subsidy removal's inflationary impact and his health records during the campaign are documented controversies.",
    majorEvents: "The 2023 general elections, the May 2023 subsidy removal, the October 2023 Supreme Court ruling, the 2024 #EndBadGovernance protests, the 2025 constitutional review debates.",
    constitutionalRole: "Executive President under the 1999 constitution; two-term limit applies.",
    historicalSignificance: "Current president as of the Last Verified date; his reform program and the 2027 election will define his historical significance.",
    summary: "Bola Tinubu is Nigeria's president, in office since 29 May 2023 following the disputed but court-affirmed 2023 election.",
    simple: "Tinubu became Nigeria's president in 2023 after a close election. His government removed the fuel subsidy and is reforming the economy.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_INEC, SRC_JOURNALISM],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §9 — Nigeria's major political parties
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_PARTIES: PartyRecord[] = [
  buildParty({
    id: "pol.party.nigeria.ncnc",
    name: "National Council of Nigeria and the Cameroons (NCNC)",
    abbreviation: "NCNC",
    countryId: NIG,
    founded: "1944",
    founders: ["Nnamdi Azikiwe", "Herbert Macaulay"],
    selfDescription: "The leading nationalist party of the independence era.",
    academicClassification: "Mass nationalist party; historically dominant among Igbo and eastern constituencies; social-democratic in rhetoric.",
    position: "Center-left nationalist (with context: parties of the First Republic were regionally based).",
    majorLeaders: ["Herbert Macaulay", "Nnamdi Azikiwe", "Mbonu Ojike"],
    historicalDevelopment: "Founded in 1944 as a nationalist umbrella; led the eastern region and the 1950s independence campaigns; governed the Eastern Region and later joined the 1960s coalition.",
    electoralHistory: "Won the eastern region in the 1951, 1954 and 1959 elections; part of the 1959–64 federal coalition.",
    currentStatus: "Defunct after the 1966 coups; its successor traditions fed into later parties (e.g. the NPP and later the PDP's eastern base).",
    governmentParticipation: "Federal coalition partner 1959–64; governed the Eastern Region.",
    historicalSignificance: "One of the two great parties of Nigeria's independence movement.",
    summary: "The NCNC was the nationalist party of Nnamdi Azikiwe and Herbert Macaulay, a leading force for Nigerian independence.",
    simple: "The NCNC was one of the big parties that fought for Nigeria's independence, led by Nnamdi Azikiwe.",
  }),
  buildParty({
    id: "pol.party.nigeria.npc",
    name: "Northern People's Congress (NPC)",
    abbreviation: "NPC",
    countryId: NIG,
    founded: "1951 (as a cultural association from 1949)",
    founders: ["Ahmadu Bello", "Abubakar Tafawa Balewa"],
    selfDescription: "The party of the Northern Region's established order.",
    academicClassification: "Conservative, regionally dominant party of the Hausa-Fulani north; linked to the traditional emirate system.",
    position: "Conservative (regional-conservative with context).",
    majorLeaders: ["Ahmadu Bello (Sardauna of Sokoto)", "Abubakar Tafawa Balewa"],
    historicalDevelopment: "Grew from the Jamiyyar Mutanen Arewa cultural association; dominated the Northern Region and the First Republic's federal government.",
    electoralHistory: "Won the Northern Region in 1951–59; led the 1959 federal coalition government under Balewa.",
    currentStatus: "Defunct after 1966; its traditions influenced later northern parties (NPN, and indirectly the APC's northern base).",
    governmentParticipation: "Led the First Republic federal government (1959–66).",
    historicalSignificance: "Represented the north's political establishment in the First Republic.",
    summary: "The NPC was the dominant party of Nigeria's Northern Region in the First Republic, led by Ahmadu Bello and Abubakar Tafawa Balewa.",
    simple: "The NPC was the powerful party of northern Nigeria in the early independence years.",
  }),
  buildParty({
    id: "pol.party.nigeria.action-group",
    name: "Action Group (AG)",
    abbreviation: "AG",
    countryId: NIG,
    founded: "1951",
    founders: ["Obafemi Awolowo"],
    selfDescription: "A progressive party for the Western Region.",
    academicClassification: "Regionally based, progressive/liberal party of the Yoruba west; associated with free education and welfare policy.",
    position: "Center-left (regional-progressive with context).",
    majorLeaders: ["Obafemi Awolowo", "Samuel Akintola", "Anthony Enahoro"],
    historicalDevelopment: "Founded by Awolowo; introduced free primary education in the Western Region; split in 1962 (Awolowo vs Akintola) which triggered the Western Region crisis.",
    electoralHistory: "Governed the Western Region 1951–1962; led the opposition in the 1959 federal election.",
    currentStatus: "Defunct after 1966; its ideology influenced later progressive parties and Awolowo's legacy remains central to Yoruba politics.",
    governmentParticipation: "Western Region government; federal opposition.",
    historicalSignificance: "Its free-education policy and the 1962 crisis shaped Nigeria's First Republic.",
    summary: "The Action Group was the progressive party of Nigeria's Western Region under Obafemi Awolowo, known for free education.",
    simple: "The Action Group was the party of the west, led by Awolowo, famous for introducing free primary school.",
  }),
  buildParty({
    id: "pol.party.nigeria.npn",
    name: "National Party of Nigeria (NPN)",
    abbreviation: "NPN",
    countryId: NIG,
    founded: "1978 (Second Republic)",
    founders: ["A nationwide coalition of former NPC and other political elites"],
    selfDescription: "The ruling party of the Second Republic.",
    academicClassification: "Conservative, northern-dominated catch-all party of the Second Republic.",
    position: "Center-right (with context).",
    majorLeaders: ["Shehu Shagari", "Adisa Akinloye", "Alex Ekwueme"],
    historicalDevelopment: "Won the 1979 and 1983 elections; governed under Shagari until the December 1983 coup.",
    electoralHistory: "Won 1979 and 1983 presidential elections; held a parliamentary majority (1979–83).",
    currentStatus: "Defunct after 1983.",
    governmentParticipation: "Federal government 1979–83.",
    historicalSignificance: "The Second Republic's ruling party.",
    summary: "The NPN governed Nigeria's Second Republic under President Shehu Shagari (1979–83).",
    simple: "The NPN was the ruling party when Shagari was president in the early 1980s.",
  }),
  buildParty({
    id: "pol.party.nigeria.sdp",
    name: "Social Democratic Party (SDP)",
    abbreviation: "SDP",
    countryId: NIG,
    founded: "1989 (one of the two parties of the Babangida transition)",
    selfDescription: "A 'little broad' center-left party of the aborted Third Republic.",
    academicClassification: "One of the two state-created parties of the 1989–93 transition (with the NRC); produced the June 12 1993 election.",
    position: "Center-left (state-crafted with context).",
    majorLeaders: ["MKO Abiola", "Baba Gana Kingibe", "Shehu Musa Yar'Adua"],
    historicalDevelopment: "Created by the Babangida regime's two-party experiment; its presidential candidate MKO Abiola won the June 12 1993 election, which was annulled.",
    electoralHistory: "Won the annulled June 12 1993 presidential election (per domestic and international observers).",
    currentStatus: "Defunct; revived as a minor party in the Fourth Republic.",
    governmentParticipation: "Never formed government due to the annulment.",
    historicalSignificance: "The party of June 12 — the annulled election that defined Nigerian democracy.",
    summary: "The SDP was one of the two parties of the aborted Third Republic; its candidate MKO Abiola won the annulled June 12, 1993 election.",
    simple: "The SDP was the party of MKO Abiola, who won the 1993 election that was cancelled.",
  }),
  buildParty({
    id: "pol.party.nigeria.pdp",
    name: "People's Democratic Party (PDP)",
    abbreviation: "PDP",
    countryId: NIG,
    founded: "1998",
    selfDescription: "The party of Nigeria's return to democracy.",
    academicClassification: "Broad catch-all party; dominated the Fourth Republic's first 16 years; internal factions matter more than ideology.",
    position: "Catch-all center (with context: Nigerian parties are broad coalitions).",
    majorLeaders: ["Olusegun Obasanjo", "Umaru Musa Yar'Adua", "Goodluck Jonathan", "Atiku Abubakar"],
    historicalDevelopment: "Founded ahead of the 1999 transition; won every presidential election from 1999 to 2011; lost power in 2015.",
    electoralHistory: "Won 1999, 2003, 2007, 2011 presidential elections; lost 2015, 2019, 2023; governs many states.",
    currentStatus: "Active; the main opposition party at the federal level (as of the Last Verified date).",
    governmentParticipation: "Federal government 1999–2015; many state governments.",
    historicalSignificance: "The party of the Fourth Republic's first 16 years.",
    summary: "The PDP ruled Nigeria from 1999 to 2015 and remains a major party and the main federal opposition.",
    simple: "The PDP was the party in power for Nigeria's first 16 years of democracy.",
  }),
  buildParty({
    id: "pol.party.nigeria.apc",
    name: "All Progressives Congress (APC)",
    abbreviation: "APC",
    countryId: NIG,
    founded: "2013 (merger)",
    founders: ["ACN, ANPP, CPC and a faction of APGA"],
    selfDescription: "A progressive merger party.",
    academicClassification: "Broad catch-all coalition of opposition parties; northern-conservative and southwestern-liberal wings.",
    position: "Catch-all center-right (with context).",
    majorLeaders: ["Muhammadu Buhari", "Bola Tinubu", "Yemi Osinbajo", "Adams Oshiomhole"],
    historicalDevelopment: "Formed by the 2013 merger of major opposition parties; defeated the PDP in 2015 — the first opposition victory in Nigerian history.",
    electoralHistory: "Won 2015, 2019 and 2023 presidential elections.",
    currentStatus: "Active; the federal ruling party (as of the Last Verified date).",
    governmentParticipation: "Federal government since 2015; many state governments.",
    historicalSignificance: "The party that ended the PDP era with the 2015 defeat of an incumbent.",
    summary: "The APC, formed in 2013, defeated the PDP in 2015 and has governed Nigeria since.",
    simple: "The APC is the party that won the 2015 election and has ruled Nigeria since then.",
  }),
  buildParty({
    id: "pol.party.nigeria.lp",
    name: "Labour Party (LP)",
    abbreviation: "LP",
    countryId: NIG,
    founded: "2002 (registered 2002; rose to prominence 2022–23)",
    selfDescription: "A progressive, labour-rooted party.",
    academicClassification: "Center-left party with labour origins; surged in 2023 behind Peter Obi.",
    position: "Center-left (with context).",
    majorLeaders: ["Julius Abure", "Peter Obi (2023 presidential candidate)", "organized labour links"],
    historicalDevelopment: "Founded with labour movement roots; Peter Obi's 2023 campaign (after leaving the PDP) made it the third force in Nigerian politics, especially among young voters.",
    electoralHistory: "Won one state (Anambra, via Alex Otti) in 2023; Obi finished third in the 2023 presidential race per INEC results.",
    currentStatus: "Active; a major opposition force.",
    governmentParticipation: "Governs Abia State (2023– ); no federal government.",
    historicalSignificance: "The 'Obidient' movement's 2023 surge reshaped Nigerian electoral politics.",
    summary: "The Labour Party, long a minor party, surged in 2023 behind Peter Obi's presidential campaign.",
    simple: "The Labour Party became famous in 2023 when Peter Obi ran for president and won millions of young supporters.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §10 — Nigeria's presidential elections
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_ELECTIONS: ElectionRecord[] = [
  buildElection({
    id: "pol.election.nigeria.1979",
    name: "Nigerian presidential election, 1979",
    countryId: NIG,
    electionType: "Presidential",
    date: "11 August 1979",
    year: 1979,
    turnout: "~35%",
    winner: "Shehu Shagari (NPN)",
    winnerParty: "NPN",
    runnerUp: "Obafemi Awolowo (UPN)",
    resultSummary: "Shagari won with about 5.7 million votes (33.8%); Awolowo ~4.9 million (29.2%). Shagari cleared the constitutional requirement of 25% in 2/3 of states (the '2/3 of 19' question was resolved by the Supreme Court).",
    electoralSystem: "Direct popular vote with a constitutional requirement of a plurality plus 25% in at least two-thirds of states.",
    importance: "The first presidential election of the Second Republic, ending 13 years of military rule.",
    disputes: "Awolowo and the UPN challenged the result; the Supreme Court resolved the two-thirds question in Shagari's favor.",
    candidates: ["Shehu Shagari", "Obafemi Awolowo", "Nnamdi Azikiwe", "Aminu Kano", "Waziri Ibrahim"],
  }),
  buildElection({
    id: "pol.election.nigeria.1983",
    name: "Nigerian presidential election, 1983",
    countryId: NIG,
    electionType: "Presidential",
    date: "6 August 1983",
    year: 1983,
    winner: "Shehu Shagari (NPN, re-elected)",
    runnerUp: "Obafemi Awolowo (UPN)",
    resultSummary: "Shagari was declared re-elected with about 12 million votes (47.5%) to Awolowo's ~7.9 million (31%).",
    electoralSystem: "Direct popular vote with the 25%-in-two-thirds rule.",
    importance: "The Second Republic's second election; its credibility was widely questioned and the military used alleged rigging as a justification for the December 31 coup.",
    disputes: "Widespread documented allegations of rigging and violence; the election's integrity is disputed.",
    candidates: ["Shehu Shagari", "Obafemi Awolowo", "Nnamdi Azikiwe", "Aminu Kano", "Hassan Yusuf"],
  }),
  buildElection({
    id: "pol.election.nigeria.1993",
    name: "Nigerian presidential election, 12 June 1993",
    countryId: NIG,
    electionType: "Presidential",
    date: "12 June 1993",
    year: 1993,
    turnout: "~35%",
    winner: "MKO Abiola (SDP) — result annulled",
    runnerUp: "Bashir Tofa (NRC)",
    resultSummary: "Interim results indicated an Abiola victory (about 58% of the vote) with strong support across regions; the election was widely judged free and fair by domestic and international observers.",
    electoralSystem: "Direct popular vote under the two-party system (SDP vs NRC).",
    importance: "The freest election in Nigerian history up to that point — and its annulment by Ibrahim Babangida on 23 June 1993 triggered the country's worst political crisis since the civil war.",
    disputes: "The annulment itself is the dispute; Abiola's victory is accepted by most observers and was never officially certified.",
    candidates: ["MKO Abiola", "Bashir Tofa"],
  }),
  buildElection({
    id: "pol.election.nigeria.1999",
    name: "Nigerian presidential election, 1999",
    countryId: NIG,
    electionType: "Presidential",
    date: "27 February 1999",
    year: 1999,
    turnout: "~52%",
    winner: "Olusegun Obasanjo (PDP)",
    winnerParty: "PDP",
    runnerUp: "Olu Falae (AD/APP joint candidate)",
    resultSummary: "Obasanjo won with about 18.7 million votes (62.8%) to Falae's ~11.1 million (37.2%), per INEC.",
    electoralSystem: "Direct popular vote, simple plurality.",
    importance: "The election that ended military rule and began the Fourth Republic.",
    disputes: "Falae challenged the result; the tribunal and Supreme Court upheld Obasanjo's victory.",
    candidates: ["Olusegun Obasanjo", "Olu Falae"],
  }),
  buildElection({
    id: "pol.election.nigeria.2003",
    name: "Nigerian presidential election, 2003",
    countryId: NIG,
    electionType: "Presidential",
    date: "19 April 2003",
    year: 2003,
    winner: "Olusegun Obasanjo (PDP, re-elected)",
    runnerUp: "Muhammadu Buhari (ANPP)",
    resultSummary: "Obasanjo won with about 24.5 million votes (61.9%) to Buhari's ~12.7 million (32.2%), per INEC.",
    electoralSystem: "Direct popular vote.",
    importance: "The first re-election of a civilian president; the first election under the Fourth Republic's framework with an opposition challenge.",
    disputes: "Opposition alleged irregularities; international observers noted serious problems while accepting the result.",
    candidates: ["Olusegun Obasanjo", "Muhammadu Buhari", "Olu Falae", "Odumegwu Ojukwu"],
  }),
  buildElection({
    id: "pol.election.nigeria.2007",
    name: "Nigerian presidential election, 2007",
    countryId: NIG,
    electionType: "Presidential",
    date: "21 April 2007",
    year: 2007,
    winner: "Umaru Musa Yar'Adua (PDP)",
    runnerUp: "Muhammadu Buhari (ANPP)",
    resultSummary: "Yar'Adua won with about 24.6 million votes (70%); Buhari ~6.6 million (18.7%), per INEC.",
    electoralSystem: "Direct popular vote.",
    importance: "The first civilian-to-civilian transfer of power in Nigerian history.",
    disputes: "The 2007 election was widely condemned by observers as deeply flawed; courts overturned many results; a post-election review led to electoral reforms (the 2010 Electoral Act).",
    candidates: ["Umaru Musa Yar'Adua", "Muhammadu Buhari", "Atiku Abubakar", "Orji Uzor Kalu"],
  }),
  buildElection({
    id: "pol.election.nigeria.2011",
    name: "Nigerian presidential election, 2011",
    countryId: NIG,
    electionType: "Presidential",
    date: "16 April 2011",
    year: 2011,
    turnout: "~54%",
    winner: "Goodluck Jonathan (PDP)",
    runnerUp: "Muhammadu Buhari (CPC)",
    resultSummary: "Jonathan won with about 22.5 million votes (58.9%) to Buhari's ~12.2 million (32%), per INEC.",
    electoralSystem: "Direct popular vote.",
    importance: "Widely regarded as the most credible election since 1993; but the result triggered post-election violence in the north, documented by Human Rights Watch.",
    disputes: "Buhari challenged the result; courts upheld Jonathan's victory.",
    candidates: ["Goodluck Jonathan", "Muhammadu Buhari", "Nuhu Ribadu"],
  }),
  buildElection({
    id: "pol.election.nigeria.2015",
    name: "Nigerian presidential election, 2015",
    countryId: NIG,
    electionType: "Presidential",
    date: "28 March 2015",
    year: 2015,
    turnout: "~44%",
    winner: "Muhammadu Buhari (APC)",
    winnerParty: "APC",
    runnerUp: "Goodluck Jonathan (PDP, incumbent)",
    resultSummary: "Buhari won with about 15.4 million votes (53.96%) to Jonathan's ~12.9 million (44.96%), per INEC.",
    electoralSystem: "Direct popular vote.",
    importance: "The first time in Nigerian history that an opposition candidate defeated an incumbent president — and Jonathan conceded peacefully.",
    disputes: "Jonathan conceded before the full count; the election was judged credible by international observers.",
    candidates: ["Muhammadu Buhari", "Goodluck Jonathan"],
  }),
  buildElection({
    id: "pol.election.nigeria.2019",
    name: "Nigerian presidential election, 2019",
    countryId: NIG,
    electionType: "Presidential",
    date: "23 February 2019",
    year: 2019,
    turnout: "~35%",
    winner: "Muhammadu Buhari (APC, re-elected)",
    runnerUp: "Atiku Abubakar (PDP)",
    resultSummary: "Buhari won with about 15.2 million votes (55.6%) to Atiku's ~11.3 million (41.2%), per INEC.",
    electoralSystem: "Direct popular vote.",
    importance: "The first re-election of an incumbent since 2003; the election was delayed by one week hours before polls opened.",
    disputes: "Atiku challenged the result; the tribunal and Supreme Court upheld Buhari's victory.",
    candidates: ["Muhammadu Buhari", "Atiku Abubakar"],
  }),
  buildElection({
    id: "pol.election.nigeria.2023",
    name: "Nigerian presidential election, 2023",
    countryId: NIG,
    electionType: "Presidential",
    date: "25 February 2023",
    year: 2023,
    turnout: "~27%",
    winner: "Bola Tinubu (APC)",
    runnerUp: "Atiku Abubakar (PDP)",
    resultSummary: "Per INEC's final results: Tinubu 8.79 million (36.6%), Atiku 6.98 million (29.1%), Peter Obi (LP) 6.10 million (25.4%), Rabiu Kwankwaso (NNPP) 1.5 million (6.4%).",
    electoralSystem: "Direct popular vote; winner must have the most votes and 25% in two-thirds of states (a new requirement of the 2022 Electoral Act).",
    importance: "The first election under the 2022 Electoral Act (including the electronic transmission of results); the opposition's legal challenges reached the Supreme Court, which affirmed Tinubu's victory in October 2023.",
    disputes: "The LP and PDP challenged the results, alleging irregularities; the Presidential Election Petition Tribunal and the Supreme Court dismissed the challenges.",
    candidates: ["Bola Tinubu", "Atiku Abubakar", "Peter Obi", "Rabiu Kwankwaso"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §6 — Lagos State governors (the spec's example)
 * ════════════════════════════════════════════════════════════════════════════ */

export const LAGOS_GOVERNORS: OfficeHolderRecord[] = [
  buildOfficeHolder({
    id: "pol.gov.lagos.johnson",
    name: "Mobolaji Johnson",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    term: "1967 – 1975",
    cameToOffice: "First governor after Lagos State was created in 1967.",
    majorWork: "Established the new state's administration.",
    summary: "Mobolaji Johnson was Lagos State's first governor (1967–1975).",
    simple: "He was the first governor of Lagos State.",
  }),
  buildOfficeHolder({
    id: "pol.gov.lagos.jakande",
    name: "Lateef Jakande",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    party: "UPN",
    term: "1979 – 1983",
    cameToOffice: "Elected in 1979 (Second Republic).",
    majorWork: "Free education and health programs, low-cost housing estates, the Lagos State University founding (1983).",
    summary: "Lateef Jakande was the first elected governor of Lagos State (1979–83), famous for mass housing and free education.",
    simple: "Jakande was Lagos's first elected governor, known for building houses and schools.",
  }),
  buildOfficeHolder({
    id: "pol.gov.lagos.tinubu",
    name: "Bola Tinubu",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    party: "AD (later AC)",
    term: "1999 – 2007",
    cameToOffice: "Elected in 1999; re-elected 2003.",
    majorWork: "Internally Generated Revenue (IGR) reforms, urban development, creation of new local governments; later president (2023).",
    summary: "Bola Tinubu was governor of Lagos State (1999–2007), credited with pioneering the state's internally generated revenue system.",
    simple: "Tinubu ran Lagos State from 1999 to 2007 and made the state less dependent on federal money.",
  }),
  buildOfficeHolder({
    id: "pol.gov.lagos.fashola",
    name: "Babatunde Fashola",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    party: "AC (later APC)",
    term: "2007 – 2015",
    cameToOffice: "Elected in 2007; re-elected 2011.",
    majorWork: "Transport and infrastructure projects (BRT, Lekki), tax administration, environmental programs.",
    summary: "Babatunde Fashola was governor of Lagos State (2007–2015), known for infrastructure and the BRT bus system.",
    simple: "Fashola ran Lagos for eight years and built roads, buses and other infrastructure.",
  }),
  buildOfficeHolder({
    id: "pol.gov.lagos.ambode",
    name: "Akinwunmi Ambode",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    party: "APC",
    term: "2015 – 2019",
    cameToOffice: "Elected in 2015.",
    majorWork: "Transport (the Lagos Light Rail work), infrastructure, and the 'Lagos at 50' programs.",
    summary: "Akinwunmi Ambode was governor of Lagos State (2015–2019).",
    simple: "Ambode was Lagos governor from 2015 to 2019.",
  }),
  buildOfficeHolder({
    id: "pol.gov.lagos.sanwo-olu",
    name: "Babajide Sanwo-Olu",
    countryId: NIG,
    office: "Governor of Lagos State",
    officeKind: "governor",
    jurisdiction: "Lagos State",
    party: "APC",
    term: "2019 – present",
    cameToOffice: "Elected in 2019; re-elected in 2023.",
    majorWork: "The Blue Line rail (Lagos's first metro), the COVID-19 response, the 'Greater Lagos' agenda.",
    summary: "Babajide Sanwo-Olu is the current governor of Lagos State (since 2019, re-elected 2023).",
    simple: "Sanwo-Olu is the governor of Lagos State today.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §7 — Illustrative legislator (historical; current legislators are dynamic)
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_LEGISLATORS: OfficeHolderRecord[] = [
  buildOfficeHolder({
    id: "pol.leg.nigeria.enahoro",
    name: "Anthony Enahoro",
    countryId: NIG,
    office: "Member of Parliament (Western Region and Federal)",
    officeKind: "mp",
    jurisdiction: "Federal Parliament, Nigeria",
    party: "Action Group",
    term: "1951 – 1966",
    cameToOffice: "Elected in 1951; at 26, the youngest MP in the Western House of Assembly.",
    majorWork: "Moved the 1953 motion for self-government 'now' — a landmark in the independence struggle; later a federal minister.",
    summary: "Anthony Enahoro was the MP whose 1953 motion for immediate self-government became a milestone of Nigeria's independence movement.",
    simple: "Enahoro was a young member of parliament who in 1953 demanded independence 'now'.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §8 — Nigeria's ministries (illustrative; ministry names differ by
 * administration — the spec's own example)
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_MINISTRIES: MinistryRecord[] = [
  buildMinistry({
    id: "pol.ministry.nigeria.finance",
    name: "Ministry of Finance",
    countryId: NIG,
    minister: "Wale Edun (as of the Last Verified date)",
    appointmentDate: "2023",
    previousMinister: "Zainab Ahmed",
    responsibilities: "Federal budget, fiscal policy, revenue and debt management.",
    historicalMinisters: ["Okonjo-Iweala", "Zainab Ahmed", "Kemi Adeosun"],
    note: "Ministerial titles and portfolios change with each administration.",
    summary: "The Federal Ministry of Finance manages Nigeria's fiscal policy and budget.",
    simple: "The Finance Ministry handles the country's money and budget.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT],
  }),
  buildMinistry({
    id: "pol.ministry.nigeria.foreign",
    name: "Ministry of Foreign Affairs",
    countryId: NIG,
    minister: "Yusuf Tuggar (as of the Last Verified date)",
    appointmentDate: "2023",
    responsibilities: "Nigeria's foreign policy, embassies and international relations.",
    historicalMinisters: ["Nuhu Ribadu (special duties, 2023–24)", "Geoffrey Onyeama"],
    summary: "The Ministry of Foreign Affairs conducts Nigeria's diplomacy.",
    simple: "The Foreign Ministry handles Nigeria's relationships with other countries.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT],
  }),
  buildMinistry({
    id: "pol.ministry.nigeria.defence",
    name: "Ministry of Defence",
    countryId: NIG,
    minister: "Mohammed Badaru Abubakar (as of the Last Verified date)",
    appointmentDate: "2023",
    responsibilities: "The armed forces, defence policy and national security coordination.",
    historicalMinisters: ["Bashir Magashi", "Mansur Dan Ali"],
    summary: "The Ministry of Defence oversees Nigeria's armed forces.",
    simple: "The Defence Ministry manages the army, navy and air force.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §11 — Nigeria's constitutions
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_CONSTITUTIONS: ConstitutionRecord[] = [
  buildConstitution({
    id: "pol.constitution.nigeria.1960",
    name: "Independence Constitution (1960)",
    countryId: NIG,
    adopted: "1 October 1960",
    previousConstitutions: ["The colonial constitutions (1922, 1946 Richards, 1951 Macpherson, 1954 Lyttleton)"],
    separationOfPowers: "Westminster model: a ceremonial Governor-General, a Prime Minister and cabinet responsible to parliament.",
    executivePowers: "Exercised by the Prime Minister and cabinet.",
    legislativePowers: "A federal Parliament (Senate and House of Representatives).",
    judicialPowers: "An independent judiciary with appeals to the Privy Council.",
    federalism: "A federation of three regions (North, West, East) plus the federal territory of Lagos.",
    electoralProvisions: "Regional and federal elections under the first-past-the-post system.",
    termLimits: "Not applicable (Westminster model).",
    emergencyPowers: "Emergency provisions modeled on the British model.",
    successionRules: "Governor-General and Prime Minister successions per convention.",
    rightsFreedoms: "A chapter of fundamental rights was included at the regions' insistence.",
    constitutionalCourt: "No dedicated constitutional court; the Supreme Court was the final court of appeal until 1963.",
    amendments: [],
    history: "Negotiated at the 1957 and 1958 London conferences; Nigeria became independent on 1 October 1960 under this constitution.",
    summary: "The 1960 Independence Constitution made Nigeria a federal parliamentary dominion under the Crown.",
    simple: "When Nigeria became independent in 1960, it used a British-style system with a prime minister.",
  }),
  buildConstitution({
    id: "pol.constitution.nigeria.1963",
    name: "Republican Constitution (1963)",
    countryId: NIG,
    adopted: "1 October 1963",
    previousConstitutions: ["The 1960 Independence Constitution"],
    separationOfPowers: "Westminster model retained; the Queen's role replaced by a ceremonial President.",
    executivePowers: "The Prime Minister and cabinet (executive); the President ceremonial.",
    legislativePowers: "Federal Parliament (Senate and House of Representatives).",
    judicialPowers: "Independent judiciary; appeals to the Privy Council abolished.",
    federalism: "Three regions (later four, after the Midwest Region was created in 1963).",
    electoralProvisions: "First-past-the-post.",
    termLimits: "Not applicable.",
    emergencyPowers: "Retained from 1960.",
    successionRules: "The President elected by a joint sitting of Parliament.",
    rightsFreedoms: "Fundamental rights chapter retained.",
    constitutionalCourt: "The Supreme Court became the final court of appeal.",
    amendments: [],
    history: "Nigeria became a republic within the Commonwealth on 1 October 1963; Nnamdi Azikiwe became the first President.",
    summary: "The 1963 Republican Constitution made Nigeria a republic with a ceremonial president.",
    simple: "In 1963 Nigeria became a republic and got its own president instead of the Queen.",
  }),
  buildConstitution({
    id: "pol.constitution.nigeria.1979",
    name: "Constitution of the Federal Republic of Nigeria (1979)",
    countryId: NIG,
    adopted: "1 October 1979",
    previousConstitutions: ["1960, 1963"],
    separationOfPowers: "US-style: a powerful executive President, a National Assembly, and an independent judiciary.",
    executivePowers: "The President is both head of state and head of government, with a two-term limit.",
    legislativePowers: "A bicameral National Assembly (Senate and House of Representatives).",
    judicialPowers: "Independent courts; the Supreme Court at the apex.",
    federalism: "19 states plus the Federal Capital Territory (Abuja).",
    electoralProvisions: "Presidential election requires a plurality plus 25% in at least two-thirds of states.",
    termLimits: "President limited to two four-year terms.",
    emergencyPowers: "The President may declare a state of emergency with legislative approval.",
    successionRules: "The Vice-President succeeds if the presidency is vacant.",
    rightsFreedoms: "A full fundamental-rights chapter.",
    constitutionalCourt: "No separate court; the judiciary reviews constitutionality.",
    amendments: [],
    history: "Drafted by the 1977–78 Constitution Drafting Committee and the Constituent Assembly; brought in the Second Republic.",
    summary: "The 1979 Constitution introduced the American-style presidential system that Nigeria has used since.",
    simple: "In 1979 Nigeria changed to a system like America's, with a strong elected president.",
  }),
  buildConstitution({
    id: "pol.constitution.nigeria.1999",
    name: "Constitution of the Federal Republic of Nigeria (1999)",
    countryId: NIG,
    adopted: "29 May 1999",
    previousConstitutions: ["1960, 1963, 1979"],
    separationOfPowers: "Presidential system with checks and balances across the executive, legislature and judiciary.",
    executivePowers: "The President is head of state and government, elected for two four-year terms; a two-thirds majority in the National Assembly can override a presidential veto.",
    legislativePowers: "Bicameral National Assembly: a 109-member Senate (3 per state + FCT) and a 360-member House of Representatives.",
    judicialPowers: "An independent judiciary; the Supreme Court is the apex court; state and federal courts are established by law.",
    federalism: "36 states, the Federal Capital Territory (Abuja), and 774 local government areas.",
    electoralProvisions: "Presidential election: most votes plus 25% in two-thirds of states (per the 1999 constitution; the 2022 Electoral Act added electronic transmission); INEC administers elections.",
    termLimits: "President and governors limited to two four-year terms.",
    emergencyPowers: "The President can declare a state of emergency in a state with the approval of the National Assembly.",
    successionRules: "The Vice-President succeeds on the president's death, resignation or removal (tested in 2010 by the 'doctrine of necessity').",
    rightsFreedoms: "Chapter IV fundamental rights; the 2011 amendments added some reforms.",
    constitutionalCourt: "No dedicated constitutional court; the Supreme Court decides constitutional questions.",
    amendments: ["First Alteration Act 2010 (electoral and other reforms)", "Fourth Alteration (2020s, judicial and other reforms)"],
    history: "Promulgated by the Abdulsalami Abubakar administration for the 1999 transition; Nigeria has operated under it through the Fourth Republic, with the 2010 'doctrine of necessity' and successive Alteration Acts shaping its practice.",
    summary: "The 1999 Constitution is the foundation of Nigeria's Fourth Republic — a federal presidential system of 36 states.",
    simple: "Nigeria's current constitution, from 1999, sets up a federal system with a strong president and 36 states.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §15 — key Nigerian political events (coups, transitions, crises)
 * ════════════════════════════════════════════════════════════════════════════ */

export const NIGERIA_EVENTS: PoliticalEventRecord[] = [
  buildEvent({
    id: "pol.event.nigeria.independence",
    name: "Nigerian independence",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "1 October 1960",
    year: 1960,
    eventType: "independence",
    description: "Nigeria became independent from Britain with Abubakar Tafawa Balewa as Prime Minister and Nnamdi Azikiwe as Governor-General.",
    keyFigures: ["Abubakar Tafawa Balewa", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello"],
    consequences: "The First Republic began; Nigeria joined the Commonwealth and the UN.",
    summary: "Nigeria gained independence from Britain on 1 October 1960.",
    simple: "Nigeria became free from British rule on October 1, 1960.",
  }),
  buildEvent({
    id: "pol.event.nigeria.civil-war",
    name: "Nigerian Civil War (Biafra)",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "6 July 1967 – 15 January 1970",
    year: 1967,
    eventType: "civil war",
    description: "The Eastern Region seceded as the Republic of Biafra under Odumegwu Ojukwu; the federal government under Yakubu Gowon fought to keep Nigeria one. The war ended with 'no victor, no vanquished'.",
    keyFigures: ["Yakubu Gowon", "Odumegwu Ojukwu", "Chukwuemeka Odumegwu Ojukwu", "Philip Effiong"],
    consequences: "Reconstruction and reconciliation; the creation of states; an estimated 1–3 million deaths, mostly from famine.",
    nonViolenceNote: "WINDELS presents this history educationally; the human costs are documented and not glorified (§15).",
    summary: "The Nigerian Civil War (1967–70) followed Biafra's secession and ended with the federation intact.",
    simple: "From 1967 to 1970 Nigeria fought a civil war when the east tried to break away as Biafra. The war ended with the country united.",
  }),
  buildEvent({
    id: "pol.event.nigeria.january-1966",
    name: "January 1966 coup",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "15 January 1966",
    year: 1966,
    eventType: "coup",
    description: "Young military officers ('the Young Majors', led by Kaduna Nzeogwu) overthrew the First Republic, killing the Prime Minister and several regional leaders; Aguiyi-Ironsi took power.",
    keyFigures: ["Kaduna Nzeogwu", "Johnson Aguiyi-Ironsi", "Abubakar Tafawa Balewa", "Ahmadu Bello"],
    consequences: "The end of the First Republic and the beginning of military rule.",
    summary: "The January 1966 coup ended Nigeria's First Republic and began 33 years of mostly military rule.",
    simple: "In January 1966, soldiers overthrew Nigeria's first democratic government.",
  }),
  buildEvent({
    id: "pol.event.nigeria.june-12",
    name: "June 12, 1993 election and annulment",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "12 June – 23 June 1993",
    year: 1993,
    eventType: "political crisis",
    description: "MKO Abiola won the freest election in Nigerian history; Ibrahim Babangida annulled it on 23 June, triggering a nationwide crisis and the eventual transition to democracy in 1999.",
    keyFigures: ["MKO Abiola", "Ibrahim Babangida", "Ernest Shonekan", "Sani Abacha"],
    consequences: "The Interim National Government, Abacha's coup, the June 12 movement, and ultimately the 1999 transition; June 12 is now Democracy Day.",
    summary: "The annulment of the June 12, 1993 election — believed won by MKO Abiola — was the defining political crisis of Nigeria's Third Republic attempt.",
    simple: "In 1993 Nigerians voted in a free election and MKO Abiola won — but the government cancelled the result, causing a huge crisis.",
  }),
  buildEvent({
    id: "pol.event.nigeria.transition-1999",
    name: "Transition to democracy (1999)",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "29 May 1999",
    year: 1999,
    eventType: "democratic transition",
    description: "After Abacha's death, Abdulsalami Abubakar organized the 1999 elections; Olusegun Obasanjo was inaugurated on 29 May 1999, ending 16 years of continuous military rule.",
    keyFigures: ["Abdulsalami Abubakar", "Olusegun Obasanjo", "MKO Abiola (died 1998)"],
    consequences: "The Fourth Republic began; Nigeria has had continuous civilian government since.",
    summary: "The 1999 transition returned Nigeria to democracy after 16 years of military rule.",
    simple: "In 1999 Nigeria returned to democratic government after many years of military rule.",
  }),
  buildEvent({
    id: "pol.event.nigeria.2015-election",
    name: "2015 general election",
    countryIds: ["pol.country.nigeria"],
    dateLabel: "28–29 March 2015",
    year: 2015,
    eventType: "election",
    description: "Muhammadu Buhari (APC) defeated incumbent Goodluck Jonathan (PDP) — the first opposition victory in Nigerian history, with a peaceful concession.",
    keyFigures: ["Muhammadu Buhari", "Goodluck Jonathan"],
    consequences: "The first democratic transfer of power between parties in Nigeria; a landmark for African democracy.",
    summary: "The 2015 election was the first time an opposition candidate defeated an incumbent president in Nigeria.",
    simple: "In 2015, for the first time, Nigerians voted out the ruling party and the loser accepted peacefully.",
  }),
];
