/**
 * Session 144 — Politics seed (part 3): notable global leaders (§4/§5) —
 * current office-holders (marked current_as_of) plus historically
 * significant heads of state and government across the covered countries.
 */
import type { LeaderRecord } from "@windels/shared";
import {
  buildLeader,
  SRC_ACADEMIC,
  SRC_ARCHIVE,
  SRC_GOVT,
  SRC_JOURNALISM,
} from "./politics.catalog.js";

export const GLOBAL_LEADERS: LeaderRecord[] = [
  /* ── United States ────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.usa.washington",
    name: "George Washington",
    countryId: "pol.country.united-states",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "None (pre-party era)",
    born: "1732 – 1799",
    officeStart: "30 April 1789",
    officeEnd: "4 March 1797",
    predecessor: "None (first president)",
    successor: "John Adams",
    cameToOffice: "Unanimously elected by the Electoral College; the first president under the 1787 Constitution.",
    ordinal: 1,
    majorPolicies: "Established the cabinet, the neutrality in the French Revolutionary Wars, the Jay Treaty, and the two-term precedent.",
    achievements: "Commanded the Continental Army to victory; presided over the Constitutional Convention; set the office's precedents.",
    controversies: "The Whiskey Rebellion's suppression and his slavery ownership are documented subjects of historical debate.",
    majorEvents: "The ratification of the Constitution, the Bill of Rights (1791), the Whiskey Rebellion (1794).",
    constitutionalRole: "Head of state and government under Article II.",
    historicalSignificance: "The 'Father of His Country' — the office's first holder and precedent-setter.",
    summary: "George Washington was the first president of the United States (1789–1797).",
    simple: "George Washington led the American army to victory and became the first president of the United States.",
  }),
  buildLeader({
    id: "pol.leader.usa.lincoln",
    name: "Abraham Lincoln",
    countryId: "pol.country.united-states",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "Republican",
    born: "1809 – 1865",
    officeStart: "4 March 1861",
    officeEnd: "15 April 1865",
    predecessor: "James Buchanan",
    successor: "Andrew Johnson",
    cameToOffice: "Elected in 1860; re-elected in 1864.",
    ordinal: 16,
    majorPolicies: "Preserved the Union through the Civil War; the Emancipation Proclamation (1863); the 13th Amendment (abolishing slavery).",
    achievements: "Led the Union to victory; emancipation; the Gettysburg Address.",
    controversies: "Suspended habeas corpus in parts of the Union during the war — a documented constitutional controversy.",
    majorEvents: "The Civil War (1861–65), the Emancipation Proclamation, his assassination on 15 April 1865.",
    constitutionalRole: "War powers under Article II.",
    historicalSignificance: "Widely regarded as the greatest US president; his leadership ended slavery and preserved the Union.",
    summary: "Abraham Lincoln, the 16th president (1861–1865), led the United States through the Civil War and emancipated the enslaved.",
    simple: "Abraham Lincoln was president during the American Civil War. He freed the slaves and kept the country together.",
  }),
  buildLeader({
    id: "pol.leader.usa.roosevelt",
    name: "Franklin D. Roosevelt",
    altNames: ["FDR"],
    countryId: "pol.country.united-states",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "Democratic",
    born: "1882 – 1945",
    officeStart: "4 March 1933",
    officeEnd: "12 April 1945",
    predecessor: "Herbert Hoover",
    successor: "Harry S. Truman",
    cameToOffice: "Elected in 1932 amid the Great Depression; re-elected in 1936, 1940 and 1944 — the only president elected four times.",
    ordinal: 32,
    majorPolicies: "The New Deal (Social Security, the WPA, banking reform), lend-lease, and leadership of the Allies in World War II.",
    achievements: "Pulled the US out of the Depression's worst; led the war effort; founded the postwar order's architecture (the UN).",
    controversies: "The 1937 court-packing attempt and the Japanese-American internment (1942) are documented controversies.",
    majorEvents: "The New Deal, Pearl Harbor (1941), World War II, his death in office (1945).",
    constitutionalRole: "Expanded the modern presidency.",
    historicalSignificance: "The defining president of the mid-20th century; the 22nd Amendment (1951) limited future presidents to two terms in response to his four terms.",
    summary: "Franklin D. Roosevelt, the 32nd president (1933–1945), led the United States through the Depression and World War II.",
    simple: "FDR was president during the Great Depression and World War II. He created the New Deal programs that helped Americans.",
  }),
  buildLeader({
    id: "pol.leader.usa.trump",
    name: "Donald Trump",
    countryId: "pol.country.united-states",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "Republican",
    born: "1946 –",
    officeStart: "20 January 2025",
    officeEnd: "",
    predecessor: "Joe Biden",
    successor: "",
    cameToOffice: "Won the 2024 presidential election (his second, non-consecutive term); previously served 2017–2021.",
    ordinal: 47,
    majorPolicies: "Tariffs and trade protectionism, immigration enforcement and mass-deportation programs, deregulation, government-efficiency cuts (the DOGE initiative), and a foreign policy of 'America First'.",
    achievements: "First president since Grover Cleveland to serve non-consecutive terms; his 2024 victory included winning the popular vote.",
    controversies: "His 2020 election-loss claims and the January 6, 2021 Capitol attack; two impeachments (2019, 2021) in his first term; felony convictions in New York (2024); and the documented disputes over his second-term policies.",
    majorEvents: "The 2024 election, the January 2025 inauguration, tariff wars with major trading partners, and the 2025 government-reform push.",
    constitutionalRole: "Head of state and government under Article II; the 22nd Amendment bars a third term.",
    historicalSignificance: "Current president as of the Last Verified date; his historical significance is a matter of ongoing debate.",
    summary: "Donald Trump is the current US president (since 20 January 2025), serving a second, non-consecutive term after winning the 2024 election.",
    simple: "Donald Trump is the president of the United States right now. He was also president from 2017 to 2021.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── United Kingdom ───────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.uk.churchill",
    name: "Winston Churchill",
    countryId: "pol.country.united-kingdom",
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Conservative",
    born: "1874 – 1965",
    officeStart: "10 May 1940",
    officeEnd: "26 July 1945",
    predecessor: "Neville Chamberlain",
    successor: "Clement Attlee",
    cameToOffice: "Appointed during World War II after Chamberlain's resignation; also served 1951–1955.",
    majorPolicies: "Led Britain through World War II; the 'iron curtain' speech (1946) framed the Cold War.",
    achievements: "Britain's wartime leadership; a Nobel Prize in Literature (1953).",
    controversies: "His views on empire and race are the subject of extensive historical debate.",
    majorEvents: "The Battle of Britain, the wartime coalition, the 1945 election defeat.",
    constitutionalRole: "Head of government commanding the Commons.",
    historicalSignificance: "Britain's most iconic wartime leader.",
    summary: "Winston Churchill was Britain's Prime Minister during World War II (1940–45, and again 1951–55).",
    simple: "Churchill was the British leader during World War II, famous for his speeches and cigars.",
  }),
  buildLeader({
    id: "pol.leader.uk.starmer",
    name: "Keir Starmer",
    countryId: "pol.country.united-kingdom",
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Labour",
    born: "1962 –",
    officeStart: "5 July 2024",
    officeEnd: "",
    predecessor: "Rishi Sunak",
    successor: "",
    cameToOffice: "Led Labour to a landslide victory in the July 2024 general election.",
    majorPolicies: "The 'change' agenda: NHS reform, planning and housing reform, workers' rights, and the reset of EU relations.",
    achievements: "Ended 14 years of Conservative government; the 2024 election gave Labour its largest majority since 1997.",
    controversies: "Policy disputes over welfare cuts, the two-child benefit cap, and the 'Chagos' deal are documented controversies of his administration.",
    majorEvents: "The 2024 election, the 2024 riots response, the October 2024 budget, and the 2025 renegotiations with the EU.",
    constitutionalRole: "Head of government; the monarch is head of state.",
    historicalSignificance: "Current Prime Minister as of the Last Verified date.",
    summary: "Keir Starmer has been the UK Prime Minister since July 2024, after Labour's landslide election victory.",
    simple: "Keir Starmer is the British prime minister now. His Labour party won the 2024 election.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── Germany ──────────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.germany.merkel",
    name: "Angela Merkel",
    countryId: "pol.country.germany",
    title: "Chancellor",
    titleKind: "chancellor",
    role: "head_of_government",
    party: "CDU",
    born: "1954 –",
    officeStart: "22 November 2005",
    officeEnd: "8 December 2021",
    predecessor: "Gerhard Schröder",
    successor: "Olaf Scholz",
    cameToOffice: "Led the CDU/CSU to the chancellorship in 2005 after a grand-coalition negotiation; re-elected in 2009, 2013 and 2017.",
    ordinal: 8,
    majorPolicies: "The Energiewende (energy transition), the 2008–09 crisis response, the Eurozone debt-crisis management, the 2015 refugee policy, and Germany's EU leadership.",
    achievements: "Germany's longest-serving chancellor (16 years); the first woman chancellor; central to Europe's crisis management for over a decade.",
    controversies: "The 2015 open-door refugee policy divided Europe; her austerity emphasis in the Eurozone crisis is debated by economists.",
    majorEvents: "The 2008 financial crisis, the Eurozone crisis, the 2015 migration crisis, the COVID-19 pandemic.",
    constitutionalRole: "Head of government under the Basic Law, elected by the Bundestag.",
    historicalSignificance: "One of the defining European leaders of the 21st century.",
    summary: "Angela Merkel was Germany's Chancellor from 2005 to 2021 — the longest-serving chancellor and a defining European leader.",
    simple: "Angela Merkel was Germany's chancellor for 16 years — the first woman in the job.",
  }),
  buildLeader({
    id: "pol.leader.germany.merz",
    name: "Friedrich Merz",
    countryId: "pol.country.germany",
    title: "Chancellor",
    titleKind: "chancellor",
    role: "head_of_government",
    party: "CDU",
    born: "1955 –",
    officeStart: "May 2025",
    officeEnd: "",
    predecessor: "Olaf Scholz",
    successor: "",
    cameToOffice: "Led the CDU/CSU to victory in the February 2025 federal election and formed a grand coalition with the SPD.",
    majorPolicies: "Economic revival and migration reform, a major infrastructure and defence investment package, and a more assertive European security posture.",
    achievements: "Returned the CDU to the chancellorship after 16 years; negotiated the 2025 coalition.",
    controversies: "The February 2025 pre-election votes with AfD support (a documented political controversy) and the coalition's spending plans are debated.",
    majorEvents: "The February 2025 election, the coalition formation, and the 2025 defence-and-infrastructure package.",
    constitutionalRole: "Head of government under the Basic Law, elected by the Bundestag.",
    historicalSignificance: "Current Chancellor as of the Last Verified date.",
    summary: "Friedrich Merz has been Germany's Chancellor since May 2025, after the CDU's election victory.",
    simple: "Friedrich Merz became Germany's chancellor in 2025.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── Kenya ─────────────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.kenya.kenyatta",
    name: "Jomo Kenyatta",
    countryId: "pol.country.kenya",
    title: "Prime Minister (1963–64); President (1964–1978)",
    titleKind: "president",
    role: "both",
    party: "KANU",
    born: "c. 1897 – 1978",
    officeStart: "1 June 1963",
    officeEnd: "22 August 1978",
    predecessor: "None (first)",
    successor: "Daniel arap Moi",
    cameToOffice: "First Prime Minister at independence; became the first President when Kenya became a republic in 1964.",
    ordinal: 1,
    majorPolicies: "'Harambee' (self-help) development, Africanization, stability and foreign investment.",
    achievements: "Founding president; kept Kenya stable and pro-Western through the Cold War.",
    controversies: "The one-party state's consolidation and the 1969 detention of Jaramogi Oginga Odinga are documented.",
    majorEvents: "Independence (1963), the republic (1964), the 1966 KPU split, his death in office (1978).",
    constitutionalRole: "Executive president under the 1963/1964 constitution.",
    historicalSignificance: "The founding father of the Kenyan state.",
    summary: "Jomo Kenyatta was Kenya's first Prime Minister and first President (1963–1978).",
    simple: "Kenyatta was the first leader of independent Kenya.",
  }),
  buildLeader({
    id: "pol.leader.kenya.ruto",
    name: "William Ruto",
    countryId: "pol.country.kenya",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "UDA",
    born: "1966 –",
    officeStart: "13 September 2022",
    officeEnd: "",
    predecessor: "Uhuru Kenyatta",
    successor: "",
    cameToOffice: "Won the August 2022 presidential election; the Supreme Court affirmed his victory after a challenge.",
    ordinal: 5,
    majorPolicies: "The 'Bottom-Up Economic Transformation Agenda' (housing, affordable credit, job creation), the 2023 Finance Act (later amended), and the 2024 cabinet restructuring after the Gen Z protests.",
    achievements: "The first president from the Kalenjin community since Moi; oversaw the handover of the 2022 transition.",
    controversies: "The 2022 election challenge; the 2023–24 cost-of-living crisis; the June 2024 Finance Bill protests (the 'Gen Z' movement), which led to the bill's withdrawal and a cabinet overhaul.",
    majorEvents: "The 2022 election, the 2023 Finance Act, the 2024 protests, the Haiti security mission deployment (2023– ).",
    constitutionalRole: "Executive president under the 2010 constitution.",
    historicalSignificance: "Current president as of the Last Verified date.",
    summary: "William Ruto has been Kenya's President since September 2022, after a Supreme Court-affirmed election.",
    simple: "William Ruto is the president of Kenya now. He became president in 2022 after a close election.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── Ghana ─────────────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.ghana.nkrumah",
    name: "Kwame Nkrumah",
    countryId: "pol.country.ghana",
    title: "Prime Minister (1952–60); President (1960–1966)",
    titleKind: "president",
    role: "both",
    party: "Convention People's Party (CPP)",
    born: "1909 – 1972",
    officeStart: "6 March 1952",
    officeEnd: "24 February 1966",
    predecessor: "None (first)",
    successor: "Joseph Ankrah (military, NLC)",
    cameToOffice: "Won the 1951 elections from prison; led Ghana to independence; became President when Ghana became a republic in 1960.",
    ordinal: 1,
    majorPolicies: "Pan-Africanism, the Volta River Project, African socialism, and anti-colonial leadership across the continent.",
    achievements: "Led the first sub-Saharan African independence; a founding figure of pan-Africanism and the OAU.",
    controversies: "The 1964 one-party amendment and the 1966 overthrow amid economic difficulties are documented.",
    majorEvents: "Independence (1957), the republic (1960), the OAU's founding (1963), the 1966 coup.",
    constitutionalRole: "Executive president from 1960.",
    historicalSignificance: "The symbol of African independence and pan-African unity.",
    summary: "Kwame Nkrumah led Ghana to independence in 1957 and became its first President (1960–1966).",
    simple: "Nkrumah was the leader who made Ghana the first independent country in sub-Saharan Africa.",
  }),
  buildLeader({
    id: "pol.leader.ghana.mahama",
    name: "John Mahama",
    countryId: "pol.country.ghana",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "NDC",
    born: "1958 –",
    officeStart: "7 January 2025",
    officeEnd: "",
    predecessor: "Nana Akufo-Addo",
    successor: "",
    cameToOffice: "Won the December 2024 presidential election; previously served as President 2012–2017 after John Atta Mills' death.",
    ordinal: 4,
    majorPolicies: "The '24-hour economy' proposal, economic recovery, and anti-corruption pledges.",
    achievements: "Returned to the presidency after losing the 2016 election — a rare comeback in Ghanaian politics.",
    controversies: "The 2016–17 energy crisis ('dumsor') during his first term is a documented criticism.",
    majorEvents: "The December 2024 election and the January 2025 inauguration.",
    constitutionalRole: "Executive president under the 1992 constitution.",
    historicalSignificance: "Current president as of the Last Verified date.",
    summary: "John Mahama returned as Ghana's President in January 2025, having previously served 2012–2017.",
    simple: "John Mahama is the president of Ghana now. He was also president years ago.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── South Africa ──────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.sa.mandela",
    name: "Nelson Mandela",
    countryId: "pol.country.south-africa",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "ANC",
    born: "1918 – 2013",
    officeStart: "10 May 1994",
    officeEnd: "16 June 1999",
    predecessor: "F. W. de Klerk",
    successor: "Thabo Mbeki",
    cameToOffice: "Elected in the 1994 election — the first fully democratic election in South African history.",
    ordinal: 1,
    majorPolicies: "Truth and Reconciliation, the Reconstruction and Development Programme, national unity.",
    achievements: "Led the negotiated end of apartheid; shared the 1993 Nobel Peace Prize with de Klerk.",
    controversies: "His earlier support for the armed struggle is part of the historical record, not a scandal.",
    majorEvents: "The 1994 election, the Truth and Reconciliation Commission (1995–98), the 1996 constitution.",
    constitutionalRole: "President under the interim and 1996 constitutions.",
    historicalSignificance: "The founding president of democratic South Africa and a global icon of reconciliation.",
    summary: "Nelson Mandela was South Africa's first democratically elected president (1994–1999).",
    simple: "Mandela spent 27 years in prison for fighting apartheid, then became South Africa's first Black president in 1994.",
  }),
  buildLeader({
    id: "pol.leader.sa.ramaphosa",
    name: "Cyril Ramaphosa",
    countryId: "pol.country.south-africa",
    title: "President",
    titleKind: "president",
    role: "both",
    party: "ANC",
    born: "1952 –",
    officeStart: "15 February 2018",
    officeEnd: "",
    predecessor: "Jacob Zuma",
    successor: "",
    cameToOffice: "Succeeded Zuma after the ANC's leadership change; re-elected after the 2024 election by the National Assembly.",
    ordinal: 5,
    majorPolicies: "Anti-corruption ('new dawn'), economic reform (Operation Vulindlela), energy reform, and the Government of National Unity after 2024.",
    achievements: "Led the ANC through the 2024 election and formed the GNU with the DA and others after the ANC lost its majority.",
    controversies: "The Phala Phala farm controversy (2022) is a documented political controversy.",
    majorEvents: "The Zuma-era corruption inquiries, the 2019 and 2024 elections, the 2024 GNU.",
    constitutionalRole: "President elected by the National Assembly (head of state and government).",
    historicalSignificance: "Current president as of the Last Verified date; the first to lead a coalition government.",
    summary: "Cyril Ramaphosa has been South Africa's President since 2018, leading a Government of National Unity since 2024.",
    simple: "Cyril Ramaphosa is the president of South Africa now.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── India ─────────────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.india.nehru",
    name: "Jawaharlal Nehru",
    countryId: "pol.country.india",
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Indian National Congress",
    born: "1889 – 1964",
    officeStart: "15 August 1947",
    officeEnd: "27 May 1964",
    predecessor: "None (first)",
    successor: "Lal Bahadur Shastri",
    cameToOffice: "Led the Congress to power at independence; the first Prime Minister.",
    ordinal: 1,
    majorPolicies: "Planned industrialization, non-alignment, secularism, parliamentary democracy, and the Panchsheel principles.",
    achievements: "Built India's democratic institutions, the Planning Commission, and the non-aligned movement's leadership.",
    controversies: "The 1962 Sino-Indian war and the Kashmir policy are documented subjects of debate.",
    majorEvents: "Independence and partition (1947), the republic (1950), the 1962 war, his death (1964).",
    constitutionalRole: "Head of government under the 1950 constitution.",
    historicalSignificance: "India's founding Prime Minister, who shaped its democratic and secular character.",
    summary: "Jawaharlal Nehru was India's first Prime Minister (1947–1964).",
    simple: "Nehru was the first prime minister of independent India.",
  }),
  buildLeader({
    id: "pol.leader.india.modi",
    name: "Narendra Modi",
    countryId: "pol.country.india",
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "BJP",
    born: "1950 –",
    officeStart: "26 May 2014",
    officeEnd: "",
    predecessor: "Manmohan Singh",
    successor: "",
    cameToOffice: "Led the BJP to a majority in the 2014 election; re-elected in 2019 and 2024 (the latter in coalition).",
    ordinal: 14,
    majorPolicies: "Economic reforms (GST, digitization), infrastructure, Hindu-nationalist cultural policies, 'Make in India', and a more assertive foreign policy.",
    achievements: "First prime minister born after independence; the 2019 abrogation of Article 370 and the 2019 re-election are landmark events.",
    controversies: "The 2002 Gujarat riots (when he was Chief Minister) remain a deeply documented controversy; citizenship and minority-rights policies are contested.",
    majorEvents: "The 2014, 2019 and 2024 elections, demonetization (2016), GST (2017), Article 370 (2019), the COVID-19 pandemic.",
    constitutionalRole: "Head of government; the President is head of state.",
    historicalSignificance: "Current Prime Minister as of the Last Verified date; the dominant figure of 21st-century Indian politics.",
    summary: "Narendra Modi has been India's Prime Minister since 2014, winning a third term in 2024.",
    simple: "Narendra Modi is the prime minister of India now. He has been in office since 2014.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),

  /* ── Ethiopia ──────────────────────────────────────────────────────── */
  buildLeader({
    id: "pol.leader.ethiopia.abiy",
    name: "Abiy Ahmed",
    countryId: "pol.country.ethiopia",
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Prosperity Party (formerly EPRDF/ODP)",
    born: "1976 –",
    officeStart: "2 April 2018",
    officeEnd: "",
    predecessor: "Hailemariam Desalegn",
    successor: "",
    cameToOffice: "Elected by the EPRDF coalition after Hailemariam's resignation.",
    ordinal: 4,
    majorPolicies: "Political liberalization ('medemer'), the release of political prisoners, peace with Eritrea (2018), and economic reform; later, the war in Tigray (2020–2022).",
    achievements: "The 2019 Nobel Peace Prize for the Eritrea peace deal; the Pretoria agreement ending the Tigray war (2022).",
    controversies: "The Tigray war's conduct (documented allegations of atrocities against all sides), the 2021 state of emergency, and federal restructuring debates.",
    majorEvents: "The 2018 reforms, the Eritrea peace, the 2021–22 Tigray war and the Pretoria agreement.",
    constitutionalRole: "Head of government; the President is ceremonial.",
    historicalSignificance: "Current Prime Minister as of the Last Verified date.",
    summary: "Abiy Ahmed has been Ethiopia's Prime Minister since 2018, a Nobel laureate whose tenure included the Tigray war.",
    simple: "Abiy Ahmed is the prime minister of Ethiopia. He won the Nobel Peace Prize, then led the country through a civil war.",
    verification: "current_as_of",
    asOfDate: "2026-08-08",
    lastVerified: "2026-08-08",
    sources: [SRC_GOVT, SRC_JOURNALISM],
  }),
];
