/**
 * Session 144 — Politics seed (part 2): global country political profiles
 * (§2/§3). Each profile covers pre-colonial → colonial → independence →
 * modern political history, institutions, electoral system, parties and the
 * current situation (marked current_as_of with a Last Verified date).
 */
import type { ConstitutionRecord, CountryProfile } from "@windels/shared";
import {
  buildConstitution,
  buildCountry,
  SRC_ACADEMIC,
  SRC_ARCHIVE,
  SRC_CONSTITUTION,
  SRC_GOVT,
  SRC_JOURNALISM,
  SRC_UN,
} from "./politics.catalog.js";

export const COUNTRY_PROFILES: CountryProfile[] = [
  buildCountry({
    id: "pol.country.nigeria",
    name: "Nigeria",
    altNames: ["Federal Republic of Nigeria", "Giant of Africa"],
    capital: "Abuja (since 1991; Lagos was the capital 1914–1991)",
    governmentForm: "federal_republic",
    federalStructure: "federal",
    constitutionRef: "pol.constitution.nigeria.1999",
    independence: "1 October 1960 (from the United Kingdom); republic 1 October 1963",
    independenceYear: 1960,
    colonialPower: "United Kingdom (the Lagos Colony 1861; amalgamation of the protectorates 1914)",
    preColonial: "Ancient cultures include the Nok civilization (c. 1000 BCE–500 CE). Major pre-colonial states: the Kanem-Bornu Empire in the northeast, the Hausa city-states (Kano, Katsina), the Oyo Empire and Ife in the southwest, the Benin Kingdom in the south (famous for its art), and the Igbo village republics in the southeast. Trans-Saharan and Atlantic trade (including the slave trade) reshaped these polities from the 15th century.",
    colonialHistory: "The British gradually extended control: Lagos was annexed in 1861, the Oil Rivers Protectorate became the Niger Coast Protectorate, and in 1900 the Protectorates of Northern and Southern Nigeria were created. The amalgamation of 1914 created modern Nigeria under Lord Lugard. Colonial administration was indirect (through traditional rulers in the north) and direct (warrant chiefs in the southeast); nationalist politics began with the Nigerian Youth Movement and the NCNC in the 1930s–40s.",
    independenceStory: "Constitutional conferences (1950–1958) led to self-government for the regions and independence on 1 October 1960, with Abubakar Tafawa Balewa as Prime Minister and Nnamdi Azikiwe as Governor-General. Nigeria became a republic in 1963 with Azikiwe as President.",
    modernHistory: "The First Republic (1960–66) ended with the January 1966 coup; the civil war over Biafra (1967–70) followed. Military rule (with the civilian Second Republic 1979–83) continued until the 1999 transition. The Fourth Republic (1999– ) has seen four peaceful transfers of power, including the landmark 2015 opposition victory and the disputed but court-affirmed 2023 election.",
    legislature: "National Assembly: the Senate (109 members, three per state + FCT) and the House of Representatives (360 members).",
    executive: "The President is head of state and head of government, elected for two four-year terms; the Vice-President and a Federal Executive Council (ministers) assist.",
    judiciary: "A hierarchical court system: the Supreme Court, Court of Appeal, Federal High Court, National Industrial Court, state high courts, and customary and sharia courts of appeal in some states.",
    electoralSystem: "First-past-the-post for the presidency and legislatures; INEC administers elections; the 2022 Electoral Act provides for electronic transmission of results.",
    parties: ["PDP", "APC", "Labour Party", "NNPP", "APGA", "SDP", "YPP"],
    currentSituation: "President Bola Tinubu (APC) has governed since May 2023; his administration removed the fuel subsidy and unified exchange rates, facing a cost-of-living crisis and the 2024 #EndBadGovernance protests. Security challenges persist in parts of the north (banditry, insurgency remnants) and the southeast. The next general election is scheduled for 2027. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "ancient", label: "Ancient period", dateLabel: "c. 1000 BCE – c. 1500 CE", year: -1000, text: "Nok civilization, Kanem-Bornu, Hausa states, Oyo, Benin, Igbo republics." },
      { id: "colonial", label: "Colonial period", dateLabel: "1861–1960", year: 1861, text: "Lagos annexation, protectorates, 1914 amalgamation, indirect rule, nationalist movement." },
      { id: "independence", label: "Independence & First Republic", dateLabel: "1960–1966", year: 1960, text: "Independence, republic, regional crises, January 1966 coup." },
      { id: "civilwar", label: "Civil war", dateLabel: "1967–1970", year: 1967, text: "Biafran secession and the federal victory." },
      { id: "military", label: "Military rule", dateLabel: "1966–1999 (with the Second Republic 1979–83)", year: 1966, text: "A succession of military governments, the June 12 1993 crisis, the 1999 transition." },
      { id: "fourthrepublic", label: "Fourth Republic", dateLabel: "1999–present", year: 1999, text: "Continuous democracy; 2015 opposition victory; 2023 election and its disputes." },
    ],
    summary: "Nigeria is Africa's most populous country and largest economy, a federal republic of 36 states with a history spanning pre-colonial empires, colonial amalgamation, civil war, long military rule and a Fourth Republic that has held continuous elections since 1999.",
    simple: "Nigeria is a big country in West Africa. It became independent from Britain in 1960, fought a civil war in the 1960s, and has been a democracy since 1999.",
    relatedIds: ["pol.leader.nigeria.tinubu", "pol.constitution.nigeria.1999", "pol.party.nigeria.apc", "pol.party.nigeria.pdp", "pol.election.nigeria.2023", "org.ecowas", "org.african-union", "org.commonwealth", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.united-states",
    name: "United States of America",
    altNames: ["USA", "United States"],
    capital: "Washington, D.C.",
    governmentForm: "federal_republic",
    federalStructure: "federal",
    constitutionRef: "pol.constitution.usa",
    independence: "4 July 1776 (Declaration of Independence); the Constitution took effect 1789",
    independenceYear: 1776,
    colonialPower: "United Kingdom (thirteen colonies)",
    preColonial: "Hundreds of Indigenous nations with diverse governance systems (the Haudenosaunee Confederacy, the Pueblo councils, the Plains nations and others) before European contact.",
    colonialHistory: "British colonization from 1607 (Jamestown) and 1620 (Plymouth); colonial assemblies developed self-government; tensions over taxation and representation produced the American Revolution (1775–1783).",
    independenceStory: "The Declaration of Independence (1776) proclaimed the new republic; the Articles of Confederation failed; the 1787 Philadelphia convention wrote the Constitution, ratified in 1788, in effect from 1789 with George Washington as first president.",
    modernHistory: "Expansion across the continent, the Civil War (1861–65) over slavery and union, Reconstruction, industrialization, two world wars, the Cold War, the civil rights movement, and its current role as a global power.",
    legislature: "Congress: the Senate (100 members, two per state) and the House of Representatives (435 members).",
    executive: "The President is head of state and head of government, elected for two four-year terms via the Electoral College; the Cabinet assists.",
    judiciary: "Federal courts under the Supreme Court (nine justices); state court systems; judicial review established by Marbury v. Madison (1803).",
    electoralSystem: "First-past-the-post with primaries; the Electoral College decides presidential elections; state-level administration of elections.",
    parties: ["Democratic Party", "Republican Party", "(minor parties: Libertarian, Green)"],
    currentSituation: "Donald Trump returned to the presidency in January 2025 for a second, non-consecutive term after winning the 2024 election; the Republican Party controls the White House and (narrowly) both chambers of Congress as of the Last Verified date. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "founding", label: "Founding", dateLabel: "1776–1789", year: 1776, text: "Revolution, Articles of Confederation, Constitutional Convention." },
      { id: "civilwar", label: "Civil War & Reconstruction", dateLabel: "1861–1877", year: 1861, text: "Secession, emancipation, the 13th–15th Amendments, Reconstruction." },
      { id: "superpower", label: "World power", dateLabel: "1917–present", year: 1917, text: "World wars, Cold War leadership, the civil rights era, contemporary politics." },
    ],
    summary: "The United States is a federal presidential republic of 50 states, founded in 1776, governed under its 1787 Constitution and a two-party system.",
    simple: "The United States is a country in North America that became independent from Britain in 1776. Its people elect a president and Congress under a constitution from 1787.",
    relatedIds: ["pol.leader.usa.trump", "pol.constitution.usa", "org.un", "org.nato", "org.g7", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_CONSTITUTION, SRC_ARCHIVE],
  }),
  buildCountry({
    id: "pol.country.united-kingdom",
    name: "United Kingdom",
    altNames: ["UK", "Britain"],
    capital: "London",
    governmentForm: "parliamentary_monarchy",
    federalStructure: "unitary",
    constitutionRef: "pol.constitution.uk",
    independence: "Unitary state formed by the Acts of Union (1707 Scotland; 1801 Ireland); the modern constitutional monarchy evolved over centuries",
    independenceYear: 1707,
    preColonial: "Anglo-Saxon kingdoms, the Norman conquest (1066), the Plantagenet and Tudor monarchies, the English Civil War (1642–51) and the Glorious Revolution (1688).",
    colonialHistory: "The UK built the largest empire in history from the 17th to the 20th century; decolonization after 1945 transformed it.",
    independenceStory: "There is no single independence date: the UK's constitutional order grew from Magna Carta (1215), the Bill of Rights (1689) and the gradual extension of the franchise in the 19th–20th centuries.",
    modernHistory: "Two world wars, the post-war welfare state, decolonization, European integration (joined the EEC 1973; left the EU in 2020 after the 2016 Brexit referendum), and devolution to Scotland, Wales and Northern Ireland.",
    legislature: "Parliament: the elected House of Commons (650 MPs) and the appointed House of Lords.",
    executive: "The monarch is head of state (ceremonial); the Prime Minister is head of government, commanding a Commons majority.",
    judiciary: "Independent courts; the Supreme Court of the United Kingdom (since 2009) replaced the Law Lords.",
    electoralSystem: "First-past-the-post for the Commons; proportional systems for devolved and European elections.",
    parties: ["Labour", "Conservative", "Liberal Democrats", "SNP", "Reform UK", "Green"],
    currentSituation: "Keir Starmer (Labour) has been Prime Minister since July 2024, after Labour's landslide victory ended 14 years of Conservative government. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "medieval", label: "Magna Carta to the Civil War", dateLabel: "1215–1688", year: 1215, text: "The growth of parliament, the Civil War, the Glorious Revolution." },
      { id: "empire", label: "Empire & reform", dateLabel: "1689–1945", year: 1689, text: "Parliamentary sovereignty, industrialization, the empire, democratic reform acts." },
      { id: "modern", label: "Modern era", dateLabel: "1945–present", year: 1945, text: "Welfare state, decolonization, EU membership and Brexit, devolution." },
    ],
    summary: "The United Kingdom is a unitary parliamentary monarchy — one of the world's oldest continuous political systems, with an uncodified constitution.",
    simple: "The UK is a country made of England, Scotland, Wales and Northern Ireland. The Queen or King is the head of state, but an elected Prime Minister and Parliament run the country.",
    relatedIds: ["pol.leader.uk.starmer", "pol.constitution.uk", "org.commonwealth", "org.un", "org.nato"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_GOVT],
  }),
  buildCountry({
    id: "pol.country.kenya",
    name: "Kenya",
    altNames: ["Republic of Kenya"],
    capital: "Nairobi",
    governmentForm: "presidential_republic",
    federalStructure: "unitary",
    constitutionRef: "pol.constitution.kenya-2010",
    independence: "12 December 1963 (from the United Kingdom); republic 1964",
    independenceYear: 1963,
    colonialPower: "United Kingdom (East Africa Protectorate 1895; colony 1920)",
    preColonial: "Coastal Swahili city-states (Mombasa, Malindi) in Indian Ocean trade for centuries; inland societies organized by ethnicity and clan (Kikuyu, Luo, Luhya, Kalenjin, Kamba, Maasai, among others) with varied governance systems.",
    colonialHistory: "The British established the protectorate in 1895 and the Kenya Colony in 1920; white settlement in the highlands created land grievances; the Mau Mau uprising (1952–60) and the state of emergency preceded independence.",
    independenceStory: "Independence came on 12 December 1963 with Jomo Kenyatta as first Prime Minister, then first President (1964) of the republic.",
    modernHistory: "Kenyatta ruled until 1978; Daniel arap Moi's long rule (1978–2002) saw the return to multi-party politics in 1991; Mwai Kibaki (2002–2013) oversaw the 2007–08 post-election crisis and the 2010 constitution; Uhuru Kenyatta (2013–2022); William Ruto (2022– ).",
    legislature: "Parliament: the National Assembly (290 constituency + nominated members) and the Senate (47 elected, one per county).",
    executive: "The President is head of state and government, elected for two five-year terms.",
    judiciary: "The Supreme Court, Court of Appeal, High Court and subordinate courts under the 2010 constitution.",
    electoralSystem: "First-past-the-post with a 25% spread requirement for the presidency; IEBC administers elections.",
    parties: ["UDA", "ODM", "Jubilee Party", "Wiper", "ANC (Kenya)"],
    currentSituation: "William Ruto (UDA) has been President since September 2022, after a Supreme Court-affirmed election; his administration faced the 2023–24 cost-of-living crisis and the 2024 Gen Z-led protests (the Finance Bill protests), which led to cabinet changes and the withdrawal of the 2024 Finance Bill. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "precolonial", label: "Pre-colonial", dateLabel: "to 1895", year: -1200, text: "Swahili city-states and inland societies." },
      { id: "colonial", label: "Colonial period", dateLabel: "1895–1963", year: 1895, text: "Protectorate, settlement, Mau Mau, emergency." },
      { id: "independent", label: "Independence & republic", dateLabel: "1963–present", year: 1963, text: "Kenyatta, Moi, multi-partyism, the 2010 constitution, contemporary politics." },
    ],
    summary: "Kenya is an East African presidential republic with a 2010 constitution, a history from Swahili city-states through colonial rule to independence in 1963, and a dynamic multi-party democracy.",
    simple: "Kenya is a country in East Africa that became independent from Britain in 1963. It has a president, a new constitution from 2010, and 47 counties.",
    relatedIds: ["pol.leader.kenya.ruto", "pol.constitution.kenya-2010", "org.african-union", "org.eac", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.ghana",
    name: "Ghana",
    altNames: ["Republic of Ghana"],
    capital: "Accra",
    governmentForm: "presidential_republic",
    federalStructure: "unitary",
    independence: "6 March 1957 (from the United Kingdom); republic 1960",
    independenceYear: 1957,
    colonialPower: "United Kingdom (Gold Coast)",
    preColonial: "The great empires of the Sahel (the Ghana Empire, from which the modern name derives, though it lay to the north), the Akan states, the Ashanti Empire (founded c. 1701, famous for its gold and its capital Kumasi), and the Fante and other coastal polities; European forts traded from the 15th century.",
    colonialHistory: "The Gold Coast became a British colony; the 1948 Accra riots and the 1951 elections under Kwame Nkrumah's Convention People's Party accelerated self-government.",
    independenceStory: "Ghana became independent on 6 March 1957 under Kwame Nkrumah — the first sub-Saharan African colony to do so — and a republic in 1960.",
    modernHistory: "Nkrumah was overthrown in 1966; a series of military governments (including Jerry Rawlings' two regimes) followed; the Fourth Republic began in 1993 with multi-party elections; power has alternated between the NPP and the NDC, including John Mahama's return in 2025.",
    legislature: "Parliament (275 members elected in single-member constituencies).",
    executive: "The President is head of state and government, limited to two four-year terms.",
    judiciary: "The Supreme Court, Court of Appeal, High Courts and lower courts.",
    electoralSystem: "First-past-the-post; the Electoral Commission administers elections.",
    parties: ["NPP", "NDC", "Convention People's Party (historic)"],
    currentSituation: "John Mahama (NDC) was inaugurated as President in January 2025 after winning the December 2024 election, returning to office after his 2017 defeat. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "precolonial", label: "Pre-colonial kingdoms", dateLabel: "to 1874", year: -1000, text: "The Ashanti Empire, Akan states, the coastal trade." },
      { id: "colonial", label: "Colonial Gold Coast", dateLabel: "1874–1957", year: 1874, text: "Colony and protectorate, nationalist politics, Nkrumah." },
      { id: "independent", label: "Independence & republics", dateLabel: "1957–present", year: 1957, text: "First African independence, coups, the Fourth Republic (1993–)." },
    ],
    summary: "Ghana, the first sub-Saharan colony to win independence (1957), is a West African presidential republic with a stable Fourth Republic since 1993.",
    simple: "Ghana, in West Africa, was the first country in sub-Saharan Africa to become independent, in 1957. It has been a democracy since 1993.",
    relatedIds: ["pol.leader.ghana.mahama", "org.ecowas", "org.african-union", "org.commonwealth", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_GOVT],
  }),
  buildCountry({
    id: "pol.country.south-africa",
    name: "South Africa",
    altNames: ["Republic of South Africa", "Mzansi"],
    capital: "Pretoria (executive), Cape Town (legislative), Bloemfontein (judicial)",
    governmentForm: "parliamentary_republic",
    federalStructure: "unitary",
    constitutionRef: "pol.constitution.sa-1996",
    independence: "Union of South Africa 1910 (dominion); republic 1961; full democracy 1994",
    independenceYear: 1910,
    colonialPower: "Dutch (Cape Colony 1652) and British (1795/1806)",
    preColonial: "Khoisan peoples and Bantu-speaking kingdoms (Zulu, Xhosa, Sotho, Tswana and others); the Zulu kingdom under Shaka (early 19th century) was the region's most powerful state.",
    colonialHistory: "Dutch settlement at the Cape (1652), British takeover, the Great Trek and the Boer republics, the Anglo-Boer War (1899–1902), and the Union of South Africa (1910) under white minority rule.",
    independenceStory: "The Union (1910) and republic (1961) were creations of the white minority; the democratic state was founded by the 1994 elections after the negotiated end of apartheid, with Nelson Mandela as first president.",
    modernHistory: "Apartheid (1948–94) systematized racial segregation; resistance (ANC, PAC, the UDF) and international pressure produced negotiations; the 1994 election and the 1996 constitution founded the democratic order; the ANC has governed since, with coalition politics emerging after the 2024 election.",
    legislature: "Parliament: the National Assembly (400 members) and the National Council of Provinces (90).",
    executive: "The President is head of state and government, elected by the National Assembly.",
    judiciary: "The Constitutional Court, Supreme Court of Appeal, High Courts and magistrates' courts.",
    electoralSystem: "Proportional representation (party lists) for the National Assembly and provinces.",
    parties: ["ANC", "DA", "EFF", "MK Party", "IFP", "PA"],
    currentSituation: "Cyril Ramaphosa (ANC) has been President since 2018 and was re-elected in 2024, leading a Government of National Unity after the ANC lost its majority for the first time. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "precolonial", label: "Pre-colonial kingdoms", dateLabel: "to 1652", year: -1500, text: "Khoisan peoples, the Zulu and other kingdoms." },
      { id: "colonial", label: "Colonial & Union", dateLabel: "1652–1948", year: 1652, text: "Dutch and British rule, the Boer republics, the Union." },
      { id: "apartheid", label: "Apartheid", dateLabel: "1948–1994", year: 1948, text: "Segregation, resistance, sanctions, negotiations." },
      { id: "democracy", label: "Democracy", dateLabel: "1994–present", year: 1994, text: "Mandela, the 1996 constitution, ANC rule, 2024 coalition." },
    ],
    summary: "South Africa is a parliamentary republic whose 1994 transition ended apartheid; its 1996 constitution and proportional system anchor one of Africa's most studied democracies.",
    simple: "South Africa used to have a system called apartheid that treated people unequally. In 1994 it became a democracy, and Nelson Mandela became its first Black president.",
    relatedIds: ["pol.leader.sa.ramaphosa", "pol.constitution.sa-1996", "org.african-union", "org.sadc", "org.brics", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.france",
    name: "France",
    altNames: ["French Republic"],
    capital: "Paris",
    governmentForm: "semi_presidential_republic",
    federalStructure: "unitary",
    independence: "The French state traces to the kingdom of the Franks (c. 5th century); the modern republics date from 1792",
    independenceYear: 1792,
    preColonial: "The Frankish kingdoms, the Capetian monarchy, the Ancien Régime's absolute monarchy, and the Revolution of 1789 that ended it.",
    colonialHistory: "France built the second-largest colonial empire (Africa, Asia, the Americas); decolonization came after 1945, including the wars in Indochina and Algeria.",
    independenceStory: "There is no single independence date: France's political history runs through five republics, two empires and the Restoration; the current Fifth Republic was founded in 1958.",
    modernHistory: "The Revolution (1789), Napoleon, the 19th-century republics, two world wars, the Fourth Republic's instability, and the Fifth Republic (1958– ) under strong presidential leadership.",
    legislature: "Parliament: the National Assembly (577) and the Senate (348).",
    executive: "The President (head of state, elected for five years) shares executive power with the Prime Minister (head of government) — the hallmark of a semi-presidential system.",
    judiciary: "Ordinary courts under the Court of Cassation; the Constitutional Council reviews laws.",
    electoralSystem: "Two-round majoritarian system for the presidency and the National Assembly; proportional for the Senate and the European Parliament.",
    parties: ["Renaissance", "National Rally (RN)", "La France Insoumise (LFI)", "Les Républicains (LR)", "Socialist Party (PS)", "Greens (EELV)"],
    currentSituation: "Emmanuel Macron has been President since 2017 (re-elected 2022); after the 2024 snap legislative elections, France entered a period of fragile coalition governments under Prime Minister Michel Barnier and then François Bayrou. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "revolution", label: "Revolution & Empire", dateLabel: "1789–1815", year: 1789, text: "The Revolution, the Republic, Napoleon." },
      { id: "republics", label: "The Republics", dateLabel: "1815–1958", year: 1815, text: "Restoration, Second Empire, Third and Fourth Republics." },
      { id: "fifth", label: "Fifth Republic", dateLabel: "1958–present", year: 1958, text: "De Gaulle's constitution, alternating presidencies, the 2024 coalitions." },
    ],
    summary: "France is a unitary semi-presidential republic — the Fifth Republic (1958– ), whose Revolution of 1789 shaped modern democratic politics worldwide.",
    simple: "France is a country in Europe. Its people had a famous revolution in 1789, and today they elect both a president and a parliament.",
    relatedIds: ["org.eu", "org.un", "org.nato", "org.g7", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.germany",
    name: "Germany",
    altNames: ["Federal Republic of Germany"],
    capital: "Berlin",
    governmentForm: "parliamentary_republic",
    federalStructure: "federal",
    independence: "Unified as the German Empire 1871; the Federal Republic founded 1949; reunified 1990",
    independenceYear: 1871,
    preColonial: "The Holy Roman Empire, the German Confederation, and the Prussian-led unification movement.",
    colonialHistory: "Germany acquired colonies briefly (1884–1919) and lost them after World War I.",
    independenceStory: "The German Empire (1871) unified the states; the Weimar Republic (1919–33) followed the monarchy's fall; after 1945 Germany was divided, with the Federal Republic (1949) and the GDR; reunification came in 1990.",
    modernHistory: "The Weimar Republic, the Nazi dictatorship (1933–45), division and the Cold War, reunification (1990), and the Federal Republic's post-war democratic stability.",
    legislature: "The Bundestag (elected) and the Bundesrat (the states' chamber).",
    executive: "The Federal President is head of state (ceremonial); the Chancellor is head of government, elected by the Bundestag.",
    judiciary: "The Federal Constitutional Court (Karlsruhe) and the federal and state courts.",
    electoralSystem: "Mixed-member proportional representation, with a 5% threshold.",
    parties: ["CDU/CSU", "SPD", "Greens", "FDP", "AfD", "The Left", "BSW"],
    currentSituation: "Friedrich Merz (CDU) became Chancellor in 2025 after the February 2025 federal election, leading a CDU/CSU–SPD coalition. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "empire", label: "Empire & Weimar", dateLabel: "1871–1933", year: 1871, text: "Unification, World War I, the Weimar Republic." },
      { id: "nazi", label: "Nazi dictatorship", dateLabel: "1933–1945", year: 1933, text: "The dictatorship, World War II, the Holocaust." },
      { id: "division", label: "Division & reunification", dateLabel: "1949–1990", year: 1949, text: "Two German states, the Wall, reunification." },
      { id: "federal", label: "Federal Republic", dateLabel: "1990–present", year: 1990, text: "Berlin Republic, EU leadership, the 2025 election." },
    ],
    summary: "Germany is a federal parliamentary republic whose Basic Law (1949) was written after the Nazi catastrophe; reunified since 1990, it is Europe's largest economy.",
    simple: "Germany is a country in Europe with a parliament and a chancellor. After a terrible dictatorship, it built a new democracy in 1949, and East and West Germany reunited in 1990.",
    relatedIds: ["org.eu", "org.un", "org.nato", "org.g7", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.india",
    name: "India",
    altNames: ["Republic of India", "Bharat"],
    capital: "New Delhi",
    governmentForm: "parliamentary_republic",
    federalStructure: "federal",
    constitutionRef: "pol.constitution.india",
    independence: "15 August 1947 (from the United Kingdom); republic 26 January 1950",
    independenceYear: 1947,
    colonialPower: "United Kingdom (the British Raj, 1858–1947; the East India Company earlier)",
    preColonial: "The Indus Valley civilization, the Maurya and Gupta empires, the Delhi Sultanate, the Mughal Empire, and the Maratha and regional kingdoms — one of the world's oldest continuous political civilizations.",
    colonialHistory: "The East India Company's conquests, the 1857 rebellion, the British Raj, and the Indian independence movement under Gandhi, Nehru and others.",
    independenceStory: "Independence came on 15 August 1947 with the partition of India and Pakistan; the Constitution took effect on 26 January 1950, making India a republic under a parliamentary system.",
    modernHistory: "Congress dominance under Nehru and his successors, the Emergency (1975–77), coalition politics from 1989, economic liberalization (1991), and the BJP's majority governments under Modi since 2014.",
    legislature: "Parliament: the Lok Sabha (House of the People, 543 elected) and the Rajya Sabha (Council of States, 245).",
    executive: "The President is head of state (ceremonial); the Prime Minister is head of government.",
    judiciary: "The Supreme Court, High Courts and subordinate courts; the Supreme Court has expansive judicial review.",
    electoralSystem: "First-past-the-post for the Lok Sabha and state assemblies; the Election Commission of India administers the world's largest elections.",
    parties: ["BJP", "Indian National Congress", "AAP", "DMK", "TMC", "SP", "Left Front"],
    currentSituation: "Narendra Modi (BJP) has been Prime Minister since 2014 and won a third term in 2024, heading a coalition (the NDA). (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "ancient", label: "Ancient empires", dateLabel: "to 1206", year: -2500, text: "Indus Valley, Maurya, Gupta." },
      { id: "medieval", label: "Sultanate & Mughals", dateLabel: "1206–1857", year: 1206, text: "Delhi Sultanate, the Mughal Empire." },
      { id: "raj", label: "British Raj", dateLabel: "1858–1947", year: 1858, text: "Colonial rule, the independence movement, partition." },
      { id: "republic", label: "Republic", dateLabel: "1950–present", year: 1950, text: "Nehruvian era, coalitions, the Modi era." },
    ],
    summary: "India is the world's largest democracy — a federal parliamentary republic with a 1950 constitution, a civilization spanning millennia, and a vibrant multi-party system.",
    simple: "India is a huge country in South Asia. It became independent from Britain in 1947 and is the world's largest democracy, with a prime minister and parliament.",
    relatedIds: ["pol.leader.india.modi", "pol.constitution.india", "org.un", "org.brics", "org.g20", "org.commonwealth"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.china",
    name: "China",
    altNames: ["People's Republic of China"],
    capital: "Beijing",
    governmentForm: "one_party_state",
    federalStructure: "unitary",
    independence: "The PRC was proclaimed on 1 October 1949; Chinese civilization's states date back millennia",
    independenceYear: 1949,
    preColonial: "The Xia/Shang/Zhou dynasties, the Qin unification (221 BCE), the Han, Tang, Song, Yuan, Ming and Qing empires — a continuous imperial tradition with a sophisticated bureaucracy.",
    colonialHistory: "The 19th-century 'century of humiliation': the Opium Wars, unequal treaties, foreign concessions, and the fall of the Qing in 1911.",
    independenceStory: "The Republic of China (1912) followed the Qing's fall; after the civil war, the Chinese Communist Party proclaimed the People's Republic in 1949 and the Nationalists retreated to Taiwan.",
    modernHistory: "Mao Zedong's era (1949–76), the Great Leap Forward and the Cultural Revolution, Deng Xiaoping's reforms (1978–), and the PRC's rise as a global power under Xi Jinping.",
    legislature: "The National People's Congress (the nominal supreme organ); the Chinese People's Political Consultative Conference advises.",
    executive: "The President and the State Council (the Premier) operate under the leadership of the Chinese Communist Party; the General Secretary of the CCP is the paramount leader.",
    judiciary: "The Supreme People's Court and the procuracy, under party leadership.",
    electoralSystem: "Elections exist at local levels and for the NPC, but they are not competitive multi-party elections; the CCP's leadership is constitutionally affirmed.",
    parties: ["Chinese Communist Party (CCP)", "(eight legally recognized minor parties under the united front)"],
    currentSituation: "Xi Jinping is the CCP General Secretary and President; the 2018 constitutional amendment removed presidential term limits; the PRC's relations with the West are strained over trade, Taiwan and human rights. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "imperial", label: "Imperial China", dateLabel: "221 BCE – 1911", year: -221, text: "The dynastic empires and the bureaucracy." },
      { id: "revolution", label: "Republic & revolution", dateLabel: "1912–1949", year: 1912, text: "The Republic of China, the civil war, the CCP's victory." },
      { id: "prc", label: "People's Republic", dateLabel: "1949–present", year: 1949, text: "Mao, reforms, the rise under Xi." },
    ],
    summary: "China is a one-party state and the world's most populous country — an imperial civilization whose Communist Party has ruled since 1949.",
    simple: "China is a very large country with an ancient history of emperors. Since 1949 it has been governed by the Communist Party.",
    relatedIds: ["org.un", "org.brics", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.brazil",
    name: "Brazil",
    altNames: ["Federative Republic of Brazil"],
    capital: "Brasília",
    governmentForm: "federal_republic",
    federalStructure: "federal",
    independence: "7 September 1822 (from Portugal); republic 15 November 1889",
    independenceYear: 1822,
    colonialPower: "Portugal (1500–1822)",
    preColonial: "Hundreds of Indigenous nations with their own political orders before Portuguese contact.",
    colonialHistory: "Portuguese colonization from 1500, the sugar and gold economies, the slave trade, and the transfer of the Portuguese court to Rio (1808).",
    independenceStory: "Brazil declared independence in 1822 under Emperor Pedro I, became a republic in 1889, and abolished slavery in 1888 — the last American country to do so.",
    modernHistory: "The Old Republic, Getúlio Vargas's era, the 1964–85 military dictatorship, redemocratization (1985), the 1988 constitution, and the Lula–Bolsonaro alternation of the 2010s–2020s.",
    legislature: "The National Congress: the Chamber of Deputies (513) and the Federal Senate (81).",
    executive: "The President is head of state and government, elected for two four-year terms.",
    judiciary: "The Supreme Federal Court and the superior courts.",
    electoralSystem: "Two-round presidential elections; open-list proportional representation for the Chamber; the Superior Electoral Court administers electronic voting.",
    parties: ["PT", "PL", "PSDB", "MDB", "PSD", "Podemos"],
    currentSituation: "Luiz Inácio Lula da Silva has been President since 2023, after defeating Jair Bolsonaro in the 2022 election. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "colonial", label: "Colonial Brazil", dateLabel: "1500–1822", year: 1500, text: "Portuguese colony, sugar and gold, the court's arrival." },
      { id: "empire", label: "Empire", dateLabel: "1822–1889", year: 1822, text: "Independence, the Empire, abolition (1888)." },
      { id: "republic", label: "Republics", dateLabel: "1889–present", year: 1889, text: "Old Republic, Vargas, dictatorship, redemocratization." },
    ],
    summary: "Brazil is a federal presidential republic — Latin America's largest country, with a 1988 constitution and a history from Portuguese colony to empire to democracy.",
    simple: "Brazil is a big country in South America. It was ruled by Portugal, then by emperors, and today its people elect a president.",
    relatedIds: ["org.un", "org.g20", "org.brics"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.canada",
    name: "Canada",
    altNames: ["Dominion of Canada"],
    capital: "Ottawa",
    governmentForm: "parliamentary_monarchy",
    federalStructure: "federal",
    independence: "Confederation 1 July 1867; full sovereignty evolved through the 1931 Statute of Westminster and the 1982 Constitution Act",
    independenceYear: 1867,
    colonialPower: "France (New France) and the United Kingdom",
    preColonial: "First Nations, Inuit and Métis peoples with diverse governance systems and treaty traditions.",
    colonialHistory: "New France (1608), the British conquest (1763), and the 19th-century union of the colonies.",
    independenceStory: "Confederation in 1867 created the Dominion; the Statute of Westminster (1931) granted legislative independence; the 1982 Constitution Act patriated the constitution with a Charter of Rights.",
    modernHistory: "Expansion westward, two world wars, the Quiet Revolution in Quebec, the 1980 and 1995 sovereignty referendums, and contemporary federal politics.",
    legislature: "Parliament: the House of Commons (338) and the appointed Senate (105).",
    executive: "The monarch (represented by the Governor General) is head of state; the Prime Minister is head of government.",
    judiciary: "The Supreme Court of Canada and the federal and provincial courts.",
    electoralSystem: "First-past-the-post for the Commons; the Chief Electoral Officer administers elections.",
    parties: ["Liberal Party", "Conservative Party", "NDP", "Bloc Québécois", "Green Party"],
    currentSituation: "Justin Trudeau (Liberal) resigned as Prime Minister in early 2025 after nine years in office; Mark Carney succeeded him as Liberal leader and Prime Minister in March 2025, with a federal election held in April 2025. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "colonial", label: "New France & British rule", dateLabel: "1608–1867", year: 1608, text: "French colony, British conquest, colonial unions." },
      { id: "confederation", label: "Confederation", dateLabel: "1867–1982", year: 1867, text: "Dominion status, the Statute of Westminster." },
      { id: "modern", label: "Modern Canada", dateLabel: "1982–present", year: 1982, text: "Patriation, the Charter, contemporary politics." },
    ],
    summary: "Canada is a federal parliamentary monarchy — a confederation of ten provinces and three territories with a Charter of Rights since 1982.",
    simple: "Canada is a country in North America. It has a King (represented by a Governor General) and an elected Prime Minister and Parliament.",
    relatedIds: ["org.commonwealth", "org.un", "org.nato", "org.g7", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.japan",
    name: "Japan",
    altNames: ["State of Japan"],
    capital: "Tokyo",
    governmentForm: "parliamentary_monarchy",
    federalStructure: "unitary",
    independence: "Unified as a state in antiquity; the modern constitutional monarchy dates from 1889; the current constitution from 1947",
    independenceYear: 1947,
    preColonial: "The Yamato state, the imperial court, the shogunates (Kamakura, Ashikaga, Tokugawa) — a thousand-year imperial tradition with feudal military government.",
    colonialHistory: "Japan was never colonized; it became a colonial power itself (Taiwan, Korea, Manchuria).",
    independenceStory: "The Meiji Restoration (1868) modernized the state; defeat in 1945 ended the empire; the 1947 constitution made Japan a parliamentary monarchy with a pacifist Article 9.",
    modernHistory: "Meiji modernization, militarism and World War II, the post-war 'economic miracle', the LDP's long dominance, and the 1990s stagnation followed by gradual reform.",
    legislature: "The National Diet: the House of Representatives (465) and the House of Councillors (248).",
    executive: "The Emperor is head of state (ceremonial); the Prime Minister is head of government.",
    judiciary: "The Supreme Court and the lower courts.",
    electoralSystem: "Mixed-member majoritarian for the House of Representatives; the House of Councillors uses parallel voting.",
    parties: ["LDP", "CDP", "Ishin", "Komeito", "DPFP", "JCP"],
    currentSituation: "Shigeru Ishiba (LDP) became Prime Minister in October 2024 after the LDP's leadership election; the LDP lost its majority in the October 2024 general election and now governs in a minority arrangement. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "imperial", label: "Imperial & shogunate Japan", dateLabel: "to 1868", year: -600, text: "The imperial court and the shogunates." },
      { id: "meiji", label: "Meiji to 1945", dateLabel: "1868–1945", year: 1868, text: "Modernization, empire, war." },
      { id: "postwar", label: "Post-war Japan", dateLabel: "1947–present", year: 1947, text: "The 1947 constitution, the economic miracle, LDP dominance." },
    ],
    summary: "Japan is a unitary parliamentary monarchy with the world's oldest continuous imperial line, governed under its pacifist 1947 constitution.",
    simple: "Japan is a country in Asia with an Emperor and an elected Prime Minister. After World War II it wrote a new constitution that renounced war.",
    relatedIds: ["org.un", "org.g7", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.russia",
    name: "Russia",
    altNames: ["Russian Federation"],
    capital: "Moscow",
    governmentForm: "semi_presidential_republic",
    federalStructure: "federal",
    independence: "The Russian Federation was proclaimed in 1991 after the Soviet Union's dissolution; the Russian state traces to the Principality of Moscow and the Tsardom",
    independenceYear: 1991,
    preColonial: "Kievan Rus', the Mongol yoke, the rise of Moscow, the Tsardom and the Russian Empire under Peter and Catherine.",
    colonialHistory: "Russia was itself an empire that expanded across Eurasia; it was never colonized.",
    independenceStory: "The 1917 revolutions ended the empire; the Soviet Union (1922–1991) succeeded it; the Russian Federation emerged from the USSR's dissolution in December 1991.",
    modernHistory: "The Soviet era (Lenin, Stalin, the Cold War), the 1990s transition under Yeltsin, the Putin era (2000–2008, 2012– ) with its centralization, and the 2022 full-scale invasion of Ukraine.",
    legislature: "The Federal Assembly: the State Duma (450) and the Federation Council.",
    executive: "The President is head of state with strong powers; the Prime Minister heads the government.",
    judiciary: "The Constitutional Court, the Supreme Court and the lower courts.",
    electoralSystem: "Mixed system for the Duma; presidential elections by popular vote (two-round).",
    parties: ["United Russia", "CPRF", "LDPR", "A Just Russia"],
    currentSituation: "Vladimir Putin has been President since 2000 (with a prime-ministerial interlude 2008–2012); the 2020 constitutional amendments reset his term limits; the war in Ukraine (2022– ) dominates Russia's politics and international relations. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "empire", label: "Tsardom & Empire", dateLabel: "1547–1917", year: 1547, text: "Ivan the Terrible to Nicholas II." },
      { id: "soviet", label: "Soviet Union", dateLabel: "1917–1991", year: 1917, text: "Revolutions, Stalinism, the Cold War, dissolution." },
      { id: "federation", label: "Russian Federation", dateLabel: "1991–present", year: 1991, text: "Yeltsin, Putin, the Ukraine war." },
    ],
    summary: "Russia is a federal semi-presidential republic — the Soviet Union's successor state, governed under the 1993 constitution and dominated by Vladimir Putin since 2000.",
    simple: "Russia is a huge country that was once the center of the Soviet Union. Since 1991 it is the Russian Federation, with a strong president.",
    relatedIds: ["org.un", "org.brics", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.egypt",
    name: "Egypt",
    altNames: ["Arab Republic of Egypt"],
    capital: "Cairo",
    governmentForm: "semi_presidential_republic",
    federalStructure: "unitary",
    independence: "Independence from the United Kingdom on 28 February 1922 (limited); full sovereignty after 1952/1956; republic 1953",
    independenceYear: 1922,
    colonialPower: "United Kingdom (protectorate 1914–1922; occupation from 1882)",
    preColonial: "One of the world's oldest states: the pharaonic civilization (c. 3100 BCE), the Ptolemaic kingdom, Roman and Byzantine rule, the Islamic caliphates, the Mamluk sultanate, and the Ottoman eyalet.",
    colonialHistory: "The French invasion (1798), Muhammad Ali's dynasty, the British occupation (1882) and protectorate (1914), and the 1919 revolution against British rule.",
    independenceStory: "Egypt gained nominal independence in 1922 under King Fuad; the 1952 revolution (the Free Officers) abolished the monarchy in 1953; the last British troops left after the 1956 Suez Crisis.",
    modernHistory: "Nasser's republic and pan-Arabism, Sadat's infitah and the Camp David peace, Mubarak's 30-year rule, the 2011 revolution, the 2013 change of government, and el-Sisi's presidency (2014– ).",
    legislature: "The House of Representatives (596) and the Senate (300, restored in 2020).",
    executive: "The President is head of state with strong powers; the Prime Minister heads the government.",
    judiciary: "The Supreme Constitutional Court and the ordinary courts.",
    electoralSystem: "Mixed system; presidential elections under the 2014 constitution.",
    parties: ["Nation's Future Party", "New Wafd", "Republican People's Party", "(others)"],
    currentSituation: "Abdel Fattah el-Sisi has been President since 2014 (re-elected 2018 and 2023); Egypt faces an economic crisis and has played a central role in the Gaza war diplomacy. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "pharaonic", label: "Pharaonic & ancient", dateLabel: "c. 3100 BCE – 641 CE", year: -3100, text: "The pharaohs, the Ptolemies, Rome and Byzantium." },
      { id: "islamic", label: "Islamic Egypt", dateLabel: "641–1882", year: 641, text: "Caliphates, Mamluks, Ottomans, Muhammad Ali." },
      { id: "modern", label: "Modern Egypt", dateLabel: "1882–present", year: 1882, text: "British occupation, the 1952 revolution, the republics." },
    ],
    summary: "Egypt is a semi-presidential republic — one of the world's oldest states, whose modern politics run from the 1952 revolution through Nasser, Sadat, Mubarak and el-Sisi.",
    simple: "Egypt is a very old country with pharaohs in its past. Today it is a republic, and its modern history began with a revolution in 1952.",
    relatedIds: ["org.arab-league", "org.african-union", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.ethiopia",
    name: "Ethiopia",
    altNames: ["Federal Democratic Republic of Ethiopia"],
    capital: "Addis Ababa",
    governmentForm: "parliamentary_republic",
    federalStructure: "federal",
    independence: "Never formally colonized (briefly occupied by Italy 1936–41); the modern federal republic dates from 1995",
    independenceYear: 1941,
    preColonial: "The Aksumite Empire (one of the ancient world's great states), the Zagwe dynasty, the Solomonic dynasty, and the 19th-century consolidation under Menelik II.",
    colonialHistory: "Ethiopia defeated Italy at Adwa in 1896 — the defining African victory over a colonial power; Italy occupied the country 1936–1941.",
    independenceStory: "There is no independence date in the colonial sense; the modern federal state was established by the 1995 constitution after the 1991 change of government.",
    modernHistory: "Haile Selassie's reign, the 1974 revolution and the Derg's military rule, the 1991 end of the Derg, the EPRDF's federal system, Abiy Ahmed's reforms (2018–), the Tigray war (2020–2022), and the ongoing federal reconfiguration.",
    legislature: "The House of Peoples' Representatives (547) and the House of Federation (112).",
    executive: "The President is head of state (ceremonial); the Prime Minister is head of government.",
    judiciary: "The Federal Supreme Court and the federal and regional courts.",
    electoralSystem: "First-past-the-post for the House of Peoples' Representatives; the National Electoral Board administers elections.",
    parties: ["Prosperity Party", "Tigray People's Liberation Front (TPLF)", "various regional parties"],
    currentSituation: "Abiy Ahmed has been Prime Minister since 2018; the 2020–2022 Tigray war ended with the Pretoria agreement (November 2022); the country faces federal restructuring debates and regional conflicts. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "aksum", label: "Aksum & the dynasties", dateLabel: "c. 1st century CE – 1855", year: 100, text: "Aksum, Zagwe, Solomonic dynasty." },
      { id: "modernization", label: "Empire to revolution", dateLabel: "1855–1991", year: 1855, text: "Tewodros to Haile Selassie, the Derg." },
      { id: "federal", label: "Federal republic", dateLabel: "1991–present", year: 1991, text: "EPRDF, Abiy's reforms, the Tigray war." },
    ],
    summary: "Ethiopia is a federal parliamentary republic — an ancient state never formally colonized, with a modern federal system since 1991.",
    simple: "Ethiopia is one of the world's oldest countries. It was never colonized, and today it is a federation led by a prime minister.",
    relatedIds: ["pol.leader.ethiopia.abiy", "org.african-union", "org.igad", "org.un"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.mexico",
    name: "Mexico",
    altNames: ["United Mexican States"],
    capital: "Mexico City",
    governmentForm: "federal_republic",
    federalStructure: "federal",
    independence: "11 September 1821 (from Spain); republic 1824",
    independenceYear: 1821,
    colonialPower: "Spain (1521–1821)",
    preColonial: "The Olmec, Maya, Teotihuacan, Toltec and Aztec civilizations — among the world's great pre-modern states.",
    colonialHistory: "The Spanish conquest (1521), the Viceroyalty of New Spain, and the colonial caste system.",
    independenceStory: "The 1810 Grito de Dolores began the war; independence came in 1821; the republic was established in 1824.",
    modernHistory: "The Reform era, the Porfiriato, the 1910 Revolution, PRI dominance (1929–2000), the transition to competitive democracy (2000–), and the Morena era (2018–).",
    legislature: "The Congress of the Union: the Chamber of Deputies (500) and the Senate (128).",
    executive: "The President is head of state and government, limited to one six-year term.",
    judiciary: "The Supreme Court of Justice and the federal judiciary.",
    electoralSystem: "Mixed-member proportional; the INE administers elections.",
    parties: ["Morena", "PAN", "PRI", "MC", "PRD"],
    currentSituation: "Claudia Sheinbaum (Morena) became the first woman president of Mexico in October 2024, succeeding Andrés Manuel López Obrador. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "ancient", label: "Ancient civilizations", dateLabel: "to 1521", year: -1500, text: "Olmec, Maya, Teotihuacan, Aztec." },
      { id: "colonial", label: "New Spain", dateLabel: "1521–1821", year: 1521, text: "The Spanish viceroyalty." },
      { id: "republic", label: "Republics & revolution", dateLabel: "1821–present", year: 1821, text: "Independence, the Revolution of 1910, PRI and the democratic era." },
    ],
    summary: "Mexico is a federal republic with one of the world's great ancient civilizations, a 1910 revolution, and a competitive democracy since 2000.",
    simple: "Mexico is a country in North America. It had great ancient civilizations, was ruled by Spain, and today is a democracy with a president.",
    relatedIds: ["org.un", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
  buildCountry({
    id: "pol.country.australia",
    name: "Australia",
    altNames: ["Commonwealth of Australia"],
    capital: "Canberra",
    governmentForm: "parliamentary_monarchy",
    federalStructure: "federal",
    independence: "Federation 1 January 1901; full sovereignty evolved through the Statute of Westminster (1931/1942) and the Australia Act (1986)",
    independenceYear: 1901,
    colonialPower: "United Kingdom (the six colonies)",
    preColonial: "Aboriginal and Torres Strait Islander peoples — among the world's oldest continuous cultures — with complex customary laws and governance.",
    colonialHistory: "British settlement from 1788 (New South Wales), the six self-governing colonies, and the 1901 federation.",
    independenceStory: "Federation in 1901 created the Commonwealth of Australia; the Australia Act (1986) ended residual British legislative power.",
    modernHistory: "Two world wars (including the Gallipoli campaign), the post-war migration program, the 1967 referendum on Indigenous rights, the 1999 republic referendum (defeated), and contemporary federal politics.",
    legislature: "The Parliament: the House of Representatives (151) and the Senate (76).",
    executive: "The monarch (represented by the Governor-General) is head of state; the Prime Minister is head of government.",
    judiciary: "The High Court of Australia and the federal and state courts.",
    electoralSystem: "Preferential voting (instant-runoff) for the House; proportional representation (STV) for the Senate; compulsory voting.",
    parties: ["Labor", "Liberal", "Nationals", "Greens", "independents"],
    currentSituation: "Anthony Albanese (Labor) has been Prime Minister since May 2022. (Current as of the Last Verified date — verify for updates.)",
    historyPeriods: [
      { id: "indigenous", label: "Indigenous Australia", dateLabel: "65,000+ years", year: null, text: "The world's oldest continuous cultures." },
      { id: "colonial", label: "Colonial Australia", dateLabel: "1788–1901", year: 1788, text: "British settlement and the six colonies." },
      { id: "federation", label: "Federation", dateLabel: "1901–present", year: 1901, text: "The Commonwealth, the wars, the modern federation." },
    ],
    summary: "Australia is a federal parliamentary monarchy — a 1901 federation with compulsory voting and one of the world's most stable democracies.",
    simple: "Australia is a country that became a federation in 1901. It has a Prime Minister, and voting in elections is compulsory.",
    relatedIds: ["org.commonwealth", "org.un", "org.g20"],
    sources: [SRC_ACADEMIC, SRC_ARCHIVE, SRC_CONSTITUTION],
  }),
];


/* ════════════════════════════════════════════════════════════════════════════
 * §11 — Constitutions for the covered countries
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_CONSTITUTIONS: ConstitutionRecord[] = [
  buildConstitution({
    id: "pol.constitution.usa",
    name: "Constitution of the United States (1787)",
    countryId: "pol.country.united-states",
    adopted: "17 September 1787 (ratified 1788; in force 4 March 1789)",
    previousConstitutions: ["The Articles of Confederation (1781–1789)"],
    separationOfPowers: "Three co-equal branches with checks and balances.",
    executivePowers: "Article II: the President is head of state and government, commander-in-chief, with veto and appointment powers.",
    legislativePowers: "Article I: a bicameral Congress (Senate and House) with enumerated powers.",
    judicialPowers: "Article III: the Supreme Court and inferior courts; judicial review established by Marbury v. Madison (1803).",
    federalism: "A federal system: enumerated federal powers, reserved state powers (10th Amendment).",
    electoralProvisions: "Presidential elections via the Electoral College; congressional elections by district.",
    termLimits: "The 22nd Amendment (1951) limits presidents to two terms.",
    emergencyPowers: "No explicit emergency clause; emergency powers are contested and derived.",
    successionRules: "The 25th Amendment (1967) covers vice-presidential succession and presidential incapacity.",
    rightsFreedoms: "The Bill of Rights (1791) and later amendments (13th, 14th, 15th, 19th, 26th).",
    constitutionalCourt: "No dedicated constitutional court; the Supreme Court exercises judicial review.",
    amendments: ["Bill of Rights (1791)", "13th (1865, abolition)", "14th (1868, equal protection)", "15th (1870, voting)", "19th (1920, women's suffrage)", "22nd (1951, term limits)", "25th (1967, succession)"],
    history: "Written at the 1787 Philadelphia convention; the world's oldest still-operative written constitution.",
    summary: "The 1787 US Constitution created the federal presidential republic and remains the world's oldest operative written constitution.",
    simple: "America's constitution from 1787 sets up three branches of government and a bill of rights.",
  }),
  buildConstitution({
    id: "pol.constitution.uk",
    name: "The uncodified constitution of the United Kingdom",
    countryId: "pol.country.united-kingdom",
    adopted: "No single document: evolved from Magna Carta (1215) to the present",
    previousConstitutions: [],
    separationOfPowers: "A 'fusion of powers': the executive sits within Parliament; the judiciary is independent.",
    executivePowers: "The Crown-in-Parliament: the Prime Minister and cabinet govern through the Commons' confidence.",
    legislativePowers: "Parliamentary sovereignty: the Commons, Lords and Crown enact legislation.",
    judicialPowers: "Independent courts; the Supreme Court (2009) heads the judiciary.",
    federalism: "Unitary with devolution to Scotland, Wales and Northern Ireland.",
    electoralProvisions: "First-past-the-post for the Commons; fixed five-year parliaments (Fixed-term Parliaments Act 2011, repealed 2022).",
    termLimits: "None for prime ministers; the monarch's role is hereditary.",
    emergencyPowers: "Civil Contingencies Act 2004 and prerogative powers.",
    successionRules: "The Succession to the Crown Act 2013; the monarch is succeeded by heredity.",
    rightsFreedoms: "The Human Rights Act 1998 incorporates the ECHR.",
    constitutionalCourt: "No constitutional court; the Supreme Court and parliamentary sovereignty coexist.",
    amendments: ["Magna Carta (1215)", "Bill of Rights (1689)", "Acts of Union (1707/1800)", "Reform Acts (19th century)", "Human Rights Act (1998)", "Brexit legislation (2020)"],
    history: "Britain's constitution is a layering of statutes, conventions, and common law over eight centuries.",
    summary: "The UK's constitution is uncodified — a layering of statutes, conventions and common law since 1215.",
    simple: "Britain has no single constitution document — its rules come from many laws and traditions built over centuries.",
  }),
  buildConstitution({
    id: "pol.constitution.kenya-2010",
    name: "Constitution of Kenya (2010)",
    countryId: "pol.country.kenya",
    adopted: "27 August 2010 (promulgated after the 2010 referendum)",
    previousConstitutions: ["The 1963 independence constitution and its amendments"],
    separationOfPowers: "Three branches with strong checks, including a two-term presidency.",
    executivePowers: "The President is head of state and government; the Deputy President and Cabinet assist.",
    legislativePowers: "A bicameral Parliament: the National Assembly and the Senate.",
    judicialPowers: "The Supreme Court, Court of Appeal, High Court; the Judicial Service Commission protects independence.",
    federalism: "Devolved government: 47 county governments with elected governors and assemblies.",
    electoralProvisions: "IEBC administers elections; the president must win a plurality and 25% in half the counties.",
    termLimits: "President limited to two five-year terms.",
    emergencyPowers: "States of emergency require National Assembly approval.",
    successionRules: "The Deputy President succeeds on vacancy (tested in 2022 by the 'dual candidacy' question).",
    rightsFreedoms: "A comprehensive Bill of Rights (Chapter Four).",
    constitutionalCourt: "The Supreme Court resolves presidential election disputes (as in 2017 and 2022).",
    amendments: ["The BBI (Building Bridges Initiative) attempt (2020–21) was invalidated by the courts"],
    history: "Drafted after the 2007–08 post-election crisis and the 2008 National Accord; approved by referendum in 2010.",
    summary: "Kenya's 2010 constitution — approved after the 2008 crisis — devolved power to 47 counties and strengthened rights and courts.",
    simple: "Kenya's 2010 constitution created county governments, a two-term president and a strong bill of rights.",
  }),
  buildConstitution({
    id: "pol.constitution.sa-1996",
    name: "Constitution of the Republic of South Africa (1996)",
    countryId: "pol.country.south-africa",
    adopted: "8 May 1996 (in force 4 February 1997)",
    previousConstitutions: ["The interim constitution (1993)", "the republican constitutions of 1961 and 1983 (apartheid-era)"],
    separationOfPowers: "Three branches; a powerful Constitutional Court at the apex.",
    executivePowers: "The President is head of state and government, elected by the National Assembly.",
    legislativePowers: "The National Assembly (400) and the National Council of Provinces (90).",
    judicialPowers: "The Constitutional Court, Supreme Court of Appeal and High Courts.",
    federalism: "A unitary state with nine provinces and strong constitutional protections.",
    electoralProvisions: "Proportional representation; the IEC administers elections.",
    termLimits: "The President limited to two five-year terms.",
    emergencyPowers: "States of emergency require parliamentary approval and judicial review.",
    successionRules: "Parliament elects a new president on vacancy.",
    rightsFreedoms: "A transformative Bill of Rights including socio-economic rights.",
    constitutionalCourt: "The Constitutional Court is the highest court on constitutional matters.",
    amendments: ["Section 25 (land) amendment debates have been prominent since 2018"],
    history: "Drafted through the multi-party negotiations that ended apartheid; the world's most admired post-conflict constitution.",
    summary: "South Africa's 1996 constitution — the product of the anti-apartheid negotiations — enshrines a transformative Bill of Rights.",
    simple: "South Africa's constitution, written after apartheid ended, gives everyone equal rights and a strong court to protect them.",
  }),
  buildConstitution({
    id: "pol.constitution.india",
    name: "Constitution of India (1950)",
    countryId: "pol.country.india",
    adopted: "26 November 1949 (in force 26 January 1950)",
    previousConstitutions: ["The Government of India Act 1935 (as the colonial framework)"],
    separationOfPowers: "Parliamentary system with an independent judiciary; a basic-structure doctrine limits amendments.",
    executivePowers: "The President is head of state (ceremonial); the Prime Minister and Council of Ministers exercise executive power.",
    legislativePowers: "The Lok Sabha and the Rajya Sabha.",
    judicialPowers: "The Supreme Court with judicial review and public-interest litigation.",
    federalism: "A federal system with a strong center; states have their own governments and assemblies.",
    electoralProvisions: "First-past-the-post; the Election Commission administers elections.",
    termLimits: "Prime ministers have no term limit; the President serves five years.",
    emergencyPowers: "Article 352 (national emergency) — declared 1975–77 (the Emergency), a defining constitutional controversy.",
    successionRules: "The Vice-President and parliamentary mechanisms cover presidential succession.",
    rightsFreedoms: "Part III Fundamental Rights; Part IV Directive Principles.",
    constitutionalCourt: "No dedicated court; the Supreme Court enforces the basic structure doctrine.",
    amendments: ["Over 100 amendments; the 42nd (1976) and 44th (1978) reshaped emergency powers; the 101st (2016) introduced GST"],
    history: "Drafted by the Constituent Assembly (1946–49) chaired by B.R. Ambedkar; the world's longest written constitution.",
    summary: "India's 1950 constitution — the world's longest — created the world's largest parliamentary democracy.",
    simple: "India's constitution, written by Dr. Ambedkar's assembly, set up the world's biggest democracy in 1950.",
  }),
];

