/**
 * Session 146 — Politics seed (global expansion): current heads of state
 * and government for every covered country (§4/§21), monarchs and a
 * traditional ruler (§4/§6), global political parties (§9), landmark global
 * elections (§10), the federal/parliamentary monarchy forms (§12), iconic
 * revolutions and a peace agreement (§15), additional diplomacy records
 * (§17), and the June 12 movement (§14).
 *
 * All current office-holders carry `current_as_of` + Last Verified (§21).
 */
import type {
  DiplomacyRecord,
  ElectionRecord,
  GovernmentFormRecord,
  LeaderRecord,
  MovementRecord,
  PartyRecord,
  PoliticalEventRecord,
} from "@windels/shared";
import {
  buildDiplomacy,
  buildElection,
  buildEvent,
  buildForm,
  buildLeader,
  buildMovement,
  buildParty,
  SRC_ACADEMIC,
  SRC_ARCHIVE,
  SRC_GOVT,
  SRC_JOURNALISM,
  SRC_UN,
} from "./politics.catalog.js";

const NIG = "pol.country.nigeria";
const USA = "pol.country.united-states";
const UK = "pol.country.united-kingdom";
const KEN = "pol.country.kenya";
const GHA = "pol.country.ghana";
const SA = "pol.country.south-africa";
const FRA = "pol.country.france";
const GER = "pol.country.germany";
const IND = "pol.country.india";
const CHN = "pol.country.china";
const BRA = "pol.country.brazil";
const CAN = "pol.country.canada";
const JPN = "pol.country.japan";
const RUS = "pol.country.russia";
const EGY = "pol.country.egypt";
const ETH = "pol.country.ethiopia";
const MEX = "pol.country.mexico";
const AUS = "pol.country.australia";

const CUR = {
  verification: "current_as_of" as const,
  asOfDate: "2026-08-08",
  lastVerified: "2026-08-08",
  sources: [SRC_GOVT, SRC_JOURNALISM],
};

/* ════════════════════════════════════════════════════════════════════════════
 * §4/§21 — current heads of state/government for every covered country
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_CURRENT_LEADERS: LeaderRecord[] = [
  buildLeader({
    id: "pol.leader.france.macron",
    name: "Emmanuel Macron",
    countryId: FRA,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "Renaissance",
    born: "1977 –",
    officeStart: "14 May 2017",
    predecessor: "François Hollande",
    cameToOffice: "Won the 2017 presidential election; re-elected in 2022 (the first re-elected president since Chirac).",
    ordinal: 8,
    majorPolicies: "Labour and pension reform, EU integration ('Europe that protects'), and the 2023 pension age rise to 64.",
    achievements: "Youngest French president since Napoleon; led France's EU and Ukraine-support diplomacy.",
    controversies: "The 2023 pension reform passed without a parliamentary vote; the 2024 snap election produced a hung parliament.",
    majorEvents: "The 2017 and 2022 elections, the Yellow Vest protests (2018–19), the 2024 snap legislative election.",
    constitutionalRole: "Head of state under the Fifth Republic, sharing executive power with the Prime Minister.",
    historicalSignificance: "Current President as of the Last Verified date.",
    summary: "Emmanuel Macron has been President of France since 2017 (re-elected 2022).",
    simple: "Emmanuel Macron is the president of France.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.china.xi",
    name: "Xi Jinping",
    countryId: CHN,
    title: "President; CCP General Secretary",
    titleKind: "president",
    role: "both",
    party: "CCP",
    born: "1953 –",
    officeStart: "14 March 2013",
    predecessor: "Hu Jintao",
    cameToOffice: "Elected President by the National People's Congress in 2013; the paramount leader as CCP General Secretary (2012– ).",
    ordinal: 7,
    majorPolicies: "The Belt and Road Initiative, the 'Chinese Dream', common prosperity, and the 2018 constitutional amendment removing presidential term limits.",
    achievements: "Presided over China's rise as a global power and the Belt and Road's expansion.",
    controversies: "The 2018 term-limit removal, the Xinjiang policies (documented human-rights allegations), the zero-COVID era, and the Ukraine-war stance are major documented controversies.",
    majorEvents: "The 2013 and 2018 constitutional changes, the trade war with the US (2018–), the COVID-19 response, the 2022 20th Party Congress third term.",
    constitutionalRole: "Head of state under the constitution; the CCP General Secretary is the paramount leader.",
    historicalSignificance: "Current paramount leader as of the Last Verified date; the longest-serving leader since Mao's era in practice.",
    summary: "Xi Jinping has led China as CCP General Secretary (2012–) and President (2013–).",
    simple: "Xi Jinping is the leader of China.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.russia.putin",
    name: "Vladimir Putin",
    countryId: RUS,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "United Russia",
    born: "1952 –",
    officeStart: "7 May 2012",
    officeEnd: "",
    predecessor: "Dmitry Medvedev (2012); first term 2000–2008",
    cameToOffice: "Served as President 2000–2008 and Prime Minister 2008–2012, then returned as President in 2012; re-elected 2018 and 2024; the 2020 constitutional amendments reset his term count.",
    ordinal: 3,
    majorPolicies: "Centralization of power, the annexation of Crimea (2014), and the full-scale invasion of Ukraine (2022–).",
    achievements: "Restored central authority after the 1990s; the longest-serving Russian leader since Stalin in office-time.",
    controversies: "The Ukraine war (2022–), the documented domestic political repression, the Navalny poisoning and death (2024), and the 2020 term-limit reset are major documented controversies.",
    majorEvents: "The 2014 annexation of Crimea, the 2020 constitutional amendments, the 2022 invasion of Ukraine and the resulting sanctions.",
    constitutionalRole: "Head of state with strong powers under the 1993 constitution (as amended 2020).",
    historicalSignificance: "Current President as of the Last Verified date.",
    summary: "Vladimir Putin has been Russia's President since 2012 (previously 2000–2008), re-elected in 2018 and 2024.",
    simple: "Vladimir Putin is the president of Russia.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.brazil.lula",
    name: "Luiz Inácio Lula da Silva",
    altNames: ["Lula"],
    countryId: BRA,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "PT",
    born: "1945 –",
    officeStart: "1 January 2023",
    predecessor: "Jair Bolsonaro",
    cameToOffice: "Won the 2022 presidential election (previously President 2003–2010).",
    ordinal: 39,
    majorPolicies: "The Bolsa Família social programs' restoration, environmental enforcement (Amazon), and industrial policy.",
    achievements: "Returned to the presidency after his 2018 conviction was annulled; his first terms (2003–2010) oversaw Brazil's commodity boom and poverty reduction.",
    controversies: "The corruption convictions and their annulment (documented and contested), and the 8 January 2023 Brasília riots response.",
    majorEvents: "The 2022 election, the 8 January 2023 attack on the government buildings, and the 2026 election campaign ahead.",
    constitutionalRole: "Head of state and government under the 1988 constitution.",
    historicalSignificance: "Current President as of the Last Verified date.",
    summary: "Luiz Inácio Lula da Silva has been Brazil's President since January 2023 (previously 2003–2010).",
    simple: "Lula is the president of Brazil.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.canada.carney",
    name: "Mark Carney",
    countryId: CAN,
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Liberal Party",
    born: "1965 –",
    officeStart: "14 March 2025",
    predecessor: "Justin Trudeau",
    cameToOffice: "Won the Liberal leadership after Trudeau's January 2025 resignation; formed government and called the April 2025 federal election.",
    ordinal: 24,
    majorPolicies: "Trade retaliation to US tariffs, 'Canada First' economic policy, and carbon-competitiveness measures.",
    achievements: "Former Governor of the Bank of Canada (2008–2013) and the Bank of England (2013–2020); led the Liberals into the April 2025 election.",
    controversies: "His government's trade confrontation with the US and the snap-election timing are documented subjects of debate.",
    majorEvents: "The March 2025 leadership transition and the April 2025 federal election.",
    constitutionalRole: "Head of government; the monarch's representative (Governor General) is head of state.",
    historicalSignificance: "Current Prime Minister as of the Last Verified date.",
    summary: "Mark Carney became Canada's Prime Minister in March 2025 after Justin Trudeau's resignation.",
    simple: "Mark Carney is the prime minister of Canada.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.japan.ishiba",
    name: "Shigeru Ishiba",
    countryId: JPN,
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "LDP",
    born: "1957 –",
    officeStart: "1 October 2024",
    predecessor: "Fumio Kishida",
    cameToOffice: "Won the LDP leadership election in September 2024; the LDP lost its majority in the October 2024 general election and governs as a minority.",
    ordinal: 102,
    majorPolicies: "Regional revitalization, defence spending increases, and political-funding reform after the LDP's scandals.",
    achievements: "Became prime minister at his fifth leadership bid; the October 2024 election was the LDP's worst result since 2009.",
    controversies: "The LDP's funding scandals and the minority-government arrangement are documented controversies.",
    majorEvents: "The September–October 2024 leadership and general elections.",
    constitutionalRole: "Head of government; the Emperor is head of state (ceremonial).",
    historicalSignificance: "Current Prime Minister as of the Last Verified date.",
    summary: "Shigeru Ishiba has been Japan's Prime Minister since October 2024, leading a minority LDP government.",
    simple: "Shigeru Ishiba is the prime minister of Japan.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.egypt.sisi",
    name: "Abdel Fattah el-Sisi",
    countryId: EGY,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "None (military background)",
    born: "1954 –",
    officeStart: "8 June 2014",
    predecessor: "Adly Mansour (interim)",
    cameToOffice: "Led the 2013 change of government as defence minister; elected president in 2014; re-elected 2018 and 2023.",
    ordinal: 6,
    majorPolicies: "Major infrastructure megaprojects, economic reform (the IMF program), and a central role in Gaza-war diplomacy.",
    achievements: "Stabilized the state after 2013; Egypt's mediator role in the 2023–24 Gaza ceasefire talks.",
    controversies: "The post-2013 crackdown on opposition (documented), the 2018 and 2023 election margins, and the economic crisis are major documented controversies.",
    majorEvents: "The 2013 change of government, the 2014/2018/2023 elections, the economic crisis (2022– ), and the Gaza war diplomacy (2023– ).",
    constitutionalRole: "Head of state with strong powers under the 2014 constitution.",
    historicalSignificance: "Current President as of the Last Verified date.",
    summary: "Abdel Fattah el-Sisi has been Egypt's President since 2014, re-elected in 2018 and 2023.",
    simple: "Abdel Fattah el-Sisi is the president of Egypt.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.mexico.sheinbaum",
    name: "Claudia Sheinbaum",
    countryId: MEX,
    title: "President",
    titleKind: "president",
    role: "both",
    party: "Morena",
    born: "1962 –",
    officeStart: "1 October 2024",
    predecessor: "Andrés Manuel López Obrador",
    cameToOffice: "Won the June 2024 presidential election with ~60% of the vote — the first woman elected president of Mexico.",
    ordinal: 66,
    majorPolicies: "Continuity with the 'Fourth Transformation', social programs, and security and energy policy.",
    achievements: "A former Mexico City mayor and climate scientist; the first woman and first Jewish person to lead Mexico.",
    controversies: "The 2024 judicial-reform controversy (elected judges) is a documented subject of national and international debate.",
    majorEvents: "The June 2024 election and the October 2024 inauguration.",
    constitutionalRole: "Head of state and government under the 1917 constitution; one six-year term.",
    historicalSignificance: "Current President as of the Last Verified date; the first woman to hold the office.",
    summary: "Claudia Sheinbaum became Mexico's President in October 2024 — the first woman elected to the office.",
    simple: "Claudia Sheinbaum is the first woman president of Mexico.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.australia.albanese",
    name: "Anthony Albanese",
    countryId: AUS,
    title: "Prime Minister",
    titleKind: "prime_minister",
    role: "head_of_government",
    party: "Labor",
    born: "1963 –",
    officeStart: "23 May 2022",
    predecessor: "Scott Morrison",
    cameToOffice: "Led Labor to victory in the May 2022 federal election.",
    ordinal: 31,
    majorPolicies: "The Voice referendum (2023), the AUKUS submarine pact, climate targets, and the National Reconstruction Fund.",
    achievements: "The 2023 Voice referendum and the 2022–23 AUKUS agreement; a 2025 federal election is scheduled.",
    controversies: "The failed Voice referendum and the 2025 election campaign are documented.",
    majorEvents: "The 2022 election, the 2023 referendum, and the 2025 federal election.",
    constitutionalRole: "Head of government; the monarch's representative (Governor-General) is head of state.",
    historicalSignificance: "Current Prime Minister as of the Last Verified date.",
    summary: "Anthony Albanese has been Australia's Prime Minister since May 2022.",
    simple: "Anthony Albanese is the prime minister of Australia.",
    ...CUR,
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §4 — Monarchs and a traditional ruler (§6, politically relevant)
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_MONARCHS: LeaderRecord[] = [
  buildLeader({
    id: "pol.leader.uk.charles",
    name: "Charles III",
    altNames: ["King Charles"],
    countryId: UK,
    title: "King of the United Kingdom",
    titleKind: "monarch_king",
    role: "head_of_state",
    born: "1948 –",
    officeStart: "8 September 2022",
    predecessor: "Elizabeth II",
    cameToOffice: "Succeeded on the death of his mother, Elizabeth II — the longest-serving heir apparent in British history.",
    majorPolicies: "A constitutional monarch: ceremonial head of state within the uncodified constitution; patron of numerous charities.",
    achievements: "The longest-serving Prince of Wales (1958–2022) before his accession.",
    controversies: "The monarchy's funding and the historical colonial-era debates are documented subjects of public debate.",
    majorEvents: "The 2022 accession, the 2023 coronation, and the 2024–25 royal health events.",
    constitutionalRole: "Head of state (ceremonial) in the parliamentary monarchy; the Prime Minister governs.",
    historicalSignificance: "Current King as of the Last Verified date.",
    summary: "Charles III has been King of the United Kingdom and the other Commonwealth realms since 8 September 2022.",
    simple: "King Charles III is the king of the United Kingdom.",
    ...CUR,
  }),
  buildLeader({
    id: "pol.leader.uk.elizabeth",
    name: "Elizabeth II",
    countryId: UK,
    title: "Queen of the United Kingdom",
    titleKind: "monarch_queen",
    role: "head_of_state",
    born: "1926 – 2022",
    officeStart: "6 February 1952",
    officeEnd: "8 September 2022",
    predecessor: "George VI",
    successor: "Charles III",
    cameToOffice: "Succeeded on the death of her father, George VI.",
    majorPolicies: "A constitutional monarch for 70 years; the longest-reigning British monarch and the longest-reigning female monarch in history.",
    achievements: "Reigned through 15 British prime ministers from Churchill to Truss; a symbol of continuity through decolonization and the Commonwealth's transformation.",
    controversies: "The monarchy's role during the Diana era and the 1997 response are documented subjects of debate.",
    majorEvents: "Decolonization, the Commonwealth's evolution, the 1977 and 2002 jubilees, the 2022 Platinum Jubilee and her death.",
    constitutionalRole: "Head of state (ceremonial) for 70 years.",
    historicalSignificance: "The defining monarch of the late 20th century; her reign spanned the end of empire.",
    summary: "Elizabeth II was Queen of the United Kingdom for 70 years (1952–2022) — the longest-reigning British monarch.",
    simple: "Queen Elizabeth II reigned for 70 years, longer than any British monarch.",
    sources: [SRC_ARCHIVE, SRC_GOVT],
  }),
  buildLeader({
    id: "pol.leader.nigeria.sultan",
    name: "Sa'adu Abubakar III",
    altNames: ["Sultan of Sokoto"],
    countryId: NIG,
    title: "Sultan of Sokoto",
    titleKind: "sultan",
    role: "other",
    born: "1956 –",
    officeStart: "2 November 2006",
    predecessor: "Muhammadu Maccido",
    cameToOffice: "Elected by the kingmakers of Sokoto after the death of Sultan Maccido; the 20th Sultan of the Sokoto Caliphate's line.",
    majorPolicies: "As the spiritual leader of Nigeria's Muslims and a traditional ruler, he promotes religious harmony and social development.",
    achievements: "A former Nigerian Army brigadier-general; a respected voice in Nigerian interfaith and national affairs.",
    controversies: "His public statements on national issues have at times drawn government criticism — a documented feature of the office's political relevance.",
    majorEvents: "His 2006 accession and his ongoing national role.",
    constitutionalRole: "Traditional ruler with customary authority and moral influence; not an elected political office (§6 'traditional rulers where politically relevant').",
    historicalSignificance: "Current Sultan of Sokoto — the most prominent traditional ruler in Nigeria.",
    summary: "Sa'adu Abubakar III has been the Sultan of Sokoto since 2006 — Nigeria's most prominent traditional ruler and the spiritual leader of Nigerian Muslims.",
    simple: "The Sultan of Sokoto is a very important traditional leader in Nigeria.",
    ...CUR,
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §9 — global political parties for the covered countries
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_PARTIES: PartyRecord[] = [
  buildParty({
    id: "pol.party.us.democratic",
    name: "Democratic Party (United States)",
    abbreviation: "DNC",
    countryId: USA,
    founded: "1828 (modern form); the Democratic-Republican lineage earlier",
    selfDescription: "The party of the working family, equal opportunity and civil rights.",
    academicClassification: "A big-tent center-left coalition: labour, minorities, urban and professional constituencies, with progressive and moderate wings.",
    position: "Center-left (with context: a broad coalition).",
    majorLeaders: ["Franklin D. Roosevelt", "Barack Obama", "Joe Biden", "Kamala Harris"],
    historicalDevelopment: "Founded under Andrew Jackson; rebuilt by the New Deal coalition; the party of civil-rights legislation in the 1960s; the modern party spans progressive and moderate wings.",
    electoralHistory: "Won the presidency in 2008, 2012 and 2020; lost in 2016 and 2024; controls neither chamber of Congress as of the Last Verified date.",
    currentStatus: "The main opposition party at the federal level (as of the Last Verified date).",
    governmentParticipation: "Controlled the presidency 2021–2025.",
    historicalSignificance: "One of the world's oldest and most consequential political parties.",
    summary: "The Democratic Party is one of the United States' two major parties — a center-left coalition since the New Deal era.",
    simple: "The Democratic Party is one of the two big parties in America.",
  }),
  buildParty({
    id: "pol.party.us.republican",
    name: "Republican Party (United States)",
    abbreviation: "GOP",
    countryId: USA,
    founded: "1854",
    founders: ["The anti-slavery coalition of the 1850s"],
    selfDescription: "The party of liberty, limited government, free enterprise and traditional values.",
    academicClassification: "A big-tent center-right party: conservative, libertarian and (since 2016) populist-nationalist wings.",
    position: "Center-right (with context: significant internal variation).",
    majorLeaders: ["Abraham Lincoln", "Ronald Reagan", "Donald Trump"],
    historicalDevelopment: "Founded in 1854 against slavery; the party of Lincoln and Reconstruction; the business-conservative coalition of the 20th century; reshaped by the Trump movement after 2016.",
    electoralHistory: "Won the presidency in 2016 and 2024; controls the Senate and the House as of the Last Verified date.",
    currentStatus: "The federal governing party (as of the Last Verified date).",
    governmentParticipation: "Controls the presidency and Congress since January 2025.",
    historicalSignificance: "One of the world's oldest and most consequential political parties.",
    summary: "The Republican Party is one of the United States' two major parties — a center-right coalition that has governed since 2025.",
    simple: "The Republican Party is one of the two big parties in America.",
  }),
  buildParty({
    id: "pol.party.uk.labour",
    name: "Labour Party (UK)",
    abbreviation: "Lab",
    countryId: UK,
    founded: "1900",
    selfDescription: "A democratic socialist party of working people.",
    academicClassification: "Social-democratic center-left; historically the party of the trade unions.",
    position: "Center-left (with context: from the Attlee welfare state to New Labour's centrism).",
    majorLeaders: ["Clement Attlee", "Harold Wilson", "Tony Blair", "Keir Starmer"],
    historicalDevelopment: "Founded by the labour movement; built the post-war welfare state under Attlee (1945–51); Blair's New Labour governed 1997–2010; Starmer returned it to government in 2024.",
    electoralHistory: "Won the 1945, 1964–70, 1974–79, 1997–2010 and 2024 elections.",
    currentStatus: "Governing party since July 2024 (as of the Last Verified date).",
    governmentParticipation: "In government 1945–51, 1964–70, 1974–79, 1997–2010, 2024– .",
    historicalSignificance: "The architect of the British welfare state.",
    summary: "The Labour Party is the UK's center-left party, in government since 2024 under Keir Starmer.",
    simple: "Labour is one of the two big parties in Britain, and it is in power now.",
  }),
  buildParty({
    id: "pol.party.uk.conservative",
    name: "Conservative Party (UK)",
    abbreviation: "Con",
    countryId: UK,
    founded: "1834 (the modern party; Tory origins in the 1670s)",
    selfDescription: "The Conservative and Unionist Party — the party of enterprise, security and the Union.",
    academicClassification: "Center-right: liberal-conservative, with Thatcherite and One-Nation wings.",
    position: "Center-right (with context).",
    majorLeaders: ["Benjamin Disraeli", "Winston Churchill", "Margaret Thatcher", "David Cameron", "Rishi Sunak"],
    historicalDevelopment: "The successor of the Tories; dominated 20th-century British politics alongside Labour; governed 2010–2024; lost the 2024 election in a landslide.",
    electoralHistory: "Won most elections between 1951 and 1997 and again in 2010–2019; the 2024 defeat was its worst since 1997.",
    currentStatus: "The main opposition party (as of the Last Verified date).",
    governmentParticipation: "In government 2010–2024.",
    historicalSignificance: "Britain's oldest major party and one of the world's most successful electoral machines.",
    summary: "The Conservative Party is the UK's center-right party, the main opposition since the 2024 election.",
    simple: "The Conservatives are one of the two big parties in Britain.",
  }),
  buildParty({
    id: "pol.party.kenya.uda",
    name: "United Democratic Alliance (Kenya)",
    abbreviation: "UDA",
    countryId: KEN,
    founded: "2020 (registered 2021)",
    founders: ["William Ruto and allied politicians"],
    selfDescription: "The party of the 'Bottom-Up' economic transformation agenda.",
    academicClassification: "A catch-all vehicle for William Ruto's coalition, drawing on the Kenya Kwanza alliance; ideology is secondary to coalition politics.",
    position: "Catch-all (with context).",
    majorLeaders: ["William Ruto", "Rigathi Gachagua", "Kithure Kindiki"],
    historicalDevelopment: "Created as Ruto's vehicle for the 2022 election; won the presidency with the Kenya Kwanza coalition; the party has since absorbed members from across the political spectrum.",
    electoralHistory: "Won the 2022 presidential election (with the Kenya Kwanza alliance).",
    currentStatus: "The governing party (as of the Last Verified date).",
    governmentParticipation: "The presidency since 2022, including the 2024 broad-based government.",
    historicalSignificance: "The vehicle of Kenya's fifth president.",
    summary: "The UDA is the Kenyan governing party, the vehicle of President William Ruto.",
    simple: "UDA is the party of Kenya's president, William Ruto.",
  }),
  buildParty({
    id: "pol.party.kenya.odm",
    name: "Orange Democratic Movement (Kenya)",
    abbreviation: "ODM",
    countryId: KEN,
    founded: "2005",
    founders: ["Raila Odinga and the 'No' campaign of the 2005 referendum"],
    selfDescription: "A social-democratic, reformist party.",
    academicClassification: "Center-left; Raila Odinga's personal vehicle with deep support in Luo Nyanza and urban areas.",
    position: "Center-left (with context).",
    majorLeaders: ["Raila Odinga", "Anyang' Nyong'o"],
    historicalDevelopment: "Born from the 2005 constitutional-referendum 'No' campaign; Odinga's presidential bids in 2007, 2013, 2017 and 2022 all fell short; joined Ruto's broad-based government in 2024.",
    electoralHistory: "Lost the 2007, 2013, 2017 and 2022 presidential elections (the 2007 result triggered the post-election crisis).",
    currentStatus: "Participates in the broad-based government since 2024 (as of the Last Verified date).",
    governmentParticipation: "Coalition government 2008–2013 (the Grand Coalition); ministers in the 2024 broad-based government.",
    historicalSignificance: "The main opposition party of Kenya's Fourth Republic until 2024.",
    summary: "ODM is Raila Odinga's party — Kenya's historic main opposition, part of the government since 2024.",
    simple: "ODM is the party of Raila Odinga, a famous Kenyan opposition leader.",
  }),
  buildParty({
    id: "pol.party.sa.anc",
    name: "African National Congress (South Africa)",
    abbreviation: "ANC",
    countryId: SA,
    founded: "1912",
    selfDescription: "A national liberation movement and the party of the democratic transition.",
    academicClassification: "A liberation movement turned dominant party; social-democratic in its post-1994 program.",
    position: "Center-left (with context: a broad liberation-movement coalition).",
    majorLeaders: ["Nelson Mandela", "Thabo Mbeki", "Jacob Zuma", "Cyril Ramaphosa"],
    historicalDevelopment: "Founded in 1912; banned 1960–1990; won the 1994 election under Mandela; governed continuously since; lost its parliamentary majority for the first time in 2024.",
    electoralHistory: "Won every national election 1994–2019 with a majority; fell to 40.2% in 2024.",
    currentStatus: "The largest party, leading the Government of National Unity (as of the Last Verified date).",
    governmentParticipation: "In government since 1994; leading the GNU since 2024.",
    historicalSignificance: "The movement that ended apartheid and built democratic South Africa.",
    summary: "The ANC, the party of Mandela and the anti-apartheid struggle, has governed South Africa since 1994.",
    simple: "The ANC is the party of Nelson Mandela and has ruled South Africa since 1994.",
  }),
  buildParty({
    id: "pol.party.sa.da",
    name: "Democratic Alliance (South Africa)",
    abbreviation: "DA",
    countryId: SA,
    founded: "2000 (merger of the DP, NNP and the Federal Alliance)",
    selfDescription: "A liberal party of the open society.",
    academicClassification: "Center-right liberal; the official opposition until 2024.",
    position: "Center-right (with context).",
    majorLeaders: ["Tony Leon", "Helen Zille", "John Steenhuisen"],
    historicalDevelopment: "Formed in 2000 as the liberal opposition; governed the Western Cape since 2009; joined the Government of National Unity in 2024.",
    electoralHistory: "Second place in every election since 1999; 21.8% in 2024.",
    currentStatus: "The second-largest party and a GNU partner (as of the Last Verified date).",
    governmentParticipation: "Provincial government in the Western Cape; national GNU partner since 2024.",
    historicalSignificance: "South Africa's principal opposition party of the democratic era.",
    summary: "The DA is South Africa's liberal opposition-turned-coalition partner in the 2024 Government of National Unity.",
    simple: "The DA is the main opposition party in South Africa, now part of the government coalition.",
  }),
  buildParty({
    id: "pol.party.germany.cdu",
    name: "Christian Democratic Union (Germany)",
    abbreviation: "CDU/CSU",
    countryId: GER,
    founded: "1945 (with the Bavarian sister party CSU)",
    selfDescription: "A people's party of the political center grounded in Christian social teaching.",
    academicClassification: "Center-right Christian-democratic; the anchor of post-war German governments.",
    position: "Center-right (with context: a broad 'people's party').",
    majorLeaders: ["Konrad Adenauer", "Helmut Kohl", "Angela Merkel", "Friedrich Merz"],
    historicalDevelopment: "Founded after 1945; governed under Adenauer, Kohl and Merkel for most of the Federal Republic's history; returned to government in 2025 under Merz.",
    electoralHistory: "Won the 1949–1969, 1982–1998 and 2005–2021 elections; 28.5% in 2025.",
    currentStatus: "The governing party since May 2025 (as of the Last Verified date).",
    governmentParticipation: "In government for most of the Federal Republic's history; the 2025 grand coalition with the SPD.",
    historicalSignificance: "The party of West Germany's reconstruction and reunification.",
    summary: "The CDU/CSU is Germany's center-right Christian-democratic bloc, governing since 2025 under Friedrich Merz.",
    simple: "The CDU is one of Germany's two big parties, and it is in power now.",
  }),
  buildParty({
    id: "pol.party.germany.spd",
    name: "Social Democratic Party of Germany",
    abbreviation: "SPD",
    countryId: GER,
    founded: "1875 (from the ADAV and SDAP)",
    selfDescription: "A social-democratic party of workers and citizens.",
    academicClassification: "Center-left; Germany's oldest party; a pioneer of social democracy.",
    position: "Center-left (with context).",
    majorLeaders: ["Willy Brandt", "Helmut Schmidt", "Gerhard Schröder", "Olaf Scholz"],
    historicalDevelopment: "Founded in the 19th century; the party of the welfare state and Ostpolitik; governed under Brandt, Schmidt, Schröder and Scholz; junior partner in the 2025 coalition.",
    electoralHistory: "16.4% in 2025 — its worst post-war result; governed 2021–2025 under Scholz.",
    currentStatus: "The junior partner in the 2025 grand coalition (as of the Last Verified date).",
    governmentParticipation: "In government for much of the Federal Republic's history; 2021–2025 led the traffic-light coalition.",
    historicalSignificance: "The founding party of European social democracy.",
    summary: "The SPD is Germany's center-left party and the junior partner in the 2025 coalition.",
    simple: "The SPD is one of Germany's two big parties.",
  }),
  buildParty({
    id: "pol.party.india.bjp",
    name: "Bharatiya Janata Party (India)",
    abbreviation: "BJP",
    countryId: IND,
    founded: "1980",
    selfDescription: "A party of cultural nationalism and integral humanism.",
    academicClassification: "Right-wing Hindu-nationalist; the political vehicle of the Sangh Parivar family.",
    position: "Right (with context: Hindu nationalism is its defining feature).",
    majorLeaders: ["Atal Bihari Vajpayee", "L.K. Advani", "Narendra Modi", "Amit Shah"],
    historicalDevelopment: "Evolved from the Bharatiya Jana Sangh (1951); governed 1998–2004 under Vajpayee; Modi's majorities 2014 and 2019; a coalition government since 2024.",
    electoralHistory: "Won 282 seats in 2014 and 303 in 2019; fell to 240 in 2024 (the NDA retains a majority).",
    currentStatus: "The governing party, leading the NDA coalition (as of the Last Verified date).",
    governmentParticipation: "In government 1998–2004 and since 2014.",
    historicalSignificance: "The dominant party of 21st-century Indian politics.",
    summary: "The BJP is India's governing Hindu-nationalist party under Narendra Modi since 2014.",
    simple: "The BJP is the party of India's prime minister, Narendra Modi.",
  }),
  buildParty({
    id: "pol.party.india.inc",
    name: "Indian National Congress",
    abbreviation: "INC",
    countryId: IND,
    founded: "1885",
    selfDescription: "A secular, social-democratic party — the party of Indian independence.",
    academicClassification: "Center to center-left catch-all; historically India's dominant party.",
    position: "Center (with context: a broad historical coalition).",
    majorLeaders: ["Mahatma Gandhi (moral leader)", "Jawaharlal Nehru", "Indira Gandhi", "Rahul Gandhi"],
    historicalDevelopment: "Founded in 1885; led the independence movement; governed India for most of 1947–2014; reduced to opposition since 2014.",
    electoralHistory: "99 seats in 2024 (its best since 2014 but far from government).",
    currentStatus: "The principal opposition party (as of the Last Verified date).",
    governmentParticipation: "Governed for most of 1947–2014.",
    historicalSignificance: "The party of Gandhi and Nehru — the architect of Indian independence.",
    summary: "The Indian National Congress, the party of Gandhi and Nehru, is India's principal opposition party.",
    simple: "The Congress party led India to independence and ruled for most of its history.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §10 — landmark global elections
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_ELECTIONS: ElectionRecord[] = [
  buildElection({
    id: "pol.election.us.2024",
    name: "United States presidential election, 2024",
    countryId: USA,
    electionType: "Presidential",
    date: "5 November 2024",
    year: 2024,
    turnout: "~63.9%",
    winner: "Donald Trump (Republican)",
    winnerParty: "Republican",
    runnerUp: "Kamala Harris (Democratic)",
    resultSummary: "Per certified results: Trump won 312 electoral votes to Harris's 226, and the popular vote roughly 77.3 million (49.8%) to 75.0 million (48.3%).",
    electoralSystem: "The Electoral College: each state's electors chosen by the statewide popular vote.",
    importance: "Trump became the second president (after Grover Cleveland in 1892) to win non-consecutive terms; Republicans swept the presidency, the Senate and the House.",
    disputes: "The result was certified without the disputes of 2020; Harris conceded the day after the election.",
    candidates: ["Donald Trump", "Kamala Harris", "Jill Stein", "Robert F. Kennedy Jr. (withdrew)"],
  }),
  buildElection({
    id: "pol.election.uk.2024",
    name: "United Kingdom general election, 2024",
    countryId: UK,
    electionType: "Parliamentary",
    date: "4 July 2024",
    year: 2024,
    turnout: "~59.8%",
    winner: "Labour Party",
    winnerParty: "Labour",
    runnerUp: "Conservative Party",
    resultSummary: "Per official results: Labour won 411 of 650 seats (a majority of 172); the Conservatives fell to 121 — their worst result ever.",
    electoralSystem: "First-past-the-post in 650 constituencies.",
    importance: "Ended 14 years of Conservative government; the largest Labour majority since 1997; the lowest turnout since 2001.",
    disputes: "No significant disputes; the result was a decisive Labour victory.",
    candidates: ["Keir Starmer", "Rishi Sunak", "Ed Davey", "Nigel Farage"],
  }),
  buildElection({
    id: "pol.election.kenya.2022",
    name: "Kenyan presidential election, 2022",
    countryId: KEN,
    electionType: "Presidential",
    date: "9 August 2022",
    year: 2022,
    turnout: "~64.9%",
    winner: "William Ruto (UDA)",
    winnerParty: "UDA",
    runnerUp: "Raila Odinga (ODM/Azimio)",
    resultSummary: "Per the IEBC: Ruto 7,176,141 votes (50.49%) to Odinga's 6,942,930 (48.85%) — the closest presidential result in Kenyan history.",
    electoralSystem: "First-past-the-post with the 25%-in-half-the-counties requirement.",
    importance: "The first election under the 2010 constitution's full framework in which a deputy president defeated the establishment candidate; Ruto became the fifth president.",
    disputes: "Odinga challenged the result; the Supreme Court unanimously upheld Ruto's victory on 5 September 2022.",
    candidates: ["William Ruto", "Raila Odinga", "George Wajackoyah", "David Mwaure"],
  }),
  buildElection({
    id: "pol.election.sa.2024",
    name: "South African general election, 2024",
    countryId: SA,
    electionType: "Parliamentary",
    date: "29 May 2024",
    year: 2024,
    turnout: "~58.6%",
    winner: "ANC (first time without a majority)",
    winnerParty: "ANC",
    runnerUp: "Democratic Alliance",
    resultSummary: "Per the IEC: ANC 40.18% (159 seats), DA 21.81% (87), MK Party 14.58% (58), EFF 9.52% (39), IFP 3.85% (17).",
    electoralSystem: "Proportional representation (national and provincial party lists).",
    importance: "The ANC lost its parliamentary majority for the first time since 1994, producing the Government of National Unity under Cyril Ramaphosa.",
    disputes: "The MK Party challenged the results; the Constitutional Court dismissed the main challenge.",
    candidates: ["Cyril Ramaphosa (ANC)", "John Steenhuisen (DA)", "Jacob Zuma (MK)", "Julius Malema (EFF)"],
  }),
  buildElection({
    id: "pol.election.ghana.2024",
    name: "Ghanaian general election, 2024",
    countryId: GHA,
    electionType: "Presidential and parliamentary",
    date: "7 December 2024",
    year: 2024,
    turnout: "~65.7%",
    winner: "John Mahama (NDC)",
    winnerParty: "NDC",
    runnerUp: "Mahamudu Bawumia (NPP)",
    resultSummary: "Per the Electoral Commission: Mahama ~56.6% (6.33 million) to Bawumia's ~41.0% (4.66 million); the NDC also won a parliamentary majority.",
    electoralSystem: "First-past-the-post for the presidency and single-member constituencies.",
    importance: "A decisive turnover: the NDC regained power after eight years, and Mahama returned to the presidency he had lost in 2016.",
    disputes: "Bawumia conceded the night of the election; the NPP accepted the result.",
    candidates: ["John Mahama", "Mahamudu Bawumia", "Alan Kyerematen"],
  }),
  buildElection({
    id: "pol.election.germany.2025",
    name: "German federal election, 2025",
    countryId: GER,
    electionType: "Parliamentary (Bundestag)",
    date: "23 February 2025",
    year: 2025,
    turnout: "~82.5%",
    winner: "CDU/CSU",
    winnerParty: "CDU/CSU",
    runnerUp: "Alternative for Germany (AfD)",
    resultSummary: "Per the federal returning officer: CDU/CSU 28.5% (208 seats), AfD 20.8% (152), SPD 16.4% (120), Greens 11.6% (85), The Left 8.8% (64); the FDP and BSW fell below the 5% threshold.",
    electoralSystem: "Mixed-member proportional with a 5% threshold.",
    importance: "The AfD became the second-largest party for the first time; the snap election followed the collapse of Scholz's traffic-light coalition; Friedrich Merz formed a CDU/CSU–SPD grand coalition in May 2025.",
    disputes: "The February 2025 votes with AfD support on migration (the 'firewall' debate) were a major documented political controversy.",
    candidates: ["Friedrich Merz (CDU/CSU)", "Olaf Scholz (SPD)", "Alice Weidel (AfD)", "Robert Habeck (Greens)"],
  }),
  buildElection({
    id: "pol.election.india.2024",
    name: "Indian general election, 2024",
    countryId: IND,
    electionType: "Parliamentary (Lok Sabha)",
    date: "19 April – 1 June 2024",
    year: 2024,
    turnout: "~66.1%",
    winner: "NDA coalition (BJP-led)",
    winnerParty: "BJP",
    runnerUp: "INDIA alliance (Congress-led)",
    resultSummary: "Per the Election Commission: the BJP won 240 seats (down from 303), the NDA coalition 293; the Congress 99, the INDIA alliance 234.",
    electoralSystem: "First-past-the-post in 543 constituencies.",
    importance: "The world's largest election (over 640 million voters); the BJP lost its single-party majority for the first time since 2014, forcing Modi's third term to depend on coalition partners.",
    disputes: "The opposition alleged irregularities (documented claims); the result was accepted after counting.",
    candidates: ["Narendra Modi (BJP/NDA)", "Rahul Gandhi (Congress/INDIA)"],
  }),
  buildElection({
    id: "pol.election.france.2024",
    name: "French legislative election, 2024 (snap)",
    countryId: FRA,
    electionType: "Legislative (National Assembly)",
    date: "30 June and 7 July 2024",
    year: 2024,
    turnout: "~66.6% (second round)",
    winner: "New Popular Front (largest bloc, no majority)",
    winnerParty: "NFP",
    runnerUp: "Ensemble (presidential bloc)",
    resultSummary: "Per the official results: the New Popular Front won ~182 seats, Ensemble ~163, the National Rally and allies ~142 — a hung National Assembly.",
    electoralSystem: "Two-round majoritarian in 577 constituencies.",
    importance: "Macron's snap election, called after the RN's European-election victory, produced a hung parliament and a period of fragile coalition governments (Barnier, then Bayrou).",
    disputes: "No formal disputes; the RN contested the coalition arithmetic politically.",
    candidates: ["Jordan Bardella (RN)", "Gabriel Attal (Ensemble)", "Jean-Luc Mélenchon (LFI/NFP)"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §12 — the remaining government forms
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_FORMS: GovernmentFormRecord[] = [
  buildForm({
    id: "pol.form.federal-monarchy",
    name: "Federal monarchy",
    definition: "A federation whose head of state is a monarch, with the federal units retaining their own rulers or governments.",
    howItWorks: "A constitutional arrangement in which sovereignty is divided between a federal center and member states, while the head of state is a monarch or a council of monarchs.",
    examples: ["United Arab Emirates (a council of seven emirs elects the president)", "Malaysia (nine hereditary rulers elect the King)", "historically the German Empire"],
    strengths: "Combines regional autonomy with monarchical continuity.",
    weaknesses: "Hereditary and elective-monarchy politics complicate federal bargaining.",
    summary: "A federal monarchy is a federation headed by a monarch — the UAE and Malaysia are the modern examples.",
    simple: "A federal monarchy is a country made of states with a king or emir as head, like the UAE.",
  }),
  buildForm({
    id: "pol.form.parliamentary-monarchy",
    name: "Parliamentary monarchy",
    definition: "A constitutional monarchy in which the monarch is entirely ceremonial and government derives exclusively from parliament.",
    howItWorks: "The monarch reigns but does not rule: the elected parliament forms the government, and the monarch's remaining powers are formal (assent, appointment on advice).",
    examples: ["United Kingdom", "Canada", "Australia", "Japan", "Sweden", "Spain"],
    strengths: "A non-partisan head of state with fully democratic government.",
    weaknesses: "The hereditary office is hard to justify on democratic principle.",
    summary: "A parliamentary monarchy is a constitutional monarchy where the monarch is ceremonial and parliament governs — the UK, Canada, Japan and Sweden.",
    simple: "In a parliamentary monarchy, the king or queen is symbolic and the elected parliament runs the country.",
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §15 — iconic revolutions and a peace agreement
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_EVENTS: PoliticalEventRecord[] = [
  buildEvent({
    id: "pol.event.france.revolution",
    name: "French Revolution (1789–1799)",
    countryIds: [FRA],
    dateLabel: "1789 – 1799",
    year: 1789,
    eventType: "revolution",
    description: "The overthrow of the Bourbon absolute monarchy: the storming of the Bastille (14 July 1789), the Declaration of the Rights of Man and of the Citizen, the abolition of feudalism, the Republic (1792), the Terror, and Napoleon's 1799 coup that ended the revolutionary decade.",
    keyFigures: ["Louis XVI", "Maximilien Robespierre", "Georges Danton", "Napoleon Bonaparte"],
    consequences: "The end of the Old Regime, the spread of revolutionary ideas across Europe, the Napoleonic Wars, and the template for modern republicanism.",
    nonViolenceNote: "Presented educationally; the Terror's human costs are documented and not glorified (§15).",
    summary: "The French Revolution (1789–1799) overthrew the monarchy and reshaped the modern political world.",
    simple: "In 1789 the French people rose up against their king, and the revolution changed politics across the world.",
    sources: [SRC_ARCHIVE, SRC_ACADEMIC],
  }),
  buildEvent({
    id: "pol.event.us.revolution",
    name: "American Revolution (1775–1783)",
    countryIds: [USA],
    dateLabel: "19 April 1775 – 3 September 1783",
    year: 1776,
    eventType: "revolution",
    description: "The thirteen colonies' war for independence from Britain: the Declaration of Independence (4 July 1776), the Continental Army under George Washington, French alliance (1778), and the Treaty of Paris (1783).",
    keyFigures: ["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"],
    consequences: "The founding of the United States and its 1787 constitution; a template for anti-colonial revolution.",
    nonViolenceNote: "Presented educationally (§15).",
    summary: "The American Revolution (1775–1783) won the thirteen colonies' independence and founded the United States.",
    simple: "The American Revolution was the war that made the United States independent from Britain.",
    sources: [SRC_ARCHIVE, SRC_ACADEMIC],
  }),
  buildEvent({
    id: "pol.event.russia.revolution",
    name: "Russian Revolution (1917)",
    countryIds: [RUS],
    dateLabel: "February – October 1917",
    year: 1917,
    eventType: "revolution",
    description: "The February Revolution ended the tsardom of Nicholas II; the October Revolution brought the Bolsheviks under Lenin to power; a civil war and the Soviet state followed.",
    keyFigures: ["Vladimir Lenin", "Leon Trotsky", "Nicholas II", "Alexander Kerensky"],
    consequences: "The world's first socialist state, the Soviet Union (1922), and the 20th century's central ideological divide.",
    nonViolenceNote: "Presented educationally; the civil war's human costs are documented and not glorified (§15).",
    summary: "The Russian Revolution of 1917 ended the tsardom and created the Soviet state.",
    simple: "In 1917 the Russian people overthrew the tsar, and a new communist government took power.",
    sources: [SRC_ARCHIVE, SRC_ACADEMIC],
  }),
  buildEvent({
    id: "pol.event.kenya.national-accord",
    name: "Kenya National Accord (2008)",
    countryIds: [KEN],
    dateLabel: "28 February 2008",
    year: 2008,
    eventType: "peace agreement",
    description: "The power-sharing agreement that ended the 2007–08 post-election crisis: brokered by Kofi Annan's Panel of Eminent African Personalities, it created a coalition government (Kibaki as president, Odinga as prime minister) and a reform agenda.",
    keyFigures: ["Mwai Kibaki", "Raila Odinga", "Kofi Annan"],
    consequences: "The coalition government, the reform agenda (the Waki Commission), and the 2010 constitution.",
    summary: "The 2008 National Accord ended Kenya's post-election crisis through power-sharing and produced the 2010 constitution.",
    simple: "In 2008 Kenya's rival leaders agreed to share power, ending the violence after the disputed election.",
    sources: [SRC_ARCHIVE, SRC_ACADEMIC],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §17 — additional diplomacy records
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_DIPLOMACY_2: DiplomacyRecord[] = [
  buildDiplomacy({
    id: "pol.dip.nigeria-south-africa",
    name: "Nigeria–South Africa relations",
    countryIds: [NIG, SA],
    partners: ["Nigeria", "South Africa"],
    relationshipType: "bilateral_relationship",
    signedAt: "Diplomatic relations from South Africa's transition to democracy (1994)",
    keyEvents: "The two continental powers established full relations after apartheid's end (1994). The relationship carries both rivalry and cooperation — leading roles in the AU, the AfCFTA, and joint peacekeeping; the 2023 xenophobic attacks on Nigerian businesses in South Africa produced a documented diplomatic row and compensation talks.",
    currentStatus: "A competitive-but-cooperative 'big two' relationship within the AU. (Current as of the Last Verified date — verify for updates.)",
    sources: [SRC_ACADEMIC, SRC_JOURNALISM],
  }),
  buildDiplomacy({
    id: "pol.dip.us-china",
    name: "United States–China relations",
    countryIds: [USA, CHN],
    partners: ["United States", "China"],
    relationshipType: "dispute",
    signedAt: "Formal relations since the 1972 Shanghai Communiqué; the strategic rivalry intensified from 2018",
    keyEvents: "Relations normalized in 1979; the 2018– trade war, technology export controls (chips), the Taiwan tensions, and the human-rights disputes have defined the rivalry. The Biden–Xi summits (2022 Bali, 2023 Woodside) managed the rivalry; the 2025 tariff escalation continued it.",
    currentStatus: "The defining strategic rivalry of the era — competition with managed dialogue. (Current as of the Last Verified date — verify for updates.)",
    sources: [SRC_ACADEMIC, SRC_JOURNALISM],
  }),
  buildDiplomacy({
    id: "pol.dip.nato-ukraine",
    name: "NATO–Ukraine relations",
    countryIds: [],
    partners: ["NATO", "Ukraine"],
    relationshipType: "negotiation",
    signedAt: "Partnership since 1994 (PfP); deepened after 2014 and especially 2022",
    keyEvents: "Ukraine joined the Partnership for Peace in 1994 and applied for membership in September 2022 after Russia's full-scale invasion. NATO allies coordinate military aid through the Ukraine Defense Contact Group; the 2024 Washington summit declared Ukraine's path 'irreversible'; membership remains under negotiation while the war continues.",
    currentStatus: "An active negotiation and support relationship amid the ongoing war. (Current as of the Last Verified date — verify for updates.)",
    note: "The 2026 summit and the war's course are dynamic information to verify at query time.",
    sources: [SRC_UN, SRC_JOURNALISM],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * §14 — the June 12 movement (Nigeria's pro-democracy struggle)
 * ════════════════════════════════════════════════════════════════════════════ */

export const GLOBAL_MOVEMENTS_2: MovementRecord[] = [
  buildMovement({
    id: "pol.mov.june12",
    name: "June 12 movement (Nigeria's pro-democracy struggle)",
    countryIds: [NIG],
    origin: "The annulment of the 12 June 1993 presidential election by Ibrahim Babangida.",
    leaders: ["MKO Abiola", "Kudirat Abiola", "the NADECO leaders (Abraham Adesanya, Bola Ige, Anthony Enahoro)"],
    goals: "The recognition of the June 12 result and the restoration of democratic government.",
    historicalContext: "The aborted Third Republic; the annulment triggered Nigeria's worst political crisis since the civil war.",
    majorEvents: "The June 1993 election, the 23 June annulment, the June 12 protests, Abacha's 1994 coup, the 1994–98 detention of Abiola, his death in July 1998, and the 1999 transition.",
    governmentResponse: "Repression, detention, and the execution of activists; the annulment's defenders cited national-security justifications (contested).",
    outcome: "The 1999 transition to democracy; June 12 was declared Democracy Day in 2019, and Abiola received a posthumous GCFR.",
    impact: "The defining struggle of Nigerian democracy; its memory still shapes Nigerian politics.",
    summary: "The June 12 movement — the struggle to honour MKO Abiola's annulled 1993 victory — forced Nigeria's return to democracy in 1999.",
    simple: "After the 1993 election was cancelled, Nigerians fought for years to restore democracy, and June 12 is now Democracy Day.",
  }),
];
