<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Admin_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function access($uid,$org){$u=$this->db->where('id',$uid)->get('users')->row_array();if(!$u||!in_array($u['role'],array('ADMIN','SUPER_ADMIN'),TRUE))return NULL;if($u['role']==='ADMIN'&&!$this->in_org($uid,$org))return NULL;return $u;}
 public function in_org($uid,$org){return $this->db->where(array('user_id'=>$uid,'organization_id'=>$org))->count_all_results('memberships')>0;}
 private function scope($org,$super){$this->db->from('users u');if(!$super)$this->db->join('memberships m','m.user_id=u.id')->where('m.organization_id',$org);}
 public function stats($org,$super){$this->scope($org,$super);$total=$this->db->count_all_results();$this->scope($org,$super);$active=$this->db->where(array('u.is_active'=>1,'u.is_suspended'=>0))->count_all_results();$this->scope($org,$super);$suspended=$this->db->where('u.is_suspended',1)->count_all_results();$organizations=$super?$this->db->count_all('organizations'):1;return array('totalUsers'=>$total,'activeUsers'=>$active,'suspendedUsers'=>$suspended,'organizations'=>$organizations);}
 public function users($org,$super,$filters,$limit,$offset){$this->scope($org,$super);if($filters['role'])$this->db->where('u.role',strtoupper($filters['role']));if($filters['status']==='active')$this->db->where(array('u.is_active'=>1,'u.is_suspended'=>0));if($filters['status']==='suspended')$this->db->where('u.is_suspended',1);if($filters['status']==='inactive')$this->db->where('u.is_active',0);if($filters['q'])$this->db->group_start()->like('u.email',$filters['q'])->or_like('u.display_name',$filters['q'])->group_end();$total=$this->db->count_all_results('',FALSE);$rows=$this->db->select('u.*')->order_by('u.created_at','DESC')->limit($limit,$offset)->get()->result_array();return array($rows,$total);}
 public function target($id,$org,$super){if(!$super&&!$this->in_org($id,$org))return NULL;return $this->db->where('id',$id)->get('users')->row_array();}
 public function update($id,$set){$set['updated_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('users',$set);return $this->db->where('id',$id)->get('users')->row_array();}
 public function activity($org,$super,$limit,$offset){if(!$super)$this->db->where('organization_id',$org);$this->db->like('event_type','admin.','after');$total=$this->db->count_all_results('audit_events',FALSE);$rows=$this->db->order_by('created_at','DESC')->limit($limit,$offset)->get()->result_array();return array($rows,$total);}
 public function audit($org,$actor,$type,$target,$meta=array()){$meta['resourceId']=$target;$this->db->insert('audit_events',array('organization_id'=>$org,'user_id'=>$actor,'event_type'=>$type,'payload'=>json_encode($meta),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}
}
