<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Agent_extension_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 private function agent($id,$org){return $this->db->where(array('id'=>$id,'organization_id'=>$org))->get('agents')->row_array();}
 public function lifecycle($id,$org){$a=$this->agent($id,$org);if(!$a)return NULL;$r=$this->db->where('agent_id',$id)->get('agent_lifecycle')->row_array();if(!$r){$map=array('PAUSED'=>'TRAINING','OFFLINE'=>'RETIRED');$r=array('state'=>$map[$a['status']]??'ACTIVE','since_at'=>$a['created_at'],'metadata'=>'{}');}$h=$this->db->where('agent_id',$id)->order_by('created_at','DESC')->limit(100)->get('agent_lifecycle_history')->result_array();return array('current'=>array('state'=>$r['state'],'since'=>$r['since_at'],'metadata'=>json_decode($r['metadata'],TRUE)?:array()),'history'=>array_map(function($x){return array('from'=>$x['from_state'],'to'=>$x['to_state'],'reason'=>$x['reason'],'userId'=>$x['user_id'],'timestamp'=>$x['created_at'],'metadata'=>json_decode($x['metadata'],TRUE)?:array());},$h));}
 public function transition($id,$org,$uid,$to,$reason,$meta){$state=$this->lifecycle($id,$org);if(!$state)return array(NULL,'missing');$from=$state['current']['state'];$valid=array('ONBOARDING'=>array('ACTIVE'),'ACTIVE'=>array('TRAINING','RETIRED'),'TRAINING'=>array('ACTIVE','RETIRED'),'RETIRED'=>array('ARCHIVED','ACTIVE'),'ARCHIVED'=>array());if(!in_array($to,$valid[$from]??array(),TRUE))return array(NULL,'transition');$now=date('Y-m-d H:i:s');$this->db->replace('agent_lifecycle',array('agent_id'=>$id,'state'=>$to,'since_at'=>$now,'metadata'=>json_encode($meta)));$this->db->insert('agent_lifecycle_history',array('agent_id'=>$id,'from_state'=>$from,'to_state'=>$to,'reason'=>$reason,'user_id'=>$uid,'metadata'=>json_encode($meta),'created_at'=>$now));$status=array('ONBOARDING'=>'IDLE','ACTIVE'=>'ONLINE','TRAINING'=>'PAUSED','RETIRED'=>'OFFLINE','ARCHIVED'=>'OFFLINE')[$to];$this->db->where('id',$id)->update('agents',array('status'=>$status,'last_activity_at'=>$now,'updated_at'=>$now));$this->db->insert('agent_events',array('id'=>$this->uuid(),'agent_id'=>$id,'type'=>'STATUS_CHANGED','message'=>'Lifecycle transition: '.$from.' → '.$to.'. Reason: '.$reason,'metadata'=>json_encode(array_merge($meta,array('lifecycleFrom'=>$from,'lifecycleTo'=>$to,'userId'=>$uid))),'created_at'=>$now));return array(array('from'=>$from,'to'=>$to,'timestamp'=>$now),NULL);}
 public function skills($aid,$org,$page,$per,$enabled=NULL){if(!$this->agent($aid,$org))return NULL;$this->db->from('agent_skills')->where('agent_id',$aid);if($enabled!==NULL)$this->db->where('enabled',$enabled);$total=$this->db->count_all_results();$this->db->where('agent_id',$aid);if($enabled!==NULL)$this->db->where('enabled',$enabled);$rows=$this->db->order_by('name')->limit($per,($page-1)*$per)->get('agent_skills')->result_array();return array('items'=>array_map(array($this,'skill_view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 public function skill($aid,$sid,$org){if(!$this->agent($aid,$org))return NULL;$r=$this->db->where(array('id'=>$sid,'agent_id'=>$aid))->get('agent_skills')->row_array();return $r?$this->skill_view($r):NULL;}
 public function save_skill($aid,$sid,$org,$d){if(!$this->agent($aid,$org))return array(NULL,'missing');$now=date('Y-m-d H:i:s');if(!$sid){if($this->db->where(array('agent_id'=>$aid,'name'=>$d['name']))->count_all_results('agent_skills'))return array(NULL,'duplicate');$sid=$this->uuid();$r=array('id'=>$sid,'agent_id'=>$aid,'name'=>$d['name'],'description'=>$d['description']??NULL,'tool_name'=>$d['toolName'],'config'=>json_encode($d['config']??array()),'enabled'=>isset($d['enabled'])?(int)$d['enabled']:1,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('agent_skills',$r);}else{$r=$this->db->where(array('id'=>$sid,'agent_id'=>$aid))->get('agent_skills')->row_array();if(!$r)return array(NULL,'missing');$map=array('name'=>'name','description'=>'description','toolName'=>'tool_name','enabled'=>'enabled');$set=array('updated_at'=>$now);foreach($map as $i=>$o)if(array_key_exists($i,$d))$set[$o]=$d[$i];if(array_key_exists('config',$d))$set['config']=json_encode($d['config']);$this->db->where('id',$sid)->update('agent_skills',$set);}return array($this->skill($aid,$sid,$org),NULL);}
 public function delete_skill($aid,$sid,$org){if(!$this->agent($aid,$org))return FALSE;$this->db->where(array('id'=>$sid,'agent_id'=>$aid))->delete('agent_skills');return $this->db->affected_rows()>0;}
 public function memories($aid,$org,$page,$per,$type,$q){if(!$this->agent($aid,$org))return NULL;return $this->resource_list('agent_memories',$aid,$page,$per,$type,$q,array('content'),TRUE);}
 public function add_memory($aid,$org,$d){if(!$this->agent($aid,$org))return NULL;$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'agent_id'=>$aid,'type'=>$d['type']??'FACT','content'=>trim($d['content']),'source'=>$d['source']??NULL,'source_ref'=>$d['sourceRef']??NULL,'importance'=>$d['importance']??0.5,'tags'=>json_encode($d['tags']??array()),'metadata'=>'{}','created_at'=>$now,'updated_at'=>$now);$this->db->insert('agent_memories',$r);$this->agent_event($aid,'MEMORY_STORED','stored memory: "'.substr($r['content'],0,80).'"',array('memoryId'=>$r['id'],'type'=>$r['type']));return $this->memory_view($r);}
 public function delete_memory($aid,$id,$org){if(!$this->agent($aid,$org))return FALSE;$this->db->where(array('id'=>$id,'agent_id'=>$aid))->delete('agent_memories');return $this->db->affected_rows()>0;}
 public function knowledge($aid,$org,$page,$per,$type,$q){if(!$this->agent($aid,$org))return NULL;return $this->resource_list('agent_knowledge',$aid,$page,$per,$type,$q,array('title','content'),FALSE);}
 public function add_knowledge($aid,$org,$d){if(!$this->agent($aid,$org))return NULL;$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'agent_id'=>$aid,'type'=>$d['type']??'SNIPPET','title'=>trim($d['title']),'content'=>$d['content'],'source'=>$d['source']??NULL,'mime_type'=>$d['mimeType']??NULL,'tokens'=>(int)ceil(strlen($d['content'])/4),'metadata'=>'{}','created_at'=>$now,'updated_at'=>$now);$this->db->insert('agent_knowledge',$r);$this->agent_event($aid,'KNOWLEDGE_ADDED','added knowledge: "'.$r['title'].'"',array('knowledgeId'=>$r['id'],'type'=>$r['type'],'tokens'=>$r['tokens']));return $this->knowledge_view($r);}
 public function delete_knowledge($aid,$id,$org){if(!$this->agent($aid,$org))return FALSE;$this->db->where(array('id'=>$id,'agent_id'=>$aid))->delete('agent_knowledge');return $this->db->affected_rows()>0;}
 private function resource_list($table,$aid,$page,$per,$type,$q,$fields,$memory){$this->db->from($table)->where('agent_id',$aid);if($type)$this->db->where('type',strtoupper($type));if($q){$this->db->group_start();foreach($fields as $i=>$f)$i?$this->db->or_like($f,$q):$this->db->like($f,$q);$this->db->group_end();}$total=$this->db->count_all_results();$this->db->where('agent_id',$aid);if($type)$this->db->where('type',strtoupper($type));if($q){$this->db->group_start();foreach($fields as $i=>$f)$i?$this->db->or_like($f,$q):$this->db->like($f,$q);$this->db->group_end();}if($memory)$this->db->order_by('importance','DESC');$rows=$this->db->order_by('created_at','DESC')->limit($per,($page-1)*$per)->get($table)->result_array();return array('items'=>array_map(array($this,$memory?'memory_view':'knowledge_view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 private function memory_view($r){return array('id'=>$r['id'],'type'=>strtolower($r['type']),'content'=>$r['content'],'source'=>$r['source'],'sourceRef'=>$r['source_ref'],'importance'=>(float)$r['importance'],'tags'=>json_decode($r['tags'],TRUE)?:array(),'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}
 private function knowledge_view($r){return array('id'=>$r['id'],'type'=>strtolower($r['type']),'title'=>$r['title'],'contentPreview'=>mb_substr($r['content'],0,200),'source'=>$r['source'],'mimeType'=>$r['mime_type'],'tokens'=>(int)$r['tokens'],'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}
 private function agent_event($aid,$type,$message,$meta){$this->db->insert('agent_events',array('id'=>$this->uuid(),'agent_id'=>$aid,'type'=>$type,'message'=>$message,'metadata'=>json_encode($meta),'created_at'=>date('Y-m-d H:i:s')));}
 private function skill_view($r){return array('id'=>$r['id'],'agentId'=>$r['agent_id'],'name'=>$r['name'],'description'=>$r['description'],'toolName'=>$r['tool_name'],'config'=>json_decode($r['config'],TRUE)?:array(),'enabled'=>(bool)$r['enabled'],'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
