<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Agent_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function listing($org,$q,$status,$page,$per){$this->db->from('agents')->where('organization_id',$org);if($status)$this->db->where('status',strtoupper($status));if($q)$this->db->group_start()->like('name',$q)->or_like('role',$q)->or_like('description',$q)->group_end();$total=$this->db->count_all_results();$this->db->where('organization_id',$org);if($status)$this->db->where('status',strtoupper($status));if($q)$this->db->group_start()->like('name',$q)->or_like('role',$q)->or_like('description',$q)->group_end();$rows=$this->db->order_by('is_built_in','DESC')->order_by('created_at')->limit($per,($page-1)*$per)->get('agents')->result_array();return array('items'=>array_map(array($this,'view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 public function one($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('agents')->row_array();return $r?$this->view($r,TRUE):NULL;}
 public function create($org,$d){$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'organization_id'=>$org,'name'=>$d['name'],'role'=>$d['role'],'color'=>$d['color']??'azure','emoji'=>$d['emoji']??'🤖','description'=>$d['description']??NULL,'system_prompt'=>$d['systemPrompt']??NULL,'department'=>$d['department']??NULL,'capabilities'=>json_encode($d['capabilities']??array()),'cloud_android_requirements'=>json_encode($d['cloudAndroidRequirements']??array()),'model_id'=>$d['modelId']??NULL,'temperature'=>$d['temperature']??0.7,'max_tokens'=>$d['maxTokens']??2048,'is_built_in'=>0,'avatar_style'=>$d['avatarStyle']??NULL,'status'=>'IDLE','last_activity_at'=>$now,'active_task_id'=>NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('agents',$r);$this->event($r['id'],'created','Agent created');return $this->view($r,TRUE);}
 public function update_agent($id,$org,$d){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('agents')->row_array();if(!$r)return NULL;$map=array('name'=>'name','role'=>'role','color'=>'color','emoji'=>'emoji','description'=>'description','systemPrompt'=>'system_prompt','department'=>'department','modelId'=>'model_id','temperature'=>'temperature','maxTokens'=>'max_tokens','avatarStyle'=>'avatar_style');$set=array();foreach($map as $i=>$o)if(array_key_exists($i,$d))$set[$o]=$d[$i];foreach(array('capabilities'=>'capabilities','cloudAndroidRequirements'=>'cloud_android_requirements') as $i=>$o)if(array_key_exists($i,$d))$set[$o]=json_encode($d[$i]);$set['updated_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('agents',$set);$this->event($id,'updated','Agent updated',array('fields'=>array_keys($d)));return $this->one($id,$org);}
 public function remove($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('agents')->row_array();if(!$r)return 'missing';if($r['is_built_in'])return 'built_in';$this->db->where('id',$id)->delete('agents');return NULL;}
 public function events($id,$org,$page,$per){if(!$this->one($id,$org))return NULL;$total=$this->db->where('agent_id',$id)->count_all_results('agent_events');$rows=$this->db->where('agent_id',$id)->order_by('created_at','DESC')->limit($per,($page-1)*$per)->get('agent_events')->result_array();$items=array_map(function($e){return array('id'=>$e['id'],'type'=>strtolower($e['type']),'message'=>$e['message'],'metadata'=>json_decode($e['metadata'],TRUE)?:array(),'createdAt'=>$e['created_at']);},$rows);return array('items'=>$items,'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 private function event($id,$type,$msg,$meta=array()){$this->db->insert('agent_events',array('id'=>$this->uuid(),'agent_id'=>$id,'type'=>$type,'message'=>$msg,'metadata'=>json_encode($meta),'created_at'=>date('Y-m-d H:i:s')));}
 public function view($r,$stats=FALSE){$out=array('id'=>$r['id'],'name'=>$r['name'],'role'=>$r['role'],'color'=>$r['color'],'emoji'=>$r['emoji'],'description'=>$r['description'],'systemPrompt'=>$r['system_prompt'],'department'=>$r['department'],'capabilities'=>json_decode($r['capabilities'],TRUE)?:array(),'cloudAndroidRequirements'=>json_decode($r['cloud_android_requirements'],TRUE)?:array(),'modelId'=>$r['model_id'],'temperature'=>(float)$r['temperature'],'maxTokens'=>(int)$r['max_tokens'],'avatarStyle'=>$r['avatar_style'],'isBuiltIn'=>(bool)$r['is_built_in'],'status'=>strtolower($r['status']),'lastActivityAt'=>$r['last_activity_at'],'activeTaskId'=>$r['active_task_id'],'activeTask'=>NULL,'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);if($stats)$out['stats']=array('tasks'=>0,'messages'=>$this->db->where('agent_id',$r['id'])->count_all_results('messages'),'memories'=>0,'knowledge'=>0,'events'=>$this->db->where('agent_id',$r['id'])->count_all_results('agent_events'));return $out;}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
