<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Ai_monitoring_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function metrics($org,$days){$since=gmdate('Y-m-d 00:00:00',strtotime('-'.($days-1).' days'));$base=array('organization_id'=>$org,'created_at >='=>$since);$total=$this->db->where($base)->count_all_results('ai_requests');$succeeded=$this->db->where($base)->where('status','succeeded')->count_all_results('ai_requests');$failed=$this->db->where($base)->where('status','failed')->count_all_results('ai_requests');$sum=$this->db->select('COALESCE(AVG(duration_ms),0) avg_latency,COALESCE(SUM(prompt_tokens),0) prompt_tokens,COALESCE(SUM(completion_tokens),0) completion_tokens',FALSE)->where($base)->get('ai_requests')->row_array();$byModel=$this->db->select('model_id,COUNT(*) count,ROUND(AVG(duration_ms)) avg_duration,SUM(prompt_tokens) prompt_tokens,SUM(completion_tokens) completion_tokens',FALSE)->where($base)->group_by('model_id')->order_by('count','DESC')->get('ai_requests')->result_array();$byChannel=$this->db->select('channel,COUNT(*) count',FALSE)->where($base)->group_by('channel')->order_by('count','DESC')->get('ai_requests')->result_array();$recent=$this->db->where('organization_id',$org)->order_by('created_at','DESC')->limit(20)->get('ai_requests')->result_array();$costRows=$this->db->select('r.prompt_tokens,r.completion_tokens,m.cost_input_per_1k,m.cost_output_per_1k')->from('ai_requests r')->join('model_registry m','m.id=r.model_registry_id','left')->where('r.organization_id',$org)->where('r.created_at >=',$since)->get()->result_array();$cost=0;foreach($costRows as $r)$cost+=(($r['prompt_tokens']/1000)*(float)$r['cost_input_per_1k'])+(($r['completion_tokens']/1000)*(float)$r['cost_output_per_1k']);return array('periodDays'=>$days,'since'=>gmdate('c',strtotime($since)),'totals'=>array('requests'=>$total,'succeeded'=>$succeeded,'failed'=>$failed,'avgLatency'=>(int)round($sum['avg_latency']),'totalCost'=>$cost,'totalPromptTokens'=>(int)$sum['prompt_tokens'],'totalCompletionTokens'=>(int)$sum['completion_tokens'],'successRate'=>$total?round($succeeded/$total*100,1):0),'byModel'=>array_map(array($this,'model_group'),$byModel),'byChannel'=>array_map(function($r){return array('channel'=>$r['channel'],'count'=>(int)$r['count']);},$byChannel),'recent'=>array_map(array($this,'request_view'),$recent));}
 public function record($r){$id=$this->uuid();$model=$this->db->group_start()->where('organization_id',$r['organization_id'])->or_where('organization_id IS NULL',NULL,FALSE)->group_end()->where(array('provider'=>$r['provider'],'model_id'=>$r['model_id']))->order_by('organization_id','DESC')->get('model_registry')->row_array();$r['id']=$id;$r['model_registry_id']=$model['id']??NULL;$r['created_at']=date('Y-m-d H:i:s');$this->db->insert('ai_requests',$r);return $id;}
 public function model_group($r){return array('modelId'=>$r['model_id'],'count'=>(int)$r['count'],'avgDurationMs'=>(int)$r['avg_duration'],'promptTokens'=>(int)$r['prompt_tokens'],'completionTokens'=>(int)$r['completion_tokens']);}
 public function request_view($r){return array('id'=>$r['id'],'channel'=>$r['channel'],'provider'=>$r['provider'],'modelId'=>$r['model_id'],'durationMs'=>(int)$r['duration_ms'],'promptTokens'=>(int)$r['prompt_tokens'],'completionTokens'=>(int)$r['completion_tokens'],'status'=>$r['status'],'error'=>$r['error'],'feature'=>$r['feature'],'createdAt'=>$r['created_at']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
