<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Api_key_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function all($org,$revoked=FALSE){$this->db->where('organization_id',$org);if(!$revoked)$this->db->where('revoked_at IS NULL',NULL,FALSE);$rows=$this->db->order_by('created_at','DESC')->get('api_keys')->result_array();return array_map(array($this,'view'),$rows);}
 public function get($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('api_keys')->row_array();return $r?$this->view($r):NULL;}
 public function raw($id,$org){return $this->db->where(array('id'=>$id,'organization_id'=>$org))->get('api_keys')->row_array();}
 public function create($org,$uid,$d){$token='wnd_'.bin2hex(random_bytes(32));$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'organization_id'=>$org,'created_by_id'=>$uid,'name'=>$d['name'],'key_prefix'=>substr($token,0,12),'key_hash'=>hash('sha256',$token),'scopes'=>json_encode($d['scopes']),'granular_scopes'=>json_encode($d['granularScopes']),'app_id'=>$d['appId'],'environment'=>$d['environment'],'ip_restrictions'=>json_encode($d['ipRestrictions']),'expires_at'=>$d['expiresInDays']?date('Y-m-d H:i:s',time()+$d['expiresInDays']*86400):NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('api_keys',$r);return array('id'=>$r['id'],'name'=>$r['name'],'key'=>$token,'keyPrefix'=>$r['key_prefix'],'scopes'=>$d['scopes'],'granularScopes'=>$d['granularScopes'],'environment'=>$d['environment'],'expiresAt'=>$r['expires_at'],'createdAt'=>$now);}
 public function update_key($id,$org,$d){$r=$this->raw($id,$org);if(!$r)return NULL;if($r['revoked_at'])return FALSE;$set=array('updated_at'=>date('Y-m-d H:i:s'));$map=array('name'=>'name','environment'=>'environment','appId'=>'app_id');foreach($map as $in=>$out)if(array_key_exists($in,$d))$set[$out]=$d[$in];foreach(array('scopes'=>'scopes','granularScopes'=>'granular_scopes','ipRestrictions'=>'ip_restrictions') as $in=>$out)if(array_key_exists($in,$d))$set[$out]=json_encode($d[$in]);if(!empty($d['revoked']))$set['revoked_at']=date('Y-m-d H:i:s');if(isset($d['expiresInDays']))$set['expires_at']=date('Y-m-d H:i:s',time()+$d['expiresInDays']*86400);$this->db->where('id',$id)->update('api_keys',$set);return $this->mutation(array_merge($r,$set));}
 public function rotate($id,$org,$uid,$days=NULL){$r=$this->raw($id,$org);if(!$r||$r['revoked_at'])return NULL;$this->db->trans_start();$this->db->where('id',$id)->update('api_keys',array('revoked_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')));$d=array('name'=>$r['name'].' (rotated)','scopes'=>json_decode($r['scopes'],TRUE),'granularScopes'=>json_decode($r['granular_scopes'],TRUE),'appId'=>$r['app_id'],'environment'=>$r['environment'],'ipRestrictions'=>json_decode($r['ip_restrictions'],TRUE),'expiresInDays'=>$days);$created=$this->create($org,$uid,$d);$this->db->trans_complete();return $this->db->trans_status()?$created:NULL;}
 public function delete_key($id,$org){if(!$this->raw($id,$org))return FALSE;$this->db->where(array('id'=>$id,'organization_id'=>$org))->delete('api_keys');return TRUE;}
 public function usage($org,$days){$since=date('Y-m-d 00:00:00',time()-($days-1)*86400);$today=date('Y-m-d 00:00:00');$rows=$this->db->select('k.id,k.name,k.key_prefix,k.revoked_at,k.last_used_at,COUNT(u.id) calls,SUM(u.created_at >= '.$this->db->escape($since).') calls_window,SUM(u.created_at >= '.$this->db->escape($today).') calls_today',FALSE)->from('api_keys k')->join('api_usage_records u','u.api_key_id=k.id','left')->where('k.organization_id',$org)->group_by('k.id')->get()->result_array();$per=array();$total=$window=$todayCalls=0;foreach($rows as $r){$total+=(int)$r['calls'];$window+=(int)$r['calls_window'];$todayCalls+=(int)$r['calls_today'];$per[]=array('keyId'=>$r['id'],'name'=>$r['name'],'keyPrefix'=>$r['key_prefix'],'revoked'=>$r['revoked_at']!==NULL,'calls'=>(int)$r['calls'],'callsInWindow'=>(int)$r['calls_window'],'callsToday'=>(int)$r['calls_today'],'lastUsedAt'=>$r['last_used_at']);}$recent=$this->db->select('api_key_id keyId,method,path,status,created_at at')->where('organization_id',$org)->order_by('created_at','DESC')->limit(50)->get('api_usage_records')->result_array();$start=$this->db->select_min('created_at','start')->where('organization_id',$org)->get('api_usage_records')->row_array()['start'];return array('windowDays'=>$days,'generatedAt'=>gmdate('c'),'ledgerAvailable'=>TRUE,'ledgerStart'=>$start,'totalCalls'=>$total,'callsInWindow'=>$window,'callsToday'=>$todayCalls,'distinctUseDays'=>(int)$this->distinct_days($org,$since),'ledgerCoveredDays'=>$start?min($days,max(1,(int)ceil((time()-strtotime($start))/86400))):0,'avgCallsPerDay'=>$start?floor(($window/max(1,min($days,ceil((time()-strtotime($start))/86400))))*100)/100:NULL,'perKey'=>$per,'recentCalls'=>$recent,'note'=>'Counts come from the durable organization-scoped MySQL API call ledger.');}
 private function distinct_days($org,$since){return $this->db->select('COUNT(DISTINCT DATE(created_at)) n',FALSE)->where('organization_id',$org)->where('created_at >=',$since)->get('api_usage_records')->row_array()['n'];}
 public function view($r){$u=$this->db->select('COUNT(*) requests,COALESCE(SUM(tokens_in),0) tokensIn,COALESCE(SUM(tokens_out),0) tokensOut,COALESCE(SUM(ai_cost_micros),0) costMicros,SUM(status >= 400) errors',FALSE)->where('api_key_id',$r['id'])->get('api_usage_records')->row_array();$creator=$this->db->select('id,display_name')->where('id',$r['created_by_id'])->get('users')->row_array();return array('id'=>$r['id'],'name'=>$r['name'],'keyPrefix'=>$r['key_prefix'],'scopes'=>json_decode($r['scopes'],TRUE)?:array(),'granularScopes'=>json_decode($r['granular_scopes'],TRUE)?:array(),'appId'=>$r['app_id'],'environment'=>$r['environment'],'ipRestrictions'=>json_decode($r['ip_restrictions'],TRUE)?:array(),'lastUsedAt'=>$r['last_used_at'],'expiresAt'=>$r['expires_at'],'revoked'=>$r['revoked_at']!==NULL,'revokedAt'=>$r['revoked_at'],'createdBy'=>array('id'=>$creator['id'],'displayName'=>$creator['display_name']?:''),'usage'=>array_map('intval',$u),'createdAt'=>$r['created_at']);}
 private function mutation($r){return array('id'=>$r['id'],'name'=>$r['name'],'scopes'=>json_decode($r['scopes'],TRUE),'granularScopes'=>json_decode($r['granular_scopes'],TRUE),'environment'=>$r['environment'],'revoked'=>$r['revoked_at']!==NULL,'revokedAt'=>$r['revoked_at'],'expiresAt'=>$r['expires_at']);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
