<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Api_governance_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function versions(){return $this->db->select('version,introduced_at introducedAt,sunset_at sunsetAt,status')->order_by('introduced_at')->get('api_versions')->result_array();}
 public function endpoints(){ $route=array();include APPPATH.'config/routes.php';$out=array();$seen=array();foreach($route as $path=>$target){if(!is_string($path)||strpos($path,'api/v1/')!==0||strpos($path,'(:any)')===0||strpos($target,'api/dispatch')===0)continue;$normalized='/'.preg_replace_callback('/\(:(any|num)\)/',function()use(&$seen){return '{param'.(count($seen)+1).'}';},$path);$methods=$this->methods($path,$target);foreach($methods as $method){$key=$method.' '.$normalized;if(isset($seen[$key]))continue;$seen[$key]=TRUE;$out[]=array('method'=>$method,'path'=>$normalized,'serviceId'=>'windels-php-api','version'=>'v1','deprecated'=>FALSE,'authRequired'=>!$this->public_route($path),'summary'=>$this->summary($method,$normalized));}}usort($out,function($a,$b){return strcmp($a['path'].$a['method'],$b['path'].$b['method']);});return $out;}
 private function methods($path,$target){if(strpos($target,'/index')!==FALSE||preg_match('#/(dashboard|stats|recent|timeline|catalog|query|resolve|validate_graph|ai_monitoring|activity|public_index)$#',$target))$m=array('GET');else $m=array('POST');if(preg_match('#(account/(username|email|profile)|enterprise/organization|settings/index|enterprise/model/|enterprise/integration/|governance/adr/)#',$target))$m[]='PATCH';if(preg_match('#(enterprise/model/|enterprise/integration/|enterprise/plugin/|discovery/service/)#',$target))$m[]='DELETE';if(preg_match('#(models|plugins|integrations|schemas|adrs|standards|reviews|tasks)$#',$path))$m=array_unique(array_merge($m,array('POST')));return array_values(array_unique($m));}
 private function public_route($path){return in_array($path,array('api/v1/health','api/v1/health/deep','api/v1/auth/register','api/v1/auth/login','api/v1/auth/refresh','api/v1/settings/public'),TRUE);}
 private function summary($method,$path){return ucfirst(strtolower($method)).' '.str_replace(array('/api/v1/','-'),array('',' '),$path);}
}
