<?php defined('BASEPATH') OR exit('No direct script access allowed');
class App_builder_model extends CI_Model{
 function __construct(){parent::__construct();$this->load->database();}
 function list_rows($table,$org,$filters=array()){$this->db->where('organization_id',$org);foreach($filters as $k=>$v)if($v!==NULL)$this->db->where($k,$v);return array_map(function($r)use($table){return $this->view($table,$r);},$this->db->order_by('created_at','DESC')->get('app_builder_'.$table)->result_array());}
 function one($table,$org,$id){$r=$this->db->where(array('organization_id'=>$org,'id'=>$id))->get('app_builder_'.$table)->row_array();return $r?$this->view($table,$r):NULL;}
 function project_save($org,$id,$uid,$d){$now=date('Y-m-d H:i:s');$map=array('name'=>'name','description'=>'description','targetType'=>'target_type','techStack'=>'tech_stack','systemPrompt'=>'system_prompt');$s=array();foreach($map as $i=>$o)if(array_key_exists($i,$d))$s[$o]=$i==='techStack'?json_encode($d[$i]):$d[$i];if(!$id){$id=$this->uuid();$s+=array('id'=>$id,'organization_id'=>$org,'target_type'=>'WEB','tech_stack'=>'{}','created_by_id'=>$uid,'created_at'=>$now);}$s['updated_at']=$now;if(isset($s['created_at']))$this->db->insert('app_builder_projects',$s);else{$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('app_builder_projects',$s);if(!$this->db->affected_rows()&&!$this->one('projects',$org,$id))return NULL;}return $this->one('projects',$org,$id);}
 function remove_project($org,$id){$this->db->where(array('organization_id'=>$org,'id'=>$id))->delete('app_builder_projects');return $this->db->affected_rows()>0;}
 function task_save($org,$project,$id,$d){if(!$id&&!$this->one('projects',$org,$project))return NULL;$now=date('Y-m-d H:i:s');$map=array('assignedAgent'=>'assigned_agent','title'=>'title','description'=>'description','isCompleted'=>'is_completed','outputCode'=>'output_code');$s=array();foreach($map as $i=>$o)if(array_key_exists($i,$d))$s[$o]=$d[$i];if(isset($d['assignedAgent']))$s['agent_group']=$this->agent_group($d['assignedAgent']);if(array_key_exists('isCompleted',$d))$s['completed_at']=$d['isCompleted']?$now:NULL;if(array_key_exists('outputCode',$d))$s['generation_source']='manual';if(!$id){$id=$this->uuid();$s+=array('id'=>$id,'organization_id'=>$org,'project_id'=>$project,'is_completed'=>0,'generation_source'=>'manual','created_at'=>$now);$this->db->insert('app_builder_tasks',$s);}else{$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('app_builder_tasks',$s);if(!$this->db->affected_rows()&&!$this->one('tasks',$org,$id))return NULL;}return $this->one('tasks',$org,$id);}
 function generate($org,$id,$code,$source){$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('app_builder_tasks',array('output_code'=>$code,'generation_source'=>$source));return $this->one('tasks',$org,$id);}
 function remove($table,$org,$id){$this->db->where(array('organization_id'=>$org,'id'=>$id))->delete('app_builder_'.$table);return $this->db->affected_rows()>0;}
 function create_run($org,$project,$uid,$version){$p=$this->one('projects',$org,$project);if(!$p)return array(NULL,NULL);if($this->db->where(array('organization_id'=>$org,'project_id'=>$project,'version'=>$version))->count_all_results('app_builder_runs'))return array(NULL,'VERSION_EXISTS');$now=date('Y-m-d H:i:s');$id=$this->uuid();$logs=array(array('at'=>date('c'),'step'=>'QUEUED','actor'=>$uid?:'system','detail'=>'Build '.$version.' queued for '.$p['name']));$this->db->insert('app_builder_runs',array('id'=>$id,'organization_id'=>$org,'project_id'=>$project,'version'=>$version,'status'=>'QUEUED','logs'=>json_encode($logs),'error_log'=>'[]','artifact_id'=>NULL,'requested_by'=>$uid,'started_at'=>$now,'finalized_at'=>NULL,'created_at'=>$now));return array($this->one('runs',$org,$id),NULL);}
 function advance($org,$id,$actor){$r=$this->db->where(array('organization_id'=>$org,'id'=>$id))->get('app_builder_runs')->row_array();if(!$r)return NULL;if(in_array($r['status'],array('SUCCEEDED','FAILED'),TRUE))return $this->view('runs',$r);$states=array('QUEUED','GENERATING_CODE','TESTING','COMPILING','SIGNING','SUCCEEDED');$next=$states[array_search($r['status'],$states,TRUE)+1];$now=date('Y-m-d H:i:s');$logs=json_decode($r['logs'],TRUE)?:array();$logs[]=array('at'=>date('c'),'step'=>$next,'actor'=>$actor?:'system','detail'=>'Advanced from '.$r['status']);$set=array('status'=>$next,'logs'=>json_encode($logs));if($next==='SUCCEEDED')$set['finalized_at']=$now;$this->db->where('id',$id)->update('app_builder_runs',$set);if($next==='SUCCEEDED'){$p=$this->db->where('id',$r['project_id'])->get('app_builder_projects')->row_array();$manifest=json_encode(array('schema'=>'windels.ai/app-builder/artifact/v1','project'=>array('id'=>$p['id'],'name'=>$p['name'],'targetType'=>$p['target_type']),'run'=>array('id'=>$id,'version'=>$r['version'],'status'=>'SUCCEEDED'),'techStack'=>json_decode($p['tech_stack'],TRUE),'logs'=>$logs,'generatedAt'=>date('c')),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);$aid=$this->uuid();$this->db->insert('app_builder_artifacts',array('id'=>$aid,'organization_id'=>$org,'project_id'=>$p['id'],'run_id'=>$id,'version'=>$r['version'],'name'=>$p['name'].'-'.$r['version'],'target_type'=>$p['target_type'],'manifest_json'=>$manifest,'sbom'=>json_encode($this->sbom(json_decode($p['tech_stack'],TRUE)?:array())),'sha256'=>hash('sha256',$manifest),'size_bytes'=>strlen($manifest),'published'=>0,'released_at'=>NULL,'created_by_id'=>$actor,'created_at'=>$now));$this->db->where('id',$id)->update('app_builder_runs',array('artifact_id'=>$aid));}return $this->one('runs',$org,$id);}
 function retry($org,$id,$actor){$r=$this->one('runs',$org,$id);if(!$r)return array(NULL,NULL);if($r['status']!=='FAILED')return array(NULL,'NOT_FAILED');$now=date('Y-m-d H:i:s');$nid=$this->uuid();$this->db->insert('app_builder_runs',array('id'=>$nid,'organization_id'=>$org,'project_id'=>$r['projectId'],'version'=>$r['version'],'status'=>'QUEUED','logs'=>json_encode(array(array('at'=>date('c'),'step'=>'QUEUED','actor'=>$actor?:'system','detail'=>'Retry of '.$id))),'error_log'=>'[]','artifact_id'=>NULL,'requested_by'=>$actor,'started_at'=>$now,'finalized_at'=>NULL,'created_at'=>$now));return array($this->one('runs',$org,$nid),NULL);}
 function request_release($org,$artifact,$uid){$a=$this->one('artifacts',$org,$artifact);if(!$a)return array(NULL,NULL);if($this->db->where(array('organization_id'=>$org,'artifact_id'=>$artifact,'status'=>'pending'))->count_all_results('app_builder_approvals'))return array(NULL,'APPROVAL_PENDING');$id=$this->uuid();$this->db->insert('app_builder_approvals',array('id'=>$id,'organization_id'=>$org,'artifact_id'=>$artifact,'project_id'=>$a['projectId'],'run_id'=>$a['runId'],'status'=>'pending','requested_by'=>$uid,'decided_by'=>NULL,'decided_at'=>NULL,'note'=>NULL,'created_at'=>date('Y-m-d H:i:s')));return array($this->one('approvals',$org,$id),NULL);}
 function decide($org,$id,$d){$a=$this->one('approvals',$org,$id);if(!$a)return array(NULL,NULL);if($a['status']!=='pending')return array(NULL,'ALREADY_DECIDED');$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('app_builder_approvals',array('status'=>$d['approved']?'approved':'denied','decided_by'=>$d['decidedBy'],'decided_at'=>date('Y-m-d H:i:s'),'note'=>$d['note']??NULL));return array($this->one('approvals',$org,$id),NULL);}
 function release($org,$id){$a=$this->one('artifacts',$org,$id);if(!$a)return array(NULL,NULL);if($a['published'])return array($a,NULL);if(!$this->db->where(array('organization_id'=>$org,'artifact_id'=>$id,'status'=>'approved'))->count_all_results('app_builder_approvals'))return array(NULL,'RELEASE_NOT_APPROVED');$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('app_builder_artifacts',array('published'=>1,'released_at'=>date('Y-m-d H:i:s')));return array($this->one('artifacts',$org,$id),NULL);}
 function rollup($org){$p=$this->list_rows('projects',$org);$t=$this->list_rows('tasks',$org);$r=$this->list_rows('runs',$org);$a=$this->list_rows('artifacts',$org);$ap=$this->list_rows('approvals',$org);$states=array_fill_keys(array('QUEUED','GENERATING_CODE','TESTING','COMPILING','SIGNING','SUCCEEDED','FAILED'),0);$dur=array();foreach($r as $x){$states[$x['status']]++;if($x['status']==='SUCCEEDED'&&$x['startedAt']&&$x['finalizedAt'])$dur[]=(strtotime($x['finalizedAt'])-strtotime($x['startedAt']))*1000;}$st=array_merge(array_column($p,'createdAt'),array_column($r,'createdAt'),array_column($a,'createdAt'));rsort($st);return array('counts'=>array('projects'=>count($p),'tasks'=>count($t),'tasksCompleted'=>count(array_filter($t,function($x){return$x['isCompleted'];})),'runs'=>count($r),'runsByStatus'=>$states,'artifacts'=>count($a),'releasedArtifacts'=>count(array_filter($a,function($x){return$x['published'];})),'pendingApprovals'=>count(array_filter($ap,function($x){return$x['status']==='pending';}))),'avgBuildTimeMs'=>$dur?round(array_sum($dur)/count($dur)):NULL,'recentProjects'=>array_slice($p,0,6),'recentRuns'=>array_slice($r,0,6),'latestArtifacts'=>array_slice($a,0,6),'lastUpdatedAt'=>$st?$st[0]:NULL);}
 private function sbom($stack){$cat=array('react'=>'18.3.1','express'=>'4.21.1','postgres'=>'16.4','redis'=>'8.0','typescript'=>'5.6.3','node'=>'20.11','python'=>'3.12','vite'=>'5.4.0','prisma'=>'5.22.0');$o=array();foreach($stack as $name){$k=strtolower(str_replace(' ','',$name));$o[]=array('name'=>$name,'version'=>$cat[$k]??'declared (unpinned)','declared'=>isset($cat[$k]));}return $o;}
 private function agent_group($a){$groups=array('Product'=>array('PM','Business Analyst','Solution Architect'),'Design'=>array('UX Researcher','UI Designer'),'Engineer'=>array('Frontend Engineer','Backend Engineer','Mobile Engineer','Desktop Engineer','Database Engineer','AI Engineer'),'Quality'=>array('QA Engineer','Security Engineer'),'Platform'=>array('DevOps Engineer','Site Reliability Engineer'),'Delivery'=>array('Technical Writer','Release Manager'));foreach($groups as $g=>$as)if(in_array($a,$as,TRUE))return$g;return'Engineer';}
 function view($t,$r){$json=array('projects'=>array('tech_stack'),'tasks'=>array(),'runs'=>array('logs','error_log'),'artifacts'=>array('sbom'),'approvals'=>array());$bool=array('is_completed','published');$o=array();foreach($r as $k=>$v){$parts=explode('_',$k);$n=array_shift($parts);foreach($parts as $x)$n.=ucfirst($x);$o[$n]=in_array($k,$json[$t],TRUE)?(json_decode($v,TRUE)?:array()):(in_array($k,$bool,TRUE)?(bool)$v:$v);}foreach($o as $k=>$v)if((substr($k,-2)==='At'||$k==='createdAt'||$k==='startedAt'||$k==='finalizedAt')&&$v)$o[$k]=date('c',strtotime($v));return$o;}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
