<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Attachment_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function target_ok($cid,$org){return !$cid||$this->db->where(array('id'=>$cid,'organization_id'=>$org,'deleted_at'=>NULL))->count_all_results('conversations')>0;}
 public function create($org,$uid,$file,$cid){$id=$this->uuid();$safe=preg_replace('/[^A-Za-z0-9_.-]+/','_',basename($file['name']));$safe=substr($safe?:'upload',0,120);$checksum=hash_file('sha256',$file['tmp_name']);$dir=APPPATH.'storage/uploads/'.$org;if(!is_dir($dir)&&!mkdir($dir,0750,TRUE))return array(NULL,'storage');$key=$org.'/'.$checksum.'-'.$safe;$path=APPPATH.'storage/uploads/'.$key;if(is_file($path)){if(hash_file('sha256',$path)!==$checksum)return array(NULL,'collision');}elseif(!move_uploaded_file($file['tmp_name'],$path))return array(NULL,'storage');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($path);$text=(strpos($mime,'text/')===0||$mime==='application/json')?substr(file_get_contents($path),0,8000):NULL;$r=array('id'=>$id,'organization_id'=>$org,'conversation_id'=>$cid?:NULL,'message_id'=>NULL,'talk_message_id'=>NULL,'uploader_id'=>$uid,'filename'=>$safe,'mime_type'=>$mime,'size_bytes'=>(int)$file['size'],'storage_key'=>$key,'checksum'=>$checksum,'extracted_text'=>$text,'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('message_attachments',$r);return array($this->view($r),NULL);}
 public function one($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('message_attachments')->row_array();return $r?:NULL;}
 public function listing($org,$q,$page,$per){$this->db->from('message_attachments')->where('organization_id',$org);if($q)$this->db->like('filename',$q);$total=$this->db->count_all_results();$this->db->where('organization_id',$org);if($q)$this->db->like('filename',$q);$rows=$this->db->order_by('created_at','DESC')->limit($per,($page-1)*$per)->get('message_attachments')->result_array();return array('items'=>array_map(array($this,'view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 public function remove($id,$org,$uid){$r=$this->one($id,$org);if(!$r)return 'missing';if($r['uploader_id']!==$uid)return 'forbidden';if($r['message_id']||$r['talk_message_id'])return 'claimed';$this->db->where('id',$id)->delete('message_attachments');$path=APPPATH.'storage/uploads/'.$r['storage_key'];if(is_file($path))@unlink($path);return NULL;}
 public function claim($ids,$org,$uid,$cid,$mid){if(!$ids)return array(TRUE,NULL);if(!is_array($ids)||count($ids)>20||count(array_unique($ids))!==count($ids))return array(FALSE,'Attachment identifiers are invalid');$rows=$this->db->where_in('id',$ids)->where(array('organization_id'=>$org,'uploader_id'=>$uid,'message_id'=>NULL,'talk_message_id'=>NULL))->get('message_attachments')->result_array();if(count($rows)!==count($ids))return array(FALSE,'One or more attachments are unavailable');foreach($rows as $r)if($r['conversation_id']&&$r['conversation_id']!==$cid)return array(FALSE,'Attachment belongs to another conversation');$this->db->where_in('id',$ids)->update('message_attachments',array('conversation_id'=>$cid,'message_id'=>$mid));return array(TRUE,NULL);}
 public function claim_talk($ids,$org,$uid,$talkId){if(!$ids)return array(TRUE,NULL);if(!is_array($ids)||count($ids)>20||count(array_unique($ids))!==count($ids))return array(FALSE,'Attachment identifiers are invalid');$rows=$this->db->where_in('id',$ids)->where(array('organization_id'=>$org,'uploader_id'=>$uid,'message_id'=>NULL,'talk_message_id'=>NULL,'conversation_id'=>NULL))->get('message_attachments')->result_array();if(count($rows)!==count($ids))return array(FALSE,'One or more attachments are unavailable');$this->db->where_in('id',$ids)->update('message_attachments',array('talk_message_id'=>$talkId));return array(TRUE,NULL);}
 public function for_message($mid,$org){$rows=$this->db->where(array('message_id'=>$mid,'organization_id'=>$org))->order_by('created_at')->get('message_attachments')->result_array();return array_map(array($this,'view'),$rows);}
 public function view($r){return array('id'=>$r['id'],'filename'=>$r['filename'],'mimeType'=>$r['mime_type'],'sizeBytes'=>(int)$r['size_bytes'],'sha256'=>$r['checksum'],'previewText'=>$r['extracted_text'],'conversationId'=>$r['conversation_id'],'talkMessageId'=>$r['talk_message_id'],'createdAt'=>$r['created_at']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
