<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Audit_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 private function filters($org,$f){$this->db->where('organization_id',$org);if(!empty($f['userId']))$this->db->where('user_id',$f['userId']);if(!empty($f['action']))$this->db->where('event_type',$f['action']);if(!empty($f['resourceType']))$this->db->where("JSON_UNQUOTE(JSON_EXTRACT(payload, '$.resourceType')) = ".$this->db->escape($f['resourceType']),NULL,FALSE);if(!empty($f['resourceId']))$this->db->where("JSON_UNQUOTE(JSON_EXTRACT(payload, '$.resourceId')) = ".$this->db->escape($f['resourceId']),NULL,FALSE);if(!empty($f['startDate']))$this->db->where('created_at >=',$f['startDate']);if(!empty($f['endDate']))$this->db->where('created_at <=',$f['endDate']);}
 public function query($org,$f,$limit,$offset){$this->filters($org,$f);$total=$this->db->count_all_results('audit_events',FALSE);$rows=$this->db->order_by('created_at','DESC')->limit($limit,$offset)->get()->result_array();return array($this->map($rows),$total);}
 public function recent($org,$limit){return $this->map($this->db->where('organization_id',$org)->order_by('created_at','DESC')->limit($limit)->get('audit_events')->result_array());}
 public function one($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('audit_events')->row_array();return $r?$this->row($r):NULL;}
 public function stats($org,$days){$start=date('Y-m-d H:i:s',time()-$days*86400);return $this->db->select('event_type action,COUNT(*) count')->where('organization_id',$org)->where('created_at >=',$start)->group_by('event_type')->order_by('count','DESC')->get('audit_events')->result_array();}
 public function timeline($org,$days){$start=date('Y-m-d',time()-($days-1)*86400);$rows=$this->db->select('DATE(created_at) day,event_type action,COUNT(*) count',FALSE)->where('organization_id',$org)->where('created_at >=',$start.' 00:00:00')->group_by(array('DATE(created_at)','event_type'))->get('audit_events')->result_array();$map=array();foreach($rows as $r){$map[$r['day']][$r['action']]=(int)$r['count'];}$out=array();for($i=$days-1;$i>=0;$i--){$d=date('Y-m-d',time()-$i*86400);$by=$map[$d]??array();$out[]=array('date'=>$d,'total'=>array_sum($by),'byAction'=>$by);}return $out;}
  private function map($rows){return array_map(array($this,'row'),$rows);} private function row($r){$p=json_decode($r['payload']?:'{}',TRUE)?:array();return array('id'=>(string)$r['id'],'organizationId'=>$r['organization_id'],'userId'=>$r['user_id'],'action'=>$r['event_type'],'resourceType'=>$p['resourceType']??NULL,'resourceId'=>$p['resourceId']??NULL,'metadata'=>$p,'ipAddress'=>$r['ip_address'],'userAgent'=>$r['user_agent'],'requestId'=>$r['request_id'],'apiKeyId'=>NULL,'createdAt'=>$r['created_at']);}
}
