<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Conversation_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 private function access($uid,$org){$this->db->where('c.organization_id',$org)->where('c.deleted_at IS NULL',NULL,FALSE)->group_start()->where('c.created_by_id',$uid)->or_where('EXISTS (SELECT 1 FROM conversation_participants cp WHERE cp.conversation_id=c.id AND cp.user_id='.$this->db->escape($uid).')',NULL,FALSE)->group_end();}
 public function all($uid,$org,$q,$page,$per){$this->db->from('conversations c');$this->access($uid,$org);$this->db->where('c.is_archived',$q['archived']?1:0);if($q['pinned'])$this->db->where('c.pinned',1);if($q['search'])$this->db->like('c.title',$q['search']);$total=$this->db->count_all_results('',FALSE);$rows=$this->db->select('c.*')->order_by('c.pinned','DESC')->order_by('c.last_message_at','DESC')->limit($per,($page-1)*$per)->get()->result_array();return array(array_map(array($this,'view'),$rows),$total);}
 public function get($id,$uid,$org){$this->db->from('conversations c');$this->access($uid,$org);$r=$this->db->where('c.id',$id)->select('c.*')->get()->row_array();return $r?$this->view($r):NULL;}
 public function create($uid,$org,$wid,$d){$now=date('Y-m-d H:i:s');$id=$this->uuid();$r=array('id'=>$id,'organization_id'=>$org,'workspace_id'=>$wid,'title'=>$d['title'],'summary'=>NULL,'created_by_id'=>$uid,'pinned'=>0,'is_archived'=>0,'model_id'=>$d['modelId']??'windels-assistant','metadata'=>'{}','last_message_at'=>$now,'created_at'=>$now,'updated_at'=>$now);$this->db->trans_start();$this->db->insert('conversations',$r);$this->db->insert('conversation_participants',array('id'=>$this->uuid(),'conversation_id'=>$id,'user_id'=>$uid,'joined_at'=>$now));if(!empty($d['firstMessage']))$this->insert_message($id,'USER',$d['firstMessage'],$uid,NULL,$r['model_id'],'COMPLETED');$this->db->trans_complete();return $this->view($r);}
 public function update_owned($id,$uid,$org,$d){if(!$this->get($id,$uid,$org))return NULL;$set=array('updated_at'=>date('Y-m-d H:i:s'));$map=array('title'=>'title','modelId'=>'model_id');foreach($map as $in=>$out)if(array_key_exists($in,$d))$set[$out]=$d[$in];if(array_key_exists('pinned',$d)){$set['pinned']=$d['pinned']?1:0;$set['pinned_at']=$d['pinned']?date('Y-m-d H:i:s'):NULL;}if(array_key_exists('isArchived',$d)){$set['is_archived']=$d['isArchived']?1:0;$set['archived_at']=$d['isArchived']?date('Y-m-d H:i:s'):NULL;}$this->db->where('id',$id)->update('conversations',$set);return $this->get($id,$uid,$org);}
 public function soft_delete($id,$uid,$org){if(!$this->get($id,$uid,$org))return FALSE;$this->db->where('id',$id)->update('conversations',array('deleted_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')));return TRUE;}
 public function messages($id,$uid,$org,$page,$per){if(!$this->get($id,$uid,$org))return NULL;$total=$this->db->where('conversation_id',$id)->count_all_results('messages');$rows=$this->db->where('conversation_id',$id)->order_by('created_at')->limit($per,($page-1)*$per)->get('messages')->result_array();return array('messages'=>array_map(array($this,'message_view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per)));}
 public function send_user($id,$uid,$org,$content,$parent=NULL){if(!$this->get($id,$uid,$org))return NULL;if($parent&&!$this->db->where(array('id'=>$parent,'conversation_id'=>$id))->count_all_results('messages'))return FALSE;$m=$this->insert_message($id,'USER',$content,$uid,$parent,NULL,'COMPLETED');$this->db->where('id',$id)->update('conversations',array('last_message_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')));return $this->message_view($m);}
 private function insert_message($cid,$role,$content,$uid,$parent,$model,$status){$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'conversation_id'=>$cid,'role'=>$role,'content'=>$content,'user_id'=>$uid,'parent_id'=>$parent,'model_id'=>$model,'status'=>$status,'citations'=>'[]','metadata'=>'{}','created_at'=>$now,'updated_at'=>$now);$this->db->insert('messages',$r);return $r;}
 public function view($r){$count=$this->db->where('conversation_id',$r['id'])->count_all_results('messages');$parts=$this->db->select('cp.id,u.id user_id,u.email,u.display_name')->from('conversation_participants cp')->join('users u','u.id=cp.user_id','left')->where('cp.conversation_id',$r['id'])->get()->result_array();$pv=array();foreach($parts as $p)$pv[]=array('id'=>$p['id'],'agent'=>NULL,'user'=>$p['user_id']?array('id'=>$p['user_id'],'email'=>$p['email'],'displayName'=>$p['display_name']):NULL);return array('id'=>$r['id'],'title'=>$r['title'],'summary'=>$r['summary'],'pinned'=>(bool)$r['pinned'],'pinnedAt'=>$r['pinned_at']??NULL,'isArchived'=>(bool)$r['is_archived'],'archivedAt'=>$r['archived_at']??NULL,'deletedAt'=>$r['deleted_at']??NULL,'createdAt'=>$r['created_at'],'modelId'=>$r['model_id'],'lastMessageAt'=>$r['last_message_at'],'messageCount'=>$count,'participants'=>$pv);}
 public function message_view($r){$u=$r['user_id']?$this->db->where('id',$r['user_id'])->get('users')->row_array():NULL;return array('id'=>$r['id'],'role'=>strtolower($r['role']),'content'=>$r['content'],'status'=>strtolower($r['status']),'modelId'=>$r['model_id'],'tokensIn'=>$r['tokens_in']??NULL,'tokensOut'=>$r['tokens_out']??NULL,'createdAt'=>$r['created_at'],'user'=>$u?array('id'=>$u['id'],'email'=>$u['email'],'displayName'=>$u['display_name'],'avatarUrl'=>$u['avatar_url']):NULL,'agent'=>NULL,'attachments'=>$this->attachment_views($r['id']));}private function attachment_views($mid){if(!$this->db->table_exists('message_attachments'))return array();$rows=$this->db->where('message_id',$mid)->order_by('created_at')->get('message_attachments')->result_array();$out=array();foreach($rows as $a)$out[]=array('id'=>$a['id'],'filename'=>$a['filename'],'mimeType'=>$a['mime_type'],'sizeBytes'=>(int)$a['size_bytes']);return $out;}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}

 public function ai_history($id,$uid,$org,$limit=50){if(!$this->get($id,$uid,$org))return NULL;$rows=$this->db->select('role,content')->where('conversation_id',$id)->where('status','COMPLETED')->order_by('created_at','DESC')->limit($limit)->get('messages')->result_array();$rows=array_reverse($rows);return array_map(function($r){return array('role'=>strtolower($r['role']),'content'=>$r['content']);},$rows);}
 public function assistant($id,$content,$model,$usage){$m=$this->insert_message($id,'ASSISTANT',$content,NULL,NULL,$model,'COMPLETED');$set=array('tokens_in'=>$usage['tokensIn'],'tokens_out'=>$usage['tokensOut'],'duration_ms'=>$usage['durationMs'],'updated_at'=>date('Y-m-d H:i:s'));$this->db->where('id',$m['id'])->update('messages',$set);$m=array_merge($m,$set);$this->db->where('id',$id)->update('conversations',array('summary'=>substr($content,0,120),'last_message_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')));return $this->message_view($m);}

 public function set_pin($id,$uid,$org,$pinned){return $this->update_owned($id,$uid,$org,array('pinned'=>$pinned));}
 public function set_archive($id,$uid,$org,$archived){return $this->update_owned($id,$uid,$org,array('isArchived'=>$archived));}
 public function rename($id,$uid,$org,$title){return $this->update_owned($id,$uid,$org,array('title'=>$title));}
 public function purge($id,$uid,$org){$this->db->from('conversations c');$this->db->where(array('c.id'=>$id,'c.organization_id'=>$org,'c.created_by_id'=>$uid));$exists=$this->db->count_all_results()>0;if(!$exists)return FALSE;$this->db->where('id',$id)->delete('conversations');return TRUE;}
}
