<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Discovery_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 private function scope($org){$this->db->group_start()->where('organization_id IS NULL',NULL,FALSE)->or_where('organization_id',$org)->group_end();}
 public function services($org,$q=array()){$this->scope($org);if(!empty($q['name']))$this->db->group_start()->like('name',$q['name'])->or_where('service_id',$q['name'])->group_end();if(!empty($q['status']))$this->db->where('status',$q['status']);elseif(empty($q['includeOffline']))$this->db->where('status !=','offline');if(!empty($q['region']))$this->db->where('region',$q['region']);$rows=$this->db->order_by("FIELD(status,'healthy','starting','degraded','unhealthy','offline')",'',FALSE)->get('service_registry')->result_array();$out=array();foreach($rows as $r){$v=$this->view($r);if(!empty($q['capability'])&&!in_array($q['capability'],$v['capabilities'],TRUE))continue;if(!empty($q['minVersion'])&&version_compare($v['version'],$q['minVersion'],'<'))continue;$out[]=$v;}return $out;}
 public function register($org,$d){$instance=$d['instanceId']??substr($d['id'].'-'.bin2hex(random_bytes(6)),0,100);$old=$this->db->where('instance_id',$instance)->get('service_registry')->row_array();if($old&&$old['organization_id']!==$org)return NULL;$now=date('Y-m-d H:i:s');$r=array('instance_id'=>$instance,'service_id'=>$d['id'],'organization_id'=>$org,'name'=>$d['name'],'version'=>$d['version'],'base_url'=>$d['baseUrl'],'health_url'=>$d['healthUrl']??NULL,'status'=>$d['status']??'healthy','capabilities'=>json_encode($d['capabilities']??array()),'region'=>$d['region']??NULL,'metadata'=>json_encode($d['metadata']??array()),'started_at'=>$old['started_at']??$now,'last_heartbeat'=>$now);$this->db->replace('service_registry',$r);return $this->view($r);}
 public function heartbeat($instance,$org,$d){$this->scope($org);$r=$this->db->where('instance_id',$instance)->get('service_registry')->row_array();if(!$r)return NULL;$set=array('last_heartbeat'=>date('Y-m-d H:i:s'),'status'=>$d['status']??'healthy');if(!empty($d['version']))$set['version']=$d['version'];$this->db->where('instance_id',$instance)->update('service_registry',$set);return $this->view(array_merge($r,$set));}
 public function remove($id,$instance,$org){$this->db->where('service_id',$id)->where('organization_id',$org);if($instance)$this->db->where('instance_id',$instance);$this->db->delete('service_registry');return $this->db->affected_rows()>0;}
 public function dependencies($org,$service=NULL){$this->db->where('organization_id',$org);if($service)$this->db->where('source_service_id',$service);$rows=$this->db->get('service_dependencies')->result_array();return array_map(function($r){return array('from'=>$r['source_service_id'],'to'=>$r['target_service_id'],'kind'=>$r['kind'],'criticality'=>$r['criticality']);},$rows);}
 public function dependency($org,$d){$this->db->replace('service_dependencies',array('organization_id'=>$org,'source_service_id'=>$d['from'],'target_service_id'=>$d['to'],'kind'=>$d['kind'],'criticality'=>$d['criticality'],'created_at'=>date('Y-m-d H:i:s')));}
 public function validate_graph($org){$services=$this->services($org,array());$healthy=array();foreach($services as $s)if($s['status']==='healthy')$healthy[$s['id']]=TRUE;$missing=array();foreach($this->dependencies($org) as $d){if($d['criticality']==='required'){if(empty($healthy[$d['from']]))$missing[$d['from']]=TRUE;if(empty($healthy[$d['to']]))$missing[$d['to']]=TRUE;}}return array('missing'=>array_keys($missing),'healthy'=>count($missing)===0);}
 public function mark_stale($org){$cut=date('Y-m-d H:i:s',time()-120);$this->db->where('organization_id',$org)->where('last_heartbeat <',$cut)->update('service_registry',array('status'=>'offline'));}
 public function view($r){return array('id'=>$r['service_id'],'name'=>$r['name'],'version'=>$r['version'],'baseUrl'=>$r['base_url'],'healthUrl'=>$r['health_url'],'status'=>$r['status'],'capabilities'=>json_decode($r['capabilities'],TRUE)?:array(),'metadata'=>json_decode($r['metadata'],TRUE)?:array(),'startedAt'=>$r['started_at'],'lastHeartbeat'=>$r['last_heartbeat'],'region'=>$r['region'],'instanceId'=>$r['instance_id']);}
}
