<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Event_bus_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function schemas($org){$rows=$this->db->group_start()->where('organization_id IS NULL',NULL,FALSE)->or_where('organization_id',$org)->group_end()->order_by('event_type')->order_by('version','DESC')->get('event_schemas')->result_array();return array_map(array($this,'schema_view'),$rows);}
 public function register_schema($org,$d){if($this->db->where(array('organization_id'=>$org,'event_type'=>$d['type'],'version'=>$d['version']))->count_all_results('event_schemas'))return NULL;$r=array('id'=>$this->uuid(),'organization_id'=>$org,'event_type'=>$d['type'],'version'=>$d['version'],'description'=>$d['description'],'producer'=>$d['producer'],'consumers'=>json_encode($d['consumers']),'schema_json'=>json_encode($d['schema'],JSON_UNESCAPED_SLASHES),'examples'=>isset($d['examples'])?json_encode($d['examples']):NULL,'deprecated'=>!empty($d['deprecated'])?1:0,'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('event_schemas',$r);return $this->schema_view($r);}
 public function publish($org,$producer,$d){$id=$this->uuid();$corr=$this->uuid();$r=array('id'=>$id,'organization_id'=>$org,'event_type'=>$d['type'],'schema_version'=>$d['schemaVersion']??'1.0.0','producer'=>$producer,'correlation_id'=>$d['correlationId']??$corr,'causation_id'=>$d['causationId']??NULL,'trace_id'=>$d['traceId']??NULL,'payload'=>json_encode($d['payload'],JSON_UNESCAPED_SLASHES),'metadata'=>json_encode($d['metadata']??array(),JSON_UNESCAPED_SLASHES),'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('enterprise_events',$r);return $this->event_view($r);}
 public function recent($org,$type,$since,$corr){$this->db->where('organization_id',$org);if($type)$this->db->where('event_type',$type);if($since)$this->db->where('created_at >=',$since);if($corr)$this->db->where('correlation_id',$corr);$rows=$this->db->order_by('created_at','DESC')->limit(1000)->get('enterprise_events')->result_array();return array_map(array($this,'event_view'),$rows);}
 public function dlq($org,$status=NULL){$this->db->where('d.organization_id',$org);if($status)$this->db->where('d.status',$status);$rows=$this->db->select('d.*,e.event_type,e.schema_version,e.producer,e.correlation_id,e.causation_id,e.trace_id,e.payload,e.metadata,e.created_at event_created_at')->from('event_dead_letters d')->join('enterprise_events e','e.id=d.event_id')->order_by('d.last_failed_at','DESC')->get()->result_array();$out=array();foreach($rows as $r)$out[]=array('id'=>$r['id'],'event'=>$this->event_view(array('id'=>$r['event_id'],'event_type'=>$r['event_type'],'schema_version'=>$r['schema_version'],'producer'=>$r['producer'],'correlation_id'=>$r['correlation_id'],'causation_id'=>$r['causation_id'],'trace_id'=>$r['trace_id'],'payload'=>$r['payload'],'metadata'=>$r['metadata'],'created_at'=>$r['event_created_at'])),'failedConsumer'=>$r['failed_consumer'],'error'=>$r['error'],'attempts'=>(int)$r['attempts'],'firstFailedAt'=>$r['first_failed_at'],'lastFailedAt'=>$r['last_failed_at'],'status'=>$r['status']);return $out;}
 public function dlq_action($id,$org,$action){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('event_dead_letters')->row_array();if(!$r||$r['status']!=='pending')return FALSE;if($action==='replay'&&(int)$r['attempts']>=5)return FALSE;$set=$action==='discard'?array('status'=>'discarded'):array('status'=>'replayed','attempts'=>(int)$r['attempts']+1,'last_failed_at'=>date('Y-m-d H:i:s'));$this->db->where('id',$id)->update('event_dead_letters',$set);return TRUE;}
 public function schema_exists($org,$type,$version){return $this->db->group_start()->where('organization_id IS NULL',NULL,FALSE)->or_where('organization_id',$org)->group_end()->where(array('event_type'=>$type,'version'=>$version,'deprecated'=>0))->count_all_results('event_schemas')>0;}
 private function schema_view($r){return array('type'=>$r['event_type'],'version'=>$r['version'],'description'=>$r['description'],'producer'=>$r['producer'],'consumers'=>json_decode($r['consumers'],TRUE)?:array(),'schema'=>json_decode($r['schema_json'],TRUE)?:array(),'examples'=>json_decode($r['examples']?:'[]',TRUE)?:array(),'deprecated'=>(bool)$r['deprecated']);}
 private function event_view($r){return array('id'=>$r['id'],'type'=>$r['event_type'],'schemaVersion'=>$r['schema_version'],'timestamp'=>$r['created_at'],'producer'=>$r['producer'],'correlationId'=>$r['correlation_id'],'causationId'=>$r['causation_id'],'traceId'=>$r['trace_id'],'payload'=>json_decode($r['payload'],TRUE),'metadata'=>json_decode($r['metadata'],TRUE)?:array());}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
