<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Gift_card_model extends CI_Model{
 function __construct(){parent::__construct();$this->load->database();}
 function cards($org,$status=NULL){$this->db->where('organization_id',$org);if($status)$this->db->where('status',$status);return array_map(array($this,'card_view'),$this->db->order_by('created_at','DESC')->get('gift_cards')->result_array());}
 function card($org,$id,$raw=FALSE){$r=$this->db->where(array('organization_id'=>$org,'id'=>$id))->get('gift_cards')->row_array();return $r?($raw?$r:$this->card_view($r)):NULL;}
 function issue($org,$uid,$d){$now=date('Y-m-d H:i:s');$id=$this->uuid();$amount=$this->cents($d['amount']);do{$code=$this->code();}while($this->db->where('code',$code)->count_all_results('gift_cards'));$row=array('id'=>$id,'organization_id'=>$org,'type'=>$d['type'],'code'=>$code,'initial_balance_cents'=>$amount,'balance_cents'=>$amount,'currency'=>strtoupper($d['currency']),'status'=>'issued','pin_hash'=>!empty($d['pin'])?password_hash($d['pin'],PASSWORD_DEFAULT):NULL,'issuer_id'=>$uid,'recipient_id'=>$d['recipientId']??NULL,'issued_at'=>$now,'expires_at'=>date('Y-m-d H:i:s',strtotime('+'.((int)($d['expiresInDays']??365)).' days')),'last_used_at'=>NULL,'personal_message'=>$d['personalMessage']??NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->trans_start();$this->db->insert('gift_cards',$row);$this->txn($org,$id,'issue',$amount,$row['currency']);$this->db->trans_complete();return $this->card($org,$id);}
 function activate($org,$id,$pin){$r=$this->card($org,$id,TRUE);if(!$r)return array(NULL,'NOT_FOUND');if(!$this->pin($r,$pin)){$this->flag($org,$id,'PIN mismatch on activate','low');return array(NULL,'BAD_PIN');}if(!in_array($r['status'],array('issued','active'),TRUE))return array(NULL,'INVALID_STATE');$this->db->where('id',$id)->update('gift_cards',array('status'=>'active','updated_at'=>date('Y-m-d H:i:s')));$this->txn($org,$id,'activate',0,$r['currency']);return array($this->card($org,$id),NULL);}
 function reload($org,$id,$amount){$r=$this->card($org,$id,TRUE);if(!$r)return array(NULL,'NOT_FOUND');if(in_array($r['status'],array('redeemed','expired','frozen'),TRUE))return array(NULL,'INVALID_STATE');$c=$this->cents($amount);$this->db->trans_start();$this->db->set('balance_cents','balance_cents+'.$c,FALSE)->set('status','active')->set('updated_at',date('Y-m-d H:i:s'))->where(array('organization_id'=>$org,'id'=>$id))->update('gift_cards');$this->txn($org,$id,'reload',$c,$r['currency']);$this->db->trans_complete();return array($this->card($org,$id),NULL);}
 function redeem($org,$id,$amount,$pin=NULL,$order=NULL){$cents=$this->cents($amount);$this->db->trans_begin();$r=$this->db->query('SELECT * FROM gift_cards WHERE organization_id=? AND id=? FOR UPDATE',array($org,$id))->row_array();if(!$r){$this->db->trans_rollback();return array(NULL,'NOT_FOUND');}if($order){$old=$this->db->where(array('card_id'=>$id,'order_id'=>$order,'kind'=>'redeem'))->get('gift_card_transactions')->row_array();if($old){$this->db->trans_commit();return array(array('card'=>$this->card($org,$id),'redeemed'=>$old['amount_cents']/100,'txn'=>$this->txn_view($old)),NULL);}}if(!$this->pin($r,$pin)){$this->db->trans_rollback();$this->flag($org,$id,'PIN mismatch on redeem','medium');return array(NULL,'BAD_PIN');}if(!in_array($r['status'],array('active','partially-redeemed'),TRUE)){$this->db->trans_rollback();return array(NULL,'INVALID_STATE');}if($r['expires_at']&&strtotime($r['expires_at'])<time()){$this->db->where('id',$id)->update('gift_cards',array('status'=>'expired'));$this->db->trans_commit();return array(NULL,'EXPIRED');}if($cents>(int)$r['balance_cents']){$this->db->trans_rollback();return array(NULL,'INSUFFICIENT_FUNDS');}$balance=(int)$r['balance_cents']-$cents;$now=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('gift_cards',array('balance_cents'=>$balance,'status'=>$balance?'partially-redeemed':'redeemed','last_used_at'=>$now,'updated_at'=>$now));$t=$this->txn($org,$id,'redeem',$cents,$r['currency'],$order);$this->db->trans_commit();return array(array('card'=>$this->card($org,$id),'redeemed'=>$cents/100,'txn'=>$this->txn_view($t)),NULL);}
 function state($org,$id,$action,$reason=NULL){$r=$this->card($org,$id,TRUE);if(!$r)return array(NULL,'NOT_FOUND');if($action==='freeze'){if(in_array($r['status'],array('frozen','redeemed','expired'),TRUE))return array(NULL,'INVALID_STATE');$status='frozen';}elseif($action==='unfreeze'){if($r['status']!=='frozen')return array(NULL,'INVALID_STATE');if($r['expires_at']&&strtotime($r['expires_at'])<time())return array(NULL,'EXPIRED');$status=(int)$r['balance_cents']?'active':'redeemed';}else $status='expired';$this->db->trans_start();$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('gift_cards',array('status'=>$status,'updated_at'=>date('Y-m-d H:i:s')));$this->txn($org,$id,$action,$action==='expire'?(int)$r['balance_cents']:0,$r['currency'],$reason);if($action==='freeze')$this->flag($org,$id,$reason,'high');$this->db->trans_complete();return array($this->card($org,$id),NULL);}
 function transactions($org,$card=NULL){$this->db->where('organization_id',$org);if($card)$this->db->where('card_id',$card);return array_map(array($this,'txn_view'),$this->db->order_by('created_at','DESC')->limit(50)->get('gift_card_transactions')->result_array());}
 function fraud($org,$resolved=NULL){$this->db->where('organization_id',$org);if($resolved!==NULL)$this->db->where('resolved',$resolved?1:0);return array_map(array($this,'fraud_view'),$this->db->order_by('flagged_at','DESC')->get('gift_card_fraud_flags')->result_array());}
 function resolve_flag($org,$id,$uid){$this->db->where(array('organization_id'=>$org,'id'=>$id))->update('gift_card_fraud_flags',array('resolved'=>1,'resolved_at'=>date('Y-m-d H:i:s'),'resolved_by'=>$uid));$r=$this->db->where(array('organization_id'=>$org,'id'=>$id))->get('gift_card_fraud_flags')->row_array();return $r?$this->fraud_view($r):NULL;}
 function loyalty($org){return array_map(function($r){return array('id'=>$r['id'],'name'=>$r['name'],'multiplier'=>(float)$r['multiplier'],'pointsIssued'=>(int)$r['points_issued'],'memberCount'=>(int)$r['member_count']);},$this->db->where('organization_id',$org)->order_by('name')->get('gift_card_loyalty_programs')->result_array());}
 function dashboard($org){$cards=$this->cards($org);$out=0;$active=$redeemed=0;foreach($cards as $c){$out+=$c['balance'];if(in_array($c['status'],array('active','partially-redeemed'),TRUE))$active++;if($c['status']==='redeemed')$redeemed++;}$rev=$this->db->select_sum('amount_cents')->where(array('organization_id'=>$org,'kind'=>'redeem'))->where('created_at >=',date('Y-m-d H:i:s',strtotime('-24 hours')))->get('gift_card_transactions')->row_array();return array('issued'=>count($cards),'active'=>$active,'redeemed'=>$redeemed,'outstandingBalance'=>$out,'revenue24h'=>(int)($rev['amount_cents']??0)/100,'fraudFlags'=>$this->db->where('organization_id',$org)->count_all_results('gift_card_fraud_flags'),'loyaltyPrograms'=>$this->db->where('organization_id',$org)->count_all_results('gift_card_loyalty_programs'),'registeredAsPaymentMethod'=>TRUE);}
 function apply_invoice($org,$cardId,$invoiceId,$pin,$amount=NULL){$inv=$this->db->where(array('organization_id'=>$org,'id'=>$invoiceId))->get('invoices')->row_array();if(!$inv)return array(NULL,'INVOICE_NOT_FOUND');$old=$this->db->where(array('organization_id'=>$org,'invoice_id'=>$invoiceId,'card_id'=>$cardId))->get('gift_card_invoice_allocations')->row_array();if($old)return array(array('success'=>TRUE,'card'=>$this->card($org,$cardId),'redeemedCents'=>(int)$old['amount_cents'],'invoice'=>$inv,'idempotent'=>TRUE,'remainingCents'=>max(0,(int)$inv['amount_cents']-(int)$old['amount_cents'])),NULL);$card=$this->card($org,$cardId);if(!$card)return array(NULL,'NOT_FOUND');if($card['currency']!==strtoupper($inv['currency']))return array(NULL,'CURRENCY_MISMATCH');$used=$this->db->select_sum('amount_cents')->where(array('organization_id'=>$org,'invoice_id'=>$invoiceId))->get('gift_card_invoice_allocations')->row_array();$remaining=(int)$inv['amount_cents']-(int)($used['amount_cents']??0);$take=$amount===NULL?$remaining:$this->cents($amount);if($take<=0||$take>$remaining)return array(NULL,'INVALID_AMOUNT');list($red,$err)=$this->redeem($org,$cardId,$take/100,$pin,'inv-'.$invoiceId.'-gift-'.$cardId);if($err)return array(NULL,$err);$this->db->insert('gift_card_invoice_allocations',array('id'=>$this->uuid(),'organization_id'=>$org,'invoice_id'=>$invoiceId,'card_id'=>$cardId,'transaction_id'=>$red['txn']['id'],'amount_cents'=>$take,'currency'=>$inv['currency'],'created_at'=>date('Y-m-d H:i:s')));$usedNow=(int)($used['amount_cents']??0)+$take;if($usedNow===(int)$inv['amount_cents']){$this->db->where(array('organization_id'=>$org,'id'=>$invoiceId))->update('invoices',array('status'=>'paid','paid_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')));$inv=$this->db->where('id',$invoiceId)->get('invoices')->row_array();}return array(array('success'=>TRUE,'card'=>$red['card'],'redeemedCents'=>$take,'invoice'=>$inv,'idempotent'=>FALSE,'remainingCents'=>(int)$inv['amount_cents']-$usedNow),NULL);}
 private function txn($org,$card,$kind,$amount,$currency,$order=NULL){$r=array('id'=>$this->uuid(),'organization_id'=>$org,'card_id'=>$card,'kind'=>$kind,'amount_cents'=>$amount,'currency'=>$currency,'order_id'=>$order,'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('gift_card_transactions',$r);return$r;}
 private function flag($org,$card,$reason,$severity){$this->db->insert('gift_card_fraud_flags',array('id'=>$this->uuid(),'organization_id'=>$org,'card_id'=>$card,'reason'=>substr($reason,0,500),'severity'=>$severity,'flagged_at'=>date('Y-m-d H:i:s'),'resolved'=>0));}
 private function pin($r,$pin){return !$r['pin_hash']||($pin!==NULL&&password_verify($pin,$r['pin_hash']));}private function cents($v){return(int)round((float)$v*100);}private function code(){$chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';$s='';for($i=0;$i<16;$i++){$s.=($i&&$i%4===0?'-':'').$chars[random_int(0,strlen($chars)-1)];}return$s;}
 function card_view($r){return array('id'=>$r['id'],'type'=>$r['type'],'code'=>$r['code'],'initialBalance'=>(int)$r['initial_balance_cents']/100,'balance'=>(int)$r['balance_cents']/100,'currency'=>$r['currency'],'status'=>$r['status'],'issuerId'=>$r['issuer_id'],'recipientId'=>$r['recipient_id'],'issuedAt'=>date('c',strtotime($r['issued_at'])),'expiresAt'=>$r['expires_at']?date('c',strtotime($r['expires_at'])):NULL,'lastUsedAt'=>$r['last_used_at']?date('c',strtotime($r['last_used_at'])):NULL,'personalMessage'=>$r['personal_message']);}function txn_view($r){return array('id'=>$r['id'],'cardId'=>$r['card_id'],'kind'=>$r['kind'],'amount'=>(int)$r['amount_cents']/100,'currency'=>$r['currency'],'at'=>date('c',strtotime($r['created_at'])),'orderId'=>$r['order_id']);}function fraud_view($r){return array('id'=>$r['id'],'cardId'=>$r['card_id'],'reason'=>$r['reason'],'severity'=>$r['severity'],'flaggedAt'=>date('c',strtotime($r['flagged_at'])),'resolved'=>(bool)$r['resolved'],'resolvedAt'=>$r['resolved_at']?date('c',strtotime($r['resolved_at'])):NULL,'resolvedBy'=>$r['resolved_by']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
