<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Governance_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function adrs($org,$status=NULL,$tag=NULL){$this->db->where('organization_id',$org);if($status)$this->db->where('status',$status);$rows=$this->db->order_by('adr_number','DESC')->get('governance_adrs')->result_array();$out=array();foreach($rows as $r){$v=$this->adr_view($r);if(!$tag||in_array($tag,$v['tags'],TRUE))$out[]=$v;}return $out;}
 public function adr($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('governance_adrs')->row_array();return $r?$this->adr_view($r):NULL;}
 public function create_adr($org,$uid,$d){$seq=$this->db->select_max('adr_number','n')->where('organization_id',$org)->get('governance_adrs')->row_array();$now=date('Y-m-d H:i:s');$authors=array_values(array_unique(array_merge(array($uid),$d['authors']??array())));$r=array('id'=>$this->uuid(),'organization_id'=>$org,'adr_number'=>(int)($seq['n']??0)+1,'title'=>$d['title'],'status'=>$d['status']??'proposed','context'=>$d['context'],'decision'=>$d['decision'],'consequences'=>$d['consequences'],'authors'=>json_encode($authors),'tags'=>json_encode($d['tags']??array()),'created_by'=>$uid,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('governance_adrs',$r);return $this->adr_view($r);}
 public function update_adr($id,$org,$set){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('governance_adrs')->row_array();if(!$r)return NULL;$set['updated_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('governance_adrs',$set);return $this->adr_view(array_merge($r,$set));}
 public function standards($org,$category=NULL){$this->db->group_start()->where('organization_id IS NULL',NULL,FALSE)->or_where('organization_id',$org)->group_end();if($category)$this->db->where('category',$category);return $this->db->order_by('code')->get('governance_standards')->result_array();}
 public function add_standard($org,$d){$r=array('id'=>$this->uuid(),'organization_id'=>$org,'code'=>$d['code'],'category'=>$d['category'],'title'=>$d['title'],'description'=>$d['description'],'severity'=>$d['severity'],'enforcement'=>$d['enforcement'],'link'=>$d['link']??NULL,'created_at'=>date('Y-m-d H:i:s'));if(!$this->db->insert('governance_standards',$r))return NULL;return $r;}
 public function reviews($org,$status=NULL,$kind=NULL){$this->db->where('organization_id',$org);if($status)$this->db->where('status',$status);if($kind)$this->db->where('kind',$kind);$rows=$this->db->order_by('created_at','DESC')->get('governance_reviews')->result_array();return array_map(array($this,'review_view'),$rows);}
 public function create_review($org,$uid,$d){$r=array('id'=>$this->uuid(),'organization_id'=>$org,'kind'=>$d['kind'],'target_id'=>$d['targetId'],'requested_by'=>$uid,'reviewers'=>json_encode($d['reviewers']??array()),'status'=>'pending','created_at'=>date('Y-m-d H:i:s'),'decided_at'=>NULL);$this->db->insert('governance_reviews',$r);return $this->review_view($r);}
 public function comment($id,$org,$uid,$body){if(!$this->db->where(array('id'=>$id,'organization_id'=>$org))->count_all_results('governance_reviews'))return NULL;$this->db->insert('governance_review_comments',array('id'=>$this->uuid(),'review_id'=>$id,'author_id'=>$uid,'body'=>$body,'created_at'=>date('Y-m-d H:i:s')));$r=$this->db->where('id',$id)->get('governance_reviews')->row_array();return $this->review_view($r);}
 public function decide($id,$org,$decision){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('governance_reviews')->row_array();if(!$r)return NULL;$r['status']=$decision;$r['decided_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('governance_reviews',array('status'=>$decision,'decided_at'=>$r['decided_at']));return $this->review_view($r);}
 private function adr_view($r){return array('id'=>$r['id'],'number'=>(int)$r['adr_number'],'title'=>$r['title'],'status'=>$r['status'],'context'=>$r['context'],'decision'=>$r['decision'],'consequences'=>$r['consequences'],'authors'=>json_decode($r['authors'],TRUE)?:array(),'date'=>$r['created_at'],'supersededBy'=>$r['superseded_by'],'tags'=>json_decode($r['tags'],TRUE)?:array());}
 private function review_view($r){$comments=$this->db->where('review_id',$r['id'])->order_by('created_at')->get('governance_review_comments')->result_array();$cv=array();foreach($comments as $c)$cv[]=array('id'=>$c['id'],'author'=>$c['author_id'],'body'=>$c['body'],'createdAt'=>$c['created_at']);return array('id'=>$r['id'],'kind'=>$r['kind'],'targetId'=>$r['target_id'],'requestedBy'=>$r['requested_by'],'status'=>$r['status'],'reviewers'=>json_decode($r['reviewers'],TRUE)?:array(),'comments'=>$cv,'createdAt'=>$r['created_at'],'decidedAt'=>$r['decided_at']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
