<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Integration_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function all($org){$rows=$this->db->where('organization_id',$org)->order_by('type')->get('integrations')->result_array();return array_map(array($this,'view'),$rows);}
 public function create($org,$d){if($this->db->where(array('organization_id'=>$org,'type'=>$d['type']))->count_all_results('integrations'))return NULL;$now=date('Y-m-d H:i:s');$creds=$d['credentials'];$creds['_tokenId']=bin2hex(random_bytes(8));$row=array('id'=>$this->uuid(),'organization_id'=>$org,'type'=>$d['type'],'name'=>$d['name'],'config'=>json_encode($d['config'],JSON_UNESCAPED_SLASHES),'credentials'=>$this->seal($creds),'status'=>'connected','last_sync_at'=>NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('integrations',$row);$v=$this->view($row);$v['credentials']=array('connected'=>TRUE);return $v;}
 public function update_owned($id,$org,$d){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('integrations')->row_array();if(!$r)return NULL;$set=array('last_sync_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s'));foreach(array('name','status') as $f)if(array_key_exists($f,$d))$set[$f]=$d[$f];if(array_key_exists('config',$d))$set['config']=json_encode($d['config'],JSON_UNESCAPED_SLASHES);if(array_key_exists('credentials',$d)){$old=$this->open($r['credentials']);$set['credentials']=$this->seal(array_merge($old,$d['credentials']));}$this->db->where('id',$id)->update('integrations',$set);$r=array_merge($r,$set);$v=$this->view($r);$v['credentials']=array('connected'=>TRUE);return $v;}
 public function delete_owned($id,$org){if(!$this->db->where(array('id'=>$id,'organization_id'=>$org))->count_all_results('integrations'))return FALSE;$this->db->where(array('id'=>$id,'organization_id'=>$org))->delete('integrations');return TRUE;}
 public function view($r){$creds=$this->open($r['credentials']);return array('id'=>$r['id'],'type'=>$r['type'],'name'=>$r['name'],'config'=>json_decode($r['config'],TRUE)?:array(),'credentials'=>$creds?array_merge(array('connected'=>TRUE),$this->redact($creds)):array('connected'=>FALSE),'status'=>$r['status'],'lastSyncAt'=>$r['last_sync_at'],'createdAt'=>$r['created_at']);}
 private function redact($v){$out=array();foreach($v as $k=>$x){if(is_array($x))$out[$k]=$this->redact($x);elseif(preg_match('/secret|token|key|password|api[_-]?key|private/i',$k))$out[$k]=$x?substr((string)$x,0,2).'••••'.substr((string)$x,-2):'';else$out[$k]=$x;}return $out;}
 private function seal($v){$iv=random_bytes(12);$tag='';$raw=openssl_encrypt(json_encode($v,JSON_UNESCAPED_SLASHES),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,$tag);if($raw===FALSE)throw new RuntimeException('Credential encryption failed');return 'enc.v1|'.base64_encode($iv.$tag.$raw);}
 private function open($v){if(strpos((string)$v,'enc.v1|')!==0)return array();$b=base64_decode(substr($v,7),TRUE);if(!$b||strlen($b)<29)return array();$raw=openssl_decrypt(substr($b,28),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,substr($b,0,12),substr($b,12,16));$d=json_decode($raw?:'{}',TRUE);return is_array($d)?$d:array();}
 private function key(){return hash('sha256',(string)getenv('VP_ENCRYPTION_KEY'),TRUE);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
