<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Mfa_assurance_model extends CI_Model {
 const POLICY_NOTE='A policy records what this organization asks of its members. It applies to this deployment login path.';
 public function __construct(){parent::__construct();$this->load->database();}
 public function policy($org){$r=$this->db->where('organization_id',$org)->get('mfa_policies')->row_array();return array('organizationId'=>$org,'mode'=>$r['mode']??'optional','enforcement'=>$r['enforcement']??'report_only','graceDays'=>(int)($r['grace_days']??14),'recoveryCodeFloor'=>(int)($r['recovery_code_floor']??2),'allowRecoveryCodes'=>$r?(bool)$r['allow_recovery_codes']:TRUE,'updatedAt'=>$r['updated_at']??NULL,'updatedBy'=>$r['updated_by']??NULL,'source'=>$r?'stored':'default','note'=>self::POLICY_NOTE,'enforcementNote'=>'report_only blocks nothing; block_after_grace refuses non-compliant password login after grace.');}
 public function save_policy($org,$uid,$d){$p=$this->policy($org);$row=array('organization_id'=>$org,'mode'=>$d['mode']??$p['mode'],'enforcement'=>$d['enforcement']??$p['enforcement'],'grace_days'=>$d['graceDays']??$p['graceDays'],'recovery_code_floor'=>$d['recoveryCodeFloor']??$p['recoveryCodeFloor'],'allow_recovery_codes'=>isset($d['allowRecoveryCodes'])?($d['allowRecoveryCodes']?1:0):($p['allowRecoveryCodes']?1:0),'updated_at'=>date('Y-m-d H:i:s'),'updated_by'=>$uid);$this->db->replace('mfa_policies',$row);return $this->policy($org);}
 public function enrollment($uid,$org){$u=$this->db->where('id',$uid)->get('users')->row_array();$state=$u['mfa_enrollment_state'];if($u['mfa_enabled']&&$state==='none')$state='unrecorded';return array('userId'=>$uid,'state'=>$state,'startedAt'=>$u['mfa_started_at'],'confirmedAt'=>$u['mfa_confirmed_at'],'lastVerifiedAt'=>$u['mfa_last_verified_at'],'lastMethod'=>$u['mfa_last_method'],'stale'=>$state==='pending'&&strtotime($u['mfa_started_at'])<time()-86400,'organizationId'=>$org,'note'=>'Enrollment state reflects durable events recorded by this deployment.');}
 public function recovery($uid,$org){$u=$this->db->where('id',$uid)->get('users')->row_array();$n=count(json_decode($u['mfa_recovery_hashes']?:'[]',TRUE)?:array());$p=$this->policy($org);return array('remaining'=>$n,'issued'=>10,'floor'=>$p['recoveryCodeFloor'],'low'=>$n<=$p['recoveryCodeFloor'],'exhausted'=>$n===0,'note'=>'Recovery codes are stored only as SHA-256 digests and consumed on use.');}
 public function lock($uid){$u=$this->db->where('id',$uid)->get('users')->row_array();$until=$u['mfa_locked_until'];$locked=$until&&strtotime($until)>time();return array('userId'=>$uid,'locked'=>(bool)$locked,'failedAttempts'=>(int)$u['mfa_failures'],'remainingAttempts'=>max(0,5-(int)$u['mfa_failures']),'firstFailureAt'=>$u['mfa_first_failure_at'],'lastFailureAt'=>$u['mfa_last_failure_at'],'lockedAt'=>$u['mfa_locked_at'],'lockedUntil'=>$until,'retryAfterSeconds'=>$locked?strtotime($until)-time():0,'maxAttempts'=>5,'windowSeconds'=>900,'note'=>'The lock throttles MFA verification on this deployment.');}
 public function abandon($uid,$org){$e=$this->enrollment($uid,$org);if($e['state']!=='pending')return array('cleared'=>FALSE,'enrollment'=>$e,'reason'=>'Only a pending enrollment can be abandoned.');$this->db->where('id',$uid)->update('users',array('mfa_secret_cipher'=>NULL,'mfa_recovery_hashes'=>NULL,'mfa_enabled'=>0,'mfa_enrollment_state'=>'none','mfa_started_at'=>NULL,'updated_at'=>date('Y-m-d H:i:s')));return array('cleared'=>TRUE,'enrollment'=>$this->enrollment($uid,$org),'reason'=>'Pending enrollment was abandoned.');}
 public function clear_lock($uid){$this->db->where('id',$uid)->update('users',array('mfa_failures'=>0,'mfa_first_failure_at'=>NULL,'mfa_last_failure_at'=>NULL,'mfa_locked_at'=>NULL,'mfa_locked_until'=>NULL));return $this->lock($uid);}

 public function coverage($org,$limit=500,$compliance=NULL){$p=$this->policy($org);$rows=$this->db->select('u.*,m.role membership_role,m.joined_at,e.expires_at exempt_until')->from('memberships m')->join('users u','u.id=m.user_id')->join('mfa_exemptions e','e.user_id=u.id AND e.organization_id=m.organization_id AND e.revoked_at IS NULL AND e.expires_at > NOW()','left')->where('m.organization_id',$org)->order_by('m.joined_at')->limit($limit)->get()->result_array();$total=$this->db->where('organization_id',$org)->count_all_results('memberships');$members=array();$counts=array('covered'=>0,'not_required'=>0,'enrollment_pending'=>0,'in_grace'=>0,'not_enrolled'=>0,'exempt'=>0);$requiredCount=$covered=0;foreach($rows as $u){$required=$p['mode']==='required_all'||($p['mode']==='required_admins'&&in_array(strtoupper($u['membership_role']),array('OWNER','ADMIN'),TRUE));$state=$u['mfa_enrollment_state'];if($u['mfa_enabled']&&$state==='none')$state='unrecorded';$grace=date('Y-m-d H:i:s',strtotime($u['joined_at'])+$p['graceDays']*86400);$expired=strtotime($grace)<=time();if($u['exempt_until'])$c='exempt';elseif(!$required)$c='not_required';elseif($state==='pending')$c='enrollment_pending';elseif($u['mfa_enabled'])$c='covered';elseif(!$expired)$c='in_grace';else$c='not_enrolled';$remaining=count(json_decode($u['mfa_recovery_hashes']?:'[]',TRUE)?:array());$counts[$c]++;if($required){$requiredCount++;if($c==='covered')$covered++;}$m=array('userId'=>$u['id'],'email'=>$u['email'],'membershipRole'=>$u['membership_role'],'required'=>$required,'enrolled'=>(bool)$u['mfa_enabled'],'enrollmentState'=>$state,'confirmedAt'=>$u['mfa_confirmed_at'],'lastVerifiedAt'=>$u['mfa_last_verified_at'],'recoveryCodesRemaining'=>$remaining,'recoveryLow'=>$remaining<=$p['recoveryCodeFloor'],'locked'=>$u['mfa_locked_until']&&strtotime($u['mfa_locked_until'])>time(),'exemptUntil'=>$u['exempt_until'],'graceEndsAt'=>$required?$grace:NULL,'graceExpired'=>$required&&$expired,'compliance'=>$c);if(!$compliance||$c===$compliance)$members[]=$m;}return array('organizationId'=>$org,'policy'=>$p,'membersConsidered'=>count($rows),'membersTotal'=>$total,'truncated'=>$total>count($rows),'counts'=>$counts,'requiredCoverageRatio'=>$requiredCount?round($covered/$requiredCount,4):NULL,'members'=>$members,'generatedAt'=>gmdate('c'),'note'=>'Coverage is computed from organization memberships stored in MySQL.','enrollmentNote'=>'Enrollment state reflects durable events recorded by this deployment.');}
 public function exemptions($org){$rows=$this->db->where('organization_id',$org)->where('revoked_at IS NULL',NULL,FALSE)->order_by('expires_at')->get('mfa_exemptions')->result_array();return array('exemptions'=>array_map(array($this,'exemption_view'),$rows),'note'=>'Exemptions are documented administrator decisions with fixed expiry.');}
 public function grant_exemption($org,$uid,$actor,$reason,$days){$row=array('organization_id'=>$org,'user_id'=>$uid,'reason'=>$reason,'granted_by'=>$actor,'granted_at'=>date('Y-m-d H:i:s'),'expires_at'=>date('Y-m-d H:i:s',time()+$days*86400),'revoked_at'=>NULL);$this->db->replace('mfa_exemptions',$row);$this->event('exemption_granted',$uid,$org,$actor,NULL,NULL,array('days'=>$days));return $this->exemption_view($row);}
 public function revoke_exemption($org,$uid,$actor){$this->db->where(array('organization_id'=>$org,'user_id'=>$uid))->update('mfa_exemptions',array('revoked_at'=>date('Y-m-d H:i:s')));$ok=$this->db->affected_rows()>0;if($ok)$this->event('exemption_revoked',$uid,$org,$actor);return array('revoked'=>$ok);}
 public function locks($org){$rows=$this->db->select('u.id,u.email')->from('memberships m')->join('users u','u.id=m.user_id')->where('m.organization_id',$org)->where('u.mfa_locked_until >',date('Y-m-d H:i:s'))->get()->result_array();$out=array();foreach($rows as $r)$out[]=array_merge($this->lock($r['id']),array('email'=>$r['email']));return array('organizationId'=>$org,'locks'=>$out,'membersConsidered'=>$this->db->where('organization_id',$org)->count_all_results('memberships'),'truncated'=>FALSE,'note'=>'Active locks recorded in this deployment.');}
 public function events($org,$uid,$limit,$kind,$scope){if($org)$this->db->where('organization_id',$org);if($uid)$this->db->where('user_id',$uid);if($kind)$this->db->where('kind',$kind);$rows=$this->db->order_by('created_at','DESC')->limit($limit)->get('mfa_events')->result_array();$out=array();foreach($rows as $r)$out[]=array('id'=>(string)$r['id'],'kind'=>$r['kind'],'userId'=>$r['user_id'],'organizationId'=>$r['organization_id'],'actorId'=>$r['actor_id'],'method'=>$r['method'],'reason'=>$r['reason'],'detail'=>json_decode($r['detail']?:'null',TRUE),'at'=>$r['created_at']);return array('events'=>$out,'returned'=>count($out),'limit'=>$limit,'scope'=>$scope,'note'=>'Events recorded since the durable MFA ledger was introduced.');}
 public function event($kind,$uid,$org,$actor=NULL,$method=NULL,$reason=NULL,$detail=NULL){$this->db->insert('mfa_events',array('kind'=>$kind,'user_id'=>$uid,'organization_id'=>$org,'actor_id'=>$actor,'method'=>$method,'reason'=>$reason,'detail'=>$detail===NULL?NULL:json_encode($detail),'created_at'=>date('Y-m-d H:i:s')));}
 public function summary($org){$c=$this->coverage($org);$locks=$this->locks($org);$ex=$this->exemptions($org);$pending=$stale=$low=0;foreach($c['members'] as $m){if($m['enrollmentState']==='pending')$pending++;if($m['enrollmentState']==='pending'&&$m['confirmedAt']===NULL)$stale++;if($m['recoveryLow'])$low++;}$events=$this->events($org,NULL,100,NULL,'organization');return array('organizationId'=>$org,'policy'=>$c['policy'],'counts'=>$c['counts'],'membersConsidered'=>$c['membersConsidered'],'membersTotal'=>$c['membersTotal'],'truncated'=>$c['truncated'],'requiredCoverageRatio'=>$c['requiredCoverageRatio'],'activeLocks'=>count($locks['locks']),'activeExemptions'=>count($ex['exemptions']),'pendingEnrollments'=>$pending,'staleEnrollments'=>$stale,'recoveryLowMembers'=>$low,'recentEvents'=>$events['returned'],'generatedAt'=>gmdate('c'),'note'=>'Measured MFA assurance summary.','coverageNote'=>$c['note'],'ledgerNote'=>$events['note']);}
 public function gaps($org){$c=$this->coverage($org);$g=array();$counts=array('high'=>0,'medium'=>0,'low'=>0);foreach($c['members'] as $m){$kind=$severity=$detail=NULL;if($m['compliance']==='not_enrolled'){$kind='member_not_enrolled';$severity='high';$detail='Required member is not enrolled.';}elseif($m['compliance']==='in_grace'){$kind='member_in_grace';$severity='medium';$detail='Required member is inside the enrollment grace period.';}elseif($m['compliance']==='enrollment_pending'){$kind='enrollment_pending';$severity='medium';$detail='Enrollment was started but not confirmed.';}elseif($m['locked']){$kind='account_locked';$severity='high';$detail='MFA verification is locked.';}elseif($m['recoveryCodesRemaining']===0&&$m['enrolled']){$kind='recovery_codes_exhausted';$severity='high';$detail='No unused recovery codes remain.';}elseif($m['recoveryLow']&&$m['enrolled']){$kind='recovery_codes_low';$severity='low';$detail='Recovery codes are at or below policy floor.';}if($kind){$counts[$severity]++;$g[]=array('kind'=>$kind,'userId'=>$m['userId'],'email'=>$m['email'],'detail'=>$detail,'severity'=>$severity);}}return array('organizationId'=>$org,'gaps'=>$g,'counts'=>$counts,'membersConsidered'=>$c['membersConsidered'],'truncated'=>$c['truncated'],'generatedAt'=>gmdate('c'),'note'=>'Concrete MFA gaps visible to this deployment.');}
 private function exemption_view($r){return array('organizationId'=>$r['organization_id'],'userId'=>$r['user_id'],'reason'=>$r['reason'],'grantedBy'=>$r['granted_by'],'grantedAt'=>$r['granted_at'],'expiresAt'=>$r['expires_at'],'active'=>$r['revoked_at']===NULL&&strtotime($r['expires_at'])>time(),'note'=>'Documented time-limited MFA exemption.');}
}
