<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Mfa_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function status($uid){$u=$this->user($uid);return array('enabled'=>(bool)$u['mfa_enabled'],'enforced'=>(bool)$u['mfa_enabled'],'recoveryCodesRemaining'=>count(json_decode($u['mfa_recovery_hashes']?:'[]',TRUE)?:array()));}
 public function enable($uid,$email){$secret=$this->base32(random_bytes(20));$codes=$this->codes();$hashes=array_map(function($c){return hash('sha256',strtoupper($c));},$codes);$this->db->where('id',$uid)->update('users',array('mfa_secret_cipher'=>$this->seal($secret),'mfa_recovery_hashes'=>json_encode($hashes),'mfa_enabled'=>1,'mfa_enrollment_state'=>'pending','mfa_started_at'=>date('Y-m-d H:i:s'),'mfa_confirmed_at'=>NULL,'mfa_last_counter'=>NULL,'mfa_failures'=>0,'mfa_locked_until'=>NULL,'updated_at'=>date('Y-m-d H:i:s')));$issuer='WINDELS AI OS';$url='otpauth://totp/'.rawurlencode($issuer).':'.rawurlencode($email).'?secret='.$secret.'&issuer='.rawurlencode($issuer).'&algorithm=SHA1&digits=6&period=30';return array('secret'=>$secret,'otpauthUrl'=>$url,'recoveryCodes'=>$codes);}
 public function verify($uid,$token){$u=$this->user($uid);if(!$u['mfa_enabled']||!$u['mfa_secret_cipher'])return array('ok'=>FALSE,'reason'=>'mfa_not_enabled');if($u['mfa_locked_until']&&strtotime($u['mfa_locked_until'])>time())return array('ok'=>FALSE,'reason'=>'locked','retryAfterSeconds'=>strtotime($u['mfa_locked_until'])-time());$secret=$this->open($u['mfa_secret_cipher']);if(!$secret)return array('ok'=>FALSE,'reason'=>'mfa_secret_decrypt_failed');if(preg_match('/^\d{6}$/',$token)){$now=(int)floor(time()/30);for($i=-1;$i<=1;$i++){$counter=$now+$i;if(hash_equals($this->totp($secret,$counter),$token)){if($u['mfa_last_counter']!==NULL&&$counter<=(int)$u['mfa_last_counter'])return array('ok'=>FALSE,'reason'=>'replayed');$this->success($uid,array('mfa_last_counter'=>$counter));return array('ok'=>TRUE,'method'=>'totp');}}}else{$hash=hash('sha256',strtoupper(trim($token)));$codes=json_decode($u['mfa_recovery_hashes']?:'[]',TRUE)?:array();$i=array_search($hash,$codes,TRUE);if($i!==FALSE){array_splice($codes,$i,1);$this->success($uid,array('mfa_recovery_hashes'=>json_encode($codes)));return array('ok'=>TRUE,'method'=>'recovery');}}$fail=(int)$u['mfa_failures']+1;$set=array('mfa_failures'=>$fail,'mfa_last_failure_at'=>date('Y-m-d H:i:s'));if(empty($u['mfa_first_failure_at']))$set['mfa_first_failure_at']=date('Y-m-d H:i:s');if($fail>=5){$set['mfa_locked_at']=date('Y-m-d H:i:s');$set['mfa_locked_until']=date('Y-m-d H:i:s',time()+900);$set['mfa_failures']=0;}$this->db->where('id',$uid)->update('users',$set);return array('ok'=>FALSE,'reason'=>'invalid_token');}
 public function disable($uid){$this->db->where('id',$uid)->update('users',array('mfa_secret_cipher'=>NULL,'mfa_recovery_hashes'=>NULL,'mfa_enabled'=>0,'mfa_enrollment_state'=>'none','mfa_started_at'=>NULL,'mfa_confirmed_at'=>NULL,'mfa_last_verified_at'=>NULL,'mfa_last_method'=>NULL,'mfa_last_counter'=>NULL,'mfa_failures'=>0,'mfa_locked_until'=>NULL,'updated_at'=>date('Y-m-d H:i:s')));}
 public function recovery($uid){$codes=$this->codes();$hashes=array_map(function($c){return hash('sha256',strtoupper($c));},$codes);$this->db->where('id',$uid)->update('users',array('mfa_recovery_hashes'=>json_encode($hashes),'updated_at'=>date('Y-m-d H:i:s')));return $codes;}
 private function user($uid){return $this->db->where('id',$uid)->get('users')->row_array();}private function success($uid,$extra){$method=isset($extra['mfa_recovery_hashes'])?'recovery':'totp';$this->db->where('id',$uid)->update('users',array_merge(array('mfa_failures'=>0,'mfa_first_failure_at'=>NULL,'mfa_last_failure_at'=>NULL,'mfa_locked_at'=>NULL,'mfa_locked_until'=>NULL,'mfa_enrollment_state'=>'confirmed','mfa_confirmed_at'=>date('Y-m-d H:i:s'),'mfa_last_verified_at'=>date('Y-m-d H:i:s'),'mfa_last_method'=>$method),$extra));}
 private function totp($secret,$counter){$key=$this->base32decode($secret);$h=hash_hmac('sha1',pack('N2',0,$counter),$key,TRUE);$o=ord(substr($h,-1))&15;$n=((ord($h[$o])&127)<<24)|((ord($h[$o+1])&255)<<16)|((ord($h[$o+2])&255)<<8)|(ord($h[$o+3])&255);return str_pad((string)($n%1000000),6,'0',STR_PAD_LEFT);}
 private function base32($raw){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split($raw) as $c)$bits.=str_pad(decbin(ord($c)),8,'0',STR_PAD_LEFT);$out='';foreach(str_split($bits,5) as $b)$out.=$a[bindec(str_pad($b,5,'0'))];return $out;}private function base32decode($s){$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split(strtoupper($s)) as $c){$v=strpos($a,$c);if($v!==FALSE)$bits.=str_pad(decbin($v),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8) as $b)if(strlen($b)===8)$out.=chr(bindec($b));return $out;}
 private function codes(){$out=array();for($i=0;$i<10;$i++)$out[]=strtoupper(substr(bin2hex(random_bytes(8)),0,10));return $out;}private function seal($v){$iv=random_bytes(12);$tag='';$c=openssl_encrypt($v,'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,$tag);return 'enc.v1|'.base64_encode($iv.$tag.$c);}private function open($v){$b=base64_decode(substr($v,7),TRUE);if(!$b)return NULL;$r=openssl_decrypt(substr($b,28),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,substr($b,0,12),substr($b,12,16));return $r===FALSE?NULL:$r;}private function key(){return hash('sha256',(string)getenv('VP_ENCRYPTION_KEY'),TRUE);}
}
