<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Model_registry_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function all($org){$rows=$this->db->group_start()->where('organization_id IS NULL',NULL,FALSE)->or_where('organization_id',$org)->group_end()->where('enabled',1)->order_by('is_default','DESC')->order_by('provider')->order_by('name')->get('model_registry')->result_array();return array_map(array($this,'view'),$rows);}
 public function create($org,$d){$exists=$this->db->where(array('organization_id'=>$org,'provider'=>$d['provider'],'model_id'=>$d['modelId'],'version'=>$d['version']))->count_all_results('model_registry');if($exists)return NULL;$now=date('Y-m-d H:i:s');$row=array('id'=>$this->uuid(),'organization_id'=>$org,'provider'=>$d['provider'],'model_id'=>$d['modelId'],'name'=>$d['name'],'version'=>$d['version'],'description'=>$d['description']??NULL,'capabilities'=>json_encode($d['capabilities']),'context_window'=>$d['contextWindow'],'max_output_tokens'=>$d['maxOutputTokens'],'cost_input_per_1k'=>$d['costInputPer1k'],'cost_output_per_1k'=>$d['costOutputPer1k'],'is_default'=>0,'enabled'=>1,'config'=>json_encode($d['config'],JSON_UNESCAPED_SLASHES),'created_at'=>$now,'updated_at'=>$now);$this->db->insert('model_registry',$row);return $this->view($row);}
 public function owned($id,$org){return $this->db->where(array('id'=>$id,'organization_id'=>$org))->get('model_registry')->row_array();}
 public function update_owned($id,$org,$set){if(!$this->owned($id,$org))return NULL;$set['updated_at']=date('Y-m-d H:i:s');$this->db->where(array('id'=>$id,'organization_id'=>$org))->update('model_registry',$set);return $this->view($this->owned($id,$org));}
 public function delete_owned($id,$org){if(!$this->owned($id,$org))return FALSE;$this->db->where(array('id'=>$id,'organization_id'=>$org))->delete('model_registry');return TRUE;}
 public function set_default($id,$org){if(!$this->owned($id,$org))return FALSE;$this->db->trans_start();$this->db->where('organization_id',$org)->update('model_registry',array('is_default'=>0,'updated_at'=>date('Y-m-d H:i:s')));$this->db->where(array('id'=>$id,'organization_id'=>$org))->update('model_registry',array('is_default'=>1,'updated_at'=>date('Y-m-d H:i:s')));$this->db->trans_complete();return $this->db->trans_status();}
 public function view($r){return array('id'=>$r['id'],'organizationId'=>$r['organization_id'],'provider'=>$r['provider'],'modelId'=>$r['model_id'],'name'=>$r['name'],'version'=>$r['version'],'description'=>$r['description'],'capabilities'=>json_decode($r['capabilities'],TRUE)?:array(),'contextWindow'=>(int)$r['context_window'],'maxOutputTokens'=>(int)$r['max_output_tokens'],'costInputPer1k'=>(float)$r['cost_input_per_1k'],'costOutputPer1k'=>(float)$r['cost_output_per_1k'],'isDefault'=>(bool)$r['is_default'],'enabled'=>(bool)$r['enabled'],'config'=>json_decode($r['config'],TRUE)?:array(),'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
