<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Notification_model extends CI_Model {
 private $defaults=array('auth.login_failed','auth.new_device','billing.invoice_failed','workflow.approval_required');
 public function __construct(){parent::__construct();$this->load->database();}
 public function all($uid,$unread,$limit,$offset){$this->db->where('user_id',$uid)->where('dismissed_at IS NULL',NULL,FALSE);if($unread)$this->db->where('read_at IS NULL',NULL,FALSE);$rows=$this->db->order_by('created_at','DESC')->limit($limit,$offset)->get('notifications')->result_array();return array_map(array($this,'view'),$rows);}
 public function unread($uid){return $this->db->where('user_id',$uid)->where('read_at IS NULL',NULL,FALSE)->where('dismissed_at IS NULL',NULL,FALSE)->count_all_results('notifications');}
 public function read($id,$uid){$this->db->where(array('id'=>$id,'user_id'=>$uid))->update('notifications',array('read_at'=>date('Y-m-d H:i:s')));return $this->db->affected_rows()>0;}
 public function read_all($uid){$this->db->where('user_id',$uid)->where('read_at IS NULL',NULL,FALSE)->where('dismissed_at IS NULL',NULL,FALSE)->update('notifications',array('read_at'=>date('Y-m-d H:i:s')));return $this->db->affected_rows();}
 public function dismiss($id,$uid){$this->db->where(array('id'=>$id,'user_id'=>$uid))->update('notifications',array('dismissed_at'=>date('Y-m-d H:i:s')));return $this->db->affected_rows()>0;}
 public function preferences($uid){$rows=$this->db->where('user_id',$uid)->get('notification_preferences')->result_array();$found=array();$out=array();foreach($rows as $r){$found[$r['category']]=TRUE;$out[]=$this->pref($r);}foreach($this->defaults as $cat)if(empty($found[$cat]))$out[]=array('userId'=>$uid,'category'=>$cat,'channels'=>array('in_app'),'enabled'=>TRUE);return $out;}
 public function preference($uid,$category,$channels,$enabled){$this->db->replace('notification_preferences',array('user_id'=>$uid,'category'=>$category,'channels'=>json_encode($channels),'enabled'=>$enabled?1:0,'updated_at'=>date('Y-m-d H:i:s')));}
 public function create($uid,$org,$input){$id=$this->uuid();$this->db->insert('notifications',array('id'=>$id,'user_id'=>$uid,'organization_id'=>$org,'type'=>$input['type']??'system','title'=>$input['title'],'body'=>$input['body'],'icon'=>$input['icon']??NULL,'url'=>$input['url']??NULL,'data'=>json_encode($input['data']??array(),JSON_UNESCAPED_SLASHES),'created_at'=>date('Y-m-d H:i:s')));return $id;}
 public function view($r){return array('id'=>$r['id'],'userId'=>$r['user_id'],'organizationId'=>$r['organization_id'],'type'=>$r['type'],'title'=>$r['title'],'body'=>$r['body'],'icon'=>$r['icon'],'url'=>$r['url'],'data'=>json_decode($r['data'],TRUE)?:array(),'pushDelivered'=>(bool)$r['push_delivered'],'readAt'=>$r['read_at'],'dismissedAt'=>$r['dismissed_at'],'createdAt'=>$r['created_at']);}private function pref($r){return array('userId'=>$r['user_id'],'category'=>$r['category'],'channels'=>json_decode($r['channels'],TRUE)?:array(),'enabled'=>(bool)$r['enabled']);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
