<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Permission_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function list_for_user($uid){$user=$this->db->select('role')->where('id',$uid)->get('users')->row_array();if(!$user)return array('role'=>NULL,'permissions'=>array(),'grants'=>array());$role=$this->db->select('p.code')->from('role_permissions rp')->join('roles r','r.id=rp.role_id')->join('permissions p','p.id=rp.permission_id')->where('r.code',$user['role'])->get()->result_array();$grants=$this->db->select('up.id,p.code permission,up.resource_id resourceId')->from('user_permissions up')->join('permissions p','p.id=up.permission_id')->where('up.user_id',$uid)->get()->result_array();$codes=array_column($role,'code');foreach($grants as $g)$codes[]=$g['permission'];return array('role'=>$user['role'],'permissions'=>array_values(array_unique($codes)),'grants'=>$grants);}
 public function has($uid,$permission,$resource=NULL){$all=$this->list_for_user($uid);if(in_array('ADMIN_STAR',$all['permissions'],TRUE)||in_array($permission,$all['permissions'],TRUE)){if($resource===NULL)return TRUE;foreach($all['grants'] as $g)if($g['permission']===$permission&&($g['resourceId']===NULL||$g['resourceId']===$resource))return TRUE;return in_array($permission,array_diff($all['permissions'],array_column($all['grants'],'permission')),TRUE);}return FALSE;}
 public function catalog(){return $this->db->select('code,description')->order_by('code')->get('permissions')->result_array();}
 public function same_org($actor,$target,$org){$a=$this->db->where(array('user_id'=>$actor,'organization_id'=>$org))->count_all_results('memberships');$t=$this->db->where(array('user_id'=>$target,'organization_id'=>$org))->count_all_results('memberships');return $a>0&&$t>0;}
 public function grant($actor,$target,$permission,$resource){$p=$this->db->where('code',$permission)->get('permissions')->row_array();if(!$p)return NULL;$existing=$this->db->where(array('user_id'=>$target,'permission_id'=>$p['id'],'resource_id'=>$resource))->get('user_permissions')->row_array();if($existing)return $existing;$row=array('id'=>$this->uuid(),'user_id'=>$target,'permission_id'=>$p['id'],'resource_id'=>$resource,'granted_by'=>$actor,'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('user_permissions',$row);return $row;}
 public function revoke($id,$org){$row=$this->db->select('up.id,m.organization_id')->from('user_permissions up')->join('memberships m','m.user_id=up.user_id')->where('up.id',$id)->where('m.organization_id',$org)->get()->row_array();if(!$row)return FALSE;$this->db->where('id',$id)->delete('user_permissions');return TRUE;}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
