<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Plugin_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function all($org){$system=$this->db->select('p.*,COALESCE(o.enabled,p.enabled) effective_enabled',FALSE)->from('plugins p')->join('plugin_overrides o','o.plugin_id=p.id AND o.organization_id='.$this->db->escape($org),'left')->where('p.is_system',1)->order_by('p.name')->get()->result_array();$custom=$this->db->where('organization_id',$org)->where('is_system',0)->order_by('created_at','DESC')->get('plugins')->result_array();foreach($system as &$r)$r['enabled']=$r['effective_enabled'];return array('system'=>array_map(array($this,'view'),$system),'custom'=>array_map(array($this,'view'),$custom));}
 public function create($org,$d){if($this->db->where(array('organization_id'=>$org,'slug'=>$d['slug']))->count_all_results('plugins'))return NULL;$now=date('Y-m-d H:i:s');$row=array('id'=>$this->uuid(),'organization_id'=>$org,'slug'=>$d['slug'],'name'=>$d['name'],'description'=>$d['description']??NULL,'version'=>$d['version'],'author'=>$d['author']??NULL,'enabled'=>1,'hooks'=>json_encode($d['hooks']),'config'=>json_encode($d['config'],JSON_UNESCAPED_SLASHES),'is_system'=>0,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('plugins',$row);return $this->view($row);}
 public function find_accessible($id,$org){return $this->db->group_start()->where('organization_id',$org)->or_where('is_system',1)->group_end()->where('id',$id)->get('plugins')->row_array();}
 public function toggle($id,$org,$enabled){$p=$this->find_accessible($id,$org);if(!$p)return NULL;if($p['is_system']){$this->db->replace('plugin_overrides',array('organization_id'=>$org,'plugin_id'=>$id,'enabled'=>$enabled?1:0,'updated_at'=>date('Y-m-d H:i:s')));$p['enabled']=$enabled?1:0;}else{$this->db->where(array('id'=>$id,'organization_id'=>$org))->update('plugins',array('enabled'=>$enabled?1:0,'updated_at'=>date('Y-m-d H:i:s')));$p['enabled']=$enabled?1:0;}return $this->view($p);}
 public function configure($id,$org,$config){$p=$this->db->where(array('id'=>$id,'organization_id'=>$org,'is_system'=>0))->get('plugins')->row_array();if(!$p)return NULL;$p['config']=json_encode($config,JSON_UNESCAPED_SLASHES);$p['updated_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update('plugins',array('config'=>$p['config'],'updated_at'=>$p['updated_at']));return $this->view($p);}
 public function delete_owned($id,$org){$p=$this->db->where(array('id'=>$id,'organization_id'=>$org,'is_system'=>0))->count_all_results('plugins');if(!$p)return FALSE;$this->db->where('id',$id)->delete('plugins');return TRUE;}
 public function view($r){return array('id'=>$r['id'],'slug'=>$r['slug'],'name'=>$r['name'],'description'=>$r['description'],'version'=>$r['version'],'author'=>$r['author'],'enabled'=>(bool)$r['enabled'],'hooks'=>json_decode($r['hooks'],TRUE)?:array(),'config'=>json_decode($r['config'],TRUE)?:array(),'isSystem'=>(bool)$r['is_system'],'createdAt'=>$r['created_at']);}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
