<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Prompt_template_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function seed($org,$uid){if($this->db->where(array('organization_id'=>$org,'is_built_in'=>1))->count_all_results('prompt_templates'))return;$rows=array(array('Summarize text','general','📝','Summarize the following text in 3 bullet points:\n\n{{text}}','Produce a concise TL;DR.'),array("Explain like I'm 5",'general','🧸','Explain the following topic to me as if I were 5 years old:\n\n{{topic}}','Simple explanations.'),array('Code review','coding','🔍','Review the following code for bugs, performance issues, and style problems:\n\n{{code}}','Review code for issues.'),array('Draft an email','writing','✉️','Draft a professional email about:\n\n{{topic}}\n\nTone: {{tone|professional}}','Write a polished email.'),array('Brainstorm','creative','💡','Brainstorm 10 creative ideas for:\n\n{{topic}}','Generate ideas quickly.'));foreach($rows as $x)$this->create($org,$uid,array('title'=>$x[0],'category'=>$x[1],'icon'=>$x[2],'content'=>$x[3],'description'=>$x[4]),TRUE);}
 public function listing($org,$category,$q,$limit){$this->db->where('organization_id',$org);if($category)$this->db->where('category',$category);if($q)$this->db->group_start()->like('title',$q)->or_like('content',$q)->or_like('description',$q)->group_end();return array_map(array($this,'view'),$this->db->order_by('is_built_in','DESC')->order_by('usage_count','DESC')->order_by('title')->limit($limit)->get('prompt_templates')->result_array());}
 public function one($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('prompt_templates')->row_array();return $r?$this->view($r):NULL;}
 public function create($org,$uid,$d,$built=FALSE){$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'organization_id'=>$org,'title'=>trim($d['title']),'description'=>$d['description']??NULL,'content'=>$d['content'],'category'=>$d['category']??'general','icon'=>$d['icon']??NULL,'created_by_id'=>$uid,'is_built_in'=>$built?1:0,'usage_count'=>0,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('prompt_templates',$r);return $this->view($r);}
 public function update_template($id,$org,$d){$raw=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('prompt_templates')->row_array();if(!$raw)return array(NULL,'missing');if($raw['is_built_in'])return array(NULL,'built_in');$map=array('title'=>'title','description'=>'description','content'=>'content','category'=>'category','icon'=>'icon');$set=array('updated_at'=>date('Y-m-d H:i:s'));foreach($map as $i=>$o)if(array_key_exists($i,$d))$set[$o]=$d[$i];$this->db->where('id',$id)->update('prompt_templates',$set);return array($this->one($id,$org),NULL);}
 public function remove($id,$org){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('prompt_templates')->row_array();if(!$r)return 'missing';if($r['is_built_in'])return 'built_in';$this->db->where('id',$id)->delete('prompt_templates');return NULL;}
 public function use_template($id,$org,$uid,$vars){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('prompt_templates')->row_array();if(!$r)return NULL;$missing=array();$rendered=preg_replace_callback('/\{\{\s*(\w+)\s*(?:\|\s*([^}]*?)\s*)?\}\}/',function($m)use($vars,&$missing){if(array_key_exists($m[1],$vars))return (string)$vars[$m[1]];if(isset($m[2]))return $m[2];if(!in_array($m[1],$missing,TRUE))$missing[]=$m[1];return '';},$r['content']);$this->db->where('id',$id)->set('usage_count','usage_count+1',FALSE)->update('prompt_templates');$this->db->insert('prompt_template_uses',array('organization_id'=>$org,'template_id'=>$id,'user_id'=>$uid,'used_at'=>date('Y-m-d H:i:s')));return array('template'=>$this->view($r),'rendered'=>$rendered,'unresolved'=>$missing);}
 public function duplicate($id,$org,$uid,$title){$r=$this->db->where(array('id'=>$id,'organization_id'=>$org))->get('prompt_templates')->row_array();if(!$r)return NULL;$title=$title?:mb_substr($r['title'],0,193).' (copy)';return $this->create($org,$uid,array('title'=>$title,'description'=>$r['description'],'content'=>$r['content'],'category'=>$r['category'],'icon'=>$r['icon']));}
 public function stats($org,$days){$rows=$this->db->where('organization_id',$org)->get('prompt_templates')->result_array();$since=date('Y-m-d H:i:s',time()-($days-1)*86400);$uses=$this->db->where('organization_id',$org)->where('used_at >=',$since)->count_all_results('prompt_template_uses');$daily=$this->db->select('DATE(used_at) day,COUNT(*) uses',FALSE)->where('organization_id',$org)->where('used_at >=',$since)->group_by('DATE(used_at)')->order_by('day')->get('prompt_template_uses')->result_array();$start=$this->db->select_min('used_at','v')->where('organization_id',$org)->get('prompt_template_uses')->row_array();$total=0;$built=0;foreach($rows as $r){$total+=(int)$r['usage_count'];$built+=(int)$r['is_built_in'];}return array('windowDays'=>$days,'generatedAt'=>date('c'),'totalTemplates'=>count($rows),'builtInTemplates'=>$built,'userTemplates'=>count($rows)-$built,'totalUses'=>$total,'ledgerAvailable'=>TRUE,'ledgerStart'=>$start['v'],'usesInWindow'=>$uses,'distinctUseDays'=>count($daily),'ledgerCoveredDays'=>$start['v']?min($days,max(1,(int)ceil((time()-strtotime($start['v']))/86400)+1)):0,'avgUsesPerDay'=>$start['v']?floor($uses/min($days,max(1,(int)ceil((time()-strtotime($start['v']))/86400)+1))*100)/100:NULL,'topTemplates'=>array(),'recentTemplates'=>array(),'daily'=>array_map(function($x){return array('day'=>$x['day'],'uses'=>(int)$x['uses']);},$daily),'note'=>'Window counts and lifetime counts are persisted in MySQL; days without recorded use are absent.');}
 private function view($r){return array('id'=>$r['id'],'organizationId'=>$r['organization_id'],'title'=>$r['title'],'description'=>$r['description'],'content'=>$r['content'],'category'=>$r['category'],'icon'=>$r['icon'],'createdById'=>$r['created_by_id'],'isBuiltIn'=>(bool)$r['is_built_in'],'usageCount'=>(int)$r['usage_count'],'createdAt'=>$r['created_at'],'updatedAt'=>$r['updated_at']);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
