<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Share_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();$this->load->model('Conversation_model','conversations');}
 public function all($cid,$uid,$org){if(!$this->conversations->get($cid,$uid,$org))return NULL;$rows=$this->db->where('conversation_id',$cid)->order_by('created_at','DESC')->get('conversation_shares')->result_array();return array_map(array($this,'view'),$rows);}
 public function create($cid,$uid,$org,$d){if(!$this->conversations->get($cid,$uid,$org))return NULL;$now=date('Y-m-d H:i:s');$r=array('id'=>$this->uuid(),'conversation_id'=>$cid,'created_by_id'=>$uid,'token'=>bin2hex(random_bytes(32)),'access_mode'=>$d['access'],'permissions'=>$d['permissions'],'allowed'=>json_encode($d['allowed']),'password_hash'=>!empty($d['password'])?password_hash($d['password'],PASSWORD_DEFAULT):NULL,'expires_at'=>!empty($d['expiresAt'])?date('Y-m-d H:i:s',strtotime($d['expiresAt'])):NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('conversation_shares',$r);return $this->view($r);}
 public function mutate($cid,$sid,$uid,$org,$d){if(!$this->conversations->get($cid,$uid,$org))return NULL;$r=$this->db->where(array('id'=>$sid,'conversation_id'=>$cid))->get('conversation_shares')->row_array();if(!$r)return NULL;$set=array('updated_at'=>date('Y-m-d H:i:s'));$map=array('access'=>'access_mode','permissions'=>'permissions');foreach($map as $i=>$o)if(array_key_exists($i,$d))$set[$o]=$d[$i];if(array_key_exists('allowed',$d))$set['allowed']=json_encode($d['allowed']);if(array_key_exists('password',$d))$set['password_hash']=$d['password']?password_hash($d['password'],PASSWORD_DEFAULT):NULL;if(array_key_exists('expiresAt',$d))$set['expires_at']=$d['expiresAt']?date('Y-m-d H:i:s',strtotime($d['expiresAt'])):NULL;if(isset($d['_enabled']))$set['revoked_at']=$d['_enabled']?NULL:date('Y-m-d H:i:s');$this->db->where('id',$sid)->update('conversation_shares',$set);return $this->view(array_merge($r,$set));}
 public function delete_share($cid,$sid,$uid,$org){if(!$this->conversations->get($cid,$uid,$org))return FALSE;$this->db->where(array('id'=>$sid,'conversation_id'=>$cid))->delete('conversation_shares');return $this->db->affected_rows()>0;}
 public function logs($cid,$sid,$uid,$org){if(!$this->conversations->get($cid,$uid,$org))return NULL;$rows=$this->db->where('share_id',$sid)->order_by('created_at','DESC')->limit(100)->get('conversation_share_access')->result_array();return array_map(function($r){return array('id'=>(string)$r['id'],'shareId'=>$r['share_id'],'userId'=>$r['user_id'],'ipAddress'=>$r['ip_address'],'userAgent'=>$r['user_agent'],'granted'=>(bool)$r['granted'],'reason'=>$r['reason'],'createdAt'=>$r['created_at']);},$rows);}
 public function resolve($token,$password,$auth){$r=$this->db->where('token',$token)->get('conversation_shares')->row_array();if(!$r)return array(NULL,'not_found',404);$conv=$this->db->where('id',$r['conversation_id'])->where('deleted_at IS NULL',NULL,FALSE)->get('conversations')->row_array();if(!$conv)return $this->denied($r,$auth,'conversation_deleted',404);if($r['revoked_at'])return $this->denied($r,$auth,'revoked',403);if($r['expires_at']&&strtotime($r['expires_at'])<time())return $this->denied($r,$auth,'expired',403);if($r['password_hash']&&!$password)return $this->denied($r,$auth,'password_required',401);if($r['password_hash']&&!password_verify($password,$r['password_hash']))return $this->denied($r,$auth,'invalid_password',401);$allowed=json_decode($r['allowed'],TRUE)?:array();$owner=$auth&&$auth['sub']===$r['created_by_id'];$orgMember=$auth&&$this->db->where(array('user_id'=>$auth['sub'],'organization_id'=>$conv['organization_id']))->count_all_results('memberships')>0;$listed=$auth&&(in_array($auth['sub'],$allowed,TRUE)||in_array($auth['email']??'',$allowed,TRUE));$granted=$r['access_mode']==='anyone_with_link'||($r['access_mode']==='organization'&&$orgMember)||($r['access_mode']==='restricted'&&$orgMember&&($owner||$listed))||($r['access_mode']==='specific'&&($owner||$listed));if(!$granted)return $this->denied($r,$auth,'access_denied',403);$this->record($r,$auth,TRUE,$r['access_mode']);$this->db->where('id',$r['id'])->set('access_count','access_count+1',FALSE)->set('last_accessed_at',date('Y-m-d H:i:s'))->update('conversation_shares');$msgs=$this->db->where('conversation_id',$conv['id'])->where_in('role',array('USER','ASSISTANT'))->order_by('created_at')->get('messages')->result_array();$ownerRow=$this->db->where('id',$r['created_by_id'])->get('users')->row_array();$mv=array();foreach($msgs as $m)$mv[]=array('id'=>$m['id'],'role'=>strtolower($m['role']),'author'=>$m['role']==='USER'?'User':'Assistant','content'=>$m['content'],'createdAt'=>$m['created_at'],'redacted'=>FALSE);return array(array('conversationId'=>$conv['id'],'title'=>$conv['title'],'summary'=>$conv['summary'],'permissions'=>$r['permissions'],'ownerName'=>$ownerRow['display_name']?:$ownerRow['email'],'createdAt'=>$conv['created_at'],'lastMessageAt'=>$conv['last_message_at'],'messages'=>$mv),NULL,200);}
 private function denied($r,$auth,$reason,$status){$this->record($r,$auth,FALSE,$reason);return array(NULL,$reason,$status);}private function record($r,$auth,$ok,$reason){$this->db->insert('conversation_share_access',array('share_id'=>$r['id'],'user_id'=>$auth['sub']??NULL,'ip_address'=>$this->input->ip_address(),'user_agent'=>substr((string)$this->input->user_agent(),0,500),'granted'=>$ok?1:0,'reason'=>$reason,'created_at'=>date('Y-m-d H:i:s')));}
 public function view($r){return array('id'=>$r['id'],'conversationId'=>$r['conversation_id'],'token'=>$r['token'],'access'=>$r['access_mode'],'permissions'=>$r['permissions'],'allowed'=>json_decode($r['allowed'],TRUE)?:array(),'hasPassword'=>!empty($r['password_hash']),'expiresAt'=>$r['expires_at']??NULL,'revokedAt'=>$r['revoked_at']??NULL,'lastAccessedAt'=>$r['last_accessed_at']??NULL,'accessCount'=>(int)($r['access_count']??0),'createdAt'=>$r['created_at'],'url'=>'/share/'.$r['token']);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
