<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Sso_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function get($org){$r=$this->db->where('organization_id',$org)->get('sso_configs')->row_array();return $r?$this->safe($r):array('configured'=>FALSE,'provider'=>NULL,'domains'=>array(),'enabled'=>FALSE);}
 public function save($org,$d){$old=$this->db->where('organization_id',$org)->get('sso_configs')->row_array();$now=date('Y-m-d H:i:s');$row=array('provider'=>$d['provider'],'entry_point'=>$d['entryPoint']??NULL,'issuer'=>$d['issuer']??NULL,'client_id'=>$d['clientId']??NULL,'domains'=>json_encode(array_values($d['domains']),JSON_UNESCAPED_SLASHES),'enabled'=>$d['enabled']?1:0,'updated_at'=>$now);if(!empty($d['cert']))$row['certificate']=$this->seal($d['cert']);elseif(!$old)$row['certificate']=NULL;if(!empty($d['clientSecret']))$row['client_secret']=$this->seal($d['clientSecret']);elseif(!$old)$row['client_secret']=NULL;if($old){$this->db->where('organization_id',$org)->update('sso_configs',$row);}else{$row['id']=$this->uuid();$row['organization_id']=$org;$row['created_at']=$now;$this->db->insert('sso_configs',$row);}$saved=$this->db->where('organization_id',$org)->get('sso_configs')->row_array();return $this->safe($saved);}
 public function disable($org){if(!$this->db->where('organization_id',$org)->count_all_results('sso_configs'))return FALSE;$this->db->where('organization_id',$org)->update('sso_configs',array('enabled'=>0,'updated_at'=>date('Y-m-d H:i:s')));return TRUE;}
 public function lookup($email){$parts=explode('@',strtolower(trim($email)));if(count($parts)!==2)return NULL;$domain=$parts[1];$rows=$this->db->where('enabled',1)->get('sso_configs')->result_array();foreach($rows as $r){$domains=json_decode($r['domains'],TRUE)?:array();if(in_array($domain,$domains,TRUE))return array('provider'=>$r['provider'],'entryPoint'=>$r['entry_point'],'clientId'=>$r['client_id']);}return NULL;}
 private function safe($r){$secret=$this->open($r['client_secret']);return array('configured'=>TRUE,'id'=>$r['id'],'provider'=>$r['provider'],'domains'=>json_decode($r['domains'],TRUE)?:array(),'enabled'=>(bool)$r['enabled'],'hasEntryPoint'=>!empty($r['entry_point']),'hasCert'=>!empty($r['certificate'])&&$this->open($r['certificate'])!==NULL,'hasClientId'=>!empty($r['client_id']),'hasClientSecret'=>$secret!==NULL,'clientSecretMasked'=>$secret?$this->mask($secret):NULL);}
 private function mask($s){$n=strlen($s);return $n<=4?str_repeat('•',$n):substr($s,0,2).str_repeat('•',max(4,$n-4)).substr($s,-2);}
 private function seal($v){$iv=random_bytes(12);$tag='';$c=openssl_encrypt($v,'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,$tag);if($c===FALSE)throw new RuntimeException('SSO encryption failed');return 'enc.v1|'.base64_encode($iv.$tag.$c);}
 private function open($v){if(!$v||strpos($v,'enc.v1|')!==0)return NULL;$b=base64_decode(substr($v,7),TRUE);if(!$b||strlen($b)<29)return NULL;$r=openssl_decrypt(substr($b,28),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,substr($b,0,12),substr($b,12,16));return $r===FALSE?NULL:$r;}
 private function key(){return hash('sha256',(string)getenv('VP_ENCRYPTION_KEY'),TRUE);}private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
