<?php defined('BASEPATH') OR exit('No direct script access allowed');
class User_model extends CI_Model {
 public function __construct(){ parent::__construct(); $this->load->database(); }
 public function find_identifier($v){ return $this->db->group_start()->where('email',strtolower($v))->or_where('username',$v)->or_where('public_user_id',$v)->group_end()->get('users')->row_array(); }
 public function find($id){ return $this->db->where('id',$id)->get('users')->row_array(); }
 public function create_account($d){ $this->db->trans_start(); $uid=$this->uuid(); $oid=$this->uuid(); $slug=$this->slug($d['organizationName']).'-'.substr(str_replace('-','',$oid),0,8); $now=date('Y-m-d H:i:s'); $this->db->insert('organizations',array('id'=>$oid,'name'=>$d['organizationName'],'slug'=>$slug,'created_at'=>$now,'updated_at'=>$now)); $wid=$this->uuid(); $this->db->insert('workspaces',array('id'=>$wid,'organization_id'=>$oid,'name'=>'Main Workspace','slug'=>'main','created_at'=>$now,'updated_at'=>$now)); $user=array('id'=>$uid,'email'=>strtolower($d['email']),'username'=>$d['username']??NULL,'public_user_id'=>'WND-'.strtoupper(substr(str_replace('-','',$uid),0,12)),'password_hash'=>password_hash($d['password'],PASSWORD_DEFAULT),'display_name'=>$d['displayName'],'role'=>'ADMIN','created_at'=>$now,'updated_at'=>$now); $this->db->insert('users',$user); $this->db->insert('memberships',array('id'=>$this->uuid(),'user_id'=>$uid,'organization_id'=>$oid,'role'=>'OWNER','joined_at'=>$now)); $this->db->trans_complete(); if(!$this->db->trans_status()) throw new RuntimeException('Account could not be created'); return array($user,array('id'=>$oid,'name'=>$d['organizationName'],'slug'=>$slug)); }
 public function membership($uid){ return $this->db->select('o.id,o.name,o.slug')->from('memberships m')->join('organizations o','o.id=m.organization_id')->where('m.user_id',$uid)->order_by('m.joined_at','ASC')->limit(1)->get()->row_array(); }
 public function refresh_create($uid,$raw,$expires){ $this->db->insert('refresh_tokens',array('id'=>$this->uuid(),'user_id'=>$uid,'token_hash'=>hash('sha256',$raw),'expires_at'=>date('Y-m-d H:i:s',$expires),'created_at'=>date('Y-m-d H:i:s'))); }
 public function refresh_consume($raw){ $hash=hash('sha256',$raw); $row=$this->db->where('token_hash',$hash)->where('revoked_at IS NULL',NULL,FALSE)->where('expires_at >',date('Y-m-d H:i:s'))->get('refresh_tokens')->row_array(); if($row)$this->db->where('id',$row['id'])->update('refresh_tokens',array('revoked_at'=>date('Y-m-d H:i:s'))); return $row; }
 public function revoke_user($uid){ $this->db->where('user_id',$uid)->where('revoked_at IS NULL',NULL,FALSE)->update('refresh_tokens',array('revoked_at'=>date('Y-m-d H:i:s'))); }
 private function uuid(){ $b=random_bytes(16); $b[6]=chr((ord($b[6])&15)|64); $b[8]=chr((ord($b[8])&63)|128); return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
 private function slug($s){ return trim(preg_replace('/[^a-z0-9]+/','-',strtolower($s)),'-')?:'organization'; }

 public function create_password_reset($uid,$raw){$this->db->where('user_id',$uid)->where('used_at IS NULL',NULL,FALSE)->update('password_reset_tokens',array('used_at'=>date('Y-m-d H:i:s')));$this->db->insert('password_reset_tokens',array('id'=>$this->uuid(),'user_id'=>$uid,'token_hash'=>hash('sha256',$raw),'expires_at'=>date('Y-m-d H:i:s',time()+3600),'created_at'=>date('Y-m-d H:i:s')));}
 public function consume_password_reset($raw){$hash=hash('sha256',$raw);$this->db->trans_start();$r=$this->db->where('token_hash',$hash)->where('used_at IS NULL',NULL,FALSE)->where('expires_at >',date('Y-m-d H:i:s'))->get('password_reset_tokens')->row_array();if($r)$this->db->where('id',$r['id'])->update('password_reset_tokens',array('used_at'=>date('Y-m-d H:i:s')));$this->db->trans_complete();return $r;}
 public function set_password($uid,$password){$this->db->where('id',$uid)->update('users',array('password_hash'=>password_hash($password,PASSWORD_DEFAULT),'updated_at'=>date('Y-m-d H:i:s')));$this->revoke_user($uid);}
}
