<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Workspace_model extends CI_Model {
 public function __construct(){parent::__construct();$this->load->database();}
 public function context($uid,$oid){$org=$this->db->where('id',$oid)->get('organizations')->row_array();$ws=$this->db->where('organization_id',$oid)->order_by('created_at')->get('workspaces')->row_array();return array($org,$ws);}
 public function tasks($oid,$limit=50,$offset=0,$status=NULL,$q=NULL){$this->db->where('organization_id',$oid);if($status)$this->db->where('status',$status);if($q)$this->db->like('title',$q);$total=$this->db->count_all_results('tasks',FALSE);$rows=$this->db->order_by('created_at','DESC')->limit($limit,$offset)->get()->result_array();return array($rows,$total);}
 public function create_task($oid,$wid,$uid,$d){$id=$this->uuid();$now=date('Y-m-d H:i:s');$row=array('id'=>$id,'organization_id'=>$oid,'workspace_id'=>$wid,'creator_id'=>$uid,'title'=>trim($d['title']),'description'=>$d['description']??NULL,'priority'=>$d['priority']??'MEDIUM','status'=>'TODO','progress'=>0,'due_date'=>isset($d['dueDate'])?date('Y-m-d H:i:s',strtotime($d['dueDate'])):NULL,'created_at'=>$now,'updated_at'=>$now);$this->db->insert('tasks',$row);$this->activity($oid,$wid,$uid,'TASK_CREATED','created task "'.$row['title'].'"',array('taskId'=>$id));return $row;}
 public function update_task($id,$oid,$uid,$wid,$d){$row=$this->db->where(array('id'=>$id,'organization_id'=>$oid))->get('tasks')->row_array();if(!$row)return NULL;$set=array('updated_at'=>date('Y-m-d H:i:s'));if(isset($d['status']))$set['status']=$d['status'];if(isset($d['progress']))$set['progress']=(int)$d['progress'];if(($set['status']??'')==='DONE'){$set['progress']=100;$set['completed_at']=date('Y-m-d H:i:s');}$this->db->where('id',$id)->update('tasks',$set);$new=array_merge($row,$set);$this->activity($oid,$wid,$uid,($new['status']==='DONE'?'TASK_COMPLETED':'TASK_UPDATED'),'moved "'.$new['title'].'" to '.strtolower(str_replace('_',' ',$new['status'])),array('taskId'=>$id,'status'=>$new['status']));return $new;}
 public function activities($oid){return $this->db->where('organization_id',$oid)->order_by('created_at','DESC')->limit(20)->get('activities')->result_array();}
 private function activity($oid,$wid,$uid,$type,$message,$meta){$this->db->insert('activities',array('organization_id'=>$oid,'workspace_id'=>$wid,'user_id'=>$uid,'type'=>$type,'message'=>$message,'metadata'=>json_encode($meta),'created_at'=>date('Y-m-d H:i:s')));}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
