import { randomUUID } from "node:crypto";
import { redisCmd as redis } from "../db/redis.js";
import type { Logger } from "pino";
import type { OpexDashboard } from "@windels/shared";
import { AppError } from "../utils/result.js";
const K = { meta: (oid: string) => `opex:${oid}:meta`, alerts: (oid: string) => `opex:${oid}:safety-alerts` };
type Alert = { id: string; category: string; severity: "info" | "warning" | "critical"; source: string; message: string; model?: string; at: string; status: "open" | "acknowledged" | "resolved"; acknowledgedBy?: string; resolvedBy?: string; note?: string };
async function list(oid: string): Promise<Alert[]> { const raw = await redis.get(K.alerts(oid)); try { return raw ? JSON.parse(raw) : []; } catch { return []; } }
async function save(oid: string, alerts: Alert[]) { await redis.set(K.alerts(oid), JSON.stringify(alerts)); }
export const OpexService = {
  async ensureBootstrapped(logger?: Logger, oid = "org-windels") { if (!(await redis.exists(K.meta(oid)))) { await redis.set(K.meta(oid), "1"); logger?.info({ msg: "[opex] safety register initialized", organizationId: oid }); } },
  async createAlert(oid: string, input: Omit<Alert, "id" | "at" | "status">) { await this.ensureBootstrapped(undefined, oid); const alerts = await list(oid); const alert: Alert = { ...input, id: `safety-${randomUUID()}`, at: new Date().toISOString(), status: "open" }; alerts.push(alert); await save(oid, alerts); return alert; },
  async updateAlert(oid: string, id: string, actorId: string, status: "acknowledged" | "resolved", note?: string) { const alerts = await list(oid); const i = alerts.findIndex((a) => a.id === id); if (i < 0) throw AppError.notFound("Safety alert not found"); const old = alerts[i]!; if (old.status === "resolved") throw AppError.conflict("Safety alert is already resolved"); const alert = { ...old, status, note: note ?? old.note, ...(status === "acknowledged" ? { acknowledgedBy: actorId } : { resolvedBy: actorId }) }; alerts[i] = alert; await save(oid, alerts); return alert; },
  async dashboard(oid: string): Promise<OpexDashboard> { await this.ensureBootstrapped(undefined, oid); const alerts = await list(oid); const open = alerts.filter((a) => a.status !== "resolved"); return { trust: { trust: 0, alignment: 0, safety: 0, compliance: 0, transparency: 0, explainability: 0, reliability: 0, hallucinationRisk: 0, evidenceQuality: 0, dataFreshnessHours: 0, humanApprovalRate: 0, operationalStability: 0 }, safety: { passRate: 0, alertsOpen: open.length, alertsCritical: open.filter((a) => a.severity === "critical").length, mitigations24h: 0, auditsCompleted: 0, benchmarks: {} }, regulations: { tracked: 0, changed30d: 0, openGaps: 0, upcoming: 0 }, playbooks: { total: 0, active: 0, simulating: 0, avgCompliancePct: 0 }, explanations: { available24h: 0, avgEvidence: 0, avgConfidence: 0, challenged: 0, challengedUpheld: 0 }, governance: { gates: [], pendingTotal: 0, emergencyShutdowns: 0, overrides24h: 0 }, continuous: { kpis: [], bottlenecks: [], maturityScore: 0 }, recentAlerts: alerts, recentRegulations: [], recentExplanations: [], collaborationSessionsActive: 0, decisionsRequiringHuman: 0 } as OpexDashboard; },
};
