<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Account extends MY_Controller {
 private $uid,$org;
 public function __construct(){parent::__construct();$c=$this->require_auth();if(!$c){$this->output->_display();exit;}$this->uid=$c['sub'];$this->org=$c['organizationId']??NULL;$this->load->model('Account_model','accounts');}
 public function index(){return $this->respond($this->accounts->snapshot($this->uid));}
 public function username(){$d=$this->body();$v=trim($d['username']??'');if(!preg_match('/^[a-zA-Z0-9._-]{3,30}$/',$v))return $this->fail('VALIDATION_ERROR','Invalid username',422);if($this->accounts->username_exists($v,$this->uid))return $this->fail('CONFLICT','Username is already used',409);$r=$this->accounts->update($this->uid,array('username'=>$v));$this->audit('account.username_changed');return $this->respond($r);}
 public function email(){$d=$this->body();$v=strtolower(trim($d['email']??''));if(!filter_var($v,FILTER_VALIDATE_EMAIL))return $this->fail('VALIDATION_ERROR','Invalid email',422);if($this->accounts->email_exists($v,$this->uid))return $this->fail('CONFLICT','Email is already used',409);$raw=bin2hex(random_bytes(24));$r=$this->accounts->update($this->uid,array('pending_email'=>$v,'email_change_token_hash'=>hash('sha256',$raw),'email_change_expires_at'=>date('Y-m-d H:i:s',time()+3600)));$r['verificationSent']=FALSE;if(ENVIRONMENT!=='production')$r['verificationToken']=$raw;$this->audit('account.email_change_requested');return $this->respond($r);}
 public function confirm_email(){$d=$this->body();$u=$this->accounts->user($this->uid);if(empty($d['token'])||empty($u['email_change_token_hash'])||!hash_equals($u['email_change_token_hash'],hash('sha256',$d['token']))||strtotime($u['email_change_expires_at'])<time())return $this->fail('INVALID_TOKEN','Email confirmation token is invalid or expired',422);$r=$this->accounts->update($this->uid,array('email'=>$u['pending_email'],'pending_email'=>NULL,'email_change_token_hash'=>NULL,'email_change_expires_at'=>NULL));$this->audit('account.email_changed');return $this->respond($r);}
 public function password(){$d=$this->body();$u=$this->accounts->user($this->uid);if(!password_verify($d['currentPassword']??'',$u['password_hash']))return $this->fail('INVALID_CREDENTIALS','Current password is incorrect',401);if(($d['newPassword']??'')!==($d['confirmPassword']??'')||strlen($d['newPassword']??'')<10)return $this->fail('VALIDATION_ERROR','New passwords must match and contain at least 10 characters',422);$this->accounts->update($this->uid,array('password_hash'=>password_hash($d['newPassword'],PASSWORD_DEFAULT)));$this->load->model('User_model','users');$this->users->revoke_user($this->uid);$this->audit('account.password_changed');return $this->respond(array('ok'=>TRUE));}
 public function pin(){$d=$this->body();$u=$this->accounts->user($this->uid);$new=$d['newPin']??'';if(!preg_match('/^\d{4}$/',$new)||$new!==($d['confirmPin']??''))return $this->fail('VALIDATION_ERROR','PIN must be four matching digits',422);if($u['pin_hash']&&!password_verify($d['currentPin']??'',$u['pin_hash']))return $this->fail('INVALID_PIN','Current PIN is incorrect',401);$r=$this->accounts->update($this->uid,array('pin_hash'=>password_hash($new,PASSWORD_DEFAULT),'pin_expires_at'=>date('Y-m-d H:i:s',time()+86400),'issued_pin_cipher'=>NULL,'issued_pin_expires_at'=>NULL));$this->audit('account.pin_changed');return $this->respond($r);}
 public function rotate_pin(){$pin=str_pad((string)random_int(0,9999),4,'0',STR_PAD_LEFT);$expires=time()+86400;$r=$this->accounts->update($this->uid,array('pin_hash'=>password_hash($pin,PASSWORD_DEFAULT),'pin_expires_at'=>date('Y-m-d H:i:s',$expires),'issued_pin_cipher'=>$this->seal($pin),'issued_pin_expires_at'=>date('Y-m-d H:i:s',$expires)));$this->audit('account.pin_rotated');return $this->respond(array('account'=>$r,'issuedPin'=>$pin,'deliveredByEmail'=>FALSE,'smtpConfigured'=>(bool)getenv('VP_MAIL_HOST'),'expiresAt'=>gmdate('c',$expires)));}
 public function issued_pin(){$u=$this->accounts->user($this->uid);$pin=($u['issued_pin_cipher']&&strtotime($u['issued_pin_expires_at'])>time())?$this->open($u['issued_pin_cipher']):NULL;$r=$this->accounts->update($this->uid,array('issued_pin_cipher'=>NULL,'issued_pin_expires_at'=>NULL));return $this->respond(array('issuedPin'=>$pin,'account'=>$r));}
 public function profile(){$d=$this->body();$set=array();if(isset($d['displayName'])){$v=trim($d['displayName']);if(!$v||strlen($v)>100)return $this->fail('VALIDATION_ERROR','Invalid display name',422);$set['display_name']=$v;}if(array_key_exists('avatarUrl',$d))$set['avatar_url']=$d['avatarUrl'];if(isset($d['bio'])){$set['bio']=substr($d['bio'],0,2000);}return $this->respond($this->accounts->update($this->uid,$set));}
 public function avatar(){$d=$this->body();$types=array('image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp','image/gif'=>'gif');if(!isset($types[$d['mime']??'']))return $this->fail('VALIDATION_ERROR','Unsupported image type',422);$bin=base64_decode($d['dataBase64']??'',TRUE);if($bin===FALSE||strlen($bin)>1500000)return $this->fail('VALIDATION_ERROR','Invalid or oversized image',422);$name=bin2hex(random_bytes(20)).'.'.$types[$d['mime']];if(file_put_contents(FCPATH.'assets/uploads/'.$name,$bin)===FALSE)return $this->fail('UPLOAD_FAILED','Avatar could not be written',500);return $this->respond($this->accounts->update($this->uid,array('avatar_url'=>rtrim(base_url(),'/').'/assets/uploads/'.$name)));}
 private function audit($e){$this->accounts->audit($this->uid,$this->org,$e);}
 private function key(){return hash('sha256',(string)getenv('VP_ENCRYPTION_KEY'),TRUE);}private function seal($v){$iv=random_bytes(12);$tag='';$c=openssl_encrypt($v,'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,$tag);return base64_encode($iv.$tag.$c);}private function open($v){$b=base64_decode($v,TRUE);if(!$b||strlen($b)<29)return NULL;return openssl_decrypt(substr($b,28),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,substr($b,0,12),substr($b,12,16))?:NULL;}
}
