<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Admin extends MY_Controller {
 private $c,$actor,$super;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Admin_model','admin');$this->actor=$this->admin->access($this->c['sub'],$this->c['organizationId']??NULL);if(!$this->actor){$this->fail('FORBIDDEN','Administrator access required',403);$this->output->_display();exit;}$this->super=$this->actor['role']==='SUPER_ADMIN';}
 public function stats(){return $this->respond($this->admin->stats($this->c['organizationId'],$this->super));}
 public function users(){$page=max(1,(int)($this->input->get('page')?:1));$per=min(100,max(1,(int)($this->input->get('perPage')?:25)));$f=array('q'=>trim((string)$this->input->get('q')),'role'=>$this->input->get('role'),'status'=>$this->input->get('status')?:'all');list($rows,$total)=$this->admin->users($this->c['organizationId'],$this->super,$f,$per,($page-1)*$per);return $this->respond(array('users'=>array_map(array($this,'view'),$rows),'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per))));}
 public function user($id){$u=$this->target($id);if(!$u)return;return $this->respond($this->view($u));}
 public function suspension($id){$u=$this->target($id);if(!$u)return;if($id===$this->c['sub'])return $this->fail('BAD_REQUEST','You cannot suspend your own account',400);if($u['role']==='SUPER_ADMIN')return $this->fail('FORBIDDEN','Cannot suspend a super admin',403);$d=$this->body();$s=(bool)($d['suspended']??FALSE);$u=$this->admin->update($id,array('is_suspended'=>$s?1:0,'is_active'=>$s?0:1));$this->admin->audit($this->c['organizationId'],$this->c['sub'],$s?'admin.user.suspend':'admin.user.unsuspend',$id);return $this->respond(array('id'=>$id,'isActive'=>(bool)$u['is_active'],'isSuspended'=>(bool)$u['is_suspended']));}
 public function role($id){if(!$this->super)return $this->fail('FORBIDDEN','Only super admins can change roles',403);if($id===$this->c['sub'])return $this->fail('BAD_REQUEST','You cannot change your own role',400);$u=$this->target($id);if(!$u)return;$d=$this->body();$role=strtoupper($d['role']??'');if(!in_array($role,array('USER','ADMIN','SUPER_ADMIN'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid role',422);$this->admin->update($id,array('role'=>$role));$this->admin->audit(NULL,$this->c['sub'],'admin.user.role_changed',$id,array('newRole'=>strtolower($role)));return $this->respond(array('id'=>$id,'role'=>strtolower($role)));}
 public function pin_reset($id){if(!$this->target($id))return;$pin=str_pad((string)random_int(0,9999),4,'0',STR_PAD_LEFT);$exp=time()+86400;$this->admin->update($id,array('pin_hash'=>password_hash($pin,PASSWORD_DEFAULT),'pin_expires_at'=>date('Y-m-d H:i:s',$exp)));$this->admin->audit($this->c['organizationId'],$this->c['sub'],'admin.user.pin_reset',$id);return $this->respond(array('id'=>$id,'issuedPin'=>$pin,'expiresAt'=>gmdate('c',$exp)));}
 public function password_reset($id){if(!$this->target($id))return;$password=$this->random_password();$this->admin->update($id,array('password_hash'=>password_hash($password,PASSWORD_DEFAULT)));$this->load->model('User_model','usersModel');$this->usersModel->revoke_user($id);$this->admin->audit($this->c['organizationId'],$this->c['sub'],'admin.user.password_reset',$id);return $this->respond(array('id'=>$id,'temporaryPassword'=>$password,'mustChangePassword'=>TRUE));}
 public function impersonate($id){$u=$this->target($id);if(!$u)return;if($id===$this->c['sub'])return $this->fail('BAD_REQUEST','Cannot impersonate yourself',400);$org=$this->super?($this->admin->in_org($id,$this->c['organizationId'])?$this->c['organizationId']:NULL):$this->c['organizationId'];$token=$this->token(array('sub'=>$u['id'],'email'=>$u['email'],'role'=>strtolower($u['role']),'organizationId'=>$org,'impersonatorId'=>$this->c['sub']),900);$this->admin->audit($org,$this->c['sub'],'admin.user.impersonate.start',$id);return $this->respond(array('token'=>$token,'expiresIn'=>900,'user'=>$this->view($u),'impersonatorId'=>$this->c['sub']));}
 public function activity(){$page=max(1,(int)($this->input->get('page')?:1));$per=min(100,max(1,(int)($this->input->get('perPage')?:40)));list($rows,$total)=$this->admin->activity($this->c['organizationId'],$this->super,$per,($page-1)*$per);$events=array();foreach($rows as $r){$m=json_decode($r['payload'],TRUE)?:array();$events[]=array('id'=>(string)$r['id'],'action'=>$r['event_type'],'actorUserId'=>$r['user_id'],'resourceId'=>$m['resourceId']??NULL,'ipAddress'=>$r['ip_address'],'createdAt'=>$r['created_at'],'metadata'=>$m);}return $this->respond(array('events'=>$events,'pagination'=>array('page'=>$page,'perPage'=>$per,'total'=>$total,'totalPages'=>(int)ceil($total/$per))));}
 public function view($u){return array('id'=>$u['id'],'email'=>$u['email'],'publicUserId'=>$u['public_user_id'],'username'=>$u['username'],'role'=>strtolower($u['role']),'isActive'=>(bool)$u['is_active'],'isSuspended'=>(bool)$u['is_suspended'],'pinSet'=>!empty($u['pin_hash']),'pinExpired'=>empty($u['pin_expires_at'])||strtotime($u['pin_expires_at'])<=time(),'createdAt'=>$u['created_at'],'profile'=>array('displayName'=>$u['display_name']));}
 private function target($id){$u=$this->admin->target($id,$this->c['organizationId'],$this->super);if(!$u){$this->fail('NOT_FOUND','User not found',404);return NULL;}return $u;}private function random_password(){return rtrim(strtr(base64_encode(random_bytes(18)),'+/','-_'),'=').'!9a';}
}
