<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Agents extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c)return;$this->load->model('Agent_model','agents');}
 public function index(){if($this->input->method(TRUE)==='POST'){if(!$this->valid($d=$this->body(),TRUE))return;$r=$this->agents->create($this->c['organizationId'],$d);return $this->respond($r,201);}$page=max(1,(int)$this->input->get('page'));$per=min(100,max(1,(int)($this->input->get('perPage')?:50)));$status=$this->input->get('status');if($status&&!in_array($status,array('idle','online','working','error','paused','offline'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid status',422);return $this->respond($this->agents->listing($this->c['organizationId'],trim((string)$this->input->get('q')),$status,$page,$per));}
 public function item($id){$method=$this->input->method(TRUE);if($method==='GET'){$r=$this->agents->one($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}if($method==='PATCH'){if(!$this->valid($d=$this->body(),FALSE))return;$r=$this->agents->update_agent($id,$this->c['organizationId'],$d);return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}$e=$this->agents->remove($id,$this->c['organizationId']);if(!$e){$this->output->set_status_header(204)->set_output('');return;}return $this->fail($e==='built_in'?'FORBIDDEN':'NOT_FOUND',$e==='built_in'?'Built-in agents cannot be deleted':'Agent not found',$e==='built_in'?403:404);}
 public function events($id){$page=max(1,(int)$this->input->get('page'));$per=min(100,max(1,(int)($this->input->get('perPage')?:20)));$r=$this->agents->events($id,$this->c['organizationId'],$page,$per);return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}
 public function models(){$models=array(array('id'=>getenv('VP_OPENAI_MODEL')?:'gpt-4o-mini','provider'=>'openai','displayName'=>getenv('VP_OPENAI_MODEL')?:'GPT-4o mini','capabilities'=>array('chat','tools'),'source'=>'real','healthy'=>NULL,'configured'=>(bool)getenv('VP_OPENAI_API_KEY')));return $this->respond($models);}
 private function valid($d,$create){if($create&&(!isset($d['name'],$d['role'])))return $this->fail('VALIDATION_ERROR','Name and role are required',422);foreach(array('name','role') as $f)if(isset($d[$f])&&(trim($d[$f])===''||strlen($d[$f])>64))return $this->fail('VALIDATION_ERROR','Invalid '.$f,422);if(isset($d['description'])&&strlen($d['description'])>500||isset($d['systemPrompt'])&&strlen($d['systemPrompt'])>8000)return $this->fail('VALIDATION_ERROR','Agent text exceeds its limit',422);if(isset($d['temperature'])&&($d['temperature']<0||$d['temperature']>2)||isset($d['maxTokens'])&&($d['maxTokens']<64||$d['maxTokens']>64000))return $this->fail('VALIDATION_ERROR','Invalid model settings',422);if(isset($d['capabilities'])&&(!is_array($d['capabilities'])||count($d['capabilities'])>50))return $this->fail('VALIDATION_ERROR','Invalid capabilities',422);return TRUE;}
 public function lifecycle($id){$this->load->model('Agent_extension_model','ext');if($this->input->method(TRUE)==='GET'){$r=$this->ext->lifecycle($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}$d=$this->body();if(!in_array($d['to']??'',array('ONBOARDING','ACTIVE','TRAINING','RETIRED','ARCHIVED'),TRUE)||trim($d['reason']??'')===''||strlen($d['reason'])>500)return $this->fail('VALIDATION_ERROR','A valid lifecycle state and reason are required',422);list($r,$e)=$this->ext->transition($id,$this->c['organizationId'],$this->c['sub'],$d['to'],trim($d['reason']),is_array($d['metadata']??NULL)?$d['metadata']:array());return $r?$this->respond($r):$this->fail($e==='missing'?'NOT_FOUND':'INVALID_TRANSITION',$e==='missing'?'Agent not found':'Invalid lifecycle transition', $e==='missing'?404:400);}
 public function skills($id){$this->load->model('Agent_extension_model','ext');if($this->input->method(TRUE)==='POST'){$d=$this->body();if(!$this->skill_valid($d,TRUE))return;list($r,$e)=$this->ext->save_skill($id,NULL,$this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail($e==='duplicate'?'CONFLICT':'NOT_FOUND',$e==='duplicate'?'Skill name already exists':'Agent not found',$e==='duplicate'?409:404);}$page=max(1,(int)$this->input->get('page'));$per=min(100,max(1,(int)($this->input->get('perPage')?:20)));$enabled=$this->input->get('enabled');$enabled=$enabled===NULL?NULL:filter_var($enabled,FILTER_VALIDATE_BOOLEAN);$r=$this->ext->skills($id,$this->c['organizationId'],$page,$per,$enabled);return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}
 public function skill($id,$sid){$this->load->model('Agent_extension_model','ext');$method=$this->input->method(TRUE);if($method==='GET'){$r=$this->ext->skill($id,$sid,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Skill not found',404);}if($method==='DELETE'){if($this->ext->delete_skill($id,$sid,$this->c['organizationId'])){$this->output->set_status_header(204)->set_output('');return;}return $this->fail('NOT_FOUND','Skill not found',404);}$d=$this->body();if(!$this->skill_valid($d,FALSE))return;list($r,$e)=$this->ext->save_skill($id,$sid,$this->c['organizationId'],$d);return $r?$this->respond($r):$this->fail('NOT_FOUND','Skill not found',404);}
 private function skill_valid($d,$create){if($create&&(!isset($d['name'],$d['toolName'])))return $this->fail('VALIDATION_ERROR','Name and toolName are required',422);foreach(array('name','toolName') as $f)if(isset($d[$f])&&(trim($d[$f])===''||strlen($d[$f])>64))return $this->fail('VALIDATION_ERROR','Invalid '.$f,422);if(isset($d['description'])&&strlen($d['description'])>500||isset($d['config'])&&!is_array($d['config']))return $this->fail('VALIDATION_ERROR','Invalid skill configuration',422);return TRUE;}
 public function memories($id){$this->load->model('Agent_extension_model','ext');if($this->input->method(TRUE)==='POST'){$d=$this->body();$types=array('FACT','PREFERENCE','PROCEDURE','CONVERSATION','TASK','FEEDBACK');if(trim($d['content']??'')===''||strlen($d['content'])>4000||!in_array($d['type']??'FACT',$types,TRUE)||isset($d['importance'])&&($d['importance']<0||$d['importance']>1)||isset($d['tags'])&&(!is_array($d['tags'])||count($d['tags'])>20))return $this->fail('VALIDATION_ERROR','Invalid memory',422);$r=$this->ext->add_memory($id,$this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail('NOT_FOUND','Agent not found',404);}return $this->agent_resource_list($id,'memories');}
 public function memory($id,$rid){$this->load->model('Agent_extension_model','ext');if($this->ext->delete_memory($id,$rid,$this->c['organizationId']))return $this->respond(array());return $this->fail('NOT_FOUND','Memory not found',404);}
 public function knowledge($id){$this->load->model('Agent_extension_model','ext');if($this->input->method(TRUE)==='POST'){$d=$this->body();if(trim($d['title']??'')===''||strlen($d['title'])>200||($d['content']??'')===''||strlen($d['content'])>200000||!in_array($d['type']??'SNIPPET',array('DOCUMENT','URL','SNIPPET','FILE'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid knowledge',422);$r=$this->ext->add_knowledge($id,$this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail('NOT_FOUND','Agent not found',404);}return $this->agent_resource_list($id,'knowledge');}
 public function knowledge_item($id,$rid){$this->load->model('Agent_extension_model','ext');if($this->ext->delete_knowledge($id,$rid,$this->c['organizationId']))return $this->respond(array());return $this->fail('NOT_FOUND','Knowledge not found',404);}
 private function agent_resource_list($id,$kind){$page=max(1,(int)$this->input->get('page'));$per=min(100,max(1,(int)($this->input->get('perPage')?:20)));$r=$this->ext->$kind($id,$this->c['organizationId'],$page,$per,$this->input->get('type'),trim((string)$this->input->get('q')));return $r?$this->respond($r):$this->fail('NOT_FOUND','Agent not found',404);}
}
