<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Api_governance extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Api_governance_model','governance');}
 public function endpoints(){$method=strtoupper((string)$this->input->get('method'));$version=$this->input->get('version');$service=$this->input->get('serviceId');$rows=$this->governance->endpoints();$rows=array_values(array_filter($rows,function($r)use($method,$version,$service){return (!$method||$r['method']===$method)&&(!$version||$r['version']===$version)&&(!$service||$r['serviceId']===$service);}));return $this->respond($rows);}
 public function versions(){return $this->respond($this->governance->versions());}
 public function openapi(){$spec=$this->spec();return $this->output->set_content_type('application/vnd.oai.openapi+json')->set_output(json_encode($spec,JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));}
 public function openapi_yaml(){$spec=$this->spec();return $this->output->set_content_type('application/yaml')->set_output(json_encode($spec,JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));}
 private function spec(){$paths=array();foreach($this->governance->endpoints() as $e){$paths[$e['path']][strtolower($e['method'])]=array('summary'=>$e['summary'],'deprecated'=>$e['deprecated'],'security'=>$e['authRequired']?array(array('bearerAuth'=>array())):array(),'tags'=>array($e['version']),'responses'=>array('200'=>array('description'=>'OK'),'400'=>array('description'=>'Bad Request'),'401'=>array('description'=>'Unauthorized'),'403'=>array('description'=>'Forbidden'),'404'=>array('description'=>'Not Found'),'500'=>array('description'=>'Internal Server Error')));}return array('openapi'=>'3.1.0','info'=>array('title'=>'WINDELS AI OS API','version'=>'1.0.0','description'=>'Generated from the active CodeIgniter route registry.'),'servers'=>array(array('url'=>rtrim(base_url(),'/').'/api/v1')),'paths'=>$paths,'components'=>array('securitySchemes'=>array('bearerAuth'=>array('type'=>'http','scheme'=>'bearer','bearerFormat'=>'JWT'))));}
}
