<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Apikeys extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Api_key_model','keys');}
 public function index(){if($this->input->method(TRUE)==='POST')return $this->create();$include=filter_var($this->input->get('includeRevoked'),FILTER_VALIDATE_BOOLEAN);return $this->respond($this->keys->all($this->c['organizationId'],$include));}
 public function usage(){$days=min(90,max(1,(int)($this->input->get('days')?:7)));return $this->respond($this->keys->usage($this->c['organizationId'],$days));}
 public function key($id){$method=$this->input->method(TRUE);if($method==='GET'){$r=$this->keys->get($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','API key not found',404);}if($method==='DELETE'){if(!$this->keys->delete_key($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','API key not found',404);$this->audit('admin.apikey.deleted',$id);return $this->respond(array('id'=>$id,'deleted'=>TRUE));}return $this->update($id);}
 public function revoke($id){return $this->update($id,array('revoked'=>TRUE));}
 public function rotate($id){$d=$this->body();$days=$d['expiresInDays']??NULL;if($days!==NULL&&(!is_int($days)||$days<1||$days>365))return $this->fail('VALIDATION_ERROR','Expiration must be 1–365 days',422);$r=$this->keys->rotate($id,$this->c['organizationId'],$this->c['sub'],$days);if(!$r)return $this->fail('CONFLICT','API key was not found or is already revoked',409);$this->audit('authz.api_key_rotate',$r['id'],array('previousKeyId'=>$id));return $this->respond($r,201);}
 private function create(){$d=$this->body();if(empty(trim($d['name']??''))||strlen($d['name'])>100)return $this->fail('VALIDATION_ERROR','Name is required',422);$d+=array('scopes'=>array('READ'),'granularScopes'=>array(),'appId'=>NULL,'environment'=>'production','ipRestrictions'=>array(),'expiresInDays'=>NULL);$err=$this->validate_input($d,TRUE);if($err)return $this->fail('VALIDATION_ERROR',$err,422);$r=$this->keys->create($this->c['organizationId'],$this->c['sub'],$d);$this->audit('admin.apikey.created',$r['id']);return $this->respond($r,201);}
 private function update($id,$override=NULL){$d=$override?:$this->body();if(!$d)return $this->fail('VALIDATION_ERROR','At least one field is required',422);$err=$this->validate_input($d,FALSE);if($err)return $this->fail('VALIDATION_ERROR',$err,422);$r=$this->keys->update_key($id,$this->c['organizationId'],$d);if($r===NULL)return $this->fail('NOT_FOUND','API key not found',404);if($r===FALSE)return $this->fail('CONFLICT','Revoked API keys cannot be changed',409);$this->audit(!empty($d['revoked'])?'admin.apikey.revoked':'admin.apikey.updated',$id);return $this->respond($r);}
 private function validate_input($d,$create){if(isset($d['name'])&&(trim($d['name'])===''||strlen($d['name'])>100))return 'Invalid name';if(isset($d['scopes'])&&(!is_array($d['scopes'])||!$d['scopes']||array_diff($d['scopes'],array('READ','WRITE','ADMIN'))))return 'Invalid scopes';if(isset($d['granularScopes'])&&(!is_array($d['granularScopes'])||count($d['granularScopes'])>50))return 'Invalid granular scopes';if(isset($d['environment'])&&!in_array($d['environment'],array('development','test','production'),TRUE))return 'Invalid environment';if(isset($d['ipRestrictions'])&&(!is_array($d['ipRestrictions'])||count($d['ipRestrictions'])>20))return 'Invalid IP restrictions';if(isset($d['expiresInDays'])&&$d['expiresInDays']!==NULL&&(!is_int($d['expiresInDays'])||$d['expiresInDays']<1||$d['expiresInDays']>365))return 'Expiration must be 1–365 days';if(isset($d['revoked'])&&$d['revoked']!==TRUE)return 'An active API key is not revoked';return NULL;}
 private function audit($type,$id,$extra=array()){$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode(array_merge(array('resourceType'=>'api_key','resourceId'=>$id),$extra)),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}
}
