<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Audit extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Permission_model','permissions');if(!$this->permissions->has($this->c['sub'],'AUDIT_READ',$this->c['organizationId'])){$this->fail('FORBIDDEN','Missing permission: AUDIT_READ',403);$this->output->_display();exit;}$this->load->model('Audit_model','audit');}
 public function index(){$limit=min(200,max(1,(int)($this->input->get('limit')?:50)));$offset=max(0,(int)($this->input->get('offset')?:0));list($rows,$total)=$this->audit->query($this->c['organizationId'],$this->filters(),$limit,$offset);return $this->respond(array('logs'=>$rows,'total'=>$total));}
 public function recent(){$limit=min(200,max(1,(int)($this->input->get('limit')?:50)));return $this->respond($this->audit->recent($this->c['organizationId'],$limit));}
 public function stats(){$days=min(365,max(1,(int)($this->input->get('days')?:30)));$rows=$this->audit->stats($this->c['organizationId'],$days);$stats=array();foreach($rows as $r)$stats[$r['action']]=(int)$r['count'];return $this->respond(array('stats'=>$stats,'period'=>array('days'=>$days)));}
 public function timeline(){$days=min(90,max(1,(int)($this->input->get('days')?:14)));return $this->respond(array('days'=>$days,'entries'=>$this->audit->timeline($this->c['organizationId'],$days)));}
 public function show($id){$r=$this->audit->one($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Audit entry not found',404);}
 public function export(){$start=$this->input->get('startDate');$end=$this->input->get('endDate');if(!$start||!$end||strtotime($start)===FALSE||strtotime($end)===FALSE||strtotime($end)<strtotime($start))return $this->fail('VALIDATION_ERROR','A valid date range is required',422);list($rows,)=$this->audit->query($this->c['organizationId'],array('startDate'=>date('Y-m-d H:i:s',strtotime($start)),'endDate'=>date('Y-m-d H:i:s',strtotime($end))),10000,0);$format=$this->input->get('format')==='csv'?'csv':'json';$name='audit-export-'.date('Y-m-d',strtotime($start)).'-to-'.date('Y-m-d',strtotime($end)).'.'.$format;$this->output->set_header('Content-Disposition: attachment; filename="'.$name.'"');if($format==='json')return $this->output->set_content_type('application/json')->set_output(json_encode($rows,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));$fp=fopen('php://temp','r+');fputcsv($fp,array('id','action','userId','resourceType','resourceId','ipAddress','createdAt','metadata'));foreach($rows as $r)fputcsv($fp,array($r['id'],$r['action'],$r['userId'],$r['resourceType'],$r['resourceId'],$r['ipAddress'],$r['createdAt'],json_encode($r['metadata'])));rewind($fp);$csv=stream_get_contents($fp);fclose($fp);return $this->output->set_content_type('text/csv')->set_output($csv);}
 private function filters(){return array('userId'=>$this->input->get('userId'),'action'=>$this->input->get('action'),'resourceType'=>$this->input->get('resourceType'),'resourceId'=>$this->input->get('resourceId'),'startDate'=>$this->date($this->input->get('startDate'),FALSE),'endDate'=>$this->date($this->input->get('endDate'),TRUE));}private function date($v,$end){if(!$v||strtotime($v)===FALSE)return NULL;return date('Y-m-d '.($end?'23:59:59':'00:00:00'),strtotime($v));}
}
