<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Auth extends MY_Controller {
 public function __construct(){ parent::__construct(); $this->load->model('User_model','users'); }
 public function register(){ if($this->input->method(TRUE)!=='POST')return $this->fail('METHOD_NOT_ALLOWED','POST required',405); $d=$this->body(); foreach(array('email','password','displayName','organizationName') as $f) if(empty($d[$f]))return $this->fail('VALIDATION_ERROR',$f.' is required',422); if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL)||strlen($d['password'])<10)return $this->fail('VALIDATION_ERROR','A valid email and password of at least 10 characters are required',422); if($this->users->find_identifier($d['email']))return $this->fail('CONFLICT','Account already exists',409); try { list($u,$o)=$this->users->create_account($d); return $this->issue($u,$o,201); } catch(Throwable $e){ log_message('error',$e->getMessage()); return $this->fail('DATABASE_ERROR','Account could not be created',500); } }
 public function login(){ $d=$this->body(); $id=trim($d['identifier']??$d['email']??''); $u=$this->users->find_identifier($id); if(!$u||!password_verify($d['password']??'',$u['password_hash']))return $this->fail('INVALID_CREDENTIALS','Invalid credentials',401); if(!$u['is_active'])return $this->fail('ACCOUNT_DISABLED','Account is disabled',403); if(!empty($u['mfa_enabled']))return $this->respond(array('mfa_required'=>TRUE,'mfaToken'=>$this->token(array('sub'=>$u['id'],'purpose'=>'mfa_login'),300))); return $this->issue($u,$this->users->membership($u['id'])); }
 public function refresh(){ $d=$this->body(); $r=$this->users->refresh_consume($d['refreshToken']??''); if(!$r)return $this->fail('INVALID_REFRESH_TOKEN','Refresh token is invalid or expired',401); $u=$this->users->find($r['user_id']); return $this->issue($u,$this->users->membership($u['id'])); }
 public function logout(){ $c=$this->require_auth(); if(!$c)return; $this->users->revoke_user($c['sub']); return $this->respond(array('loggedOut'=>TRUE)); }
 public function end_impersonation(){ $c=$this->require_auth(); if(!$c)return; if(empty($c['impersonatorId']))return $this->fail('BAD_REQUEST','No active impersonation session',400); $u=$this->users->find($c['impersonatorId']); if(!$u)return $this->fail('NOT_FOUND','Administrator not found',404); return $this->issue($u,$this->users->membership($u['id'])); }
 public function me(){ $c=$this->require_auth(); if(!$c)return; $u=$this->users->find($c['sub']); if(!$u)return $this->fail('NOT_FOUND','User not found',404); $o=$this->users->membership($u['id']); return $this->respond(array('id'=>$u['id'],'email'=>$u['email'],'role'=>strtolower($u['role']),'displayName'=>$u['display_name'],'avatarUrl'=>$u['avatar_url'],'publicUserId'=>$u['public_user_id'],'username'=>$u['username'],'pinExpired'=>FALSE,'locale'=>$u['locale'],'timezone'=>$u['timezone'],'theme'=>$u['theme'],'organization'=>$o,'workspace'=>NULL)); }
 private function issue($u,$o,$status=200){ $token=$this->token(array('sub'=>$u['id'],'email'=>$u['email'],'role'=>strtolower($u['role']),'organizationId'=>$o['id']??NULL)); $refresh=bin2hex(random_bytes(32)); $this->users->refresh_create($u['id'],$refresh,time()+604800); return $this->respond(array('token'=>$token,'refreshToken'=>$refresh,'expiresIn'=>900,'user'=>array('id'=>$u['id'],'email'=>$u['email'],'role'=>strtolower($u['role']),'displayName'=>$u['display_name'],'organizationId'=>$o['id']??NULL)),$status); }

 public function forgot(){if($this->input->method(TRUE)!=='POST')return $this->fail('METHOD_NOT_ALLOWED','POST required',405);$d=$this->body();$email=strtolower(trim($d['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))return $this->fail('VALIDATION_ERROR','Valid email is required',422);$u=$this->users->find_identifier($email);$debug=NULL;if($u&&strtolower($u['email'])===$email){$raw=bin2hex(random_bytes(32));$this->users->create_password_reset($u['id'],$raw);$url=rtrim((string)getenv('VP_BASE_URL'),'/').'/reset-password?token='.rawurlencode($raw);$sent=$this->send_reset_mail($email,$url);if(!$sent)log_message('error','Password reset mail could not be sent for user '.$u['id']);if(ENVIRONMENT!=='production')$debug=$raw;}$result=array('message'=>'If an account exists for that email, a password reset link has been sent.');if($debug)$result['resetToken']=$debug;return $this->respond($result);}
 public function reset(){if($this->input->method(TRUE)!=='POST')return $this->fail('METHOD_NOT_ALLOWED','POST required',405);$d=$this->body();$password=$d['password']??'';if(strlen($d['token']??'')<20||strlen($password)<10)return $this->fail('VALIDATION_ERROR','Valid token and password of at least 10 characters are required',422);$r=$this->users->consume_password_reset($d['token']);if(!$r)return $this->fail('INVALID_TOKEN','Password reset token is invalid or expired',422);$this->users->set_password($r['user_id'],$password);return $this->respond(array('reset'=>TRUE));}
 private function send_reset_mail($email,$url){$from=getenv('VP_MAIL_FROM')?:'no-reply@'.($_SERVER['HTTP_HOST']??'localhost');$subject='Reset your WINDELS AI OS password';$body="A password reset was requested for your account.\n\nOpen this link within one hour:\n".$url."\n\nIf you did not request this, ignore this message.";$headers='From: WINDELS AI OS <'.$from.">\r\nContent-Type: text/plain; charset=UTF-8";return @mail($email,$subject,$body,$headers);}

 public function mfa_complete(){$d=$this->body();$parts=explode('.',$d['mfaToken']??'');if(count($parts)!==3)return $this->fail('INVALID_TOKEN','Invalid MFA login token',401);$expected=rtrim(strtr(base64_encode(hash_hmac('sha256',$parts[0].'.'.$parts[1],getenv('VP_AUTH_SECRET'),TRUE)),'+/','-_'),'=');if(!hash_equals($expected,$parts[2]))return $this->fail('INVALID_TOKEN','Invalid MFA login token',401);$claims=json_decode(base64_decode(strtr($parts[1],'-_','+/')),TRUE);if(!$claims||($claims['exp']??0)<time()||($claims['purpose']??'')!=='mfa_login')return $this->fail('INVALID_TOKEN','MFA login token expired',401);$this->load->model('Mfa_model','mfa');$v=$this->mfa->verify($claims['sub'],$d['totp']??'');if(!$v['ok'])return $this->fail('INVALID_TOTP',$v['reason']??'Invalid MFA code',401);$u=$this->users->find($claims['sub']);return $this->issue($u,$this->users->membership($u['id']));}
}
