<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Discovery extends MY_Controller {
 private $c;private $statuses=array('starting','healthy','degraded','unhealthy','offline');public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Discovery_model','discovery');$this->discovery->mark_stale($this->c['organizationId']);}
 public function services(){if($this->input->method(TRUE)==='POST')return $this->register();return $this->respond($this->discovery->services($this->c['organizationId'],array('includeOffline'=>TRUE)));}
 public function query(){return $this->respond($this->discovery->services($this->c['organizationId'],array('name'=>$this->input->get('name'),'capability'=>$this->input->get('capability'),'status'=>$this->input->get('status'),'region'=>$this->input->get('region'),'minVersion'=>$this->input->get('minVersion'),'includeOffline'=>$this->input->get('status')==='offline')));}
 public function resolve($name){$rows=$this->discovery->services($this->c['organizationId'],array('name'=>$name));return $rows?$this->respond($rows[0]):$this->fail('NOT_FOUND','Service not found',404);}
 public function heartbeat($instance){$d=$this->body();if(isset($d['status'])&&!in_array($d['status'],$this->statuses,TRUE))return $this->fail('VALIDATION_ERROR','Invalid service status',422);$r=$this->discovery->heartbeat($instance,$this->c['organizationId'],$d);return $r?$this->respond($r):$this->fail('NOT_FOUND','Service instance not found',404);}
 public function service($id){if($this->input->method(TRUE)!=='DELETE')return $this->fail('METHOD_NOT_ALLOWED','DELETE required',405);if(!$this->admin())return;$ok=$this->discovery->remove($id,$this->input->get('instanceId'),$this->c['organizationId']);return $ok?$this->respond(array('deleted'=>TRUE)):$this->fail('NOT_FOUND','Service not found',404);}
 public function dependencies(){if($this->input->method(TRUE)==='POST')return $this->add_dependency();return $this->respond($this->discovery->dependencies($this->c['organizationId'],$this->input->get('service')));}
 public function validate_graph(){return $this->respond($this->discovery->validate_graph($this->c['organizationId']));}
 private function register(){if(!$this->admin())return;$d=$this->body();foreach(array('id','name','version','baseUrl') as $f)if(empty(trim($d[$f]??'')))return $this->fail('VALIDATION_ERROR',$f.' is required',422);if(!preg_match('/^v?\d+(?:\.\d+){0,2}/',$d['version']))return $this->fail('VALIDATION_ERROR','Invalid semantic version',422);if(!filter_var($d['baseUrl'],FILTER_VALIDATE_URL))return $this->fail('VALIDATION_ERROR','Invalid base URL',422);if(isset($d['status'])&&!in_array($d['status'],$this->statuses,TRUE))return $this->fail('VALIDATION_ERROR','Invalid status',422);foreach(array('capabilities','metadata') as $f)if(isset($d[$f])&&!is_array($d[$f]))return $this->fail('VALIDATION_ERROR',$f.' must be an array or object',422);$r=$this->discovery->register($this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail('CONFLICT','Service instance belongs to another organization',409);}
 private function add_dependency(){if(!$this->admin())return;$d=$this->body();if(empty($d['from'])||empty($d['to']))return $this->fail('VALIDATION_ERROR','Dependency source and target are required',422);$d+=array('kind'=>'http','criticality'=>'required');if(!in_array($d['kind'],array('http','event','grpc','internal'),TRUE)||!in_array($d['criticality'],array('required','optional'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid dependency classification',422);$this->discovery->dependency($this->c['organizationId'],$d);return $this->respond(array('created'=>TRUE),201);}
 private function admin(){$this->load->model('Permission_model','discoveryPermissions');if(!$this->discoveryPermissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Organization administrator access required',403);return FALSE;}return TRUE;}
}
