<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Enterprise extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Organization_model','organizations');}
 public function organization(){$org=$this->organizations->get_for_user($this->c['sub'],$this->c['organizationId']);if(!$org)return $this->fail('NOT_FOUND','Organization not found',404);if(in_array($this->input->method(TRUE),array('PATCH','PUT'),TRUE))return $this->update_organization($org);return $this->respond($this->organizations->view($org));}
 private function update_organization($org){$this->load->model('Permission_model','permissions');if(!$this->permissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId']))return $this->fail('FORBIDDEN','Only admins can update organization settings',403);$d=$this->body();$set=array();if(array_key_exists('name',$d)){if(!is_string($d['name'])||trim($d['name'])===''||strlen($d['name'])>100)return $this->fail('VALIDATION_ERROR','Organization name must contain 1–100 characters',422);$set['name']=trim($d['name']);}if(isset($d['whiteLabel'])){if(!is_array($d['whiteLabel']))return $this->fail('VALIDATION_ERROR','whiteLabel must be an object',422);$current=json_decode($org['white_label']?:'{}',TRUE)?:array();$allowed=array('appName','logoUrl','primaryColor','secondaryColor','brandingHidden','supportEmail');foreach($d['whiteLabel'] as $k=>$v){if(!in_array($k,$allowed,TRUE))return $this->fail('VALIDATION_ERROR','Unknown white-label field: '.$k,422);if($k==='appName'&&(!is_string($v)||trim($v)===''||strlen($v)>60))return $this->fail('VALIDATION_ERROR','Invalid app name',422);if(in_array($k,array('primaryColor','secondaryColor'),TRUE)&&!preg_match('/^#[0-9A-Fa-f]{6}$/',(string)$v))return $this->fail('VALIDATION_ERROR','Invalid color',422);if($k==='supportEmail'&&$v!==NULL&&!filter_var($v,FILTER_VALIDATE_EMAIL))return $this->fail('VALIDATION_ERROR','Invalid support email',422);if($k==='logoUrl'&&$v!==NULL&&!filter_var($v,FILTER_VALIDATE_URL))return $this->fail('VALIDATION_ERROR','Invalid logo URL',422);if($k==='brandingHidden'&&!is_bool($v))return $this->fail('VALIDATION_ERROR','Invalid branding flag',422);$current[$k]=$v;}$set['white_label']=json_encode($current,JSON_UNESCAPED_SLASHES);if(array_key_exists('logoUrl',$d['whiteLabel']))$set['logo_url']=$d['whiteLabel']['logoUrl'];}if(!$set)return $this->fail('VALIDATION_ERROR','No supported changes supplied',422);$updated=$this->organizations->update($org['id'],$set);$this->db->insert('audit_events',array('organization_id'=>$org['id'],'user_id'=>$this->c['sub'],'event_type'=>'data.update','payload'=>json_encode(array('resourceType'=>'organization','resourceId'=>$org['id'],'fields'=>array_keys($set))),'ip_address'=>$this->input->ip_address(),'user_agent'=>substr((string)$this->input->user_agent(),0,500),'created_at'=>date('Y-m-d H:i:s')));return $this->respond($this->organizations->view($updated));}

 public function models(){$this->load->model('Model_registry_model','models');if($this->input->method(TRUE)==='POST')return $this->create_model();return $this->respond($this->models->all($this->c['organizationId']));}
 public function model($id){$this->load->model('Model_registry_model','models');$method=$this->input->method(TRUE);if($method==='DELETE'){if(!$this->models->delete_owned($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','Model not found',404);$this->audit_model('data.delete',$id);return $this->respond(array('deleted'=>TRUE));}if(!in_array($method,array('PATCH','PUT'),TRUE))return $this->fail('METHOD_NOT_ALLOWED','PATCH or DELETE required',405);$d=$this->body();$set=$this->model_fields($d,FALSE);if(isset($set['error']))return $this->fail('VALIDATION_ERROR',$set['error'],422);if(!$set)return $this->fail('VALIDATION_ERROR','No supported changes supplied',422);$r=$this->models->update_owned($id,$this->c['organizationId'],$set);if(!$r)return $this->fail('NOT_FOUND','Model not found',404);$this->audit_model('data.update',$id);return $this->respond($r);}
 public function model_default($id){$this->load->model('Model_registry_model','models');if(!$this->models->set_default($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','Model not found',404);$this->audit_model('system.config_change',$id);return $this->respond(array('default'=>TRUE));}
 private function create_model(){$d=$this->body();foreach(array('provider','modelId','name') as $f)if(!isset($d[$f])||!is_string($d[$f])||trim($d[$f])==='')return $this->fail('VALIDATION_ERROR',$f.' is required',422);$d+=array('version'=>'1.0','capabilities'=>array('chat'),'contextWindow'=>128000,'maxOutputTokens'=>4096,'costInputPer1k'=>0,'costOutputPer1k'=>0,'config'=>array());$set=$this->model_fields($d,TRUE);if(isset($set['error']))return $this->fail('VALIDATION_ERROR',$set['error'],422);$input=array('provider'=>$set['provider'],'modelId'=>$set['model_id'],'name'=>$set['name'],'version'=>$set['version'],'description'=>$set['description']??NULL,'capabilities'=>json_decode($set['capabilities'],TRUE),'contextWindow'=>$set['context_window'],'maxOutputTokens'=>$set['max_output_tokens'],'costInputPer1k'=>$set['cost_input_per_1k'],'costOutputPer1k'=>$set['cost_output_per_1k'],'config'=>json_decode($set['config'],TRUE));$r=$this->models->create($this->c['organizationId'],$input);if(!$r)return $this->fail('CONFLICT','Model already registered',409);$this->audit_model('data.create',$r['id']);return $this->respond($r,201);}
 private function model_fields($d,$creating){$map=array('provider'=>'provider','modelId'=>'model_id','name'=>'name','version'=>'version','description'=>'description','contextWindow'=>'context_window','maxOutputTokens'=>'max_output_tokens','costInputPer1k'=>'cost_input_per_1k','costOutputPer1k'=>'cost_output_per_1k','isDefault'=>'is_default','enabled'=>'enabled');$set=array();foreach($map as $in=>$out)if(array_key_exists($in,$d))$set[$out]=$d[$in];if(isset($set['provider'])&&(strlen($set['provider'])<1||strlen($set['provider'])>40))return array('error'=>'Invalid provider');if(isset($set['model_id'])&&(strlen($set['model_id'])<1||strlen($set['model_id'])>100))return array('error'=>'Invalid model ID');if(isset($set['name'])&&(strlen($set['name'])<1||strlen($set['name'])>100))return array('error'=>'Invalid model name');if(isset($set['context_window'])&&(int)$set['context_window']<256)return array('error'=>'Context window must be at least 256');if(isset($set['max_output_tokens'])&&(int)$set['max_output_tokens']<64)return array('error'=>'Output token limit must be at least 64');foreach(array('cost_input_per_1k','cost_output_per_1k') as $f)if(isset($set[$f])&&(!is_numeric($set[$f])||$set[$f]<0))return array('error'=>'Model costs cannot be negative');if(array_key_exists('capabilities',$d)){if(!is_array($d['capabilities']))return array('error'=>'Capabilities must be an array');$set['capabilities']=json_encode(array_values($d['capabilities']));}if(array_key_exists('config',$d)){if(!is_array($d['config']))return array('error'=>'Config must be an object');$set['config']=json_encode($d['config'],JSON_UNESCAPED_SLASHES);}return $set;}
 private function audit_model($type,$id){$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode(array('resourceType'=>'model','resourceId'=>$id)),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}

 public function ai_monitoring(){$days=min(90,max(1,(int)($this->input->get('days')?:30)));$this->load->model('Ai_monitoring_model','monitoring');return $this->respond($this->monitoring->metrics($this->c['organizationId'],$days));}

 public function plugins(){$this->load->model('Plugin_model','plugins');if($this->input->method(TRUE)==='POST')return $this->install_plugin();return $this->respond($this->plugins->all($this->c['organizationId']));}
 public function plugin_toggle($id){$this->load->model('Plugin_model','plugins');$d=$this->body();$enabled=!array_key_exists('enabled',$d)||$d['enabled']!==FALSE;$r=$this->plugins->toggle($id,$this->c['organizationId'],$enabled);if(!$r)return $this->fail('NOT_FOUND','Plugin not found',404);$this->audit_plugin('system.feature_flag_toggle',$id,array('enabled'=>$enabled));return $this->respond($r);}
 public function plugin_config($id){$this->load->model('Plugin_model','plugins');$d=$this->body();$config=$d['config']??array();if(!is_array($config))return $this->fail('VALIDATION_ERROR','Config must be an object',422);$r=$this->plugins->configure($id,$this->c['organizationId'],$config);if(!$r)return $this->fail('NOT_FOUND','Custom plugin not found',404);$this->audit_plugin('system.config_change',$id);return $this->respond($r);}
 public function plugin($id){if($this->input->method(TRUE)!=='DELETE')return $this->fail('METHOD_NOT_ALLOWED','DELETE required',405);$this->load->model('Plugin_model','plugins');if(!$this->plugins->delete_owned($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','Custom plugin not found',404);$this->audit_plugin('data.delete',$id);return $this->respond(array('deleted'=>TRUE));}
 private function install_plugin(){$d=$this->body();if(!preg_match('/^[a-z0-9-]+$/',$d['slug']??''))return $this->fail('VALIDATION_ERROR','Slug must be kebab-case',422);if(empty(trim($d['name']??''))||strlen($d['name'])>100)return $this->fail('VALIDATION_ERROR','Plugin name is required',422);$d+=array('version'=>'1.0.0','hooks'=>array(),'config'=>array());if(!is_array($d['hooks'])||!is_array($d['config']))return $this->fail('VALIDATION_ERROR','Hooks and config must be arrays or objects',422);$this->load->model('Plugin_model','plugins');$r=$this->plugins->create($this->c['organizationId'],$d);if(!$r)return $this->fail('CONFLICT','Plugin is already installed',409);$this->audit_plugin('data.create',$r['id'],array('slug'=>$r['slug']));return $this->respond($r,201);}
 private function audit_plugin($type,$id,$extra=array()){$payload=array_merge(array('resourceType'=>'integration','resourceId'=>$id),$extra);$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode($payload),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}

 public function integrations(){$this->load->model('Integration_model','integrations');if($this->input->method(TRUE)==='POST')return $this->connect_integration();$available=array(array('type'=>'slack','name'=>'Slack','description'=>'Send Talk notifications and receive slash commands from Slack','icon'=>'💬'),array('type'=>'discord','name'=>'Discord','description'=>'Post workflow updates to Discord channels','icon'=>'🎮'),array('type'=>'email','name'=>'Email (SMTP)','description'=>'Send emails via SMTP for approvals and alerts','icon'=>'✉'),array('type'=>'github','name'=>'GitHub','description'=>'Open issues, comment on PRs, trigger workflows on pushes','icon'=>'🐙'),array('type'=>'linear','name'=>'Linear','description'=>'Sync tasks with Linear issues','icon'=>'📐'),array('type'=>'jira','name'=>'Jira','description'=>'Sync tasks with Jira tickets','icon'=>'🧩'),array('type'=>'notion','name'=>'Notion','description'=>'Publish pages and read databases','icon'=>'📝'),array('type'=>'google_drive','name'=>'Google Drive','description'=>'Attach and index files from Drive','icon'=>'📁'),array('type'=>'s3','name'=>'S3-compatible storage','description'=>'Store attachments and backups to any S3 bucket','icon'=>'🗄'),array('type'=>'webhook','name'=>'Custom Webhook','description'=>'Generic outgoing webhook integration','icon'=>'🔗'));return $this->respond(array('available'=>$available,'installed'=>$this->integrations->all($this->c['organizationId'])));}
 public function integration($id){$this->load->model('Integration_model','integrations');if($this->input->method(TRUE)==='DELETE'){if(!$this->integrations->delete_owned($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','Integration not found',404);$this->audit_integration('data.delete',$id);return $this->respond(array('deleted'=>TRUE));}$d=$this->body();if(isset($d['name'])&&(trim($d['name'])===''||strlen($d['name'])>100))return $this->fail('VALIDATION_ERROR','Invalid integration name',422);if(isset($d['status'])&&!in_array($d['status'],array('connected','disconnected','error'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid integration status',422);if(isset($d['config'])&&!is_array($d['config'])||isset($d['credentials'])&&!is_array($d['credentials']))return $this->fail('VALIDATION_ERROR','Config and credentials must be objects',422);$r=$this->integrations->update_owned($id,$this->c['organizationId'],$d);if(!$r)return $this->fail('NOT_FOUND','Integration not found',404);$this->audit_integration('data.update',$id);return $this->respond($r);}
 private function connect_integration(){$d=$this->body();if(empty(trim($d['type']??''))||empty(trim($d['name']??''))||strlen($d['name'])>100)return $this->fail('VALIDATION_ERROR','Type and name are required',422);$d+=array('config'=>array(),'credentials'=>array());if(!is_array($d['config'])||!is_array($d['credentials']))return $this->fail('VALIDATION_ERROR','Config and credentials must be objects',422);$this->load->model('Integration_model','integrations');try{$r=$this->integrations->create($this->c['organizationId'],$d);}catch(Throwable $e){log_message('error',$e->getMessage());return $this->fail('ENCRYPTION_ERROR','Integration credentials could not be encrypted',500);}if(!$r)return $this->fail('CONFLICT',$d['type'].' is already connected. Update it instead.',409);$this->audit_integration('data.create',$r['id']);return $this->respond($r,201);}
 private function audit_integration($type,$id){$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode(array('resourceType'=>'integration','resourceId'=>$id)),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}

 public function sso(){$this->load->model('Sso_model','ssoModel');if(in_array($this->input->method(TRUE),array('PUT','PATCH'),TRUE))return $this->save_sso();return $this->respond($this->ssoModel->get($this->c['organizationId']));}
 public function sso_disable(){if(!$this->enterprise_admin())return;$this->load->model('Sso_model','ssoModel');if(!$this->ssoModel->disable($this->c['organizationId']))return $this->fail('NOT_FOUND','SSO is not configured',404);$this->audit_sso('system.config_change',array('enabled'=>FALSE));return $this->respond(array('disabled'=>TRUE));}
 public function sso_lookup(){$email=(string)$this->input->get('email');if(!filter_var($email,FILTER_VALIDATE_EMAIL))return $this->fail('VALIDATION_ERROR','Valid email is required',422);$this->load->model('Sso_model','ssoModel');return $this->respond($this->ssoModel->lookup($email));}
 private function save_sso(){if(!$this->enterprise_admin())return;$d=$this->body();if(!in_array($d['provider']??'',array('saml','oidc','google','microsoft'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid SSO provider',422);$d+=array('domains'=>array(),'enabled'=>FALSE);if(!is_array($d['domains']))return $this->fail('VALIDATION_ERROR','Domains must be an array',422);$domains=array();foreach($d['domains'] as $domain){$domain=strtolower(trim($domain));if(!preg_match('/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/',$domain))return $this->fail('VALIDATION_ERROR','Invalid SSO domain: '.$domain,422);$domains[]=$domain;}$d['domains']=array_values(array_unique($domains));if(isset($d['entryPoint'])&&!filter_var($d['entryPoint'],FILTER_VALIDATE_URL))return $this->fail('VALIDATION_ERROR','Invalid SSO entry point',422);if(!is_bool($d['enabled']))return $this->fail('VALIDATION_ERROR','Enabled must be boolean',422);$this->load->model('Sso_model','ssoModel');try{$r=$this->ssoModel->save($this->c['organizationId'],$d);}catch(Throwable $e){log_message('error',$e->getMessage());return $this->fail('ENCRYPTION_ERROR','SSO secrets could not be encrypted',500);}$this->audit_sso('system.config_change',array('provider'=>$d['provider'],'enabled'=>$d['enabled']));return $this->respond($r);}
 private function enterprise_admin(){$this->load->model('Permission_model','enterprisePermissions');if(!$this->enterprisePermissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Only admins can configure SSO',403);return FALSE;}return TRUE;}
 private function audit_sso($type,$extra){$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode(array_merge(array('resourceType'=>'integration','resourceId'=>'sso'),$extra)),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}
}
