<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Events extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Event_bus_model','events');}
 public function schemas(){if($this->input->method(TRUE)==='POST')return $this->register_schema();return $this->respond($this->events->schemas($this->c['organizationId']));}
 public function recent(){$since=$this->input->get('since');if($since&&strtotime($since)===FALSE)return $this->fail('VALIDATION_ERROR','Invalid since timestamp',422);return $this->respond($this->events->recent($this->c['organizationId'],$this->input->get('type'),$since?date('Y-m-d H:i:s',strtotime($since)):NULL,$this->input->get('correlationId')));}
 public function publish(){$d=$this->body();if(strlen(trim($d['type']??''))<2||!array_key_exists('payload',$d))return $this->fail('VALIDATION_ERROR','Event type and payload are required',422);$version=$d['schemaVersion']??'1.0.0';if(!$this->events->schema_exists($this->c['organizationId'],$d['type'],$version))return $this->fail('SCHEMA_NOT_FOUND','No active schema is registered for this event type and version',422);if(isset($d['metadata'])&&!is_array($d['metadata']))return $this->fail('VALIDATION_ERROR','Metadata must be an object',422);return $this->respond($this->events->publish($this->c['organizationId'],$this->c['sub'],$d),202);}
 public function dlq(){if(!$this->admin())return;$status=$this->input->get('status');if($status&&!in_array($status,array('pending','replayed','discarded'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid DLQ status',422);return $this->respond($this->events->dlq($this->c['organizationId'],$status));}
 public function dlq_replay($id){if(!$this->admin())return;return $this->respond(array('replayed'=>$this->events->dlq_action($id,$this->c['organizationId'],'replay')));}
 public function dlq_discard($id){if(!$this->admin())return;return $this->respond(array('discarded'=>$this->events->dlq_action($id,$this->c['organizationId'],'discard')));}
 private function register_schema(){if(!$this->admin())return;$d=$this->body();if(strlen(trim($d['type']??''))<2||empty($d['producer']))return $this->fail('VALIDATION_ERROR','Type and producer are required',422);$d+=array('version'=>'1.0.0','description'=>'','consumers'=>array(),'schema'=>array(),'deprecated'=>FALSE);if(!preg_match('/^v?\d+(?:\.\d+){0,2}/',$d['version'])||!is_array($d['consumers'])||!is_array($d['schema']))return $this->fail('VALIDATION_ERROR','Invalid schema registration',422);$r=$this->events->register_schema($this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail('CONFLICT','Event schema version is already registered',409);}
 private function admin(){$this->load->model('Permission_model','eventPermissions');if(!$this->eventPermissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Organization administrator access required',403);return FALSE;}return TRUE;}
}
