<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Governance extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Governance_model','governance');}
 public function adrs(){if($this->input->method(TRUE)==='POST')return $this->create_adr();$status=$this->input->get('status');if($status&&!in_array($status,$this->statuses(),TRUE))return $this->fail('VALIDATION_ERROR','Invalid ADR status',422);return $this->respond($this->governance->adrs($this->c['organizationId'],$status,$this->input->get('tag')));}
 public function adr($id){if(in_array($this->input->method(TRUE),array('PATCH','PUT'),TRUE))return $this->update_adr($id);$r=$this->governance->adr($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','ADR not found',404);}
 public function standards(){if($this->input->method(TRUE)==='POST')return $this->create_standard();$cat=$this->input->get('category');if($cat&&!in_array($cat,$this->categories(),TRUE))return $this->fail('VALIDATION_ERROR','Invalid standard category',422);return $this->respond($this->governance->standards($this->c['organizationId'],$cat));}
 public function reviews(){if($this->input->method(TRUE)==='POST')return $this->create_review();return $this->respond($this->governance->reviews($this->c['organizationId'],$this->input->get('status'),$this->input->get('kind')));}
 public function review_comment($id){$d=$this->body();$body=trim($d['body']??'');if($body==='')return $this->fail('VALIDATION_ERROR','Comment body is required',422);$r=$this->governance->comment($id,$this->c['organizationId'],$this->c['sub'],$body);return $r?$this->respond($r):$this->fail('NOT_FOUND','Review not found',404);}
 public function review_decide($id){if(!$this->admin())return;$d=$this->body();if(!in_array($d['decision']??'',array('approved','changes_requested','rejected'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid review decision',422);$r=$this->governance->decide($id,$this->c['organizationId'],$d['decision']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Review not found',404);}
 private function create_adr(){if(!$this->admin())return;$d=$this->body();foreach(array('title'=>3,'context'=>10,'decision'=>10,'consequences'=>5) as $f=>$min)if(!is_string($d[$f]??NULL)||strlen(trim($d[$f]))<$min)return $this->fail('VALIDATION_ERROR',$f.' is too short',422);if(isset($d['status'])&&!in_array($d['status'],$this->statuses(),TRUE))return $this->fail('VALIDATION_ERROR','Invalid ADR status',422);if(isset($d['authors'])&&!is_array($d['authors'])||isset($d['tags'])&&!is_array($d['tags']))return $this->fail('VALIDATION_ERROR','Authors and tags must be arrays',422);return $this->respond($this->governance->create_adr($this->c['organizationId'],$this->c['sub'],$d),201);}
 private function update_adr($id){if(!$this->admin())return;$d=$this->body();$allowed=array('title','context','decision','consequences','status','tags','supersededBy');$set=array();foreach($d as $k=>$v){if(!in_array($k,$allowed,TRUE))return $this->fail('VALIDATION_ERROR','Unknown ADR field: '.$k,422);$set[$k==='supersededBy'?'superseded_by':$k]=$k==='tags'?json_encode($v):$v;}if(isset($d['status'])&&!in_array($d['status'],$this->statuses(),TRUE))return $this->fail('VALIDATION_ERROR','Invalid ADR status',422);$r=$this->governance->update_adr($id,$this->c['organizationId'],$set);return $r?$this->respond($r):$this->fail('NOT_FOUND','ADR not found',404);}
 private function create_standard(){if(!$this->admin())return;$d=$this->body();if(strlen(trim($d['code']??''))<3||strlen(trim($d['title']??''))<3)return $this->fail('VALIDATION_ERROR','Code and title are required',422);if(!in_array($d['category']??'',$this->categories(),TRUE)||!in_array($d['severity']??'',array('must','should','may'),TRUE)||!in_array($d['enforcement']??'',array('manual','automated','advisory'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid standard classification',422);$r=$this->governance->add_standard($this->c['organizationId'],$d);return $r?$this->respond($r,201):$this->fail('CONFLICT','Standard code already exists',409);}
 private function create_review(){$d=$this->body();if(!in_array($d['kind']??'',array('adr','service','event','api','deployment'),TRUE)||empty($d['targetId']))return $this->fail('VALIDATION_ERROR','Valid kind and targetId are required',422);if(isset($d['reviewers'])&&!is_array($d['reviewers']))return $this->fail('VALIDATION_ERROR','Reviewers must be an array',422);return $this->respond($this->governance->create_review($this->c['organizationId'],$this->c['sub'],$d),201);}
 private function admin(){$this->load->model('Permission_model','governancePermissions');if(!$this->governancePermissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Organization administrator access required',403);return FALSE;}return TRUE;}private function statuses(){return array('proposed','accepted','superseded','deprecated','rejected');}private function categories(){return array('api','security','data','ui','infra','naming','testing');}
}
