<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Mfa extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Mfa_model','mfa');}
 public function status(){return $this->respond($this->mfa->status($this->c['sub']));}
 public function enable(){$s=$this->mfa->status($this->c['sub']);if($s['enabled'])return $this->fail('MFA_ALREADY_ENABLED','MFA is already enabled. Disable it first.',400);$this->load->model('User_model','users');$u=$this->users->find($this->c['sub']);$r=$this->mfa->enable($u['id'],$u['email']);$this->audit('auth.mfa_enable');return $this->respond($r);}
 public function confirm(){return $this->verification(TRUE);}
 public function verify(){return $this->verification(FALSE);}
 public function disable(){$d=$this->body();$v=$this->check($d['token']??'');if(!$v)return;$this->mfa->disable($this->c['sub']);$this->audit('auth.mfa_disable');return $this->respond(array('disabled'=>TRUE));}
 public function recovery_codes(){$d=$this->body();$v=$this->check($d['token']??'');if(!$v)return;$codes=$this->mfa->recovery($this->c['sub']);$this->load->model('Mfa_assurance_model','assuranceRecord');$this->assuranceRecord->event('recovery_codes_regenerated',$this->c['sub'],$this->c['organizationId'],$this->c['sub']);return $this->respond(array('recoveryCodes'=>$codes));}
 private function verification($confirm){$d=$this->body();$v=$this->check($d['token']??'');if(!$v)return;if($confirm)return $this->respond(array('verified'=>TRUE,'method'=>$v['method']));return $this->respond($v);}
 private function check($token){if(strlen($token)<6||strlen($token)>12){$this->fail('VALIDATION_ERROR','Token must contain 6–12 characters',422);return FALSE;}$v=$this->mfa->verify($this->c['sub'],$token);if(!$v['ok']){$this->load->model('Mfa_assurance_model','assuranceVerify');$this->assuranceVerify->event($v['reason']==='locked'?'verification_blocked':'verification_failed',$this->c['sub'],$this->c['organizationId'],$this->c['sub'],NULL,$v['reason']);if($v['reason']==='locked'){$this->output->set_header('Retry-After: '.$v['retryAfterSeconds']);$this->fail('MFA_LOCKED','Too many failed attempts',429,array('retryAfterSeconds'=>$v['retryAfterSeconds']));}elseif($v['reason']==='replayed')$this->fail('MFA_CODE_REPLAYED','This code has already been used',400);else $this->fail('INVALID_TOTP',$v['reason'],400);return FALSE;}$this->load->model('Mfa_assurance_model','assuranceSuccess');$this->assuranceSuccess->event('verification_succeeded',$this->c['sub'],$this->c['organizationId'],$this->c['sub'],$v['method']);if($v['method']==='recovery')$this->assuranceSuccess->event('recovery_code_used',$this->c['sub'],$this->c['organizationId'],$this->c['sub'],'recovery');return $v;}
 private function audit($type){$kind=$type==='auth.mfa_enable'?'enrollment_started':'mfa_disabled';$this->load->model('Mfa_assurance_model','assuranceAudit');$this->assuranceAudit->event($kind,$this->c['sub'],$this->c['organizationId'],$this->c['sub']);$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>'{}','ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}

 public function policy(){$this->load->model('Mfa_assurance_model','assurance');if(in_array($this->input->method(TRUE),array('PUT','PATCH'),TRUE)){if(!$this->admin())return;$d=$this->body();if(!$d)return $this->fail('VALIDATION_ERROR','Provide at least one policy field',422);if(isset($d['mode'])&&!in_array($d['mode'],array('optional','required_admins','required_all'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid policy mode',422);if(isset($d['enforcement'])&&!in_array($d['enforcement'],array('report_only','block_after_grace'),TRUE))return $this->fail('VALIDATION_ERROR','Invalid enforcement mode',422);if(isset($d['graceDays'])&&(!is_int($d['graceDays'])||$d['graceDays']<0||$d['graceDays']>365))return $this->fail('VALIDATION_ERROR','Invalid grace period',422);if(isset($d['recoveryCodeFloor'])&&(!is_int($d['recoveryCodeFloor'])||$d['recoveryCodeFloor']<0||$d['recoveryCodeFloor']>10))return $this->fail('VALIDATION_ERROR','Invalid recovery-code floor',422);if(($d['enforcement']??'')==='block_after_grace'&&!$this->mfa->status($this->c['sub'])['enabled'])return $this->fail('SELF_LOCKOUT','Enable MFA before activating blocking enforcement',409);return $this->respond($this->assurance->save_policy($this->c['organizationId'],$this->c['sub'],$d));}return $this->respond($this->assurance->policy($this->c['organizationId']));}
 public function enrollment(){$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->enrollment($this->c['sub'],$this->c['organizationId']));}
 public function abandon_enrollment(){$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->abandon($this->c['sub'],$this->c['organizationId']));}
 public function recovery_health(){$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->recovery($this->c['sub'],$this->c['organizationId']));}
 public function lock(){$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->lock($this->c['sub']));}
 public function configuration(){return $this->respond(array('totp'=>array('algorithm'=>'SHA1','digits'=>6,'periodSeconds'=>30,'driftWindows'=>1,'liveSeconds'=>90,'vectorsPinned'=>TRUE),'recoveryCodes'=>array('issuedPerEnrollment'=>10,'storage'=>'sha256_digest','lowWatermark'=>2),'secretStorage'=>array('at'=>'mysql','encryption'=>'aes-256-gcm','keyConfigured'=>strlen((string)getenv('VP_ENCRYPTION_KEY'))>0,'keySource'=>getenv('VP_ENCRYPTION_KEY')?'environment':'development_fallback'),'throttle'=>array('maxFailedAttempts'=>5,'windowSeconds'=>900,'lockoutSeconds'=>900,'wiredInto'=>array('/mfa/confirm','/mfa/verify','/mfa/disable','/mfa/recovery-codes','/auth/mfa/complete')),'replayGuard'=>array('enabled'=>TRUE,'seconds'=>90,'wiredInto'=>array('/mfa/confirm','/mfa/verify','/auth/mfa/complete')),'ledger'=>array('perOrganizationLimit'=>1000,'perMemberLimit'=>200),'note'=>'Configuration values used by this deployment.','configNote'=>'Only a real authenticator enrollment proves interoperability.'));}
 private function admin(){$this->load->model('Permission_model','mfaPermissions');if(!$this->mfaPermissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Administrator access required',403);return FALSE;}return TRUE;}

 public function assurance_summary(){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->summary($this->c['organizationId']));}
 public function assurance_gaps(){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->gaps($this->c['organizationId']));}
 public function coverage(){if(!$this->admin())return;$limit=min(500,max(1,(int)($this->input->get('limit')?:500)));$compliance=$this->input->get('compliance');$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->coverage($this->c['organizationId'],$limit,$compliance));}
 public function coverage_me(){$this->load->model('Mfa_assurance_model','assurance');$e=$this->assurance->enrollment($this->c['sub'],$this->c['organizationId']);$r=$this->assurance->recovery($this->c['sub'],$this->c['organizationId']);$l=$this->assurance->lock($this->c['sub']);$p=$this->assurance->policy($this->c['organizationId']);$c=$this->assurance->coverage($this->c['organizationId']);$mine=NULL;foreach($c['members'] as $m)if($m['userId']===$this->c['sub']){$mine=$m;break;}return $this->respond(array('userId'=>$this->c['sub'],'organizationId'=>$this->c['organizationId'],'enabled'=>$e['state']==='confirmed'||$e['state']==='unrecorded','enrollment'=>$e,'recovery'=>$r,'lock'=>$l,'policy'=>$p,'required'=>$mine?$mine['required']:FALSE,'compliance'=>$mine?$mine['compliance']:'not_required','graceEndsAt'=>$mine?$mine['graceEndsAt']:NULL,'exemptUntil'=>$mine?$mine['exemptUntil']:NULL));}
 public function locks(){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->locks($this->c['organizationId']));}
 public function clear_lock($uid){if(!$this->admin())return;if(!$this->member($uid))return $this->fail('NOT_FOUND','Member not found',404);$this->load->model('Mfa_assurance_model','assurance');$r=$this->assurance->clear_lock($uid);$this->assurance->event('lock_cleared',$uid,$this->c['organizationId'],$this->c['sub']);return $this->respond($r);}
 public function exemptions(){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');if($this->input->method(TRUE)==='POST'){$d=$this->body();$uid=$d['userId']??'';$reason=trim($d['reason']??'');$days=$d['days']??0;if(!$this->member($uid))return $this->fail('NOT_FOUND','Member not found',404);if($reason===''||strlen($reason)>500||!is_int($days)||$days<1||$days>180)return $this->fail('VALIDATION_ERROR','User, reason, and 1–180 days are required',422);return $this->respond($this->assurance->grant_exemption($this->c['organizationId'],$uid,$this->c['sub'],$reason,$days),201);}return $this->respond($this->assurance->exemptions($this->c['organizationId']));}
 public function revoke_exemption($uid){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->revoke_exemption($this->c['organizationId'],$uid,$this->c['sub']));}
 public function events(){if(!$this->admin())return;$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->events($this->c['organizationId'],NULL,min(200,max(1,(int)($this->input->get('limit')?:50))),$this->input->get('kind'),'organization'));}
 public function events_me(){$this->load->model('Mfa_assurance_model','assurance');return $this->respond($this->assurance->events(NULL,$this->c['sub'],min(200,max(1,(int)($this->input->get('limit')?:50))),$this->input->get('kind'),'member'));}
 private function member($uid){return $this->db->where(array('user_id'=>$uid,'organization_id'=>$this->c['organizationId']))->count_all_results('memberships')>0;}
}
