<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Permissions extends MY_Controller {
 private $c;private $allowed=array('ORG_READ','ORG_WRITE','ORG_ADMIN','WORKFLOW_READ','WORKFLOW_WRITE','WORKFLOW_RUN','AGENT_READ','AGENT_WRITE','TALK_READ','TALK_WRITE','CANVAS_READ','CANVAS_WRITE','BILLING_READ','BILLING_WRITE','DEVELOPER_READ','DEVELOPER_WRITE','AUDIT_READ','NFC_READ','NFC_WRITE','NFC_DESTRUCTIVE','NFC_ADMIN','CLOUD_ANDROID_READ','CLOUD_ANDROID_CONTROL','CLOUD_ANDROID_MANAGE','CLOUD_ANDROID_APP','CLOUD_ANDROID_FILE','CLOUD_ANDROID_SENSITIVE','CLOUD_ANDROID_ADMIN','ADMIN_STAR');
 public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c){$this->output->_display();exit;}$this->load->model('Permission_model','permissions');}
 public function index(){return $this->respond($this->permissions->list_for_user($this->c['sub']));}
 public function catalog(){if(!$this->admin())return;$rows=$this->permissions->catalog();$categories=array();foreach($rows as $r){$prefix=strtolower(explode('_',$r['code'])[0]);$categories[$prefix][]=$r['code'];}return $this->respond(array('permissions'=>$rows,'categories'=>$categories));}
 public function user($uid){if(!$this->admin())return;if(!$this->permissions->same_org($this->c['sub'],$uid,$this->c['organizationId']))return $this->fail('NOT_FOUND','User not found',404);return $this->respond($this->permissions->list_for_user($uid));}
 public function grant(){$d=$this->body();if(!$this->admin())return;$target=$d['targetUserId']??'';$perm=$d['permission']??'';if(!in_array($perm,$this->allowed,TRUE))return $this->fail('VALIDATION_ERROR','Unknown permission',422);if(!$this->permissions->same_org($this->c['sub'],$target,$this->c['organizationId']))return $this->fail('NOT_FOUND','User not found',404);$resource=$d['resourceId']??$this->c['organizationId'];$row=$this->permissions->grant($this->c['sub'],$target,$perm,$resource);$this->audit('permission.granted',array('targetUserId'=>$target,'permission'=>$perm,'resourceId'=>$resource));return $this->respond(array('granted'=>TRUE,'grantId'=>$row['id']));}
 public function revoke($id){if(!$this->admin())return;if(!$this->permissions->revoke($id,$this->c['organizationId']))return $this->fail('NOT_FOUND','Permission grant not found',404);$this->audit('permission.revoked',array('grantId'=>$id));return $this->respond(array('revoked'=>TRUE));}
 public function check(){$p=(string)$this->input->get('permission');if(!in_array($p,$this->allowed,TRUE))return $this->fail('VALIDATION_ERROR','Unknown permission',422);return $this->respond(array('hasPermission'=>$this->permissions->has($this->c['sub'],$p,$this->c['organizationId'])));}
 private function admin(){if(!$this->permissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId'])){$this->fail('FORBIDDEN','Missing permission: ORG_ADMIN',403);return FALSE;}return TRUE;}
 private function audit($type,$payload){$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>$type,'payload'=>json_encode($payload),'ip_address'=>$this->input->ip_address(),'created_at'=>date('Y-m-d H:i:s')));}
}
