<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Prompt_templates extends MY_Controller {
 private $c;public function __construct(){parent::__construct();$this->c=$this->require_auth();if(!$this->c)return;$this->load->model('Prompt_template_model','templates');$this->templates->seed($this->c['organizationId'],$this->c['sub']);}
 public function index(){if($this->input->method(TRUE)==='POST'){if(!$this->valid($d=$this->body(),TRUE))return;return $this->respond($this->templates->create($this->c['organizationId'],$this->c['sub'],$d),201);}return $this->respond($this->templates->listing($this->c['organizationId'],$this->input->get('category'),trim((string)$this->input->get('q')),min(100,max(1,(int)($this->input->get('limit')?:100)))));}
 public function item($id){$method=$this->input->method(TRUE);if($method==='GET'){$r=$this->templates->one($id,$this->c['organizationId']);return $r?$this->respond($r):$this->fail('NOT_FOUND','Template not found',404);}if($method==='PATCH'){if(!$this->valid($d=$this->body(),FALSE))return;list($r,$e)=$this->templates->update_template($id,$this->c['organizationId'],$d);return $r?$this->respond($r):$this->fail($e==='built_in'?'FORBIDDEN':'NOT_FOUND',$e==='built_in'?'Built-in templates cannot be modified':'Template not found',$e==='built_in'?403:404);}$e=$this->templates->remove($id,$this->c['organizationId']);if(!$e)return $this->respond(array());return $this->fail($e==='built_in'?'FORBIDDEN':'NOT_FOUND',$e==='built_in'?'Built-in templates cannot be deleted':'Template not found',$e==='built_in'?403:404);}
 public function use_template($id){$d=$this->body();foreach($d as $v)if(!is_string($v))return $this->fail('VALIDATION_ERROR','Template variables must be strings',422);$r=$this->templates->use_template($id,$this->c['organizationId'],$this->c['sub'],$d);return $r?$this->respond($r):$this->fail('NOT_FOUND','Template not found',404);}
 public function duplicate($id){$title=trim($this->body()['title']??'');if(strlen($title)>200)return $this->fail('VALIDATION_ERROR','Title is too long',422);$r=$this->templates->duplicate($id,$this->c['organizationId'],$this->c['sub'],$title);return $r?$this->respond($r,201):$this->fail('NOT_FOUND','Template not found',404);}
 public function stats(){return $this->respond($this->templates->stats($this->c['organizationId'],min(90,max(1,(int)($this->input->get('days')?:7)))));}
 private function valid($d,$create){if($create&&(!isset($d['title'],$d['content'])))return $this->fail('VALIDATION_ERROR','Title and content are required',422);if(isset($d['title'])&&(trim($d['title'])===''||strlen($d['title'])>200)||isset($d['content'])&&($d['content']===''||strlen($d['content'])>20000)||isset($d['description'])&&strlen($d['description'])>500||isset($d['category'])&&(trim($d['category'])===''||strlen($d['category'])>40))return $this->fail('VALIDATION_ERROR','Invalid template input',422);return TRUE;}
}
