<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Settings extends MY_Controller {
 private $c;private $definitions=array('organization.default_locale'=>array('string',20),'organization.default_timezone'=>array('string',64),'organization.allow_member_invites'=>array('boolean',0),'organization.audit_retention_days'=>array('integer',0),'security.session_idle_minutes'=>array('integer',0),'security.require_mfa_admin'=>array('boolean',0));
 public function __construct(){parent::__construct();$this->load->model('Setting_model','settings');}
 public function public_index(){return $this->respond($this->settings->public_settings());}
 public function index(){if(in_array($this->input->method(TRUE),array('PATCH','PUT'),TRUE))return $this->update();$this->auth();if(!$this->c)return;$this->load->model('Permission_model','permissions');$private=$this->permissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId']);return $this->respond(array('settings'=>$this->settings->all($this->c['organizationId'],$private),'editable'=>$private?'organization':FALSE));}
 public function update(){$this->auth();if(!$this->c)return;$this->load->model('Permission_model','permissions');if(!$this->permissions->has($this->c['sub'],'ORG_ADMIN',$this->c['organizationId']))return $this->fail('FORBIDDEN','Missing permission: ORG_ADMIN',403);$d=$this->body();$changes=$d['settings']??$d;if(!is_array($changes)||!$changes)return $this->fail('VALIDATION_ERROR','Settings object is required',422);$safe=array();foreach($changes as $key=>$value){if(!isset($this->definitions[$key]))return $this->fail('VALIDATION_ERROR','Setting is not editable: '.$key,422);list($type,$max)=$this->definitions[$key];if($type==='string'&&(!is_string($value)||strlen($value)>$max))return $this->fail('VALIDATION_ERROR','Invalid value for '.$key,422);if($type==='boolean'&&!is_bool($value))return $this->fail('VALIDATION_ERROR','Invalid value for '.$key,422);if($type==='integer'&&(!is_int($value)||$value<1||$value>3650))return $this->fail('VALIDATION_ERROR','Invalid value for '.$key,422);$safe[$key]=array('value'=>$value,'type'=>$type);}if(!$this->settings->update_org($this->c['organizationId'],$this->c['sub'],$safe))return $this->fail('DATABASE_ERROR','Settings could not be saved',500);$this->db->insert('audit_events',array('organization_id'=>$this->c['organizationId'],'user_id'=>$this->c['sub'],'event_type'=>'system.config_change','payload'=>json_encode(array('keys'=>array_keys($safe),'resourceType'=>'organization','resourceId'=>$this->c['organizationId'])),'ip_address'=>$this->input->ip_address(),'user_agent'=>substr((string)$this->input->user_agent(),0,500),'created_at'=>date('Y-m-d H:i:s')));return $this->respond(array('settings'=>$this->settings->all($this->c['organizationId'],TRUE),'updated'=>array_keys($safe)));}
 private function auth(){$this->c=$this->require_auth();}
}
