ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "whiteLabel" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "organizationId" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "apiKeyId" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
