/** Session 108 — dedicated Camera Feed registry and alert console. */
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { AlertTriangle, Camera as CameraIcon, CheckCircle2, Eye, Plus, RefreshCw, ShieldCheck, Trash2, Video } from "lucide-react";
import { cameraApi, type CamAlert, type CamFeed, type CamStatus, type CamStreamSession } from "@/lib/camera";
import { useAuthStore } from "@/store/auth";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";

const STATUSES: CamStatus[] = ["online", "offline", "degraded", "maintenance"];
const SEVERITIES: CamAlert["severity"][] = ["info", "warning", "critical"];
function Stat({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg border border-crimson/20 bg-crimson/10 p-2 text-crimson">{icon}</div><div><div className="text-2xl font-black text-text-bright">{value}</div><div className="text-xs text-text-muted">{label}</div></div></CardContent></Card>; }
function statusVariant(status: string): "emerald" | "amber" | "crimson" | "slate" { return status === "online" ? "emerald" : status === "degraded" || status === "maintenance" ? "amber" : status === "offline" ? "slate" : "crimson"; }

export function CameraPage() {
  const user = useAuthStore((state) => state.user);
  const canWrite = user?.role === "admin" || user?.role === "super_admin";
  const [feeds, setFeeds] = useState<CamFeed[]>([]);
  const [selected, setSelected] = useState<CamFeed | null>(null);
  const [alerts, setAlerts] = useState<CamAlert[]>([]);
  const [stream, setStream] = useState<CamStreamSession | null>(null);
  const [form, setForm] = useState({ name: "", streamUrl: "", locationName: "", resolution: "1920x1080" });
  const [alertForm, setAlertForm] = useState({ severity: "warning" as CamAlert["severity"], triggerClass: "", metadata: "{}" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const load = useCallback(async () => { setLoading(true); try { setFeeds(await cameraApi.listFeeds()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 3000); };
  async function selectFeed(feed: CamFeed) { setSelected(feed); setStream(null); try { setAlerts(await cameraApi.listAlerts(feed.id)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function create() { if (!form.name || !form.streamUrl) return; try { const feed = await cameraApi.createFeed(form); setForm({ name: "", streamUrl: "", locationName: "", resolution: "1920x1080" }); flash("Camera feed registered."); await load(); await selectFeed(feed); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function status(feed: CamFeed, next: CamStatus) { try { const updated = await cameraApi.updateFeed(feed.id, { status: next }); setFeeds((current) => current.map((item) => item.id === feed.id ? updated : item)); if (selected?.id === feed.id) setSelected(updated); flash("Feed status updated."); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function remove(feed: CamFeed) { if (!confirm(`Delete ${feed.name} and its alerts?`)) return; try { await cameraApi.deleteFeed(feed.id); setSelected(null); setAlerts([]); flash("Feed deleted."); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function openStream(feed: CamFeed) { try { setStream(await cameraApi.getStream(feed.id)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function triggerAlert() { if (!selected || !alertForm.triggerClass) return; try { let metadata: Record<string, unknown> = {}; try { metadata = JSON.parse(alertForm.metadata); } catch { throw new Error("Alert metadata must be valid JSON"); } const alert = await cameraApi.triggerAlert(selected.id, { severity: alertForm.severity, triggerClass: alertForm.triggerClass, metadata }); setAlerts((current) => [alert, ...current]); setAlertForm({ ...alertForm, triggerClass: "" }); flash("Alert recorded."); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }

  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CameraIcon className="h-6 w-6 text-crimson" /><h1 className="text-2xl font-black text-text-bright">Camera Intelligence</h1><Badge variant="crimson">advisory feed registry</Badge></div><p className="mt-1 max-w-3xl text-sm text-text-muted">Manage org-scoped RTSP/RTMP feed metadata and operator/model alerts. Live decoding requires an external media gateway; configuration alone is never shown as a live stream.</p></div><Button size="sm" variant="outline" onClick={() => void load()} loading={loading}><RefreshCw className="h-4 w-4" />Refresh</Button></div>
    {error ? <div className="rounded-lg border border-crimson/30 bg-crimson/10 px-4 py-3 text-sm text-crimson">{error}<button className="float-right" onClick={() => setError(null)}>✕</button></div> : null}{notice ? <div className="rounded-lg border border-emerald/30 bg-emerald/10 px-4 py-3 text-sm text-emerald">{notice}</div> : null}
    <div className="grid grid-cols-1 gap-3 md:grid-cols-3"><Stat icon={<Video className="h-5 w-5" />} label="Feeds" value={String(feeds.length)} /><Stat icon={<CheckCircle2 className="h-5 w-5" />} label="Online" value={String(feeds.filter((feed) => feed.status === "online").length)} /><Stat icon={<AlertTriangle className="h-5 w-5" />} label="Alerts selected" value={String(alerts.length)} /></div>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle>Feed registry</CardTitle><CardDescription>Feed status is an observed/admin-entered state; offline is the safe default.</CardDescription></CardHeader><CardContent><div className="space-y-2">{feeds.map((feed) => <div key={feed.id} onClick={() => void selectFeed(feed)} className={`cursor-pointer rounded-lg border p-3 ${selected?.id === feed.id ? "border-azure/40 bg-azure/10" : "border-white/10 bg-white/5"}`}><div className="flex flex-wrap items-center gap-2"><CameraIcon className="h-4 w-4 text-crimson" /><span className="flex-1 font-medium text-text-bright">{feed.name}</span><Badge variant={statusVariant(feed.status)}>{feed.status}</Badge>{canWrite ? <Select className="w-32" value={feed.status} onClick={(e) => e.stopPropagation()} onChange={(e) => void status(feed, e.target.value as CamStatus)}>{STATUSES.map((item) => <option key={item} value={item}>{item}</option>)}</Select> : null}<span className="text-xs text-text-muted">{feed.locationName || "No location"}</span></div><div className="mt-1 truncate font-mono text-xs text-text-muted">{feed.streamUrl}</div>{selected?.id === feed.id && canWrite ? <div className="mt-2 text-right"><Button size="sm" variant="danger" onClick={(e) => { e.stopPropagation(); void remove(feed); }}><Trash2 className="h-3 w-3" />Delete feed</Button></div> : null}</div>)}{feeds.length === 0 ? <p className="py-8 text-center text-sm text-text-muted">No camera feeds recorded for this organization.</p> : null}</div></CardContent></Card>{canWrite ? <Card><CardHeader><CardTitle className="text-base">Register feed</CardTitle><CardDescription>Credentials should be supplied through a protected gateway; they are not rendered in this UI.</CardDescription></CardHeader><CardContent className="space-y-2"><Input placeholder="Feed name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input placeholder="rtsp:// or rtmp:// URL" value={form.streamUrl} onChange={(e) => setForm({ ...form, streamUrl: e.target.value })} /><Input placeholder="Location" value={form.locationName} onChange={(e) => setForm({ ...form, locationName: e.target.value })} /><Input placeholder="Resolution" value={form.resolution} onChange={(e) => setForm({ ...form, resolution: e.target.value })} /><Button className="w-full" onClick={() => void create()}><Plus className="h-4 w-4" />Register feed</Button></CardContent></Card> : <Card><CardContent className="p-5 text-sm text-text-muted">Read-only view. Administrator access is required to change feed configuration.</CardContent></Card>}</div>
    {selected ? <><Card><CardHeader><CardTitle className="flex items-center gap-2"><Eye className="h-5 w-5 text-azure" />Stream handoff — {selected.name}</CardTitle><CardDescription>A token is not a live stream. The response reports whether the external media gateway is configured and the feed is online.</CardDescription></CardHeader><CardContent><Button onClick={() => void openStream(selected)}>Request 60-second stream session</Button>{stream ? <div className="mt-3 rounded border border-white/10 bg-white/5 p-3 text-xs"><div className="flex gap-2"><Badge variant={stream.streamAvailable ? "emerald" : "amber"}>{stream.streamAvailable ? "gateway handoff available" : "media unavailable"}</Badge><Badge variant={stream.turnConfigured ? "emerald" : "amber"}>{stream.turnConfigured ? "TURN configured" : "STUN only"}</Badge></div><div className="mt-2 text-text-muted">{stream.note} Expires {new Date(stream.expiresAt).toLocaleTimeString()}.</div></div> : null}</CardContent></Card><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle>Alert timeline</CardTitle><CardDescription>Alerts are advisory records and require operator review before action.</CardDescription></CardHeader><CardContent><div className="space-y-2">{alerts.map((alert) => <div key={alert.id} className="rounded border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><Badge variant={alert.severity === "critical" ? "crimson" : alert.severity === "warning" ? "amber" : "azure"}>{alert.severity}</Badge><span className="font-medium text-text-bright">{alert.triggerClass}</span><span className="ml-auto text-xs text-text-muted">{new Date(alert.createdAt).toLocaleString()}</span></div><div className="mt-1 text-xs text-text-muted">{JSON.stringify(alert.metadata)}</div></div>)}{alerts.length === 0 ? <p className="py-8 text-center text-sm text-text-muted">No alerts recorded for this feed.</p> : null}</div></CardContent></Card>{canWrite ? <Card><CardHeader><CardTitle className="text-base">Record advisory alert</CardTitle><CardDescription>Use this for a real model/operator observation; no verdict is fabricated.</CardDescription></CardHeader><CardContent className="space-y-2"><Select value={alertForm.severity} onChange={(e) => setAlertForm({ ...alertForm, severity: e.target.value as CamAlert["severity"] })}>{SEVERITIES.map((severity) => <option key={severity} value={severity}>{severity}</option>)}</Select><Input placeholder="Trigger class" value={alertForm.triggerClass} onChange={(e) => setAlertForm({ ...alertForm, triggerClass: e.target.value })} /><Textarea rows={3} placeholder="Metadata JSON" value={alertForm.metadata} onChange={(e) => setAlertForm({ ...alertForm, metadata: e.target.value })} /><Button className="w-full" onClick={() => void triggerAlert()}><Plus className="h-4 w-4" />Record alert</Button></CardContent></Card> : null}</div></> : null}
    <Card><CardContent className="flex items-start gap-2 p-4 text-xs text-text-muted"><ShieldCheck className="h-4 w-4 shrink-0 text-emerald" />No automatic safety action is executed by this registry. Live inference, snapshots, privacy redaction and downstream dispatch require the external approved camera pipeline.</CardContent></Card>
  </div>;
}
