import { Router } from "express";
import { z } from "zod";
import { requireScope } from "../middleware/apiKeyAuth.js";
import { validate } from "../middleware/validate.js";
import { apiProductQuota } from "../middleware/nativeAiQuota.js";
import { CloudAndroidAppInstallSchema, CloudAndroidAppLaunchSchema, CloudAndroidDeviceConfigSchema, CloudAndroidSessionSchema, CloudAndroidUiActionSchema } from "@windels/shared/cloudAndroid";
import { CloudAndroidOrchestrator, type CloudAndroidActor } from "../../cloudAndroid/orchestrator.service.js";

const Id = z.object({ id: z.string().cuid() });
function actor(req: any): CloudAndroidActor { return { organizationId: req.apiOrganization.id, userId: req.apiUser.id, apiKeyId: req.apiKey.id, agentId: req.body?.agentId ?? req.query?.agentId }; }
function usage(res: any, endpoint: string, permission: string, extra: Record<string, unknown> = {}) { res.locals = { ...(res.locals ?? {}), apiUsage: { ...(res.locals?.apiUsage ?? {}), endpoint, channel: "cloud-android", productSlug: "cloud-android", permission, ...extra } }; }

/** API-key surface mounted below the already-authenticated top-level /v1 router. */
export function registerCloudAndroidPublicRoutes(router: Router) {
  router.use("/cloud-android", apiProductQuota("cloud-android"));
  router.get("/cloud-android/devices", requireScope("cloud-android:read"), async (req, res, next) => { try { usage(res, "cloud-android.devices.list", "cloud-android:read"); res.json({ object: "list", data: await CloudAndroidOrchestrator.listDevices(actor(req)) }); } catch (error) { next(error); } });
  router.post("/cloud-android/devices", requireScope("cloud-android:manage"), validate({ body: CloudAndroidDeviceConfigSchema }), async (req, res, next) => { try { usage(res, "cloud-android.devices.create", "cloud-android:manage"); res.status(201).json(await CloudAndroidOrchestrator.createDevice(actor(req), req.body)); } catch (error) { next(error); } });
  router.get("/cloud-android/devices/:id", requireScope("cloud-android:read"), validate({ params: Id }), async (req, res, next) => { try { usage(res, "cloud-android.devices.get", "cloud-android:read"); res.json(await CloudAndroidOrchestrator.getDevice(actor(req), req.params.id)); } catch (error) { next(error); } });
  for (const command of ["start", "stop", "restart"] as const) router.post(`/cloud-android/devices/:id/${command}`, requireScope("cloud-android:control"), validate({ params: Id }), async (req, res, next) => { try { usage(res, `cloud-android.devices.${command}`, "cloud-android:control"); res.json(await CloudAndroidOrchestrator.lifecycle(actor(req), req.params.id, command)); } catch (error) { next(error); } });
  router.post("/cloud-android/devices/:id/sessions", requireScope("cloud-android:control"), validate({ params: Id, body: CloudAndroidSessionSchema }), async (req, res, next) => { try { usage(res, "cloud-android.sessions.create", "cloud-android:control"); res.status(201).json(await CloudAndroidOrchestrator.startSession(actor(req), req.params.id, req.body)); } catch (error) { next(error); } });

  router.post("/cloud-android/devices/:id/apps/install", requireScope("cloud-android:apps"), validate({ params: Id, body: CloudAndroidAppInstallSchema.extend({ sessionId: z.string().cuid(), agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { usage(res, "cloud-android.apps.install", "cloud-android:apps"); res.json(await CloudAndroidOrchestrator.executeManagedAction(actor(req), req.params.id, req.body.sessionId, "app.install", req.body)); } catch (error) { next(error); } });
  router.post("/cloud-android/devices/:id/apps/launch", requireScope("cloud-android:apps"), validate({ params: Id, body: CloudAndroidAppLaunchSchema.extend({ sessionId: z.string().cuid(), agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { usage(res, "cloud-android.apps.launch", "cloud-android:apps"); res.json(await CloudAndroidOrchestrator.executeManagedAction(actor(req), req.params.id, req.body.sessionId, "app.launch", req.body)); } catch (error) { next(error); } });

  const ui = (type: "tap" | "type" | "swipe") => async (req: any, res: any, next: any) => { try { usage(res, `cloud-android.ui.${type}`, "cloud-android:control"); const action = CloudAndroidUiActionSchema.parse({ type, ...req.body }); res.json(await CloudAndroidOrchestrator.executeUiAction(actor(req), req.params.id, req.body.sessionId, action)); } catch (error) { next(error); } };
  router.post("/cloud-android/devices/:id/ui/tap", requireScope("cloud-android:control"), validate({ params: Id, body: z.object({ sessionId: z.string().cuid(), agentId: z.string().cuid().optional(), elementId: z.string().optional(), x: z.number().int().nonnegative().optional(), y: z.number().int().nonnegative().optional(), intendedAction: z.string().max(500).optional() }) }), ui("tap"));
  router.post("/cloud-android/devices/:id/ui/type", requireScope("cloud-android:control"), validate({ params: Id, body: z.object({ sessionId: z.string().cuid(), agentId: z.string().cuid().optional(), elementId: z.string().optional(), text: z.string().max(20_000), replace: z.boolean().optional(), intendedAction: z.string().max(500).optional() }) }), ui("type"));
  router.post("/cloud-android/devices/:id/ui/swipe", requireScope("cloud-android:control"), validate({ params: Id, body: z.object({ sessionId: z.string().cuid(), agentId: z.string().cuid().optional(), startX: z.number().int().nonnegative(), startY: z.number().int().nonnegative(), endX: z.number().int().nonnegative(), endY: z.number().int().nonnegative(), durationMs: z.number().int().optional() }) }), ui("swipe"));

  router.get("/cloud-android/devices/:id/screen", requireScope("cloud-android:read"), validate({ params: Id }), async (req, res, next) => { try { usage(res, "cloud-android.screen", "cloud-android:read"); res.json(await CloudAndroidOrchestrator.observe(actor(req), req.params.id)); } catch (error) { next(error); } });
  router.post("/cloud-android/devices/:id/snapshot", requireScope("cloud-android:manage"), validate({ params: Id, body: z.object({ name: z.string().min(2).max(100) }) }), async (req, res, next) => { try { usage(res, "cloud-android.snapshots.create", "cloud-android:manage"); res.status(201).json(await CloudAndroidOrchestrator.snapshot(actor(req), req.params.id, req.body.name)); } catch (error) { next(error); } });
  router.get("/cloud-android/sessions", requireScope("cloud-android:read"), async (req, res, next) => { try { usage(res, "cloud-android.sessions.list", "cloud-android:read"); res.json({ object: "list", data: await CloudAndroidOrchestrator.listSessions(actor(req)) }); } catch (error) { next(error); } });
  router.get("/cloud-android/audit", requireScope("cloud-android:read"), async (req, res, next) => { try { usage(res, "cloud-android.audit", "cloud-android:read"); res.json({ object: "list", data: await CloudAndroidOrchestrator.listAudit(actor(req)) }); } catch (error) { next(error); } });
  router.get("/cloud-android/approvals", requireScope("cloud-android:read"), async (req, res, next) => { try { usage(res, "cloud-android.approvals.list", "cloud-android:read"); res.json({ object: "list", data: await CloudAndroidOrchestrator.listApprovals(actor(req)) }); } catch (error) { next(error); } });
  router.post("/cloud-android/approvals/:id/decision", requireScope("cloud-android:approve"), validate({ params: Id, body: z.object({ decision: z.enum(["APPROVED", "REJECTED"]), note: z.string().max(1000).optional() }) }), async (req, res, next) => { try { usage(res, "cloud-android.approvals.decision", "cloud-android:approve"); res.json(await CloudAndroidOrchestrator.decideApproval(actor(req), req.params.id, req.body.decision, req.body.note)); } catch (error) { next(error); } });
}
