import { Router } from "express";
import { z } from "zod";
import { Permission } from "@prisma/client";
import { authenticate, requireAdmin } from "../middleware/auth.js";
import { validate } from "../middleware/validate.js";
import { requirePerm } from "../../services/permissions.service.js";
import { CloudAndroidAgentGrantSchema, CloudAndroidApprovalDecisionSchema, CloudAndroidBulkSchema, CloudAndroidDeviceConfigSchema, CloudAndroidSessionSchema, CloudAndroidTemplateSchema, CloudAndroidUiActionSchema, CloudAndroidAppInstallSchema, CloudAndroidAppLaunchSchema } from "@windels/shared/cloudAndroid";
import { CloudAndroidOrchestrator, type CloudAndroidActor } from "../../cloudAndroid/orchestrator.service.js";
import { AppError } from "../../utils/result.js";

const Id = z.object({ id: z.string().cuid() });
const SessionId = z.object({ id: z.string().cuid(), sessionId: z.string().cuid() });
const ApprovalId = z.object({ id: z.string().cuid() });
function actor(req: any): CloudAndroidActor { if (!req.user?.organizationId) throw AppError.forbidden("Organization context required"); return { organizationId: req.user.organizationId, userId: req.user.id, agentId: req.body?.agentId ?? req.query?.agentId }; }
function meta(req: any) { return { requestId: req.requestId, tookMs: Date.now() - req.startedAt }; }

/** Authenticated WINDELS application control plane. */
export function registerCloudAndroidRoutes(parent: Router) {
  const router = Router(); router.use(authenticate);
  router.get("/status", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.status(), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/dashboard", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.fleetDashboard(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/devices", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listDevices(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ body: CloudAndroidDeviceConfigSchema }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.createDevice(actor(req), req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/devices/:id", requirePerm(Permission.CLOUD_ANDROID_READ), validate({ params: Id }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.getDevice(actor(req), req.params.id), meta: meta(req) }); } catch (error) { next(error); } });
  for (const command of ["start", "stop", "restart", "delete"] as const) router.post(`/devices/:id/${command}`, requirePerm(command === "delete" ? Permission.CLOUD_ANDROID_MANAGE : Permission.CLOUD_ANDROID_CONTROL), validate({ params: Id }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.lifecycle(actor(req), req.params.id, command), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/devices/:id/screen", requirePerm(Permission.CLOUD_ANDROID_READ), validate({ params: Id }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.observe(actor(req), req.params.id), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/devices/:id/metrics", requirePerm(Permission.CLOUD_ANDROID_READ), validate({ params: Id }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.metrics(actor(req), req.params.id), meta: meta(req) }); } catch (error) { next(error); } });

  router.post("/devices/:id/agents", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ params: Id, body: CloudAndroidAgentGrantSchema }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.assignAgent(actor(req), req.params.id, req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices/:id/sessions", requirePerm(Permission.CLOUD_ANDROID_CONTROL), validate({ params: Id, body: CloudAndroidSessionSchema }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.startSession(actor(req), req.params.id, req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/sessions/:id/takeover", requirePerm(Permission.CLOUD_ANDROID_CONTROL), validate({ params: Id, body: z.object({ controller: z.enum(["HUMAN", "AGENT"]), agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.takeover({ ...actor(req), agentId: req.body.agentId }, req.params.id, req.body.controller), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/sessions/:id/end", requirePerm(Permission.CLOUD_ANDROID_CONTROL), validate({ params: Id, body: z.object({ result: z.record(z.unknown()).default({}) }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.endSession(actor(req), req.params.id, req.body.result), meta: meta(req) }); } catch (error) { next(error); } });

  router.post("/devices/:id/sessions/:sessionId/ui", requirePerm(Permission.CLOUD_ANDROID_CONTROL), validate({ params: SessionId, body: z.object({ action: CloudAndroidUiActionSchema, agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.executeUiAction({ ...actor(req), agentId: req.body.agentId }, req.params.id, req.params.sessionId, req.body.action), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices/:id/sessions/:sessionId/apps/install", requirePerm(Permission.CLOUD_ANDROID_APP), validate({ params: SessionId, body: CloudAndroidAppInstallSchema.extend({ agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.executeManagedAction({ ...actor(req), agentId: req.body.agentId }, req.params.id, req.params.sessionId, "app.install", req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices/:id/sessions/:sessionId/apps/launch", requirePerm(Permission.CLOUD_ANDROID_APP), validate({ params: SessionId, body: CloudAndroidAppLaunchSchema.extend({ agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.executeManagedAction({ ...actor(req), agentId: req.body.agentId }, req.params.id, req.params.sessionId, "app.launch", req.body), meta: meta(req) }); } catch (error) { next(error); } });
  for (const command of ["uninstall", "stop", "list"] as const) router.post(`/devices/:id/sessions/:sessionId/apps/${command}`, requirePerm(Permission.CLOUD_ANDROID_APP), validate({ params: SessionId, body: z.object({ packageName: command === "list" ? z.string().optional() : z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*(?:\.[a-zA-Z0-9_]+)+$/), agentId: z.string().cuid().optional() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.executeManagedAction({ ...actor(req), agentId: req.body.agentId }, req.params.id, req.params.sessionId, `app.${command}`, req.body), meta: meta(req) }); } catch (error) { next(error); } });

  router.get("/sessions", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listSessions(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/approvals", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listApprovals(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/approvals/:id/decision", requirePerm(Permission.CLOUD_ANDROID_SENSITIVE), validate({ params: ApprovalId, body: CloudAndroidApprovalDecisionSchema }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.decideApproval(actor(req), req.params.id, req.body.decision, req.body.note), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/audit", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listAudit(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });

  router.get("/images", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listImages(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/images", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ body: z.object({ sourceDeviceId: z.string().cuid(), name: z.string().min(2).max(100), version: z.string().regex(/^\d+\.\d+\.\d+$/) }) }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.createImage(actor(req), req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.get("/templates", requirePerm(Permission.CLOUD_ANDROID_READ), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.listTemplates(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/templates", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ body: CloudAndroidTemplateSchema }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.createTemplate(actor(req), req.body), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices/:id/snapshot", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ params: Id, body: z.object({ name: z.string().min(2).max(100) }) }), async (req, res, next) => { try { res.status(201).json({ ok: true, data: await CloudAndroidOrchestrator.snapshot(actor(req), req.params.id, req.body.name), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/devices/:id/restore", requirePerm(Permission.CLOUD_ANDROID_MANAGE), validate({ params: Id, body: z.object({ snapshotId: z.string().cuid() }) }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.restoreSnapshot(actor(req), req.params.id, req.body.snapshotId), meta: meta(req) }); } catch (error) { next(error); } });
  for (const command of ["start", "stop", "restart", "delete"] as const) router.post(`/fleet/${command}`, requireAdmin, requirePerm(Permission.CLOUD_ANDROID_ADMIN), validate({ body: CloudAndroidBulkSchema }), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.bulkLifecycle(actor(req), req.body.deviceIds, command), meta: meta(req) }); } catch (error) { next(error); } });
  router.post("/fleet/reconcile", requireAdmin, requirePerm(Permission.CLOUD_ANDROID_ADMIN), async (req, res, next) => { try { res.json({ ok: true, data: await CloudAndroidOrchestrator.reconcileHealth(actor(req)), meta: meta(req) }); } catch (error) { next(error); } });

  parent.use("/cloud-android", router);
}
