import { prisma } from "../db/client.js";
import { AppError } from "../utils/result.js";
import { resolveUserContext } from "./workspace.service.js";
import { z } from "zod";
import type { PaginationQuery } from "@windels/shared/api";
import {
  WorkflowStatus,
  WorkflowRunStatus,
} from "@prisma/client";
import { aiRegistry } from "./ai/registry.js";
import { EventBus } from "./eventBus.js";

// Lazy import to avoid circular dependency at module load; emit to webhooks AND in-process EventBus.
function dispatch(event: string, orgId: string, payload: Record<string, any>) {
  const full = { ...payload, organizationId: orgId };
  import("./webhook.service.js").then(({ dispatchEvent }) => dispatchEvent(orgId, event, full)).catch(() => {});
  EventBus.emit(event, full).catch(() => {});
}

// String-literal enums for types stored only in JSON columns (not generated by Prisma).
export const WorkflowNodeType = {
  TRIGGER: "TRIGGER",
  ACTION: "ACTION",
  AI: "AI",
  CONDITION: "CONDITION",
  LOOP: "LOOP",
  APPROVAL: "APPROVAL",
  DELAY: "DELAY",
  END: "END",
} as const;
export type WorkflowNodeType = typeof WorkflowNodeType[keyof typeof WorkflowNodeType];

export const NodeRunStatus = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  RETRYING: "RETRYING",
} as const;
export type NodeRunStatus = typeof NodeRunStatus[keyof typeof NodeRunStatus];

// ─── Schema ─────────────────────────────────────────────────────
export const NodeShape = z.object({
  id: z.string().min(1),
  type: z.enum(["TRIGGER", "ACTION", "AI", "CONDITION", "LOOP", "APPROVAL", "DELAY", "END"]),
  x: z.number().default(0),
  y: z.number().default(0),
  label: z.string().min(1).max(120),
  config: z.record(z.any()).default({}),
});
export type FlowNode = z.infer<typeof NodeShape>;

export const EdgeShape = z.object({
  id: z.string().min(1),
  fromId: z.string().min(1),
  toId: z.string().min(1),
  label: z.string().optional(),
  condition: z.string().optional(), // e.g. "true" / "false"
});
export type FlowEdge = z.infer<typeof EdgeShape>;

export const CreateWorkflowSchema = z.object({
  name: z.string().min(1).max(120),
  description: z.string().max(500).optional(),
  workspaceId: z.string().cuid().optional(),
  nodes: z.array(NodeShape).default([]),
  edges: z.array(EdgeShape).default([]),
  triggers: z.array(z.object({
    type: z.enum(["manual", "schedule", "event", "webhook", "api"]),
    config: z.record(z.any()).default({}),
  })).default([{ type: "manual", config: {} }]),
  settings: z.object({
    retryCount: z.number().int().min(0).max(10).default(1),
    retryDelayMs: z.number().int().min(0).default(1000),
    agentId: z.string().cuid().optional(),
    notifyOnFailure: z.boolean().default(true),
  }).default({}),
});

export const UpdateWorkflowSchema = z.object({
  name: z.string().min(1).max(120).optional(),
  description: z.string().max(500).optional(),
  nodes: z.array(NodeShape).optional(),
  edges: z.array(EdgeShape).optional(),
  triggers: z.array(z.object({
    type: z.enum(["manual", "schedule", "event", "webhook", "api"]),
    config: z.record(z.any()).default({}),
  })).optional(),
  settings: z.record(z.any()).optional(),
  status: z.enum(["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]).optional(),
});

export const RunWorkflowSchema = z.object({
  input: z.record(z.any()).default({}),
  triggerType: z.enum(["manual", "schedule", "event", "webhook", "api"]).default("manual"),
  triggerData: z.record(z.any()).default({}),
});

// ─── Helpers ────────────────────────────────────────────────────
function topo(nodes: FlowNode[], edges: FlowEdge[]): string[] {
  const indeg = new Map<string, number>();
  const adj = new Map<string, string[]>();
  for (const n of nodes) { indeg.set(n.id, 0); adj.set(n.id, []); }
  for (const e of edges) {
    if (!indeg.has(e.fromId) || !indeg.has(e.toId)) continue;
    adj.get(e.fromId)!.push(e.toId);
    indeg.set(e.toId, (indeg.get(e.toId) ?? 0) + 1);
  }
  const queue: string[] = [];
  for (const [id, d] of indeg) if (d === 0) queue.push(id);
  const order: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    order.push(id);
    for (const next of adj.get(id) ?? []) {
      indeg.set(next, (indeg.get(next) ?? 1) - 1);
      if (indeg.get(next) === 0) queue.push(next);
    }
  }
  return order;
}

async function executeNode(
  node: FlowNode,
  context: Record<string, any>,
  orgId: string,
  signal: AbortSignal,
): Promise<{ output: any; status: NodeRunStatus; error?: string }> {
  const startedAt = new Date();
  try {
    switch (node.type) {
      case "TRIGGER":
        return { output: context.input ?? {}, status: NodeRunStatus.SUCCEEDED };
      case "END":
        return {
          output: { completed: true, finishedAt: new Date().toISOString() },
          status: NodeRunStatus.SUCCEEDED,
        };
      case "DELAY": {
        const ms = Math.min((node.config.delayMs ?? 1000), 60_000);
        await new Promise((r) => setTimeout(r, ms));
        return { output: { delayed: ms }, status: NodeRunStatus.SUCCEEDED };
      }
      case "ACTION": {
        // Built-in actions: sendMessage, createTask, createActionItem, httpRequest, log
        const action = node.config.action as string;
        switch (action) {
          case "log":
            return { output: { logged: node.config.message ?? "" }, status: NodeRunStatus.SUCCEEDED };
          case "createTask": {
            const title = renderTemplate(String(node.config.title ?? "Workflow task"), context);
            const t = await prisma.task.create({
              data: {
                organizationId: orgId,
                title,
                description: renderTemplate(String(node.config.description ?? ""), context),
                priority: (node.config.priority as any) ?? "MEDIUM",
                agentId: node.config.agentId ?? null,
                creatorId: context.__createdById,
              },
            });
            return { output: { taskId: t.id, title: t.title }, status: NodeRunStatus.SUCCEEDED };
          }
          case "createActionItem": {
            const a = await prisma.actionItem.create({
              data: {
                organizationId: orgId,
                title: renderTemplate(String(node.config.title ?? "Action item"), context),
                description: renderTemplate(String(node.config.description ?? ""), context),
                priority: (node.config.priority as any) ?? "MEDIUM",
                channelId: node.config.channelId ?? null,
                assigneeId: node.config.assigneeId ?? null,
                createdById: context.__createdById,
              },
            });
            return { output: { actionItemId: a.id }, status: NodeRunStatus.SUCCEEDED };
          }
          case "sendMessage": {
            const chId = node.config.channelId as string | undefined;
            if (!chId) throw AppError.badRequest("sendMessage requires channelId");
            const content = renderTemplate(String(node.config.message ?? "(workflow message)"), context);
            const msg = await prisma.talkMessage.create({
              data: { channelId: chId, type: "TEXT" as any, content, userId: context.__createdById },
            });
            await prisma.talkChannel.update({ where: { id: chId }, data: { lastMessageAt: new Date() } });
            return { output: { messageId: msg.id }, status: NodeRunStatus.SUCCEEDED };
          }
          case "httpRequest": {
            const url = String(node.config.url ?? "");
            if (!url) throw AppError.badRequest("httpRequest requires url");
            const method = String(node.config.method ?? "GET").toUpperCase();
            const headers: Record<string, string> = { "Content-Type": "application/json" };
            if (node.config.headers) Object.assign(headers, node.config.headers);
            let body: string | undefined;
            if (method !== "GET" && node.config.body) body = JSON.stringify(renderObject(node.config.body, context));
            const resp = await fetch(url, { method, headers, body, signal });
            const text = await resp.text();
            let json: any = undefined;
            try { json = JSON.parse(text); } catch { json = text; }
            if (!resp.ok) return { output: { status: resp.status, body: json }, status: NodeRunStatus.FAILED, error: `HTTP ${resp.status}` };
            return { output: { status: resp.status, body: json }, status: NodeRunStatus.SUCCEEDED };
          }
          default:
            return { output: { note: `No-op action: ${action ?? "none"}` }, status: NodeRunStatus.SUCCEEDED };
        }
      }
      case "AI": {
        const modelId = node.config.modelId as string | undefined;
        const resolved = aiRegistry.resolve(modelId);
        if (!resolved) {
          return { output: { error: "AI PROVIDER CONFIGURATION REQUIRED" }, status: NodeRunStatus.FAILED };
        }
        const sys = node.config.systemPrompt as string | undefined
          ?? `You are a workflow AI node. Execute the instruction using the provided context and return JSON only.`;
        const prompt = renderTemplate(String(node.config.prompt ?? node.label), context);
        let out = "";
        for await (const chunk of aiRegistry.guardedStream({
          model: resolved.model.id,
          messages: [
            { role: "system", content: sys },
            { role: "user", content: `${prompt}\n\nContext: ${JSON.stringify(context).slice(0, 4000)}` },
          ],
          stream: true,
          signal,
        }, { userId: context.__createdById, feature: "workflow-ai-node" })) {
          if (chunk.type === "token") out += chunk.text ?? "";
        }
        // Try parse JSON; fall back to raw string
        let parsed: any = out.trim();
        try { parsed = JSON.parse(out); } catch { /* keep string */ }
        return { output: { result: parsed, raw: out }, status: NodeRunStatus.SUCCEEDED };
      }
      case "CONDITION": {
        const expr = String(node.config.expr ?? "true");
        // Safe-ish condition eval: only supports equality + truthy on context paths.
        const result = evalCondition(expr, context);
        return { output: { result }, status: NodeRunStatus.SUCCEEDED };
      }
      case "LOOP": {
        const over = resolvePath(context, String(node.config.collectionPath ?? "items")) ?? [];
        const items = Array.isArray(over) ? over : [];
        const results: any[] = [];
        const maxItems = Math.min(items.length, 20);
        for (let i = 0; i < maxItems; i++) results.push({ index: i, item: items[i] });
        return { output: { iterations: results, count: results.length }, status: NodeRunStatus.SUCCEEDED };
      }
      case "APPROVAL": {
        // In MVP this pauses the run waiting on human. For synchronous execution in this slice we
        // treat it as immediately approved unless settings.autoApprove is false, in which case we
        // mark the run as WAITING_APPROVAL.
        if (node.config.requireHuman) {
          return { output: { approved: false, pending: true }, status: NodeRunStatus.WAITING_APPROVAL };
        }
        return { output: { approved: true }, status: NodeRunStatus.SUCCEEDED };
      }
      default:
        return { output: null, status: NodeRunStatus.SKIPPED };
    }
  } catch (err: any) {
    return { output: null, status: NodeRunStatus.FAILED, error: err?.message ?? String(err) };
  } finally {
    void startedAt;
  }
}

function evalCondition(expr: string, ctx: any): boolean {
  // Tiny, sandboxed condition: supports "a.b == 'x'", "a.b", "a.b > 2", "true", "false".
  const m = expr.match(/^([\w.]+)\s*(==|!=|>=|<=|>|<)\s*(.+)$/);
  if (!m) return !!resolvePath(ctx, expr);
  const [, path, op, rawVal] = m;
  const left = resolvePath(ctx, path!);
  let right: any = rawVal!.trim();
  if ((right.startsWith("'") && right.endsWith("'")) || (right.startsWith('"') && right.endsWith('"'))) right = right.slice(1, -1);
  else if (!isNaN(Number(right))) right = Number(right);
  else if (right === "true") right = true;
  else if (right === "false") right = false;
  switch (op) {
    case "==": return left == right;
    case "!=": return left != right;
    case ">": return Number(left) > Number(right);
    case "<": return Number(left) < Number(right);
    case ">=": return Number(left) >= Number(right);
    case "<=": return Number(left) <= Number(right);
  }
  return false;
}

function resolvePath(obj: any, path: string): any {
  return path.split(".").reduce((acc, k) => (acc == null ? acc : acc[k]), obj);
}

function renderTemplate(tmpl: string, ctx: any): string {
  return tmpl.replace(/\{\{\s*([\w.]+)(?:\s*\|[^}]*)?\s*\}\}/g, (_m, p) => {
    const v = resolvePath(ctx, p);
    return v == null ? "" : String(v);
  });
}
function renderObject(obj: any, ctx: any): any {
  if (typeof obj === "string") return renderTemplate(obj, ctx);
  if (Array.isArray(obj)) return obj.map((v) => renderObject(v, ctx));
  if (obj && typeof obj === "object") {
    const out: Record<string, any> = {};
    for (const [k, v] of Object.entries(obj)) out[k] = renderObject(v, ctx);
    return out;
  }
  return obj;
}

// ─── CRUD ───────────────────────────────────────────────────────
export async function listWorkflows(userId: string, q: PaginationQuery & { status?: string }) {
  const ctx = await resolveUserContext(userId);
  const where: any = { organizationId: ctx.organizationId, deletedAt: null };
  if (q.status) where.status = q.status;
  const [items, total] = await Promise.all([
    prisma.workflow.findMany({
      where, orderBy: { updatedAt: "desc" },
      skip: (q.page - 1) * q.perPage, take: q.perPage,
      include: { createdBy: { include: { profile: true } }, _count: { select: { runs: true } } },
    }),
    prisma.workflow.count({ where }),
  ]);
  return {
    items: items.map((w: any) => ({
      id: w.id, name: w.name, description: w.description,
      status: w.status.toLowerCase(),
      triggers: w.triggers, settings: w.settings,
      runsCount: w._count.runs,
      lastRunAt: w.lastRunAt,
      successCount: w.successCount, failureCount: w.failureCount,
      createdBy: { id: w.createdBy.id, displayName: w.createdBy.profile?.displayName ?? w.createdBy.email },
      createdAt: w.createdAt, updatedAt: w.updatedAt,
    })),
    pagination: { page: q.page, perPage: q.perPage, total, totalPages: Math.ceil(total / q.perPage) },
  };
}

export async function getWorkflow(userId: string, id: string) {
  const ctx = await resolveUserContext(userId);
  const w = await prisma.workflow.findFirst({
    where: { id, organizationId: ctx.organizationId, deletedAt: null },
    include: { createdBy: { include: { profile: true } } },
  });
  if (!w) throw AppError.notFound("Workflow not found");
  return {
    id: w.id, name: w.name, description: w.description, status: w.status.toLowerCase(),
    nodes: w.nodes as FlowNode[], edges: w.edges as FlowEdge[],
    triggers: w.triggers, settings: w.settings,
    runsCount: w.runsCount, successCount: w.successCount, failureCount: w.failureCount, lastRunAt: w.lastRunAt,
    createdBy: { id: w.createdBy.id, displayName: w.createdBy.profile?.displayName ?? w.createdBy.email },
    createdAt: w.createdAt, updatedAt: w.updatedAt,
  };
}

export async function createWorkflow(userId: string, input: z.infer<typeof CreateWorkflowSchema>) {
  const ctx = await resolveUserContext(userId);
  const w = await prisma.workflow.create({
    data: {
      organizationId: ctx.organizationId,
      workspaceId: input.workspaceId ?? ctx.workspaceId,
      name: input.name, description: input.description,
      nodes: input.nodes as any, edges: input.edges as any,
      triggers: input.triggers as any,
      settings: input.settings as any,
      status: WorkflowStatus.DRAFT,
      createdById: userId,
    },
  });
  return w;
}

export async function updateWorkflow(userId: string, id: string, input: z.infer<typeof UpdateWorkflowSchema>) {
  const ctx = await resolveUserContext(userId);
  const existing = await prisma.workflow.findFirst({ where: { id, organizationId: ctx.organizationId, deletedAt: null } });
  if (!existing) throw AppError.notFound("Workflow not found");
  const data: any = { ...input };
  if (input.nodes) data.nodes = input.nodes as any;
  if (input.edges) data.edges = input.edges as any;
  if (input.triggers) data.triggers = input.triggers as any;
  return prisma.workflow.update({ where: { id }, data });
}

export async function deleteWorkflow(userId: string, id: string) {
  const ctx = await resolveUserContext(userId);
  const existing = await prisma.workflow.findFirst({ where: { id, organizationId: ctx.organizationId, deletedAt: null } });
  if (!existing) throw AppError.notFound("Workflow not found");
  await prisma.workflow.update({ where: { id }, data: { deletedAt: new Date(), status: WorkflowStatus.ARCHIVED } });
}

// ─── Execution ──────────────────────────────────────────────────
/**
 * Run a workflow. With `organizationId` omitted (the default) the workflow
 * is resolved through the actor's membership — the historical behaviour.
 *
 * Session 120 — the public API gateway passes the *API key's* organization
 * explicitly. Before that, the public route called this with only the key
 * creator's user id, so the workflow was resolved through the creator's
 * membership: a key issued to org A whose creator also belonged to org B
 * could trigger org B's workflows — a cross-tenant hole on the public
 * surface. With the organization pinned, the lookup cannot leave the key's
 * tenant, and the actor's membership is not consulted at all.
 */
export async function runWorkflow(userId: string, id: string, input: z.infer<typeof RunWorkflowSchema>, organizationId?: string) {
  const ctx = organizationId ? null : await resolveUserContext(userId);
  const orgId = organizationId ?? ctx!.organizationId;
  const w = await prisma.workflow.findFirst({ where: { id, organizationId: orgId, deletedAt: null } });
  if (!w) throw AppError.notFound("Workflow not found");
  if (w.status !== WorkflowStatus.ACTIVE && w.status !== WorkflowStatus.DRAFT) {
    throw AppError.badRequest(`Workflow is ${w.status.toLowerCase()}; cannot run.`);
  }
  const nodes = (w.nodes as any as FlowNode[]);
  const edges = (w.edges as any as FlowEdge[]);
  const settings = (w.settings as any) ?? {};

  // Build a run record
  const run = await prisma.workflowRun.create({
    data: {
      workflowId: id,
      triggerType: input.triggerType,
      triggerData: input.triggerData as any,
      status: WorkflowRunStatus.RUNNING,
      startedAt: new Date(),
      input: { ...input.input, __createdById: userId, __workflowId: id } as any,
      createdById: userId,
    },
  });

  const order = topo(nodes, edges);
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));
  const outs = new Map<string, any>();
  outs.set("__input", input.input);
  const nodeRuns: any[] = [];
  let status: WorkflowRunStatus = WorkflowRunStatus.SUCCEEDED;
  let error: string | null = null;
  const controller = new AbortController();

  const startNode = nodes.find((n) => n.type === "TRIGGER") ?? nodes[0];
  const context: Record<string, any> = { ...input.input, __createdById: userId, __workflowId: id };

  // Follow edges starting from startNode; traverse in BFS order honoring conditions
  const visited = new Set<string>();
  const queue: string[] = startNode ? [startNode.id] : order;
  while (queue.length) {
    const nid = queue.shift()!;
    if (visited.has(nid)) continue;
    visited.add(nid);
    const node = nodeMap.get(nid);
    if (!node) continue;
    const retryCount = Math.max(0, Number(settings.retryCount ?? 1));
    let lastResult: any = null;
    for (let attempt = 0; attempt <= retryCount; attempt++) {
      const t0 = Date.now();
      const res = await executeNode(node, context, orgId, controller.signal);
      nodeRuns.push({
        nodeId: node.id, label: node.label, type: node.type,
        status: res.status, attempts: attempt + 1, durationMs: Date.now() - t0,
        output: res.output, error: res.error ?? null,
      });
      lastResult = res;
      if (res.status === NodeRunStatus.SUCCEEDED) {
        // put node output on context keyed by node id
        context[node.id] = res.output;
        outs.set(node.id, res.output);
        // Find outgoing edges
        const out = edges.filter((e) => e.fromId === node.id);
        for (const e of out) {
          if (node.type === "CONDITION") {
            const branchMatches = String(e.condition ?? "true").trim().toLowerCase() === String(!!res.output?.result).toLowerCase();
            if (!branchMatches && !(e.condition == null)) continue;
          }
          queue.push(e.toId);
        }
        break;
      } else if (res.status === NodeRunStatus.WAITING_APPROVAL) {
        status = WorkflowRunStatus.WAITING_APPROVAL;
        await prisma.workflowRun.update({
          where: { id: run.id },
          data: { status, nodeRuns: nodeRuns as any, output: outs.get("__input") as any },
        });
        return { runId: run.id, status: "waiting_approval", nodeRuns };
      } else if (attempt < retryCount) {
        await new Promise((r) => setTimeout(r, Number(settings.retryDelayMs ?? 1000)));
      } else {
        status = WorkflowRunStatus.FAILED;
        error = res.error ?? `Node "${node.label}" failed`;
        await prisma.workflow.update({
          where: { id },
          data: {
            failureCount: { increment: 1 },
            lastRunAt: new Date(),
            runsCount: { increment: 1 },
          },
        });
        await prisma.workflowRun.update({
          where: { id: run.id },
          data: { status, endedAt: new Date(), error, nodeRuns: nodeRuns as any, output: outs.get("__input") as any },
        });
        dispatch("workflow.run.failed", orgId, { workflowId: id, workflowName: w.name, runId: run.id, error });
        throw new AppError("INTERNAL_ERROR", error ?? `Node "${node.label}" failed`, 500);
      }
    }
    void lastResult;
  }

  await prisma.workflow.update({
    where: { id },
    data: {
      successCount: { increment: 1 },
      runsCount: { increment: 1 },
      lastRunAt: new Date(),
    },
  });
  await prisma.workflowRun.update({
    where: { id: run.id },
    data: { status, endedAt: new Date(), nodeRuns: nodeRuns as any, output: outs as any },
  });
  dispatch("workflow.run.succeeded", orgId, { workflowId: id, workflowName: w.name, runId: run.id });
  return { runId: run.id, status: "succeeded", nodeRuns };
}

export async function approveRun(userId: string, runId: string, approved: boolean, feedback?: string) {
  const ctx = await resolveUserContext(userId);
  const run = await prisma.workflowRun.findFirst({
    where: { id: runId }, include: { workflow: true },
  });
  if (!run || run.workflow.organizationId !== ctx.organizationId) throw AppError.notFound("Run not found");
  if (run.status !== WorkflowRunStatus.WAITING_APPROVAL) throw AppError.badRequest("Run not awaiting approval");
  await prisma.workflowRun.update({
    where: { id: runId },
    data: {
      status: approved ? WorkflowRunStatus.RUNNING : WorkflowRunStatus.CANCELLED,
      output: { ...(run.output as any), __approval: { approved, feedback } } as any,
      endedAt: approved ? null : new Date(),
    },
  });
  return { ok: true };
}

export async function listRuns(userId: string, q: PaginationQuery & { workflowId?: string; status?: string }) {
  const ctx = await resolveUserContext(userId);
  const where: any = { workflow: { organizationId: ctx.organizationId, deletedAt: null } };
  if (q.workflowId) where.workflowId = q.workflowId;
  if (q.status) where.status = q.status;
  const [items, total] = await Promise.all([
    prisma.workflowRun.findMany({
      where, orderBy: { createdAt: "desc" },
      skip: (q.page - 1) * q.perPage, take: q.perPage,
      include: { workflow: { select: { id: true, name: true } }, createdBy: { include: { profile: true } } },
    }),
    prisma.workflowRun.count({ where }),
  ]);
  return {
    items: items.map((r: any) => ({
      id: r.id, workflowId: r.workflowId, workflowName: r.workflow.name,
      status: r.status.toLowerCase(), triggerType: r.triggerType,
      startedAt: r.startedAt, endedAt: r.endedAt, error: r.error,
      createdBy: r.createdBy ? { id: r.createdBy.id, displayName: r.createdBy.profile?.displayName ?? r.createdBy.email } : null,
      createdAt: r.createdAt,
    })),
    pagination: { page: q.page, perPage: q.perPage, total, totalPages: Math.ceil(total / q.perPage) },
  };
}

export async function getRun(userId: string, id: string) {
  const ctx = await resolveUserContext(userId);
  const r = await prisma.workflowRun.findFirst({
    where: { id, workflow: { organizationId: ctx.organizationId } },
    include: { workflow: true, createdBy: { include: { profile: true } } },
  });
  if (!r) throw AppError.notFound("Run not found");
  return {
    id: r.id, workflowId: r.workflowId, workflowName: r.workflow.name,
    status: r.status.toLowerCase(), triggerType: r.triggerType,
    input: r.input, output: r.output, error: r.error,
    nodeRuns: r.nodeRuns, startedAt: r.startedAt, endedAt: r.endedAt,
    createdBy: r.createdBy ? { id: r.createdBy.id, displayName: r.createdBy.profile?.displayName ?? r.createdBy.email } : null,
    createdAt: r.createdAt,
  };
}

export async function cancelRun(userId: string, id: string) {
  const ctx = await resolveUserContext(userId);
  const r = await prisma.workflowRun.findFirst({ where: { id, workflow: { organizationId: ctx.organizationId } } });
  if (!r) throw AppError.notFound("Run not found");
  await prisma.workflowRun.update({ where: { id }, data: { status: WorkflowRunStatus.CANCELLED, endedAt: new Date() } });
}

// ─── Analytics ─────────────────────────────────────────────────
export async function getAnalytics(userId: string) {
  const ctx = await resolveUserContext(userId);
  const orgId = ctx.organizationId;

  const [workflowCount, totalRuns, succeededRuns, failedRuns, waitingRuns, recentRuns, topWorkflows] = await Promise.all([
    prisma.workflow.count({ where: { organizationId: orgId, deletedAt: null } }),
    prisma.workflowRun.count({ where: { workflow: { organizationId: orgId, deletedAt: null } } }),
    prisma.workflowRun.count({ where: { workflow: { organizationId: orgId, deletedAt: null }, status: WorkflowRunStatus.SUCCEEDED } }),
    prisma.workflowRun.count({ where: { workflow: { organizationId: orgId, deletedAt: null }, status: WorkflowRunStatus.FAILED } }),
    prisma.workflowRun.count({ where: { workflow: { organizationId: orgId, deletedAt: null }, status: WorkflowRunStatus.WAITING_APPROVAL } }),
    prisma.workflowRun.findMany({
      where: { workflow: { organizationId: orgId, deletedAt: null } },
      orderBy: { createdAt: "desc" },
      take: 20,
      select: { id: true, status: true, startedAt: true, endedAt: true, createdAt: true, error: true, workflowId: true },
    }),
    prisma.workflow.findMany({
      where: { organizationId: orgId, deletedAt: null },
      orderBy: { runsCount: "desc" },
      take: 10,
      select: { id: true, name: true, runsCount: true, successCount: true, failureCount: true, lastRunAt: true },
    }),
  ]);

  // Compute avg duration from recent runs that have both timestamps
  const durations = recentRuns
    .filter((r: any) => r.startedAt && r.endedAt)
    .map((r: any) => new Date(r.endedAt!).getTime() - new Date(r.startedAt!).getTime());
  const avgDurationMs = durations.length
    ? Math.round(durations.reduce((a: any, b: any) => a + b, 0) / durations.length)
    : 0;

  // Run counts per day for last 14 days
  const since = new Date(); since.setDate(since.getDate() - 14);
  const runsInWindow = await prisma.workflowRun.findMany({
    where: { workflow: { organizationId: orgId, deletedAt: null }, createdAt: { gte: since } },
    select: { status: true, createdAt: true },
  });
  const byDay: Record<string, { date: string; total: number; succeeded: number; failed: number }> = {};
  for (let i = 13; i >= 0; i--) {
    const d = new Date(); d.setDate(d.getDate() - i);
    const key = d.toISOString().slice(0, 10);
    byDay[key] = { date: key, total: 0, succeeded: 0, failed: 0 };
  }
  for (const r of runsInWindow) {
    const key = new Date(r.createdAt).toISOString().slice(0, 10);
    if (!byDay[key]) continue;
    byDay[key].total++;
    if (r.status === WorkflowRunStatus.SUCCEEDED) byDay[key].succeeded++;
    if (r.status === WorkflowRunStatus.FAILED) byDay[key].failed++;
  }

  const successRate = totalRuns > 0 ? Math.round((succeededRuns / totalRuns) * 1000) / 10 : 0;

  return {
    workflows: workflowCount,
    runs: { total: totalRuns, succeeded: succeededRuns, failed: failedRuns, waiting: waitingRuns, successRate, avgDurationMs },
    byDay: Object.values(byDay),
    topWorkflows,
    recentRuns: recentRuns.map((r: any) => ({
      id: r.id, workflowId: r.workflowId, status: r.status.toLowerCase(),
      startedAt: r.startedAt, endedAt: r.endedAt, createdAt: r.createdAt, error: r.error,
    })),
  };
}

// ─── Scheduled trigger ticker (MVP stub) ──────────────────────
// Checks ACTIVE workflows with `schedule` triggers and fires them when due.
// Persists next-run-at in settings.nextRunAt; ticks every 30s.
export async function tickScheduledTriggers() {
  const now = new Date();
  const active = await prisma.workflow.findMany({
    where: { status: WorkflowStatus.ACTIVE, deletedAt: null },
  });
  let fired = 0;
  for (const w of active) {
    try {
      const triggers = Array.isArray(w.triggers) ? (w.triggers as any[]) : [];
      const settings: any = w.settings ?? {};
      const schedule = triggers.find((t) => t?.type === "schedule");
      if (!schedule?.config?.cron && !schedule?.config?.everyMs) continue;
      const next = settings.nextRunAt ? new Date(settings.nextRunAt) : now;
      if (next > now) continue;
      // Fire it (best effort — don't await within loop to keep tick snappy)
      runWorkflowSystem(w.id, w.organizationId, { input: { firedAt: now.toISOString() }, triggerType: "schedule", triggerData: { firedAt: now.toISOString() } })
        .catch((e) => logger?.warn?.(`scheduled workflow ${w.id} failed: ${e?.message}`) ?? void 0);
      fired++;
      // Compute next run (MVP: use everyMs interval, default 1 hour if only cron label provided)
      const everyMs = Number(schedule.config.everyMs ?? 60 * 60 * 1000);
      await prisma.workflow.update({
        where: { id: w.id },
        data: { settings: { ...settings, nextRunAt: new Date(Date.now() + everyMs).toISOString() } },
      });
    } catch (e: any) {
      // swallow per-workflow errors, keep tick going
    }
  }
  return { fired };
}

// System-run a workflow without an authenticated user (for scheduled/webhook/event triggers).
// Uses the organization owner / workflow creator as the actor.
async function runWorkflowSystem(workflowId: string, orgId: string, input: z.infer<typeof RunWorkflowSchema>) {
  const w = await prisma.workflow.findFirst({ where: { id: workflowId, organizationId: orgId, deletedAt: null } });
  if (!w) throw AppError.notFound("Workflow not found");
  // Find actor: creator, else any org owner
  const actorId = w.createdById;
  // Reuse runWorkflow by looking up userId from creator
  return runWorkflow(actorId, workflowId, input);
}

// logger stub to avoid import cycle — uses console in production runtime
const logger = { warn: (msg: string) => console.warn("[workflow]", msg) };
