/**
 * Session 141 — Religion seed (part 3): ancient and historical religions,
 * new religious movements, non-theistic/humanistic movements, and the
 * knowledge-system policy records (§3, §14, §18, §19, §20).
 */
import type { ReligionRecord } from "@windels/shared";
import { buildReligion, SRC_ENCYCLOPEDIA, SRC_PEW, SRC_WORLD_HISTORY } from "./religions.catalog.js";

export const RELIGIONS_ANCIENT_NRM_POLICY: ReligionRecord[] = [
  /* ── Ancient & historical religions (§3) ────────────────────────────── */
  buildReligion({
    id: "anc.egyptian",
    name: "Ancient Egyptian religion",
    altNames: ["Egyptian religion", "the religion of the pharaohs"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Egypt"],
    originLabel: "c. 3000 BCE (early dynastic period); roots in prehistory",
    originYear: -3000,
    keyFigures: ["the pharaohs", "the priesthoods", "the gods: Ra, Osiris, Isis, Horus, Amun, Thoth"],
    centralTeachings: "Ancient Egyptian religion centered on the cosmic order (maat) upheld by the gods and the pharaoh: the sun god Ra journeyed through the sky by day and the underworld by night; Osiris, killed and restored, became lord of the afterlife, offering the hope of resurrection; the elaborate funerary rites (mummification, the Book of the Dead) prepared the soul's judgment before Osiris. Temples, festivals and offerings sustained the gods and the land.",
    deityConcept: "A vast pantheon — Ra/Amun-Ra, Osiris, Isis, Horus, Thoth, Anubis — with local gods of every nome.",
    afterlife: "Judgment in the Hall of Two Truths (the weighing of the heart against maat), then the Fields of Reeds; resurrection in the afterlife.",
    salvation: "Living by maat and securing the funerary rites.",
    worship: "Temple cults, daily offerings, festivals (e.g. Opet), oracles and the funerary rites.",
    prayer: "Hymns and prayers (e.g. the Great Hymn to the Aten).",
    religiousLeaders: "The pharaoh as high priest, the priesthoods of the temples.",
    festivals: ["Opet", "the Beautiful Feast of the Valley", "the festival of Osiris at Abydos"],
    sacredTexts: ["the Pyramid Texts", "the Coffin Texts", "the Book of the Dead", "the hymns"],
    historicalDevelopment: "Egyptian religion evolved over three millennia, experimented with monotheism under Akhenaten (the Aten, c. 1350 BCE), absorbed Greek and Roman elements, and faded with the Christianization of Egypt (4th–6th centuries CE); its last temple (Philae) closed c. 550 CE.",
    modernStatus: "Extinct as a living religion; its legacy persists in Egyptology, art and the Hermetic tradition.",
    distribution: "Historical: Egypt.",
    relatedReligions: ["anc.greek", "anc.mesopotamian", "rel.christianity"],
    differences: "Egyptian religion's pharaonic cult and its distinctive afterlife literature distinguish it from the other ancient religions.",
    similarities: "Polytheistic pantheons, temple sacrifice and afterlife judgment shared with the ancient world.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Ancient Egyptian religion — maat, the gods, the pharaoh and the afterlife rites — sustained one of the world's longest civilizations.",
    simple: "Ancient Egyptians believed in many gods, a king who was holy, and a life after death. They mummified the dead and wrote spells to help them pass the judgment of the god Osiris.",
  }),
  buildReligion({
    id: "anc.mesopotamian",
    name: "Ancient Mesopotamian religion",
    altNames: ["Mesopotamian religion", "the religion of Sumer and Akkad"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Iraq (Mesopotamia)"],
    originLabel: "c. 3500 BCE (Sumer); continuous through the Babylonian and Assyrian empires",
    originYear: -3500,
    keyFigures: ["the gods: Anu, Enlil, Enki, Inanna/Ishtar, Marduk, Ashur", "the kings as the gods' stewards", "the temple priesthoods"],
    centralTeachings: "Mesopotamian religion — Sumerian, Akkadian, Babylonian and Assyrian — centered on the city-gods: each city belonged to a god (Enlil of Nippur, Marduk of Babylon, Ashur of Assyria) whose temple (ziggurat) was its heart; humans were created to serve the gods, and the king was their steward. The creation epic (Enuma Elish) and the flood story (Atrahasis) shaped later biblical literature; divination and the observation of omens were central.",
    deityConcept: "A large pantheon: Anu (sky), Enlil (wind), Enki/Ea (waters and wisdom), Inanna/Ishtar (love and war), Marduk, Ashur.",
    afterlife: "The underworld (Kur/Irkalla), a dim house of dust where all the dead dwelt; the heroic dead (Gilgamesh's search for immortality) remained famous.",
    salvation: "No salvation in the later sense: the good life was serving the gods, justice and leaving a name.",
    worship: "Temple cults, daily offerings, the great New Year festival (Akitu), and divination.",
    prayer: "The hymns and prayers (e.g. the prayers to Ishtar, the penitential psalms).",
    religiousLeaders: "The temple priests (sanga, en), the diviners (baru) and the kings.",
    festivals: ["Akitu (New Year)", "the festivals of the city-gods"],
    sacredTexts: ["the Enuma Elish", "the Epic of Gilgamesh", "the Atrahasis epic", "the omen and hymn corpora"],
    historicalDevelopment: "Mesopotamian religion evolved from Sumer through Akkad, Babylon and Assyria, influenced the Levant and Greece, and died out with the Persian and Hellenistic periods and the rise of Christianity.",
    modernStatus: "Extinct; its myths and laws (Hammurabi) survive in cuneiform and in biblical echoes.",
    distribution: "Historical: Mesopotamia (Iraq).",
    relatedReligions: ["anc.egyptian", "anc.canaanite", "anc.greek"],
    differences: "Mesopotamia's city-god polity and its omen science distinguish it within the ancient Near East.",
    similarities: "Polytheism, temple sacrifice and flood/creation myths shared with the ancient Near East.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Ancient Mesopotamian religion — the city-gods, the ziggurats and the epics — shaped the religious imagination of the ancient Near East.",
    simple: "The ancient people of Iraq (Mesopotamia) believed each city belonged to a god. They built tall temples called ziggurats and wrote great stories like the Epic of Gilgamesh.",
  }),
  buildReligion({
    id: "anc.sumerian",
    name: "Sumerian religion",
    altNames: ["the religion of Sumer"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Southern Mesopotamia (Iraq)"],
    originLabel: "c. 3500–3000 BCE",
    originYear: -3500,
    keyFigures: ["An, Enlil, Enki, Ninhursag, Inanna, Utu, Nanna", "the temple households"],
    centralTeachings: "Sumerian religion is the earliest recorded religion: the gods created humans from clay to serve them; each city's temple was the god's house, and the king was chosen by the gods; the Sumerian hymns, myths (Inanna's descent) and the ziggurats shaped all later Mesopotamian religion.",
    deityConcept: "The Anunna gods: An (heaven), Enlil (air/authority), Enki (waters), Inanna (love/war), Utu (sun), Nanna (moon).",
    afterlife: "The underworld (Kur), where the dead ate dust; only exceptional figures (e.g. Tammuz) returned.",
    salvation: "Serving the gods and the temple; a good name on earth.",
    worship: "Temple cults, offerings, festivals and the sacred marriage rite (in some cities).",
    prayer: "The Sumerian hymns and laments.",
    religiousLeaders: "The temple priests and the ensi (city rulers).",
    festivals: ["The New Year and the agricultural festivals"],
    sacredTexts: ["the Sumerian hymns", "the myth of Inanna's descent", "the Instructions of Shuruppak"],
    historicalDevelopment: "Sumerian religion was absorbed into the Akkadian and Babylonian traditions after Sumer's decline (c. 2000 BCE) and died with the ancient world.",
    modernStatus: "Extinct.",
    distribution: "Historical: southern Mesopotamia.",
    relatedReligions: ["anc.mesopotamian", "anc.babylonian"],
    differences: "Sumerian is the earliest stratum of the Mesopotamian tradition, with its own language and pantheon.",
    similarities: "City-gods, temples and creation myths shared with the Mesopotamian tradition.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Sumerian religion, the earliest recorded, built the city-god temples and myths that Mesopotamia inherited.",
    simple: "Sumerian religion was the first religion we have writings about, from ancient Iraq. Its people believed in gods like Inanna and built temples called ziggurats.",
  }),
  buildReligion({
    id: "anc.greek",
    name: "Ancient Greek religion",
    altNames: ["Greek polytheism", "the religion of the Greeks", "Hellenic religion"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Greece", "the Greek world (Ionia, Magna Graecia, the Hellenistic East)"],
    originLabel: "c. 2nd millennium BCE (Mycenaean roots); classical form c. 8th century BCE",
    originYear: -800,
    keyFigures: ["the Olympians: Zeus, Hera, Athena, Apollo, Artemis, Poseidon, Demeter, Dionysus", "the poets Homer and Hesiod", "the oracle of Delphi", "the philosophers (as critics and interpreters)"],
    centralTeachings: "Ancient Greek religion centered on the Olympian gods — Zeus, Athena, Apollo and the rest — whose myths the poets told and whose favor the cities sought: worship was civic and public (sacrifice, festivals, processions), the oracle of Delphi guided decisions, and the mystery cults (Eleusis, Orphism) offered deeper hopes of the afterlife; the philosophers (Socrates, Plato) reinterpreted the tradition, and the gods remained part of public life into the Roman era.",
    deityConcept: "The Olympian pantheon under Zeus, with the chthonic gods and the heroes.",
    afterlife: "Hades, the house of the dead; the mystery cults promised better afterlives (Elysium for the initiated).",
    salvation: "Civic piety, heroism and, in the mysteries, purification and initiation.",
    worship: "Temple sacrifice, festivals (the Panathenaea, the Olympics), processions and oracles.",
    prayer: "Hymns and prayers (e.g. the Homeric Hymns) at the altars.",
    religiousLeaders: "The priests and priestesses of the temples and the oracle, with the civic magistrates.",
    festivals: ["the Panathenaea", "the Olympic games (to Zeus)", "the Dionysia", "the Eleusinian Mysteries"],
    sacredTexts: ["the Homeric epics", "the Homeric Hymns", "Hesiod's Theogony", "the Orphic fragments"],
    historicalDevelopment: "Greek religion developed from Mycenaean roots, flourished in the classical poleis, spread across the Hellenistic world, was absorbed into Roman religion, and faded with Christianity's triumph (4th–6th centuries CE); it has been revived in modern Hellenism.",
    modernStatus: "Historical as the ancient cult; revived in contemporary Hellenic (Hellenism) communities.",
    distribution: "Historical: Greece and the Mediterranean; revival communities worldwide.",
    relatedReligions: ["anc.roman", "anc.egyptian", "anc.minoan"],
    differences: "Greek religion's civic festival culture and its philosophical engagement distinguish it within the ancient world.",
    similarities: "Olympian-style pantheons, sacrifice and oracles shared with the ancient Mediterranean.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "verified",
    summary: "Ancient Greek religion — the Olympians, the city festivals and the mysteries — shaped Western imagination for two and a half thousand years.",
    simple: "The ancient Greeks believed in gods who lived on Mount Olympus — Zeus, Athena, Apollo. They built temples, held the Olympic games for Zeus, and asked the oracle at Delphi for advice.",
  }),
  buildReligion({
    id: "anc.roman",
    name: "Ancient Roman religion",
    altNames: ["Roman polytheism", "the religion of Rome"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Rome", "the Roman Empire"],
    originLabel: "c. 8th century BCE (with Rome's founding); developed through the Republic and Empire",
    originYear: -750,
    keyFigures: ["Jupiter, Mars, Quirinus, Vesta, Janus, Minerva", "the pontiffs and augurs", "the emperors (as divi after death)"],
    centralTeachings: "Roman religion was a religion of exact ritual and the pax deorum — the peace of the gods maintained by correct observance: the state's priests (pontiffs, augurs) read the gods' will through auspices and omens; the household gods (Lares, Penates) and the Vestals' fire guarded family and state; Greek gods were adopted and identified with Roman ones (Zeus→Jupiter); the imperial cult joined the emperor to the divine order. Its genius was conservatism and the absorption of other peoples' gods.",
    deityConcept: "Jupiter and the Capitoline triad, with Mars, Vesta, Janus and the adopted Greek gods.",
    afterlife: "The underworld (Orcus, the Manes); the mystery cults (Mithras, Isis) offered richer hopes.",
    salvation: "Pax deorum — correct ritual, piety (pietas) and the state's favor.",
    worship: "State sacrifice, the games (ludi), the household rites and the festivals of the calendar.",
    prayer: "The formulae of the priests and the vows of the people.",
    religiousLeaders: "The pontiffs, the augurs, the flamens and the Vestals, under the pontifex maximus.",
    festivals: ["Saturnalia", "the Lupercalia", "the ludi Romani", "the Vestalia"],
    sacredTexts: ["the pontifical books", "the Sibylline Books", "Ovid's Fasti (festival calendar)"],
    historicalDevelopment: "Roman religion evolved from the city's founding rites, absorbed Greek and eastern gods (Cybele, Isis, Mithras), and was transformed by the emperors' cult; Christianity's triumph (4th century) ended the old cults, though many festival customs passed into Christian and folk practice.",
    modernStatus: "Historical; revived in modern reconstructionist communities (Religio Romana).",
    distribution: "Historical: the Roman world; revival communities worldwide.",
    relatedReligions: ["anc.greek", "anc.etruscan"],
    differences: "Roman religion's ritual exactness and imperial cult distinguish it from Greek religion's festival culture.",
    similarities: "Pantheon, sacrifice and civic religion shared with the ancient Mediterranean.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "verified",
    summary: "Ancient Roman religion — the pax deorum, the priests and the festivals — ordered Roman public life for a millennium.",
    simple: "The ancient Romans believed in gods like Jupiter and Mars. They performed exact rituals to keep peace with the gods, and many of their festivals became holidays we still know.",
  }),
  buildReligion({
    id: "anc.norse",
    name: "Norse religion",
    altNames: ["Norse paganism", "Old Norse religion", "the religion of the Vikings"],
    indigenousNames: [{ name: "Forn siðr", lang: "non", script: "Latin (Old Norse)", note: "the old custom" }],
    namesByLanguage: { non: ["Forn siðr"] },
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Scandinavia", "Iceland", "the Norse world"],
    originLabel: "c. 1st millennium CE (Germanic roots); attested from the Viking Age",
    originYear: 800,
    keyFigures: ["Odin, Thor, Freyja, Freyr, Loki, Tyr, Baldr", "the seiðr practitioners", "the goðar (priest-chieftains)"],
    centralTeachings: "Norse religion centered on the gods of Asgard — Odin (wisdom and war), Thor (thunder and protection), Freyja and the Vanir (fertility) — with the world-tree Yggdrasil binding the nine worlds: the gods and humans face the prophesied doom of Ragnarök. Worship was local: the hof (temples) and the blót (sacrifices and feasts), the thing (assemblies) under the goðar, and the sagas' heroes; the runes carried sacred meaning.",
    deityConcept: "The Æsir and Vanir: Odin, Thor, Freyja, Freyr, Loki, Tyr, with the giants and the dwarfs.",
    afterlife: "Valhalla (Odin's hall for the slain), Folkvangr (Freyja's field), Hel and the sea-goddess Rán's realm.",
    salvation: "Honor, courage and reputation (the good death); fate (wyrd) accepted with courage.",
    worship: "The blót (sacrifices and feasts), the hof rites, the seasonal festivals and the personal gods (fulltrui).",
    prayer: "The invocations and the runic prayers.",
    religiousLeaders: "The goðar (priest-chieftains) and the völur (seeresses).",
    festivals: ["Yule (midwinter)", "the blóts of the year", "the disablot"],
    sacredTexts: ["the Poetic Edda", "the Prose Edda (Snorri Sturluson)", "the sagas", "the runic inscriptions"],
    historicalDevelopment: "Norse religion developed from Germanic religion, spread with the Vikings across the North Atlantic, and was replaced by Christianity in Scandinavia and Iceland (c. 1000 CE); its myths survived in the Eddas and were revived in modern Ásatrú/Heathenry.",
    modernStatus: "Historical as the old cult; revived in Ásatrú and Heathen communities.",
    distribution: "Historical: Scandinavia and the Norse world; revival communities worldwide.",
    relatedReligions: ["anc.germanic", "anc.celtic", "anc.slavic"],
    differences: "Norse religion's Ragnarök cosmology and its warrior ethos distinguish it within the Germanic world.",
    similarities: "Aesir-style pantheons, sacrifice and fate shared with the Germanic and Celtic traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Norse religion — Odin, Thor, the nine worlds and Ragnarök — was the faith of the Viking world, surviving in the Eddas and modern Heathenry.",
    simple: "The Vikings believed in gods like Odin and Thor, who lived in Asgard. They thought brave warriors went to Valhalla, and that the world would end at Ragnarök.",
  }),
  buildReligion({
    id: "anc.celtic",
    name: "Celtic religion",
    altNames: ["Celtic paganism", "the religion of the Celts"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Gaul", "Britain", "Ireland", "the Celtic world"],
    originLabel: "c. 1st millennium BCE; attested from the Iron Age",
    originYear: -800,
    keyFigures: ["the gods of the Gauls (Lugus, Taranis, Epona)", "the Irish Tuatha Dé Danann", "the druids"],
    centralTeachings: "Celtic religion is known from classical accounts, inscriptions and the insular traditions: the druids — priests, judges and philosophers — led the cult; the gods were local and tribal (Lugus/Lug, Taranis, the Matres, Epona), and the Otherworld was ever-present, reached through the síd mounds and the sacred waters; the seasonal festivals (Samhain, Imbolc, Beltaine, Lughnasadh) marked the year, and the Irish tales preserved the mythology after Christianization.",
    deityConcept: "Tribal and local gods: Lug, Taranis, Cernunnos, Epona, Brigid and the Tuatha Dé Danann.",
    afterlife: "The Otherworld: a blessed land reached through the síd, the waters and the west; rebirth in the tradition of the tales.",
    salvation: "Heroic honor, the druids' wisdom and the favor of the gods.",
    worship: "Sacred groves and waters, sacrifice, the festivals and the druids' rites.",
    prayer: "The invocations and the sung charms (preserved in Irish tradition).",
    religiousLeaders: "The druids, the vates (seers) and the bards.",
    festivals: ["Samhain", "Imbolc", "Beltaine", "Lughnasadh"],
    sacredTexts: ["the classical accounts (Caesar)", "the Irish sagas (e.g. the Táin)", "the Welsh Mabinogion", "the inscriptions"],
    historicalDevelopment: "Celtic religion flourished in the Iron Age, was romanized in Gaul and Britain, survived longest in Ireland until Christianization (5th century), and its festivals and mythology passed into Christian and folk tradition; modern Celtic reconstructionism revives it.",
    modernStatus: "Historical; revived in modern Celtic reconstructionist communities.",
    distribution: "Historical: the Celtic world; revival communities in Ireland, Britain, Brittany and beyond.",
    relatedReligions: ["anc.norse", "anc.germanic", "anc.greek"],
    differences: "Celtic religion's druidic order and its Otherworld geography distinguish it within the ancient world.",
    similarities: "Polytheism, sacrifice and seasonal festivals shared with the Indo-European traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Celtic religion — the druids, the tribal gods and the Otherworld — survives in the Irish and Welsh tales and modern reconstruction.",
    simple: "The ancient Celts believed in many gods and a magical Otherworld. Their priests were called druids, and their festivals like Samhain became part of later traditions.",
  }),
  buildReligion({
    id: "anc.slavic",
    name: "Slavic paganism",
    altNames: ["Slavic religion", "the faith of the Slavs"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Eastern Europe", "the Balkans", "Russia"],
    originLabel: "c. 1st millennium CE (Slavic expansion); attested from the 6th century",
    originYear: 500,
    keyFigures: ["Perun (thunder)", "Veles (the underworld and cattle)", "Svarog, Dazhbog, Mokosh", "the volkhvy (priests)"],
    centralTeachings: "Slavic paganism centered on Perun, the thunder god, and Veles, the chthonic god of cattle and the underworld, with Svarog (the sky-smith), Dazhbog (the sun), Mokosh (the earth) and the household and nature spirits (domovoi, rusalki): worship was local — the sacred groves, the rivers, the ancestor rites and the seasonal festivals — and the volkhvy (priests) served the gods until Christianization.",
    deityConcept: "Perun, Veles, Svarog, Dazhbog, Mokosh, Stribog and the many spirits.",
    afterlife: "The otherworld (Navi, Vyraj) and the ancestors' continued presence.",
    salvation: "Right order, the ancestors' honor and the gods' favor.",
    worship: "Sacred groves and waters, offerings, the festivals and the household rites.",
    prayer: "The invocations and the sung charms.",
    religiousLeaders: "The volkhvy (priests) and the elders.",
    festivals: ["Kupala (summer solstice)", "Koliada (winter)", "Maslenitsa", "the harvest rites"],
    sacredTexts: ["the Primary Chronicle's accounts", "the folk charms and songs", "the archaeological cult sites"],
    historicalDevelopment: "Slavic paganism developed with the Slavic migrations, was displaced by Christianity from the 9th–12th centuries (Vladimir's baptism of Rus', 988), and survived in folk custom; modern Rodnovery revives it.",
    modernStatus: "Historical; revived in modern Slavic native-faith (Rodnovery) communities.",
    distribution: "Historical: the Slavic world; revival communities in Russia, Poland, Ukraine and the Balkans.",
    relatedReligions: ["anc.norse", "anc.baltic", "anc.germanic"],
    differences: "Slavic religion's Perun–Veles polarity and its household spirits distinguish it within the Indo-European traditions.",
    similarities: "Thunder gods, nature spirits and seasonal festivals shared with the European traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Slavic paganism — Perun, Veles and the household spirits — was the faith of the Slavic peoples before Christianization.",
    simple: "The ancient Slavs believed in gods like Perun (thunder) and spirits of the home and nature. Their festivals and customs still echo in Eastern European folk life.",
  }),
  buildReligion({
    id: "anc.canaanite",
    name: "Ancient Canaanite religion",
    altNames: ["Canaanite religion", "the religion of the Levant"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["the Levant (Lebanon, Syria, Palestine/Israel, Jordan)"],
    originLabel: "c. 3rd millennium BCE; attested from the Bronze Age",
    originYear: -3000,
    keyFigures: ["El, Baal, Asherah, Anat, Mot, Yam", "the kings and priests of the city-states", "the Ugaritic scribes"],
    centralTeachings: "Canaanite religion centered on El, the high god, and Baal, the storm god who died and rose with the seasons, with Asherah (the mother goddess), Anat and Mot (death): the Ugaritic texts (14th century BCE) record its myths — Baal's battle with Yam and Mot — and its temple cults of sacrifice and festival; it is the immediate religious world from which ancient Israelite religion emerged and distinguished itself.",
    deityConcept: "El (the high god), Baal (storm and fertility), Asherah, Anat, Mot (death), Yam (the sea).",
    afterlife: "The underworld (Mot's realm), where the dead dwelt; the shades (Rephaim) were honored.",
    salvation: "Fertility, the king's justice and the gods' favor; no salvation doctrine.",
    worship: "Temple sacrifice, the high places, the festivals of the agricultural year.",
    prayer: "The Ugaritic prayers and hymns.",
    religiousLeaders: "The kings (as sacred rulers), the priests and the temple personnel.",
    festivals: ["the agricultural festivals of Baal and the seasons"],
    sacredTexts: ["the Ugaritic texts (Baal cycle)", "the El Amarna letters", "the biblical polemics (as testimony)"],
    historicalDevelopment: "Canaanite religion flourished in the Bronze and Iron Age Levant, influenced Phoenician and Israelite religion, and died out under the empires and the spread of monotheism.",
    modernStatus: "Extinct.",
    distribution: "Historical: the Levant.",
    relatedReligions: ["anc.phoenician", "rel.judaism", "anc.mesopotamian"],
    differences: "Canaanite religion's Baal cycle and its temple polities distinguish it within the ancient Near East.",
    similarities: "Storm gods, fertility cults and sacrifice shared with the ancient Near East.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Ancient Canaanite religion — El, Baal, Asherah — was the Levantine world from which Israelite monotheism emerged.",
    simple: "The ancient Canaanites of the Middle East believed in gods like El and Baal. Their stories were written on clay tablets found at Ugarit.",
  }),
  buildReligion({
    id: "anc.phoenician",
    name: "Phoenician religion",
    altNames: ["the religion of Phoenicia", "Punic religion (Carthage)"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Lebanon (Tyre, Sidon, Byblos)", "Carthage", "the Phoenician colonies"],
    originLabel: "c. 2nd millennium BCE; flourished 1st millennium BCE",
    originYear: -2000,
    keyFigures: ["Baal (Melqart of Tyre), Astarte, Eshmun, Tanit", "the kings and the priestly families"],
    centralTeachings: "Phoenician religion, kin to Canaanite, centered on the city-gods — Melqart of Tyre, Astarte (love and war), Eshmun (healing) and, at Carthage, Tanit and Baal Hammon — with the royal cults, the high places and the famous (and much-debated) child-sacrifice traditions of Carthage (the tophets): Phoenician trade carried their gods around the Mediterranean.",
    deityConcept: "Baal/Melqart, Astarte, Eshmun, Tanit, Baal Hammon.",
    afterlife: "The shades of the dead in the underworld; the royal tombs and the ancestor rites.",
    salvation: "The gods' favor for the city and its trade.",
    worship: "Temple sacrifice, the tophet rites (Carthage), the festivals of the city-gods.",
    prayer: "The votive inscriptions and prayers.",
    religiousLeaders: "The kings, the priests (kohanim) and the temple staff.",
    festivals: ["the festivals of Melqart and Astarte", "the spring rites"],
    sacredTexts: ["the inscriptions (e.g. the Pyrgi tablets)", "the biblical and classical accounts", "the Carthaginian votive texts"],
    historicalDevelopment: "Phoenician religion developed from Canaanite roots, spread with the trading cities and Carthage, and was absorbed by the Roman world after Carthage's fall (146 BCE).",
    modernStatus: "Extinct.",
    distribution: "Historical: Lebanon, North Africa, the western Mediterranean.",
    relatedReligions: ["anc.canaanite", "anc.egyptian"],
    differences: "The Phoenician tradition's city-god cults and its Carthaginian rites distinguish it within the Levantine world.",
    similarities: "Baal/Astarte worship and sacrifice shared with Canaanite religion.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Phoenician religion — Melqart, Astarte and Tanit — was carried by the great trading cities around the Mediterranean.",
    simple: "The Phoenicians, famous sailors of Lebanon, believed in gods like Melqart and Astarte, and their colony Carthage worshipped the goddess Tanit.",
  }),
  buildReligion({
    id: "anc.etruscan",
    name: "Etruscan religion",
    altNames: ["the religion of the Etruscans"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Italy (Etruria)"],
    originLabel: "c. 8th century BCE; attested from the Iron Age",
    originYear: -800,
    keyFigures: ["Tinia, Uni, Menrva, Aplu", "the haruspices (diviners)", "the lucumones (kings)"],
    centralTeachings: "Etruscan religion was famous in antiquity for its divination: the haruspices read the gods' will in the entrails of sacrifice and the lightning (the disciplina etrusca); the pantheon — Tinia (the sky), Uni, Menrva — paralleled the Greek and Roman gods; the Etruscan tombs and the belief in a detailed afterlife shaped their art and the later Roman religion.",
    deityConcept: "Tinia, Uni, Menrva and the many gods of the Etruscan cities.",
    afterlife: "A richly pictured afterlife (the painted tombs of Tarquinia), with the journey of the dead.",
    salvation: "The gods' favor read through correct divination.",
    worship: "Sacrifice, divination, the templum (sacred space) and the festivals.",
    prayer: "The prayers of the haruspices and the votive offerings.",
    religiousLeaders: "The haruspices (diviners), the priests and the kings.",
    festivals: ["the festivals of the Etruscan cities (e.g. the Augustalia of the later period)"],
    sacredTexts: ["the Libri Haruspicini (reported)", "the inscriptions", "the painted tombs"],
    historicalDevelopment: "Etruscan religion flourished in Etruria, deeply influenced Rome (the haruspices remained into the empire), and faded with the Etruscans' absorption into Rome (1st century BCE).",
    modernStatus: "Extinct.",
    distribution: "Historical: Etruria (Tuscany, Italy).",
    relatedReligions: ["anc.roman", "anc.greek"],
    differences: "The Etruscan tradition's disciplined divination and its tomb art distinguish it within the ancient Mediterranean.",
    similarities: "Pantheon and sacrifice shared with the Italic and Greek worlds.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Etruscan religion, famous for its divination and painted tombs, shaped Rome's religious practice.",
    simple: "The Etruscans, an ancient people of Italy, were famous for reading the future from animal organs and lightning. Rome learned many of its rituals from them.",
  }),
  buildReligion({
    id: "anc.babylonian",
    name: "Babylonian religion",
    altNames: ["the religion of Babylon"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Babylonia (Iraq)"],
    originLabel: "c. 2nd millennium BCE; Marduk's rise with Babylon (18th century BCE)",
    originYear: -1800,
    keyFigures: ["Marduk, Ishtar, Nabu, Shamash, Ea", "the kings of Babylon", "the temple priesthoods"],
    centralTeachings: "Babylonian religion raised Marduk, the city-god of Babylon, to the head of the Mesopotamian pantheon (the Enuma Elish celebrates his kingship): the great ziggurat Etemenanki, the New Year festival (Akitu) where the king was re-enthroned, and the omen literature structured imperial religion; Nabu (writing), Ishtar (love and war) and Shamash (justice) were the great gods of the empire.",
    deityConcept: "Marduk at the head, with Nabu, Ishtar, Shamash, Ea and the ancient pantheon.",
    afterlife: "The underworld (Irkalla), the house of dust.",
    salvation: "The king's right order and the gods' favor; personal piety grew in the first millennium.",
    worship: "The temple cults, the Akitu festival, the daily offerings and divination.",
    prayer: "The Babylonian psalms and prayers (e.g. the prayers to Marduk).",
    religiousLeaders: "The temple priests and the king as the gods' steward.",
    festivals: ["Akitu (New Year)", "the festivals of Ishtar and Nabu"],
    sacredTexts: ["the Enuma Elish", "the Epic of Gilgamesh (Babylonian version)", "the omen series (e.g. Enuma Anu Enlil)"],
    historicalDevelopment: "Babylonian religion developed from Sumerian and Old Babylonian roots, dominated the Near East under Nebuchadnezzar and his successors, and died with the Persian conquest (539 BCE) and the later rise of Christianity.",
    modernStatus: "Extinct.",
    distribution: "Historical: Babylonia (Iraq).",
    relatedReligions: ["anc.mesopotamian", "anc.sumerian", "anc.assyrian"],
    differences: "Marduk's imperial supremacy and the Akitu festival distinguish the Babylonian form of the Mesopotamian tradition.",
    similarities: "Temple cults, omens and the pantheon shared with Mesopotamia.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Babylonian religion raised Marduk to the head of the gods and built the empire's great temple festivals.",
    simple: "The Babylonians believed their god Marduk created the world and was king of the gods. Each New Year they held a great festival in his honor.",
  }),
  buildReligion({
    id: "anc.israelite",
    name: "Ancient Israelite religion",
    altNames: ["the religion of ancient Israel", "Yahwism"],
    family: "ancient",
    category: "ancient_religion",
    status: "transformed",
    theism: "monotheistic",
    region: ["Israel and Judah", "the ancient Levant"],
    originLabel: "c. 2nd millennium BCE (patriarchal traditions); the monarchy's temple cult c. 10th century BCE",
    originYear: -1200,
    keyFigures: ["Moses (traditional lawgiver)", "the kings (David, Solomon)", "the prophets (Elijah, Isaiah, Jeremiah)", "the priests and Levites"],
    centralTeachings: "Ancient Israelite religion developed from the West Semitic world into the worship of Yahweh alone: the covenant at Sinai, the Torah (law), the Jerusalem Temple with its priesthood and sacrifice, and the prophets' call to justice and exclusive loyalty to Yahweh; the religion of Israel and Judah evolved from monolatry (worshiping Yahweh among other gods) to monotheism, and after the Temple's destruction (70 CE) transformed into rabbinic Judaism — while the Hebrew Bible became scripture for Judaism, Christianity and Islam.",
    deityConcept: "Yahweh, the God of Israel, who became, in the prophets' teaching, the one God of all the earth.",
    afterlife: "Sheol, the shadowy underworld of the dead; resurrection appears only in the later texts (Daniel).",
    salvation: "Covenant faithfulness: justice, worship and the Torah's commands.",
    worship: "The Jerusalem Temple: sacrifice, the festivals (Passover, Weeks, Booths), prayer and the pilgrimage.",
    prayer: "The Psalms and the prayers of the people.",
    religiousLeaders: "The priests (Kohanim), the Levites, the prophets and the kings.",
    festivals: ["Passover", "Shavuot (Weeks)", "Sukkot (Booths)", "the Day of Atonement (Yom Kippur)"],
    sacredTexts: ["the Hebrew Bible (Torah, Prophets, Writings)"],
    historicalDevelopment: "Israelite religion's history is reconstructed from the Bible and archaeology: from the patriarchs and the exodus (traditional dating c. 13th century BCE), through the monarchy and the prophets, the exile (586 BCE) and the Second Temple, to its transformation after 70 CE into rabbinic Judaism and the emergence of Christianity.",
    modernStatus: "Transformed: the parent of rabbinic Judaism, Christianity and (in its prophetic heritage) Islam.",
    distribution: "Historical: Israel and Judah; its scriptures are world scripture.",
    relatedReligions: ["rel.judaism", "anc.canaanite", "rel.christianity", "rel.islam"],
    differences: "Israelite religion's exclusive covenant with Yahweh distinguished it from Canaanite religion, its parent world.",
    similarities: "Sacrifice, festivals and the temple cult shared with the ancient Near East.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Ancient Israelite religion — the covenant, the Temple and the prophets — grew from the Levantine world into monotheism and became the root of Judaism, Christianity and Islam.",
    simple: "The ancient Israelites were the people of the Bible. They worshipped one God, Yahweh, with a great Temple in Jerusalem, and their prophets taught justice and faithfulness.",
    researchNote: "The reconstruction of Israelite religion combines the Hebrew Bible with archaeology; scholars debate the exodus's historicity, the speed of the transition to monotheism, and the relationship between the temple cult and the prophets.",
  }),
  buildReligion({
    id: "anc.minoan",
    name: "Minoan religion",
    altNames: ["the religion of Bronze Age Crete"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Crete (the Minoan civilization)"],
    originLabel: "c. 3000–1100 BCE (the Bronze Age)",
    originYear: -3000,
    keyFigures: ["the Snake Goddess and the Mother Goddess figures", "the bull (of the bull-leaping rites)", "the priestesses and priests of the palaces"],
    centralTeachings: "Minoan religion is known from the art and archaeology of Bronze Age Crete: goddess-centered worship (the Snake Goddess, the Mother of the Mountains), the sacred caves and peak sanctuaries, the double axe and the horns of consecration, the bull-leaping rites, and the palace shrines (Knossos); its goddesses and symbols entered the Greek world's memory (the labyrinth, the Minotaur).",
    deityConcept: "The Great Goddess in her forms, with nature deities and the sacred bull.",
    afterlife: "The larnax (clay coffin) burials suggest beliefs in an afterlife; the details are unknown.",
    salvation: "The goddess's favor for fertility and the palace-community.",
    worship: "The palace and cave sanctuaries, the peak rites, the offerings and the festivals.",
    prayer: "Unknown; the figurines and the seals suggest devotional practice.",
    religiousLeaders: "The priestesses and priests of the palaces (reconstructed from art).",
    festivals: ["Reconstructed from the frescoes (processions, the bull rites)"],
    sacredTexts: ["Undeciphered (Linear A)", "the art and the archaeology"],
    historicalDevelopment: "Minoan religion flourished in Bronze Age Crete, declined with the palaces (c. 1450 BCE), and passed its myths into Greek tradition.",
    modernStatus: "Extinct.",
    distribution: "Historical: Crete.",
    relatedReligions: ["anc.greek", "anc.mycenean"],
    differences: "Minoan religion's goddess-centered, palace-based cult distinguishes it within the Aegean world.",
    similarities: "Nature deities and sacred animals shared with the Aegean and Near Eastern worlds.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "uncertain",
    summary: "Minoan religion, known from Crete's palaces and art, centered on the goddess, the caves and the sacred bull.",
    simple: "The Minoans of ancient Crete worshipped goddesses in their palaces and caves, and held ceremonies with bulls. We know them from their beautiful paintings.",
  }),
  buildReligion({
    id: "anc.thracian",
    name: "Thracian religion",
    altNames: ["the religion of the Thracians"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Thrace (Bulgaria, Greece, Turkey)"],
    originLabel: "c. 1st millennium BCE; attested from the classical period",
    originYear: -700,
    keyFigures: ["Zalmoxis (the god-king of the Getae)", "Dionysus (in the Thracian form)", "the Thracian horseman (the Hero)"],
    centralTeachings: "Thracian religion is known from Greek accounts and the archaeology of Thrace: Zalmoxis, the immortal god-king of the Getae (of whom Herodotus wrote), the Thracian Dionysus with his mysteries, and the ubiquitous Thracian Horseman (the Hero) of the votive plaques; the tombs of the Thracian kings (Kazanlak) show a rich afterlife belief.",
    deityConcept: "Zalmoxis, the Thracian Dionysus, the Hero (the Horseman) and the nature spirits.",
    afterlife: "Herodotus reports the Getae's belief in immortality and Zalmoxis's return; the tombs suggest a journey after death.",
    salvation: "Initiation into the mysteries (of Zalmoxis and Dionysus) and heroic virtue.",
    worship: "The sanctuaries and tombs, the votive plaques, the mysteries.",
    prayer: "The invocations reported by the Greeks.",
    religiousLeaders: "The kings (as priests, e.g. the Getae's 'immortal' kings) and the initiates.",
    festivals: ["the mysteries of Dionysus and the seasonal rites"],
    sacredTexts: ["Herodotus and the Greek accounts", "the votive inscriptions", "the tomb paintings"],
    historicalDevelopment: "Thracian religion flourished in the first millennium BCE, influenced the Greek Dionysus cult, and faded under the Roman and later Christian centuries.",
    modernStatus: "Extinct.",
    distribution: "Historical: Thrace (Bulgaria, northern Greece, European Turkey).",
    relatedReligions: ["anc.greek", "anc.scythian"],
    differences: "The Thracian tradition's Zalmoxis cult and its Horseman devotion distinguish it within the ancient world.",
    similarities: "Mystery initiations and heroic cults shared with the Aegean world.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "uncertain",
    summary: "Thracian religion — Zalmoxis, the mysteries and the Horseman — is known from Greek accounts and the royal tombs of Thrace.",
    simple: "The ancient Thracians of the Balkans believed in a god-king named Zalmoxis and in life after death. Their kings were buried in great painted tombs.",
  }),
  buildReligion({
    id: "anc.scythian",
    name: "Scythian religion",
    altNames: ["the religion of the Scythians"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["the Eurasian steppe (Ukraine, southern Russia, Central Asia)"],
    originLabel: "c. 1st millennium BCE; attested from the 7th century BCE",
    originYear: -700,
    keyFigures: ["Tabiti (the hearth goddess)", "Papaios (the sky god)", "the Scythian equivalents of Apollo, Ares, Heracles", "the enarees (shamanic diviners)"],
    centralTeachings: "Scythian religion, reported by Herodotus, centered on Tabiti, the hearth goddess, and Papaios, the sky god, with a pantheon the Greeks identified with their own; the royal funeral rites (the burial of the king with his retinue, described by Herodotus and confirmed at Arzhan and Pazyryk), the gold animal art, and the enarees (gender-crossing diviners) marked its shamanic-steppe character.",
    deityConcept: "Tabiti, Papaios, Api (the earth) and the pantheon of the steppe.",
    afterlife: "The royal tombs and the funeral rites show a rich afterlife belief (the journey of the dead).",
    salvation: "The warrior ethos and the favor of the gods of the steppe.",
    worship: "The royal funerals, the sacrificial rites and the gold votives.",
    prayer: "The invocations reported by Herodotus.",
    religiousLeaders: "The kings (as priests) and the enarees (diviners).",
    festivals: ["the annual rites of the king's hearth (reported by Herodotus)"],
    sacredTexts: ["Herodotus's account", "the archaeology of the kurgans (Pazyryk, Arzhan)"],
    historicalDevelopment: "Scythian religion flourished with the steppe empires of the first millennium BCE, influenced the later steppe peoples, and faded with the Scythians' absorption into the Sarmatian and other worlds.",
    modernStatus: "Extinct.",
    distribution: "Historical: the Eurasian steppe.",
    relatedReligions: ["anc.thracian", "rel.tengrism"],
    differences: "The Scythian tradition's hearth cult, royal funerals and shamanic diviners distinguish it within the ancient world.",
    similarities: "Sky gods and funeral rites shared with the Indo-European and steppe traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "uncertain",
    summary: "Scythian religion — Tabiti, the royal funerals and the gold of the kurgans — was the faith of the first great steppe horsemen.",
    simple: "The Scythians were ancient horsemen of the steppe. Their kings were buried in great mounds with gold and horses, and they believed in a life after death.",
  }),

  /* ── New religious movements & humanistic traditions ────────────────── */
  buildReligion({
    id: "nrm.wicca",
    name: "Wicca",
    altNames: ["Modern witchcraft", "the Craft"],
    family: "new_religious_movement",
    category: "new_religious_movement",
    status: "active",
    theism: "polytheistic",
    region: ["United Kingdom (origins)", "United States", "Europe", "worldwide"],
    originLabel: "Mid-20th century (publicized by Gerald Gardner, 1954)",
    originYear: 1950,
    keyFigures: ["Gerald Gardner", "Doreen Valiente", "the founders of the traditions (Alexandrian, Gardnerian, Dianic)"],
    centralTeachings: "Wicca is a modern nature religion that emerged in mid-20th-century Britain: it worships the Goddess and the Horned God, celebrates the eight sabbats of the wheel of the year (Samhain, Yule, Imbolc, Ostara, Beltane, Litha, Lammas, Mabon), practices ritual magic within an ethical frame (the Wiccan Rede: 'harm none'), and organizes in covens and initiatory traditions; it is the largest of the modern Pagan religions.",
    deityConcept: "The Goddess (in her maiden/mother/crone forms) and the Horned God; many Wiccans are duotheistic or polytheistic.",
    afterlife: "Varied belief; many hold that the soul rests in the Summerland and may be reborn.",
    salvation: "Harmony with nature and the divine; no salvation doctrine.",
    worship: "The circle rites, the sabbats and esbats (full moons), and the coven's rituals.",
    prayer: "The invocations of the Goddess and the God within the rites.",
    religiousLeaders: "The high priestesses and high priests of the covens.",
    festivals: ["the eight sabbats (Samhain, Yule, Imbolc, Ostara, Beltane, Litha, Lammas, Mabon)"],
    sacredTexts: ["the Book of Shadows (tradition-specific)", "the writings of Gardner and Valiente"],
    historicalDevelopment: "Wicca was publicized by Gerald Gardner in the 1950s, drew on earlier ceremonial magic and folklore, spread to the United States in the 1960s–70s, diversified into many traditions, and is now a recognized religion in several countries.",
    modernStatus: "Active; hundreds of thousands of practitioners worldwide.",
    distribution: "United Kingdom, the United States, Canada, Australia, Europe.",
    relatedReligions: ["nrm.modern-paganism", "anc.celtic", "anc.greek"],
    differences: "Wicca is a modern religion that draws on pre-Christian imagery; it is not a direct continuation of ancient cults.",
    similarities: "Nature reverence and seasonal festivals shared with the wider modern Pagan movement.",
    sources: [SRC_ENCYCLOPEDIA, { label: "Wiccan and Pagan community sources", type: "community" }],
    confidence: "well_supported",
    summary: "Wicca is the largest modern Pagan religion — the Goddess and the Horned God, the wheel of the year, and ritual magic — born in 1950s Britain.",
    simple: "Wicca is a modern nature religion. Wiccans honor the Goddess and the God, celebrate eight seasonal festivals, and follow the rule of harming none.",
  }),
  buildReligion({
    id: "nrm.humanism",
    name: "Secular humanism",
    altNames: ["Humanism", "humanistic naturalism"],
    family: "humanistic",
    category: "philosophical_tradition",
    status: "active",
    theism: "non_theistic",
    region: ["Worldwide", "roots in Europe"],
    originLabel: "Modern form from the 19th–20th centuries; roots in classical and Enlightenment thought",
    originYear: 1900,
    keyFigures: ["the Enlightenment thinkers", "the Humanist Manifesto authors (1933, 1973, 2003)", "the humanist organizations' founders"],
    centralTeachings: "Secular humanism is the non-theistic life stance that human reason, ethics and dignity — without supernatural belief — can ground a meaningful life: it affirms human rights, science, free inquiry, and the responsibility of humans for their own futures. Humanists mark life's passages (naming, marriage, funerals) with ceremonies that celebrate human meaning, and many belong to humanist organizations (Humanists International).",
    deityConcept: "None; the natural world as understood by science.",
    afterlife: "This life is the only life; meaning is made in it.",
    salvation: "Human flourishing, reason, compassion and justice.",
    worship: "Humanist ceremonies and community gatherings; no worship in the religious sense.",
    prayer: "Contemplation and reflection; no petitionary prayer.",
    religiousLeaders: "Humanist celebrants and the elected leaders of humanist organizations.",
    festivals: ["Humanist weddings and funerals", "Darwin Day", "HumanLight", "World Humanist Day"],
    sacredTexts: ["the Humanist Manifestos", "the Amsterdam Declaration (2002)", "the works of the humanist tradition"],
    historicalDevelopment: "Humanism's modern form grew from the Enlightenment, organized in the 19th–20th centuries (the Ethical Culture movement, the American Humanist Association), and is recognized as a life stance in international human-rights instruments.",
    modernStatus: "Active; hundreds of millions of people hold humanistic worldviews, with organized humanism numbering in the millions.",
    distribution: "Europe, North America, Latin America, Africa, Asia and worldwide.",
    relatedReligions: ["nrm.unitarian-universalism"],
    differences: "Humanism is non-theistic and non-supernatural; it differs from religions in having no revelation, creed or clergy.",
    similarities: "Ethics, community and life-passage ceremonies parallel religious forms without supernatural claims.",
    sources: [SRC_ENCYCLOPEDIA, { label: "Humanists International", type: "community" }],
    confidence: "well_supported",
    summary: "Secular humanism is the non-theistic life stance of reason, ethics and human dignity, with ceremonies and communities of its own.",
    simple: "Humanism is a way of life without gods or religion. Humanists believe people can be good and find meaning through reason, kindness and science.",
  }),
  buildReligion({
    id: "nrm.unitarian-universalism",
    name: "Unitarian Universalism",
    altNames: ["UU", "Unitarianism"],
    family: "humanistic",
    category: "new_religious_movement",
    status: "active",
    theism: "unclassifiable",
    region: ["United States", "Canada", "Europe", "worldwide"],
    originLabel: "1961 (merger of the Unitarian and Universalist churches); roots in the 16th–18th centuries",
    originYear: 1961,
    keyFigures: ["Michael Servetus", "John Murray", "Hosea Ballou", "William Ellery Channing"],
    centralTeachings: "Unitarian Universalism is a liberal religious tradition formed by the 1961 merger of the Unitarians (who affirmed God's unity against the Trinity) and the Universalists (who taught universal salvation): today its congregations covenant to affirm the inherent worth of every person, justice and compassion, and a free and responsible search for truth and meaning — with members holding theist, humanist, Buddhist, earth-centered and other beliefs in one community.",
    deityConcept: "None required: belief ranges from theism to humanism to earth-centered spirituality.",
    afterlife: "Varied belief; the emphasis is on this life and its meaning.",
    salvation: "Spiritual growth, justice and love — understood pluralistically.",
    worship: "Congregational services with music, reflection and the congregation's voice.",
    prayer: "Meditation, reflection and prayer as each member chooses.",
    religiousLeaders: "Ordained ministers and the congregations' elected leaders.",
    festivals: ["the Christian and Jewish festivals, Earth Day, and the members' own traditions"],
    sacredTexts: ["the sources of the tradition: scripture, reason, experience, the world's religions"],
    historicalDevelopment: "Unitarianism grew from the Reformation's anti-Trinitarian streams, Universalism from 18th-century American revivalism; their 1961 merger created the modern UU movement, which championed civil rights and interfaith openness.",
    modernStatus: "Active; approximately 150,000–200,000 members in North America and communities worldwide.",
    distribution: "United States, Canada, Europe, and small communities worldwide.",
    relatedReligions: ["den.protestant", "nrm.humanism"],
    differences: "UU is creedless: it requires no belief, only covenantal community, distinguishing it from confessional churches.",
    similarities: "Congregational polity and service culture shared with liberal Protestantism.",
    sources: [SRC_ENCYCLOPEDIA, { label: "Unitarian Universalist Association", type: "community" }],
    confidence: "well_supported",
    summary: "Unitarian Universalism is a creedless liberal religious community born of the 1961 merger, covenanting around dignity, justice and free search.",
    simple: "Unitarian Universalists are a church without a required creed. Members believe different things — some believe in God, some don't — but they gather to learn, serve and grow together.",
  }),

  /* ── Policy records (§14, §18, §19, §20) ────────────────────────────── */
  buildReligion({
    id: "pol.neutrality",
    name: "How WINDELS teaches religion",
    altNames: ["religion neutrality policy", "the neutrality requirement"],
    family: "other",
    category: "policy",
    status: "active",
    theism: "unclassifiable",
    region: ["WINDELS AI OS (system policy)"],
    originLabel: "Session 141, 2026",
    originYear: 2026,
    centralTeachings: "WINDELS presents the world's religions educationally, objectively and respectfully: it never promotes one religion as universally superior, never insults or mocks beliefs, never manufactures teachings, and never treats followers of a religion as identical. Contested claims are attributed ('Christian traditions generally teach X, while Islamic traditions generally teach Y'), uncertainty is labelled, and 'which religion is true?' is answered by explaining that truth claims are matters of faith, theology, philosophy and personal belief — WINDELS does not claim to have chosen a religion.",
    deityConcept: "Not applicable — this is a system policy record, not a religion.",
    afterlife: "Not applicable.",
    salvation: "Not applicable.",
    worship: "Not applicable.",
    prayer: "Not applicable.",
    religiousLeaders: "Not applicable.",
    festivals: [],
    sacredTexts: [],
    historicalDevelopment: "The neutrality policy was adopted with the religion knowledge system in Session 141 and is enforced by the record structure, the attributed comparison engine and the teaching-level rendering.",
    modernStatus: "Active policy of the knowledge system.",
    distribution: "Applies to all religion content served by WINDELS AI OS.",
    relatedReligions: [],
    differences: "Not applicable.",
    similarities: "Not applicable.",
    sources: [SRC_ENCYCLOPEDIA],
    confidence: "verified",
    summary: "WINDELS teaches religion educationally and respectfully: no superiority claims, no insults, no invented teachings, no uniformity assumptions, and no claim that WINDELS itself has chosen a religion.",
    simple: "WINDELS tells you what religions teach fairly, without saying one is better or true. When religions disagree, it says what each side teaches.",
    controversialNote: "This record itself is the neutrality policy; it is not a religious claim.",
  }),
  buildReligion({
    id: "pol.expansion",
    name: "How the religion database expands",
    altNames: ["the expansion process", "religion submission policy"],
    family: "other",
    category: "policy",
    status: "active",
    theism: "unclassifiable",
    region: ["WINDELS AI OS (system policy)"],
    originLabel: "Session 141, 2026",
    originYear: 2026,
    centralTeachings: "The religion knowledge base is expandable without a fixed target number: new traditions enter through the ten-step process — identity verification, classification, source verification, historical verification, community review where appropriate, duplicate detection (aliases are mapped, never duplicated), related-tradition mapping, branch/denomination mapping, confidence scoring, and Super Admin knowledge-base approval. No fake religions are created to reach a numerical target, and names from multiple sources for one tradition are recorded as aliases.",
    deityConcept: "Not applicable — policy record.",
    afterlife: "Not applicable.",
    salvation: "Not applicable.",
    worship: "Not applicable.",
    prayer: "Not applicable.",
    religiousLeaders: "Not applicable.",
    festivals: [],
    sacredTexts: [],
    historicalDevelopment: "The expansion process was designed in Session 141 to keep the knowledge base indefinitely expandable while preventing duplication and fabrication.",
    modernStatus: "Active policy; submissions are reviewed through the documented pipeline.",
    distribution: "Applies to all religion submissions in WINDELS AI OS.",
    relatedReligions: [],
    differences: "Not applicable.",
    similarities: "Not applicable.",
    sources: [SRC_ENCYCLOPEDIA],
    confidence: "verified",
    summary: "New religious traditions enter the knowledge base through a ten-step verified process; aliases are mapped rather than duplicated, and no fake religions are created.",
    simple: "When people want to add a new religion to WINDELS, it goes through careful checks: is it real, is it sourced, is it a duplicate? Only then is it approved.",
    controversialNote: "This record describes the system's own process; it is not a religious claim.",
  }),

  buildReligion({
    id: "rel.gnosticism",
    name: "Gnosticism",
    altNames: ["the Gnostic traditions", "Gnosis"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "dualistic",
    region: ["Mediterranean world (Egypt, Syria, Rome)"],
    originLabel: "1st–3rd centuries CE (with earlier roots in Hellenistic and Near Eastern thought)",
    originYear: 100,
    keyFigures: ["Valentinus", "Basilides", "Marcion (related teacher)", "the Nag Hammadi texts' authors"],
    centralTeachings: "Gnosticism is a family of ancient esoteric traditions teaching that the material world is flawed — created by an ignorant or lesser power (the demiurge) — and that the divine spark within humans can be saved through gnosis, the direct knowledge of the true God: the Nag Hammadi library (1945) revealed its texts (the Gospel of Thomas, the Gospel of Judas), and its influence spread across Christianity, Manichaeism and later esoteric currents.",
    deityConcept: "The true transcendent God beyond the demiurge who made the world.",
    afterlife: "The soul's ascent through the spheres of the archons back to the pleroma (the fullness of the divine).",
    salvation: "Gnosis — awakening to one's divine origin and escaping the material world.",
    worship: "Communal meals, hymns and initiatory teaching; the traditions varied widely.",
    prayer: "Hymns and invocations (e.g. the Hymn of the Pearl, the Thunder Perfect Mind).",
    religiousLeaders: "Teachers (didaskaloi) and initiators; the traditions were decentralized.",
    festivals: ["Not well attested; baptismal and anointing rites are known"],
    sacredTexts: ["the Nag Hammadi library", "the writings of the church fathers (as testimony)", "the Hermetic corpus (related)"],
    historicalDevelopment: "Gnosticism flourished in the 2nd–3rd centuries, was condemned by the emerging orthodox churches, influenced Manichaeism and Mandaeism, and survived in medieval and modern esoteric currents.",
    modernStatus: "Extinct as a living religion; influential in scholarship and modern esotericism.",
    distribution: "Historical: the Mediterranean world.",
    relatedReligions: ["rel.manichaeism", "rel.mandaeism", "rel.christianity"],
    differences: "Gnosticism's demiurge mythology and its salvation-by-knowledge distinguish it from orthodox Christianity and the mystery cults.",
    similarities: "Dualism and esoteric salvation shared with Manichaeism and the mystery religions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Gnosticism is the ancient family of esoteric traditions of salvation through knowledge, revealed anew by the Nag Hammadi texts.",
    simple: "Gnosticism was an old religion of secret knowledge. Gnostics believed the world was made by a lesser god and that people carry a divine spark that can be saved by understanding the truth.",
  }),
  buildReligion({
    id: "anc.germanic",
    name: "Germanic paganism",
    altNames: ["Germanic religion", "the religion of the Germanic peoples"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Germania", "Scandinavia", "Anglo-Saxon England", "the Germanic world"],
    originLabel: "c. 1st millennium BCE (Indo-European roots); attested from the Roman era",
    originYear: -500,
    keyFigures: ["Wodan/Odin, Donar/Thor, Tiw/Tyr, Frigg/Freyja", "the tribal kings and priests", "the seeresses (e.g. Veleda)"],
    centralTeachings: "Germanic paganism is the religion of the Germanic peoples before Christianization: a polytheism of war, fate and fertility — Wodan (Odin), Donar (Thor), Tiw (Tyr), Frigg and Freyja — with sacred groves, sacrifice (blót), the thing assemblies, runes, and the tribal gods attested by Tacitus and the later Norse sources; it is the parent of Norse religion.",
    deityConcept: "Wodan, Donar, Tiw, Frigg, Nerthus and the tribal and household gods.",
    afterlife: "The dead journey to the ancestors' halls; warrior afterlives (Valhalla's roots) appear in the later Norse sources.",
    salvation: "Honor, fate (wyrd) and the favor of the gods.",
    worship: "Sacred groves and springs, sacrifice, the festivals of the year and the tribal rites.",
    prayer: "The invocations and the runic charms.",
    religiousLeaders: "The tribal priests (gudja), the kings and the seeresses.",
    festivals: ["Yule (midwinter)", "the spring and harvest blóts", "the tribal festivals"],
    sacredTexts: ["Tacitus's Germania", "the later Norse Eddas and sagas", "the runic inscriptions"],
    historicalDevelopment: "Germanic paganism was the religion of the Germanic peoples through the migration period, was gradually Christianized from the 4th–11th centuries, and survived in folklore; modern Heathenry revives it.",
    modernStatus: "Historical; revived in modern Heathenry/Ásatrú.",
    distribution: "Historical: the Germanic world; revival communities worldwide.",
    relatedReligions: ["anc.norse", "anc.celtic", "anc.slavic"],
    differences: "Germanic religion's tribal character and its attested forms differ from the later, richer Norse sources.",
    similarities: "Pantheon and sacrifice shared with the Norse and Indo-European traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Germanic paganism — Wodan, Donar and the sacred groves — was the religion of the Germanic peoples before Christianity, parent of Norse religion.",
    simple: "The ancient Germanic peoples of Europe believed in gods like Wodan and Donar (Thor). They worshipped in sacred groves and their customs lived on in folklore.",
  }),
  buildReligion({
    id: "anc.baltic",
    name: "Baltic paganism",
    altNames: ["Baltic religion", "the religion of the Balts"],
    family: "ancient",
    category: "ancient_religion",
    status: "historical",
    theism: "polytheistic",
    region: ["Lithuania", "Latvia", "Prussia (the Baltic lands)"],
    originLabel: "Ancient Indo-European roots; attested from the medieval chronicles",
    originYear: -1000,
    keyFigures: ["Perkūnas (the thunder god)", "Dievas (the sky god)", "the vaidilutės (priestesses) and kriviai (priests)", "the old Prussian gods"],
    centralTeachings: "Baltic paganism is the Indo-European religion of the Baltic peoples, the last in Europe to be officially Christianized: Perkūnas the thunder god, Dievas the sky god, and the household and nature spirits; the sacred groves, the eternal fire (the sanctuary of Romuva in old Prussia), the sun (Saulė) and the seasonal festivals of the year. Its folk songs (dainos) preserved the mythology.",
    deityConcept: "Dievas, Perkūnas, Saulė (the sun), Laima (fate), and the spirits of home and nature.",
    afterlife: "The soul's journey; the dead return at the festivals of the ancestors.",
    salvation: "Harmony with the gods, nature and the ancestors.",
    worship: "The sacred fire and groves, the festivals of the year, offerings and the household rites.",
    prayer: "The folk prayers and the songs (dainos).",
    religiousLeaders: "The kriviai (priests) and the vaidilutės (fire priestesses), with the household elders.",
    festivals: ["Jāņi/Līgo (midsummer)", "the winter solstice (Kūčios)", "the spring and harvest rites"],
    sacredTexts: ["the medieval chronicles (e.g. the Chronicle of the Prussian Land)", "the dainos (folk songs)", "the archaeology of the sanctuaries"],
    historicalDevelopment: "Baltic paganism survived into the 14th–15th centuries (the Grand Duchy of Lithuania's official religion until 1387), was then Christianized while persisting in folk custom; modern Romuva revives it.",
    modernStatus: "Historical; revived in modern Baltic native faith (Romuva, Dievturība).",
    distribution: "Historical: the Baltic lands; revival communities in Lithuania and Latvia.",
    relatedReligions: ["anc.slavic", "anc.norse", "anc.germanic"],
    differences: "Baltic religion's fire sanctuaries, its late survival and its folk-song transmission distinguish it within the Indo-European world.",
    similarities: "Thunder gods, fate goddesses and seasonal festivals shared with the European traditions.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Baltic paganism — Perkūnas, Dievas and the eternal fire — was the last officially pagan religion of Europe, surviving in folk song and modern Romuva.",
    simple: "The Baltic peoples of Lithuania and Latvia kept their old religion of thunder god Perkūnas and sacred fires longer than any other Europeans. Their folk songs still carry the old myths.",
  }),
  buildReligion({
    id: "anc.assyrian",
    name: "Assyrian religion",
    altNames: ["the religion of Assyria", "the cult of Ashur"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Assyria (northern Mesopotamia, Iraq)"],
    originLabel: "c. 2nd millennium BCE; Ashur's supremacy with the Assyrian Empire (14th–7th centuries BCE)",
    originYear: -1300,
    keyFigures: ["Ashur (the national god)", "Ishtar of Nineveh and Arbela", "the Assyrian kings (as Ashur's regents)"],
    centralTeachings: "Assyrian religion centered on Ashur, the national god who went to war with the Assyrian armies: the king was Ashur's regent, the campaigns were holy wars, and the state festivals (the akitu) renewed the kingship; Ishtar of Nineveh and Arbela gave oracles, and the great library of Ashurbanipal preserved the omen and epic literature.",
    deityConcept: "Ashur at the head, with Ishtar, Nabu, Shamash and the Mesopotamian pantheon.",
    afterlife: "The underworld of the dead, as in the wider Mesopotamian tradition.",
    salvation: "The king's service to Ashur and the empire's favor.",
    worship: "The temple cults of Ashur and Ishtar, the akitu festival, the oracles and the omen rites.",
    prayer: "The royal prayers and the oracular queries.",
    religiousLeaders: "The king as high priest, the temple priests and the diviners.",
    festivals: ["Akitu (New Year)", "the festivals of Ishtar of Nineveh"],
    sacredTexts: ["the royal inscriptions", "the omen series", "the Epic of Gilgamesh (Assyrian versions)", "Ashurbanipal's library"],
    historicalDevelopment: "Assyrian religion dominated the Near East with the empire, fell with Nineveh (612 BCE), and its gods and texts passed into the later Mesopotamian and biblical memory.",
    modernStatus: "Extinct.",
    distribution: "Historical: Assyria (northern Iraq).",
    relatedReligions: ["anc.mesopotamian", "anc.babylonian", "anc.sumerian"],
    differences: "Ashur's national-war cult and the oracles of Ishtar distinguish the Assyrian form of Mesopotamian religion.",
    similarities: "Temple cults, omens and the pantheon shared with Mesopotamia.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Assyrian religion, the war-cult of the god Ashur, sustained the Assyrian Empire and its famous library.",
    simple: "The Assyrians believed their god Ashur fought with their armies. Their kings built great libraries of the gods' stories and omens.",
  }),
  buildReligion({
    id: "anc.mycenean",
    name: "Mycenaean religion",
    altNames: ["the religion of Mycenaean Greece"],
    family: "ancient",
    category: "ancient_religion",
    status: "extinct",
    theism: "polytheistic",
    region: ["Greece (Mycenaean palaces: Mycenae, Pylos, Knossos)"],
    originLabel: "c. 1600–1100 BCE (the Late Bronze Age)",
    originYear: -1600,
    keyFigures: ["the gods of the Linear B tablets (Zeus, Hera, Poseidon, Dionysus, Artemis)", "the wanax (palace kings)", "the priests of the shrines"],
    centralTeachings: "Mycenaean religion, known from the Linear B tablets and the archaeology of the palaces, already worshipped many of the classical Greek gods — Zeus, Hera, Poseidon, Dionysus, Artemis — with palace shrines, offerings, processions and the famous tholos tombs and cult centers; it is the direct ancestor of ancient Greek religion.",
    deityConcept: "Zeus, Hera, Poseidon, Dionysus, Artemis, and the goddesses of the tablets (e.g. Potnia).",
    afterlife: "The rich grave goods of the shaft and tholos tombs suggest beliefs in an afterlife for the elite.",
    salvation: "The gods' favor for the palace-community.",
    worship: "Palace and peak sanctuaries, offerings, processions and the funerary cults.",
    prayer: "The votive offerings and the tablet records (the prayers themselves are lost).",
    religiousLeaders: "The wanax (king) and the priests and priestesses of the shrines.",
    festivals: ["Reconstructed from the tablets (month-names and festival offerings)"],
    sacredTexts: ["the Linear B tablets", "the archaeology of the palaces and tombs"],
    historicalDevelopment: "Mycenaean religion flourished in the Late Bronze Age, collapsed with the palaces (c. 1200–1100 BCE), and its gods survived into the Greek Dark Age and classical religion.",
    modernStatus: "Extinct; ancestral to Greek religion.",
    distribution: "Historical: mainland Greece and Crete.",
    relatedReligions: ["anc.greek", "anc.minoan"],
    differences: "Mycenaean religion's palace-based cults and its Linear B attestations distinguish it from the later, richer Greek sources.",
    similarities: "The same gods and sacrifice shared with Greek religion.",
    sources: [SRC_ENCYCLOPEDIA, SRC_WORLD_HISTORY],
    confidence: "well_supported",
    summary: "Mycenaean religion, attested in the Linear B tablets, already worshipped Zeus, Hera and Poseidon at the palaces of Bronze Age Greece.",
    simple: "The Mycenaeans, the Greeks of the Bronze Age, already worshipped Zeus, Hera and Poseidon. We know this from clay tablets found in their palaces.",
  }),
  buildReligion({
    id: "nrm.modern-paganism",
    name: "Modern Paganism",
    altNames: ["Contemporary Paganism", "Neopaganism"],
    family: "new_religious_movement",
    category: "new_religious_movement",
    status: "active",
    theism: "polytheistic",
    region: ["Europe", "North America", "Australia", "worldwide"],
    originLabel: "19th–20th centuries (as a self-conscious revival)",
    originYear: 1900,
    keyFigures: ["Gerald Gardner (Wicca)", "Doreen Valiente", "the founders of the reconstructionist traditions", "the Pagan federations' leaders"],
    centralTeachings: "Modern Paganism is the family of contemporary religions that revive or reconstruct pre-Christian traditions: Wicca and the wider Goddess movement, reconstructionist traditions (Heathenry/Ásatrú, Hellenism, Celtic, Slavic Rodnovery, Baltic Romuva, Kemetic), and eclectic earth-centered spirituality — sharing nature reverence, polytheism or pantheism, festival cycles and ritual practice, with no central authority.",
    deityConcept: "Polytheistic, pantheistic or duotheistic, varying by tradition.",
    afterlife: "Varied; ancestor reverence and rebirth beliefs are common.",
    salvation: "Harmony with nature and the gods; no salvation doctrine.",
    worship: "Ritual circles, seasonal festivals, ancestor rites and the traditions' liturgies.",
    prayer: "The invocations and devotional practices of each tradition.",
    religiousLeaders: "Tradition-specific: priests/priestesses, gothi, druids, and community elders.",
    festivals: ["the wheel of the year (Wicca)", "the historical festivals of each reconstructed tradition (e.g. Yule, Samhain, Midsummer)"],
    sacredTexts: ["Tradition-specific: the Eddas, the Mabinogion, the Greek hymns, or modern liturgical writings"],
    historicalDevelopment: "Modern Paganism grew from 19th-century Romanticism and folklore studies, organized in the mid-20th century (Wicca), expanded through the 1960s–80s counterculture, and is now a recognized religious family in many countries.",
    modernStatus: "Active; hundreds of thousands to millions of practitioners worldwide.",
    distribution: "United States, the United Kingdom, Germany, Scandinavia, Australia, and worldwide.",
    relatedReligions: ["nrm.wicca", "anc.norse", "anc.celtic", "anc.greek"],
    differences: "Modern Paganism is a contemporary revival, not a direct continuation of the ancient cults — a distinction its own communities and scholars debate.",
    similarities: "Nature reverence, polytheism and festivals shared across its traditions.",
    sources: [SRC_ENCYCLOPEDIA, { label: "Pagan federations and academic Pagan studies", type: "community" }],
    confidence: "well_supported",
    summary: "Modern Paganism is the family of contemporary nature-revering religions that revive or reconstruct pre-Christian traditions worldwide.",
    simple: "Modern Pagans are people today who follow the old religions of Europe and other lands — honoring many gods, nature and the seasons. Wicca is the best known of these.",
  }),
];
