/**
 * Module 111: AI Model Auto-Documentation Service
 * WINDELS AI OS - Phase 2
 * 
 * Provides automatic documentation generation for AI models including API documentation,
 * model cards, usage guides, and technical specifications from code, configs, and metadata.
 */

import { randomUUID } from 'crypto';

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface DocumentationProject {
  id: string;
  organizationId: string;
  modelId: string;
  modelName: string;
  status: DocumentationStatus;
  configuration: DocumentationConfiguration;
  sections: DocumentationSection[];
  versions: DocumentationVersion[];
  lastGeneratedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type DocumentationStatus = 'draft' | 'generating' | 'complete' | 'published' | 'outdated';

export interface DocumentationConfiguration {
  outputFormat: 'markdown' | 'html' | 'pdf' | 'all';
  includeAPIReference: boolean;
  includeModelCard: boolean;
  includeUsageGuide: boolean;
  includeTechnicalSpecs: boolean;
  includeExamples: boolean;
  includeChangelog: boolean;
  customTemplates: Record<string, string>;
  styleGuide: StyleGuide;
}

export interface StyleGuide {
  tone: 'technical' | 'friendly' | 'formal';
  language: string;
  codeStyle: 'tabs' | 'spaces';
  maxLineWidth: number;
  includeTOC: boolean;
}

export interface DocumentationSection {
  id: string;
  type: SectionType;
  title: string;
  content: string;
  order: number;
  autoGenerated: boolean;
  sourceData?: Record<string, any>;
  lastUpdated: string;
}

export type SectionType =
  | 'overview'
  | 'installation'
  | 'quickstart'
  | 'api_reference'
  | 'model_card'
  | 'usage_guide'
  | 'technical_specs'
  | 'examples'
  | 'troubleshooting'
  | 'changelog'
  | 'faq'
  | 'custom';

export interface DocumentationVersion {
  version: string;
  generatedAt: string;
  sections: DocumentationSection[];
  changeLog: string;
  publishedAt?: string;
}

export interface ModelCard {
  id: string;
  modelId: string;
  modelName: string;
  modelVersion: string;
  sections: ModelCardSection[];
  metadata: ModelCardMetadata;
  generatedAt: string;
  updatedAt: string;
}

export interface ModelCardSection {
  title: string;
  content: string;
  type: 'text' | 'table' | 'list' | 'code' | 'metrics';
  data?: any;
}

export interface ModelCardMetadata {
  developers: string[];
  organization: string;
  license: string;
  tags: string[];
  relatedModels: string[];
  datasets: string[];
  papers: string[];
}

export interface APIEndpoint {
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  summary: string;
  description: string;
  parameters: APIParameter[];
  requestBody?: APIRequestBody;
  responses: APIResponse[];
  examples: APIExample[];
  authentication: boolean;
  rateLimit?: string;
}

export interface APIParameter {
  name: string;
  in: 'path' | 'query' | 'header' | 'cookie';
  required: boolean;
  type: string;
  description: string;
  example?: any;
  schema?: Record<string, any>;
}

export interface APIRequestBody {
  required: boolean;
  contentType: string;
  schema: Record<string, any>;
  example?: any;
  description: string;
}

export interface APIResponse {
  statusCode: number;
  description: string;
  contentType: string;
  schema: Record<string, any>;
  example?: any;
}

export interface APIExample {
  name: string;
  description: string;
  request: any;
  response: any;
  language: string;
}

export interface UsageExample {
  id: string;
  title: string;
  description: string;
  code: string;
  language: string;
  output?: string;
  tags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export interface DocumentationTemplate {
  id: string;
  name: string;
  description: string;
  type: SectionType;
  template: string;
  variables: TemplateVariable[];
  createdAt: string;
}

export interface TemplateVariable {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  required: boolean;
  default?: any;
  description: string;
}

// ─── In-Memory Store ──────────────────────────────────────────────────────────

const documentationProjects = new Map<string, DocumentationProject>();
const modelCards = new Map<string, ModelCard>();
const apiEndpoints = new Map<string, APIEndpoint[]>();
const usageExamples = new Map<string, UsageExample[]>();
const documentationTemplates = new Map<string, DocumentationTemplate>();

// ─── Helper Functions ─────────────────────────────────────────────────────────

function generateOverviewSection(modelName: string, modelId: string): DocumentationSection {
  return {
    id: randomUUID(),
    type: 'overview',
    title: 'Overview',
    content: `# ${modelName}\n\n${modelName} is an AI model designed for [purpose]. This documentation provides comprehensive information about installation, usage, and technical specifications.\n\n## Key Features\n\n- Feature 1\n- Feature 2\n- Feature 3\n\n## Model ID\n\n\`${modelId}\``,
    order: 1,
    autoGenerated: true,
    lastUpdated: new Date().toISOString(),
  };
}

function generateInstallationSection(): DocumentationSection {
  return {
    id: randomUUID(),
    type: 'installation',
    title: 'Installation',
    content: `# Installation\n\n## Prerequisites\n\n- Python 3.8+\n- pip or conda\n\n## Install via pip\n\n\`\`\`bash\npip install windels-ai-sdk\n\`\`\`\n\n## Install via conda\n\n\`\`\`bash\nconda install -c windels windels-ai-sdk\n\`\`\`\n\n## Verify Installation\n\n\`\`\`python\nimport windels\nprint(windels.__version__)\n\`\`\``,
    order: 2,
    autoGenerated: true,
    lastUpdated: new Date().toISOString(),
  };
}

function generateQuickstartSection(modelName: string): DocumentationSection {
  return {
    id: randomUUID(),
    type: 'quickstart',
    title: 'Quick Start',
    content: `# Quick Start\n\nGet started with ${modelName} in just a few minutes.\n\n## 1. Import the SDK\n\n\`\`\`python\nfrom windels import Model\n\`\`\`\n\n## 2. Load the Model\n\n\`\`\`python\nmodel = Model.load("model-id")\n\`\`\`\n\n## 3. Make a Prediction\n\n\`\`\`python\nresult = model.predict(input_data)\nprint(result)\n\`\`\`\n\n## Next Steps\n\n- Read the [Usage Guide](#usage-guide) for detailed examples\n- Check the [API Reference](#api-reference) for all available methods`,
    order: 3,
    autoGenerated: true,
    lastUpdated: new Date().toISOString(),
  };
}

function generateModelCardSections(): ModelCardSection[] {
  return [
    {
      title: 'Model Details',
      content: '## Model Details\n\n- **Model Type**: [Type]\n- **Architecture**: [Architecture]\n- **Framework**: [Framework]\n- **License**: [License]',
      type: 'text',
    },
    {
      title: 'Intended Use',
      content: '## Intended Use\n\n### Primary Uses\n- Use case 1\n- Use case 2\n\n### Out of Scope\n- Out of scope use 1',
      type: 'text',
    },
    {
      title: 'Training Data',
      content: '## Training Data\n\n- **Dataset**: [Dataset name]\n- **Size**: [Size]\n- **Collection Method**: [Method]\n- **Preprocessing**: [Preprocessing steps]',
      type: 'text',
    },
    {
      title: 'Evaluation',
      content: '## Evaluation Results\n\n| Metric | Value |\n|--------|-------|\n| Accuracy | -- |\n| Precision | -- |\n| Recall | -- |\n| F1 Score | -- |',
      type: 'metrics',
      data: { accuracy: 0, precision: 0, recall: 0, f1: 0 },
    },
    {
      title: 'Ethical Considerations',
      content: '## Ethical Considerations\n\n### Limitations\n- Limitation 1\n- Limitation 2\n\n### Bias\n- Bias consideration 1\n\n### Recommendations\n- Recommendation 1',
      type: 'text',
    },
  ];
}

// ─── Service Implementation ───────────────────────────────────────────────────

export function createDocumentationProject(params: {
  organizationId: string;
  modelId: string;
  modelName: string;
  configuration?: Partial<DocumentationConfiguration>;
}): DocumentationProject {
  const now = new Date().toISOString();
  const id = randomUUID();

  const defaultConfig: DocumentationConfiguration = {
    outputFormat: 'all',
    includeAPIReference: true,
    includeModelCard: true,
    includeUsageGuide: true,
    includeTechnicalSpecs: true,
    includeExamples: true,
    includeChangelog: true,
    customTemplates: {},
    styleGuide: {
      tone: 'technical',
      language: 'en',
      codeStyle: 'spaces',
      maxLineWidth: 100,
      includeTOC: true,
    },
  };

  const project: DocumentationProject = {
    id,
    organizationId: params.organizationId,
    modelId: params.modelId,
    modelName: params.modelName,
    status: 'draft',
    configuration: { ...defaultConfig, ...params.configuration },
    sections: [
      generateOverviewSection(params.modelName, params.modelId),
      generateInstallationSection(),
      generateQuickstartSection(params.modelName),
    ],
    versions: [],
    createdAt: now,
    updatedAt: now,
  };

  documentationProjects.set(id, project);
  return project;
}

export function getDocumentationProject(id: string): DocumentationProject | undefined {
  return documentationProjects.get(id);
}

export function listDocumentationProjects(
  organizationId: string,
  filters?: { modelId?: string; status?: DocumentationStatus }
): DocumentationProject[] {
  let result = Array.from(documentationProjects.values()).filter(
    p => p.organizationId === organizationId
  );

  if (filters?.modelId) result = result.filter(p => p.modelId === filters.modelId);
  if (filters?.status) result = result.filter(p => p.status === filters.status);

  return result.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
}

export function generateDocumentation(projectId: string): DocumentationProject {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  project.status = 'generating';
  project.updatedAt = new Date().toISOString();

  // Generate sections based on configuration
  const sections: DocumentationSection[] = [...project.sections];

  if (project.configuration.includeAPIReference) {
    sections.push({
      id: randomUUID(),
      type: 'api_reference',
      title: 'API Reference',
      content: '# API Reference\n\nComplete API documentation for all endpoints.\n\n## Endpoints\n\n[Auto-generated from API definitions]',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  if (project.configuration.includeModelCard) {
    sections.push({
      id: randomUUID(),
      type: 'model_card',
      title: 'Model Card',
      content: '# Model Card\n\n[Auto-generated model card with model details, intended use, and evaluation results]',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  if (project.configuration.includeUsageGuide) {
    sections.push({
      id: randomUUID(),
      type: 'usage_guide',
      title: 'Usage Guide',
      content: '# Usage Guide\n\nDetailed guide on how to use the model effectively.\n\n## Basic Usage\n\n[Examples and best practices]',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  if (project.configuration.includeTechnicalSpecs) {
    sections.push({
      id: randomUUID(),
      type: 'technical_specs',
      title: 'Technical Specifications',
      content: '# Technical Specifications\n\n## Architecture\n\n[Model architecture details]\n\n## Performance\n\n[Performance benchmarks]\n\n## Requirements\n\n[System requirements]',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  if (project.configuration.includeExamples) {
    sections.push({
      id: randomUUID(),
      type: 'examples',
      title: 'Examples',
      content: '# Examples\n\nCollection of usage examples and tutorials.\n\n[Auto-generated from example library]',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  if (project.configuration.includeChangelog) {
    sections.push({
      id: randomUUID(),
      type: 'changelog',
      title: 'Changelog',
      content: '# Changelog\n\nAll notable changes to this model will be documented in this file.\n\n## [Unreleased]\n\n- Initial release',
      order: sections.length + 1,
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    });
  }

  project.sections = sections.sort((a, b) => a.order - b.order);
  project.status = 'complete';
  project.lastGeneratedAt = new Date().toISOString();
  project.updatedAt = new Date().toISOString();

  return project;
}

export function addDocumentationSection(
  projectId: string,
  section: Omit<DocumentationSection, 'id' | 'lastUpdated'>
): DocumentationProject {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  const newSection: DocumentationSection = {
    ...section,
    id: randomUUID(),
    lastUpdated: new Date().toISOString(),
  };

  project.sections.push(newSection);
  project.sections.sort((a, b) => a.order - b.order);
  project.updatedAt = new Date().toISOString();

  return project;
}

export function updateDocumentationSection(
  projectId: string,
  sectionId: string,
  updates: Partial<DocumentationSection>
): DocumentationProject {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  const section = project.sections.find(s => s.id === sectionId);
  if (!section) throw new Error(`Section ${sectionId} not found`);

  Object.assign(section, updates, { lastUpdated: new Date().toISOString() });
  project.updatedAt = new Date().toISOString();

  return project;
}

export function deleteDocumentationSection(projectId: string, sectionId: string): DocumentationProject {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  project.sections = project.sections.filter(s => s.id !== sectionId);
  project.updatedAt = new Date().toISOString();

  return project;
}

export function publishDocumentation(projectId: string, version: string): DocumentationProject {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  const docVersion: DocumentationVersion = {
    version,
    generatedAt: new Date().toISOString(),
    sections: [...project.sections],
    changeLog: `Published version ${version}`,
    publishedAt: new Date().toISOString(),
  };

  project.versions.push(docVersion);
  project.status = 'published';
  project.updatedAt = new Date().toISOString();

  return project;
}

export function generateModelCard(params: {
  modelId: string;
  modelName: string;
  modelVersion: string;
  metadata: ModelCardMetadata;
  customSections?: ModelCardSection[];
}): ModelCard {
  const now = new Date().toISOString();
  const id = randomUUID();

  const modelCard: ModelCard = {
    id,
    modelId: params.modelId,
    modelName: params.modelName,
    modelVersion: params.modelVersion,
    sections: [
      ...generateModelCardSections(),
      ...(params.customSections || []),
    ],
    metadata: params.metadata,
    generatedAt: now,
    updatedAt: now,
  };

  modelCards.set(id, modelCard);
  return modelCard;
}

export function getModelCard(id: string): ModelCard | undefined {
  return modelCards.get(id);
}

export function getModelCardByModelId(modelId: string): ModelCard | undefined {
  return Array.from(modelCards.values()).find(c => c.modelId === modelId);
}

export function updateModelCard(
  modelCardId: string,
  updates: Partial<ModelCard>
): ModelCard {
  const modelCard = modelCards.get(modelCardId);
  if (!modelCard) throw new Error(`Model card ${modelCardId} not found`);

  Object.assign(modelCard, updates, { updatedAt: new Date().toISOString() });
  return modelCard;
}

export function addAPIEndpoint(modelId: string, endpoint: Omit<APIEndpoint, 'path'> & { path: string }): APIEndpoint {
  const endpoints = apiEndpoints.get(modelId) || [];
  
  const newEndpoint: APIEndpoint = {
    ...endpoint,
    examples: endpoint.examples || [],
  };

  endpoints.push(newEndpoint);
  apiEndpoints.set(modelId, endpoints);

  return newEndpoint;
}

export function getAPIEndpoints(modelId: string): APIEndpoint[] {
  return apiEndpoints.get(modelId) || [];
}

export function updateAPIEndpoint(
  modelId: string,
  path: string,
  method: string,
  updates: Partial<APIEndpoint>
): APIEndpoint {
  const endpoints = apiEndpoints.get(modelId) || [];
  const endpoint = endpoints.find(e => e.path === path && e.method === method);
  if (!endpoint) throw new Error(`API endpoint ${method} ${path} not found`);

  Object.assign(endpoint, updates);
  return endpoint;
}

export function addUsageExample(
  modelId: string,
  example: Omit<UsageExample, 'id'>
): UsageExample {
  const examples = usageExamples.get(modelId) || [];

  const newExample: UsageExample = {
    ...example,
    id: randomUUID(),
  };

  examples.push(newExample);
  usageExamples.set(modelId, examples);

  return newExample;
}

export function getUsageExamples(
  modelId: string,
  filters?: { difficulty?: string; tag?: string }
): UsageExample[] {
  let result = usageExamples.get(modelId) || [];

  if (filters?.difficulty) result = result.filter(e => e.difficulty === filters.difficulty);
  if (filters?.tag) result = result.filter(e => e.tags.includes(filters.tag!));

  return result;
}

export function createDocumentationTemplate(params: {
  name: string;
  description: string;
  type: SectionType;
  template: string;
  variables: Omit<TemplateVariable, 'name'>[];
}): DocumentationTemplate {
  const id = randomUUID();

  const template: DocumentationTemplate = {
    id,
    name: params.name,
    description: params.description,
    type: params.type,
    template: params.template,
    variables: params.variables.map(v => ({ ...v, name: randomUUID() })),
    createdAt: new Date().toISOString(),
  };

  documentationTemplates.set(id, template);
  return template;
}

export function getDocumentationTemplate(id: string): DocumentationTemplate | undefined {
  return documentationTemplates.get(id);
}

export function listDocumentationTemplates(
  filters?: { type?: SectionType }
): DocumentationTemplate[] {
  let result = Array.from(documentationTemplates.values());

  if (filters?.type) result = result.filter(t => t.type === filters.type);

  return result.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function applyTemplate(
  templateId: string,
  variables: Record<string, any>
): string {
  const template = documentationTemplates.get(templateId);
  if (!template) throw new Error(`Documentation template ${templateId} not found`);

  let content = template.template;

  for (const [key, value] of Object.entries(variables)) {
    content = content.replace(new RegExp(`{{${key}}}`, 'g'), String(value));
  }

  return content;
}

export function exportDocumentation(
  projectId: string,
  format: 'markdown' | 'html' | 'pdf'
): { content: string; filename: string } {
  const project = documentationProjects.get(projectId);
  if (!project) throw new Error(`Documentation project ${projectId} not found`);

  let content = '';
  const filename = `${project.modelName.toLowerCase().replace(/\s+/g, '-')}-documentation`;

  if (format === 'markdown') {
    content = project.sections.map(s => s.content).join('\n\n---\n\n');
    return { content, filename: `${filename}.md` };
  }

  if (format === 'html') {
    const htmlContent = project.sections.map(s => {
      return `<section>\n${markdownToHtml(s.content)}\n</section>`;
    }).join('\n');

    content = `<!DOCTYPE html>
<html>
<head>
  <title>${project.modelName} Documentation</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1, h2, h3 { color: #333; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
    pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
  </style>
</head>
<body>
${htmlContent}
</body>
</html>`;

    return { content, filename: `${filename}.html` };
  }

  // PDF would require a PDF generation library
  content = project.sections.map(s => s.content).join('\n\n');
  return { content, filename: `${filename}.txt` };
}

function markdownToHtml(markdown: string): string {
  // Simplified markdown to HTML conversion
  let html = markdown;
  
  // Headers
  html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');
  
  // Bold
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  
  // Italic
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');
  
  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
  
  // Inline code
  html = html.replace(/`(.*?)`/g, '<code>$1</code>');
  
  // Line breaks
  html = html.replace(/\n/g, '<br>');
  
  return html;
}
