/**
 * Curated domain catalog for the Universal University & Higher Education Engine.
 * Encodes the world's major university faculties and course families as
 * structured data (AcademicDomain → AcademicField). Courses/programs are
 * generated deterministically from this on demand.
 */
import type { AcademicDomain } from "./universityEngine.js";

export const UNIVERSITY_DOMAINS: AcademicDomain[] = [
  {
    id: "engineering",
    name: "Engineering & Technology",
    description: "Applied mathematics and science to design, build and maintain machines, structures, processes and systems.",
    fields: [
      { id: "civil-engineering", name: "Civil Engineering", description: "Design and construction of infrastructure — roads, bridges, buildings, water systems.", careers: ["Civil Engineer", "Structural Engineer", "Construction Manager", "Infrastructure Planner"], researchPathway: true },
      { id: "mechanical-engineering", name: "Mechanical Engineering", description: "Machines, energy systems, manufacturing and thermal-fluid science.", careers: ["Mechanical Engineer", "Design Engineer", "Manufacturing Engineer", "Energy Analyst"], researchPathway: true },
      { id: "electrical-engineering", name: "Electrical/Electronic Engineering", description: "Circuits, power, electronics and embedded systems.", careers: ["Electrical Engineer", "Power Systems Engineer", "Embedded Systems Engineer"], researchPathway: true },
      { id: "computer-engineering", name: "Computer Engineering", description: "Hardware and software integration, microprocessors and systems.", careers: ["Computer Engineer", "Hardware Engineer", "Firmware Engineer"], researchPathway: true },
      { id: "chemical-engineering", name: "Chemical Engineering", description: "Processes that transform raw materials into products.", careers: ["Chemical Engineer", "Process Engineer", "Quality Engineer"], researchPathway: true },
      { id: "petroleum-engineering", name: "Petroleum Engineering", description: "Exploration, drilling and extraction of oil and gas.", careers: ["Petroleum Engineer", "Reservoir Engineer", "Drilling Engineer"], researchPathway: true },
      { id: "software-engineering", name: "Software Engineering", description: "Design, development and maintenance of software systems.", careers: ["Software Engineer", "Engineering Manager", "DevOps Engineer"], researchPathway: true },
      { id: "biomedical-engineering", name: "Biomedical Engineering", description: "Engineering applied to medicine and healthcare devices.", careers: ["Biomedical Engineer", "Medical Device Engineer", "Clinical Engineer"], researchPathway: true },
      { id: "aerospace-engineering", name: "Aerospace Engineering", description: "Aircraft and spacecraft design, propulsion and systems.", careers: ["Aerospace Engineer", "Flight Systems Engineer", "Propulsion Engineer"], researchPathway: true },
      { id: "environmental-engineering", name: "Environmental Engineering", description: "Environmental protection, water, waste and sustainability.", careers: ["Environmental Engineer", "Sustainability Consultant"], researchPathway: true },
      { id: "agricultural-engineering", name: "Agricultural Engineering", description: "Machinery, structures and systems for agriculture.", careers: ["Agricultural Engineer", "Irrigation Engineer"], researchPathway: true },
      { id: "telecommunications-engineering", name: "Telecommunications Engineering", description: "Communication networks, signals and transmission systems.", careers: ["Telecom Engineer", "Network Engineer"], researchPathway: true },
      { id: "mechatronics", name: "Mechatronics", description: "Integration of mechanical, electronic and computing systems.", careers: ["Mechatronics Engineer", "Automation Engineer", "Robotics Engineer"], researchPathway: true },
      { id: "robotics", name: "Robotics", description: "Design, control and programming of robots and autonomous systems.", careers: ["Robotics Engineer", "Automation Specialist", "AI Robotics Researcher"], researchPathway: true },
      { id: "artificial-intelligence", name: "Artificial Intelligence", description: "Intelligent systems, learning algorithms and autonomous reasoning.", careers: ["AI Engineer", "ML Engineer", "Research Scientist"], researchPathway: true },
      { id: "cybersecurity", name: "Cybersecurity", description: "Protecting systems, networks and data from attack.", careers: ["Security Analyst", "Penetration Tester", "Security Architect"], researchPathway: true },
      { id: "data-science", name: "Data Science", description: "Extracting insight and value from data at scale.", careers: ["Data Scientist", "Data Analyst", "ML Engineer"], researchPathway: true },
    ],
  },
  {
    id: "computing",
    name: "Computer Science & Information Technology",
    description: "Computation, software, data and information systems.",
    fields: [
      { id: "computer-science", name: "Computer Science", description: "Foundations of computation, algorithms, programming and systems.", careers: ["Software Engineer", "Computer Scientist", "Researcher"], researchPathway: true },
      { id: "information-technology", name: "Information Technology", description: "Deploying and managing technology in organisations.", careers: ["IT Specialist", "Systems Administrator", "Support Engineer"] },
      { id: "information-systems", name: "Information Systems", description: "People, processes and technology in organisations.", careers: ["Systems Analyst", "IT Consultant", "Business Analyst"] },
      { id: "software-development", name: "Software Development", description: "Building and shipping software products.", careers: ["Developer", "Full-stack Engineer", "Technical Lead"] },
      { id: "cloud-computing", name: "Cloud Computing", description: "Distributed systems, cloud platforms and infrastructure as code.", careers: ["Cloud Architect", "DevOps Engineer", "SRE"], researchPathway: true },
      { id: "machine-learning", name: "Machine Learning", description: "Algorithms that learn from data.", careers: ["ML Engineer", "MLOps Engineer", "Research Scientist"], researchPathway: true },
      { id: "data-analytics", name: "Data Analytics", description: "Analysing data to support decisions.", careers: ["Data Analyst", "BI Analyst", "Analytics Manager"] },
      { id: "database-systems", name: "Database Systems", description: "Storing, querying and modelling data.", careers: ["Database Administrator", "Data Engineer"] },
      { id: "networking", name: "Networking", description: "Computer networks, protocols and connectivity.", careers: ["Network Engineer", "Network Architect"] },
      { id: "human-computer-interaction", name: "Human-Computer Interaction", description: "Designing usable and accessible interfaces.", careers: ["UX Researcher", "Interaction Designer"], researchPathway: true },
      { id: "computer-graphics", name: "Computer Graphics", description: "Rendering, animation and visual computing.", careers: ["Graphics Programmer", "Technical Artist"], researchPathway: true },
      { id: "game-development", name: "Game Development", description: "Designing and building games.", careers: ["Game Developer", "Game Designer", "QA Tester"] },
      { id: "blockchain-web3", name: "Blockchain/Web3", description: "Distributed ledgers and decentralised applications.", careers: ["Blockchain Developer", "Web3 Engineer"], researchPathway: true },
    ],
  },
  {
    id: "medicine",
    name: "Medicine & Health Sciences",
    description: "Health, medicine and the allied health professions.",
    fields: [
      { id: "medicine", name: "Medicine", description: "Diagnosis, treatment and prevention of disease.", careers: ["Medical Doctor", "Specialist", "Medical Researcher"], researchPathway: true },
      { id: "nursing", name: "Nursing", description: "Patient care and health promotion.", careers: ["Registered Nurse", "Nurse Practitioner", "Nurse Educator"] },
      { id: "pharmacy", name: "Pharmacy", description: "Drugs, their action and safe dispensing.", careers: ["Pharmacist", "Clinical Pharmacist", "Pharmaceutical Researcher"], researchPathway: true },
      { id: "dentistry", name: "Dentistry", description: "Oral health and dental treatment.", careers: ["Dentist", "Dental Surgeon", "Orthodontist"] },
      { id: "medical-laboratory-science", name: "Medical Laboratory Science", description: "Laboratory diagnosis of disease.", careers: ["Medical Lab Scientist", "Pathology Technician"] },
      { id: "public-health", name: "Public Health", description: "Population health, prevention and policy.", careers: ["Public Health Officer", "Epidemiologist", "Health Policy Analyst"], researchPathway: true },
      { id: "physiotherapy", name: "Physiotherapy", description: "Movement, function and rehabilitation.", careers: ["Physiotherapist", "Rehabilitation Specialist"] },
      { id: "radiography", name: "Radiography", description: "Medical imaging for diagnosis and therapy.", careers: ["Radiographer", "Imaging Technologist"] },
      { id: "optometry", name: "Optometry", description: "Vision, eye health and correction.", careers: ["Optometrist", "Vision Scientist"] },
      { id: "nutrition", name: "Nutrition & Dietetics", description: "Diet, health and clinical nutrition.", careers: ["Dietitian", "Nutritionist", "Food Scientist"] },
      { id: "biomedical-sciences", name: "Biomedical Sciences", description: "Biological basis of health and disease.", careers: ["Biomedical Scientist", "Research Associate"], researchPathway: true },
      { id: "anatomy", name: "Anatomy", description: "Structure of the human body.", careers: ["Anatomist", "Medical Educator"], researchPathway: true },
      { id: "physiology", name: "Physiology", description: "Function of the human body.", careers: ["Physiologist", "Exercise Physiologist"], researchPathway: true },
      { id: "veterinary-medicine", name: "Veterinary Medicine", description: "Animal health and medicine.", careers: ["Veterinarian", "Veterinary Surgeon"], researchPathway: true },
      { id: "health-administration", name: "Health Administration", description: "Managing health organisations and systems.", careers: ["Hospital Administrator", "Health Services Manager"] },
    ],
  },
  {
    id: "business",
    name: "Business & Economics",
    description: "Organisations, markets, finance and management.",
    fields: [
      { id: "accounting", name: "Accounting", description: "Recording, reporting and auditing financial information.", careers: ["Accountant", "Auditor", "CFO"], researchPathway: true },
      { id: "finance", name: "Finance", description: "Money, investment and financial markets.", careers: ["Financial Analyst", "Investment Banker", "Portfolio Manager"], researchPathway: true },
      { id: "economics", name: "Economics", description: "Production, distribution and consumption of resources.", careers: ["Economist", "Policy Analyst", "Data Economist"], researchPathway: true },
      { id: "business-administration", name: "Business Administration", description: "General management of organisations.", careers: ["Business Manager", "Administrator", "Entrepreneur"] },
      { id: "marketing", name: "Marketing", description: "Understanding customers and promoting products.", careers: ["Marketing Manager", "Brand Manager", "Digital Marketer"] },
      { id: "entrepreneurship", name: "Entrepreneurship", description: "Creating and scaling new ventures.", careers: ["Founder", "Startup Consultant", "Venture Capitalist"] },
      { id: "management", name: "Management", description: "Planning, organising, leading and controlling.", careers: ["Operations Manager", "Project Manager", "General Manager"] },
      { id: "human-resources", name: "Human Resources", description: "Managing people and organisational culture.", careers: ["HR Manager", "Recruiter", "People Ops Lead"] },
      { id: "international-business", name: "International Business", description: "Business across borders and cultures.", careers: ["International Trade Manager", "Export Manager"] },
      { id: "banking", name: "Banking", description: "Financial intermediation and bank operations.", careers: ["Banker", "Credit Analyst", "Relationship Manager"] },
      { id: "insurance", name: "Insurance", description: "Risk transfer, underwriting and claims.", careers: ["Underwriter", "Actuary", "Claims Manager"] },
      { id: "supply-chain", name: "Supply Chain Management", description: "Flow of goods, services and information.", careers: ["Supply Chain Manager", "Logistics Manager", "Procurement Lead"] },
      { id: "procurement", name: "Procurement", description: "Acquiring goods and services for organisations.", careers: ["Procurement Officer", "Buyer", "Category Manager"] },
      { id: "business-analytics", name: "Business Analytics", description: "Data-driven business decision making.", careers: ["Business Analyst", "Analytics Consultant"], researchPathway: true },
    ],
  },
  {
    id: "law",
    name: "Law",
    description: "Legal systems, justice, rights and legal practice.",
    fields: [
      { id: "law", name: "Law", description: "General legal study and legal practice.", careers: ["Lawyer", "Barrister", "Legal Advisor"], researchPathway: true },
      { id: "international-law", name: "International Law", description: "Law governing states and international actors.", careers: ["International Lawyer", "Diplomat"], researchPathway: true },
      { id: "corporate-law", name: "Corporate Law", description: "Law of business entities and governance.", careers: ["Corporate Counsel", "Compliance Officer"], researchPathway: true },
      { id: "commercial-law", name: "Commercial Law", description: "Law of commerce, trade and transactions.", careers: ["Commercial Lawyer", "Transaction Advisor"] },
      { id: "criminal-law", name: "Criminal Law", description: "Crimes, defences and criminal procedure.", careers: ["Prosecutor", "Defence Lawyer", "Criminal Justice Advisor"] },
      { id: "constitutional-law", name: "Constitutional Law", description: "State structure and fundamental rights.", careers: ["Constitutional Lawyer", "Public Law Counsel"], researchPathway: true },
      { id: "human-rights-law", name: "Human Rights Law", description: "Protection of fundamental rights.", careers: ["Human Rights Lawyer", "NGO Counsel"], researchPathway: true },
      { id: "intellectual-property", name: "Intellectual Property Law", description: "Patents, trademarks, copyright and IP rights.", careers: ["IP Attorney", "Patent Agent"] },
      { id: "environmental-law", name: "Environmental Law", description: "Law protecting the environment.", careers: ["Environmental Lawyer", "Regulatory Advisor"] },
      { id: "maritime-law", name: "Maritime Law", description: "Law of the sea and shipping.", careers: ["Maritime Lawyer", "Shipping Counsel"] },
      { id: "tax-law", name: "Tax Law", description: "Taxation and fiscal regulation.", careers: ["Tax Lawyer", "Tax Advisor"] },
    ],
  },
  {
    id: "natural-sciences",
    name: "Natural Sciences",
    description: "The fundamental sciences of matter, life and the universe.",
    fields: [
      { id: "mathematics", name: "Mathematics", description: "Numbers, structure, space and change.", careers: ["Mathematician", "Quantitative Analyst", "Data Scientist"], researchPathway: true },
      { id: "statistics", name: "Statistics", description: "Collecting and analysing data.", careers: ["Statistician", "Biostatistician", "Data Scientist"], researchPathway: true },
      { id: "physics", name: "Physics", description: "Matter, energy and the laws of the universe.", careers: ["Physicist", "Research Scientist", "Quantitative Analyst"], researchPathway: true },
      { id: "chemistry", name: "Chemistry", description: "Composition, structure and reactions of matter.", careers: ["Chemist", "Chemical Analyst", "Materials Scientist"], researchPathway: true },
      { id: "biology", name: "Biology", description: "Life and living organisms.", careers: ["Biologist", "Lab Researcher", "Conservation Scientist"], researchPathway: true },
      { id: "biochemistry", name: "Biochemistry", description: "Chemical processes in living organisms.", careers: ["Biochemist", "Pharmaceutical Researcher"], researchPathway: true },
      { id: "biotechnology", name: "Biotechnology", description: "Using biology for technology and products.", careers: ["Biotechnologist", "R&D Scientist"], researchPathway: true },
      { id: "microbiology", name: "Microbiology", description: "Microorganisms and their effects.", careers: ["Microbiologist", "Quality Control Scientist"], researchPathway: true },
      { id: "geology", name: "Geology", description: "The Earth, its materials and processes.", careers: ["Geologist", "Petroleum Geologist", "Environmental Consultant"], researchPathway: true },
      { id: "environmental-science", name: "Environmental Science", description: "Interactions between environment and society.", careers: ["Environmental Scientist", "Sustainability Analyst"], researchPathway: true },
      { id: "astronomy", name: "Astronomy", description: "Celestial objects and the cosmos.", careers: ["Astronomer", "Astrophysicist"], researchPathway: true },
      { id: "earth-sciences", name: "Earth Sciences", description: "The physical Earth and climate systems.", careers: ["Earth Scientist", "Climate Scientist"], researchPathway: true },
    ],
  },
  {
    id: "social-sciences",
    name: "Social Sciences",
    description: "Human society, behaviour and relationships.",
    fields: [
      { id: "psychology", name: "Psychology", description: "Mind, behaviour and mental processes.", careers: ["Psychologist", "Counsellor", "Researcher"], researchPathway: true },
      { id: "sociology", name: "Sociology", description: "Society, institutions and social change.", careers: ["Sociologist", "Policy Researcher"], researchPathway: true },
      { id: "political-science", name: "Political Science", description: "Power, governance and political systems.", careers: ["Policy Analyst", "Political Consultant", "Researcher"], researchPathway: true },
      { id: "international-relations", name: "International Relations", description: "Relations between states and global actors.", careers: ["Diplomat", "Intelligence Analyst", "NGO Specialist"], researchPathway: true },
      { id: "geography", name: "Geography", description: "People, places and the environment.", careers: ["Geographer", "GIS Specialist", "Urban Planner"] },
      { id: "anthropology", name: "Anthropology", description: "Human cultures, societies and evolution.", careers: ["Anthropologist", "Researcher"], researchPathway: true },
      { id: "development-studies", name: "Development Studies", description: "Social and economic development.", careers: ["Development Officer", "NGO Programme Manager"] },
      { id: "social-work", name: "Social Work", description: "Supporting individuals and communities.", careers: ["Social Worker", "Community Organiser"] },
      { id: "criminology", name: "Criminology", description: "Crime, its causes and control.", careers: ["Criminologist", "Crime Analyst", "Corrections Specialist"], researchPathway: true },
      { id: "communication-studies", name: "Communication Studies", description: "Human and mediated communication.", careers: ["Communication Specialist", "Corporate Communicator"] },
    ],
  },
  {
    id: "arts-humanities",
    name: "Arts & Humanities",
    description: "Human culture, creativity, language and ideas.",
    fields: [
      { id: "english", name: "English", description: "English language, literature and writing.", careers: ["Writer", "Editor", "Educator"], researchPathway: true },
      { id: "history", name: "History", description: "The human past and historical analysis.", careers: ["Historian", "Archivist", "Researcher"], researchPathway: true },
      { id: "philosophy", name: "Philosophy", description: "Reasoning about existence, knowledge and ethics.", careers: ["Philosopher", "Analyst", "Researcher"], researchPathway: true },
      { id: "religious-studies", name: "Religious Studies", description: "Religion, belief and practice.", careers: ["Religious Scholar", "Researcher"], researchPathway: true },
      { id: "languages", name: "Languages", description: "Modern and classical languages.", careers: ["Translator", "Interpreter", "Language Educator"] },
      { id: "linguistics", name: "Linguistics", description: "The science of language.", careers: ["Linguist", "NLP Specialist", "Researcher"], researchPathway: true },
      { id: "literature", name: "Literature", description: "Literary works and criticism.", careers: ["Critic", "Writer", "Academic"], researchPathway: true },
      { id: "cultural-studies", name: "Cultural Studies", description: "Culture, media and meaning.", careers: ["Cultural Analyst", "Researcher"], researchPathway: true },
      { id: "fine-arts", name: "Fine Arts", description: "Visual art creation and theory.", careers: ["Artist", "Curator", "Art Educator"] },
      { id: "music", name: "Music", description: "Music performance, theory and history.", careers: ["Musician", "Composer", "Music Educator"] },
      { id: "theatre", name: "Theatre", description: "Performance and dramatic arts.", careers: ["Actor", "Director", "Dramaturg"] },
      { id: "film", name: "Film", description: "Film production and studies.", careers: ["Filmmaker", "Screenwriter", "Editor"] },
      { id: "dance", name: "Dance", description: "Dance performance and choreography.", careers: ["Dancer", "Choreographer"] },
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Teaching, learning and educational systems.",
    fields: [
      { id: "early-childhood", name: "Early Childhood Education", description: "Education of young children.", careers: ["Early Childhood Educator", "Kindergarten Teacher"] },
      { id: "primary-education", name: "Primary Education", description: "Teaching in primary schools.", careers: ["Primary Teacher"] },
      { id: "secondary-education", name: "Secondary Education", description: "Teaching in secondary schools.", careers: ["Secondary Teacher", "Subject Specialist"] },
      { id: "special-education", name: "Special Education", description: "Education for learners with special needs.", careers: ["Special Educator", "Inclusion Specialist"] },
      { id: "educational-psychology", name: "Educational Psychology", description: "Psychology of learning and development.", careers: ["Educational Psychologist"], researchPathway: true },
      { id: "educational-administration", name: "Educational Administration", description: "Leading schools and education systems.", careers: ["School Principal", "Education Administrator"] },
      { id: "curriculum-studies", name: "Curriculum Studies", description: "Design of curricula and learning programmes.", careers: ["Curriculum Designer", "Instructional Designer"] },
      { id: "educational-technology", name: "Educational Technology", description: "Technology for learning.", careers: ["EdTech Specialist", "E-learning Designer"] },
      { id: "adult-education", name: "Adult Education", description: "Education for adult learners.", careers: ["Adult Educator", "Trainer"] },
      { id: "vocational-education", name: "Vocational Education", description: "Skills and trade education.", careers: ["Vocational Instructor", "Skills Trainer"] },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture & Environmental Studies",
    description: "Food, farming, forestry, fisheries and the environment.",
    fields: [
      { id: "agriculture", name: "Agriculture", description: "Farming and agricultural systems.", careers: ["Farmer", "Agricultural Officer"], researchPathway: true },
      { id: "agronomy", name: "Agronomy", description: "Crop and soil science.", careers: ["Agronomist", "Crop Scientist"], researchPathway: true },
      { id: "animal-science", name: "Animal Science", description: "Livestock production and animal biology.", careers: ["Animal Scientist", "Livestock Manager"], researchPathway: true },
      { id: "crop-science", name: "Crop Science", description: "Crop production and improvement.", careers: ["Crop Scientist", "Plant Breeder"], researchPathway: true },
      { id: "forestry", name: "Forestry", description: "Forest management and conservation.", careers: ["Forester", "Conservation Manager"], researchPathway: true },
      { id: "fisheries", name: "Fisheries", description: "Fish and aquatic resource management.", careers: ["Fisheries Officer", "Aquaculture Specialist"] },
      { id: "agricultural-economics", name: "Agricultural Economics", description: "Economics of agriculture and food.", careers: ["Agricultural Economist", "Policy Analyst"], researchPathway: true },
      { id: "soil-science", name: "Soil Science", description: "Soil as a resource for life.", careers: ["Soil Scientist", "Environmental Consultant"], researchPathway: true },
      { id: "environmental-management", name: "Environmental Management", description: "Managing environmental impact and resources.", careers: ["Environmental Manager", "Sustainability Officer"] },
      { id: "climate-science", name: "Climate Science", description: "Climate systems and change.", careers: ["Climate Scientist", "Climate Policy Advisor"], researchPathway: true },
      { id: "food-science", name: "Food Science", description: "Food production, safety and technology.", careers: ["Food Scientist", "Quality Assurance Manager"], researchPathway: true },
      { id: "agricultural-technology", name: "Agricultural Technology", description: "Technology and precision in agriculture.", careers: ["AgTech Specialist", "Precision Agriculture Analyst"] },
    ],
  },
  {
    id: "architecture",
    name: "Architecture, Construction & Built Environment",
    description: "Design and management of buildings and the built environment.",
    fields: [
      { id: "architecture", name: "Architecture", description: "Design of buildings and spaces.", careers: ["Architect", "Urban Designer"], researchPathway: true },
      { id: "urban-planning", name: "Urban Planning", description: "Planning cities and regions.", careers: ["Urban Planner", "Regional Planner"], researchPathway: true },
      { id: "quantity-surveying", name: "Quantity Surveying", description: "Construction cost and contract management.", careers: ["Quantity Surveyor", "Cost Consultant"] },
      { id: "estate-management", name: "Estate Management", description: "Property and facilities management.", careers: ["Estate Manager", "Property Manager"] },
      { id: "building-technology", name: "Building Technology", description: "Construction methods and building science.", careers: ["Building Technologist", "Construction Supervisor"] },
      { id: "surveying-geoinformatics", name: "Surveying & Geoinformatics", description: "Measurement and mapping of land.", careers: ["Surveyor", "Geomatics Engineer", "GIS Specialist"] },
      { id: "construction-management", name: "Construction Management", description: "Managing construction projects.", careers: ["Construction Manager", "Project Director"] },
      { id: "landscape-architecture", name: "Landscape Architecture", description: "Design of outdoor spaces.", careers: ["Landscape Architect", "Landscape Designer"] },
    ],
  },
  {
    id: "media",
    name: "Media & Communication",
    description: "Journalism, broadcasting and media production.",
    fields: [
      { id: "journalism", name: "Journalism", description: "News reporting and storytelling.", careers: ["Journalist", "Reporter", "Correspondent"] },
      { id: "mass-communication", name: "Mass Communication", description: "Communication to large audiences.", careers: ["Communications Officer", "Media Planner"] },
      { id: "public-relations", name: "Public Relations", description: "Managing public image and relationships.", careers: ["PR Specialist", "Communications Manager"] },
      { id: "advertising", name: "Advertising", description: "Creating and placing advertisements.", careers: ["Copywriter", "Media Buyer", "Brand Strategist"] },
      { id: "broadcasting", name: "Broadcasting", description: "Radio and television production.", careers: ["Broadcaster", "Producer", "Announcer"] },
      { id: "digital-media", name: "Digital Media", description: "Digital content and platforms.", careers: ["Digital Media Specialist", "Content Strategist"] },
      { id: "film-production", name: "Film Production", description: "Producing films and media.", careers: ["Film Producer", "Production Manager"] },
      { id: "strategic-communication", name: "Strategic Communication", description: "Communication aligned to strategy.", careers: ["Strategic Communicator", "Crisis Communicator"] },
    ],
  },
  {
    id: "hospitality",
    name: "Hospitality, Tourism & Aviation",
    description: "Hospitality, travel and aviation industries.",
    fields: [
      { id: "tourism-management", name: "Tourism Management", description: "Managing tourism businesses and destinations.", careers: ["Tourism Manager", "Destination Specialist"] },
      { id: "hospitality-management", name: "Hospitality Management", description: "Managing hospitality businesses.", careers: ["Hospitality Manager", "Operations Director"] },
      { id: "hotel-management", name: "Hotel Management", description: "Managing hotels and accommodation.", careers: ["Hotel Manager", "Front Office Manager"] },
      { id: "travel-management", name: "Travel Management", description: "Planning and selling travel.", careers: ["Travel Consultant", "Tour Operator"] },
      { id: "aviation-management", name: "Aviation Management", description: "Managing aviation operations.", careers: ["Aviation Manager", "Airport Operations Manager"] },
      { id: "airport-management", name: "Airport Management", description: "Managing airport operations.", careers: ["Airport Manager", "Ground Operations Lead"] },
      { id: "airline-operations", name: "Airline Operations", description: "Running airline operations.", careers: ["Operations Controller", "Crew Manager"] },
    ],
  },
  {
    id: "transportation",
    name: "Transportation & Maritime",
    description: "Movement of people, goods and ships.",
    fields: [
      { id: "transportation-management", name: "Transportation Management", description: "Managing transport systems.", careers: ["Transport Manager", "Logistics Planner"] },
      { id: "logistics", name: "Logistics", description: "Coordinating movement and storage.", careers: ["Logistics Manager", "Warehouse Manager"] },
      { id: "maritime-studies", name: "Maritime Studies", description: "The shipping and maritime industry.", careers: ["Maritime Officer", "Shipping Manager"], researchPathway: true },
      { id: "marine-engineering", name: "Marine Engineering", description: "Engineering of ships and marine systems.", careers: ["Marine Engineer", "Naval Architect"], researchPathway: true },
      { id: "nautical-science", name: "Nautical Science", description: "Navigation and ship operation.", careers: ["Ship Captain", "Navigator"] },
      { id: "port-management", name: "Port Management", description: "Managing ports and terminals.", careers: ["Port Manager", "Terminal Operator"] },
    ],
  },
  {
    id: "military-security",
    name: "Military, Security & Emergency Studies",
    description: "Security, intelligence, defence and emergency response.",
    fields: [
      { id: "security-studies", name: "Security Studies", description: "Security threats and strategy.", careers: ["Security Analyst", "Security Advisor"], researchPathway: true },
      { id: "intelligence-studies", name: "Intelligence Studies", description: "Intelligence collection and analysis.", careers: ["Intelligence Analyst", "Counterintelligence Officer"], researchPathway: true },
      { id: "forensic-science", name: "Forensic Science", description: "Applying science to legal investigation.", careers: ["Forensic Scientist", "Crime Lab Analyst"], researchPathway: true },
      { id: "emergency-management", name: "Emergency Management", description: "Preparing for and responding to emergencies.", careers: ["Emergency Manager", "First Responder Coordinator"] },
      { id: "disaster-management", name: "Disaster Management", description: "Managing disasters and recovery.", careers: ["Disaster Manager", "Humanitarian Coordinator"] },
      { id: "peace-conflict", name: "Peace & Conflict Studies", description: "Conflict resolution and peacebuilding.", careers: ["Peacebuilding Officer", "Mediator"], researchPathway: true },
      { id: "strategic-studies", name: "Strategic Studies", description: "Strategy in security and defence.", careers: ["Strategy Analyst", "Defence Researcher"], researchPathway: true },
      { id: "defence-studies", name: "Defence Studies", description: "Defence policy and operations.", careers: ["Defence Analyst", "Policy Advisor"], researchPathway: true },
    ],
  },
  {
    id: "professional",
    name: "Professional & Specialized Fields",
    description: "Specialised professions and interdisciplinary studies.",
    fields: [
      { id: "library-science", name: "Library & Information Science", description: "Managing libraries and information.", careers: ["Librarian", "Information Specialist"], researchPathway: true },
      { id: "sports-science", name: "Sports Science", description: "Science of sport and performance.", careers: ["Sports Scientist", "Performance Analyst"], researchPathway: true },
      { id: "kinesiology", name: "Kinesiology", description: "Human movement science.", careers: ["Kinesiologist", "Exercise Specialist"] },
      { id: "fashion", name: "Fashion", description: "Fashion design and business.", careers: ["Fashion Designer", "Fashion Buyer"] },
      { id: "interior-design", name: "Interior Design", description: "Design of interior spaces.", careers: ["Interior Designer", "Space Planner"] },
      { id: "real-estate", name: "Real Estate", description: "Property, valuation and investment.", careers: ["Real Estate Agent", "Valuer", "Property Developer"] },
      { id: "public-administration", name: "Public Administration", description: "Managing public institutions.", careers: ["Public Administrator", "Civil Servant"], researchPathway: true },
      { id: "international-development", name: "International Development", description: "Global development and aid.", careers: ["Development Specialist", "Programme Officer"], researchPathway: true },
      { id: "occupational-safety", name: "Occupational Safety", description: "Workplace safety and health.", careers: ["Safety Officer", "EHS Specialist"] },
      { id: "occupational-health", name: "Occupational Health", description: "Health at work.", careers: ["Occupational Health Advisor"] },
      { id: "indigenous-studies", name: "Indigenous Studies", description: "Indigenous cultures and knowledge.", careers: ["Indigenous Policy Advisor", "Researcher"], researchPathway: true },
      { id: "gender-studies", name: "Gender Studies", description: "Gender and society.", careers: ["Gender Specialist", "Researcher"], researchPathway: true },
      { id: "african-studies", name: "African Studies", description: "African societies, history and politics.", careers: ["African Studies Researcher", "Policy Advisor"], researchPathway: true },
      { id: "area-studies", name: "Area Studies", description: "Regional studies of the world.", careers: ["Area Specialist", "Researcher", "Diplomat"], researchPathway: true },
    ],
  },
];

export const DOMAIN_BY_ID: Record<string, AcademicDomain> = Object.fromEntries(
  UNIVERSITY_DOMAINS.map((d) => [d.id, d]),
);

export const FIELD_BY_ID: Record<string, { domain: AcademicDomain; field: AcademicDomain["fields"][number] }> =
  Object.fromEntries(
    UNIVERSITY_DOMAINS.flatMap((d) => d.fields.map((f) => [f.id, { domain: d, field: f }])),
  );
