/**
 * Global University Directory + country education-system profiles.
 * Representative seed data for the Universal University engine's directory —
 * real institutions. Education providers can extend via imports / admin / APIs.
 */
import type { CountryEducationProfile, UniversityRecord } from "./universityEngine.js";

const DEG = [
  "undergraduate_certificate", "undergraduate_diploma", "associate_degree", "bachelor",
  "postgraduate_diploma", "master", "professional_master", "phd", "postdoctoral",
  "professional_certification", "continuing_education", "executive_education",
] as UniversityRecord["degreesOffered"];

export const UNIVERSITY_DIRECTORY: UniversityRecord[] = [
  // ── Africa ─────────────────────────────────────────────────────
  { id: "unilag", name: "University of Lagos", country: "NG", city: "Lagos", type: "university", ownership: "public", founded: 1962, website: "unilag.edu.ng", domains: ["engineering", "medicine", "business", "law", "natural-sciences"], degreesOffered: DEG, notes: ["First-choice Nigerian federal university", "Accredited by NUC"] },
  { id: "unn", name: "University of Nigeria, Nsukka", country: "NG", city: "Nsukka", type: "university", ownership: "public", founded: 1955, website: "unn.edu.ng", domains: ["engineering", "agriculture", "medicine", "education", "social-sciences"], degreesOffered: DEG, notes: ["First fully-fledged Nigerian university", "Large research output"] },
  { id: "covenant", name: "Covenant University", country: "NG", city: "Ota", type: "university", ownership: "private", founded: 2002, website: "covenantuniversity.edu.ng", domains: ["engineering", "computing", "business", "natural-sciences"], degreesOffered: DEG, notes: ["Top-ranked private university in Nigeria"] },
  { id: "university-of-ghana", name: "University of Ghana", country: "GH", city: "Accra", type: "university", ownership: "public", founded: 1948, website: "ug.edu.gh", domains: ["medicine", "law", "business", "social-sciences", "natural-sciences"], degreesOffered: DEG, notes: ["Oldest and largest university in Ghana", "Accredited by GTEC"] },
  { id: "kwame-nkrumah", name: "Kwame Nkrumah University of Science & Technology", country: "GH", city: "Kumasi", type: "university", ownership: "public", founded: 1952, website: "knust.edu.gh", domains: ["engineering", "architecture", "medicine", "agriculture"], degreesOffered: DEG, notes: ["Ghana's leading science & technology university"] },
  { id: "university-of-nairobi", name: "University of Nairobi", country: "KE", city: "Nairobi", type: "university", ownership: "public", founded: 1970, website: "uonbi.ac.ke", domains: ["engineering", "medicine", "law", "business", "agriculture"], degreesOffered: DEG, notes: ["Kenya's premier research university"] },
  { id: "university-of-cape-town", name: "University of Cape Town", country: "ZA", city: "Cape Town", type: "university", ownership: "public", founded: 1829, website: "uct.ac.za", domains: ["engineering", "medicine", "business", "law", "natural-sciences"], degreesOffered: DEG, notes: ["Africa's highest-ranked university", "Research-intensive"] },
  { id: "stellenbosch", name: "Stellenbosch University", country: "ZA", city: "Stellenbosch", type: "university", ownership: "public", founded: 1918, website: "sun.ac.za", domains: ["engineering", "medicine", "agriculture", "business"], degreesOffered: DEG, notes: ["Leading South African research university"] },
  { id: "university-of-ibadan", name: "University of Ibadan", country: "NG", city: "Ibadan", type: "university", ownership: "public", founded: 1948, website: "ui.edu.ng", domains: ["medicine", "agriculture", "social-sciences", "arts-humanities"], degreesOffered: DEG, notes: ["Nigeria's first university", "Historically strong humanities"] },
  { id: "kwara-state", name: "Kwara State University", country: "NG", city: "Malete", type: "university", ownership: "public", founded: 2009, website: "kwasu.edu.ng", domains: ["engineering", "computing", "business", "agriculture"], degreesOffered: DEG, notes: ["State university with growing tech programmes"] },
  { id: "university-of-benin", name: "University of Benin", country: "NG", city: "Benin City", type: "university", ownership: "public", founded: 1970, website: "uniben.edu", domains: ["engineering", "medicine", "law", "education", "natural-sciences"], degreesOffered: DEG, notes: ["Major Nigerian federal university in Benin City"] },

  // ── United States ──────────────────────────────────────────────
  { id: "harvard", name: "Harvard University", country: "US", city: "Cambridge, MA", type: "university", ownership: "private", founded: 1636, website: "harvard.edu", domains: ["business", "law", "medicine", "arts-humanities", "social-sciences", "natural-sciences"], degreesOffered: DEG, notes: ["Ivy League", "World's oldest university in the US", "Highly selective"] },
  { id: "mit", name: "Massachusetts Institute of Technology", country: "US", city: "Cambridge, MA", type: "institute", ownership: "private", founded: 1861, website: "mit.edu", domains: ["engineering", "computing", "natural-sciences", "architecture"], degreesOffered: DEG, notes: ["World leader in engineering & computing", "Research-intensive"] },
  { id: "stanford", name: "Stanford University", country: "US", city: "Stanford, CA", type: "university", ownership: "private", founded: 1885, website: "stanford.edu", domains: ["engineering", "computing", "business", "law", "medicine"], degreesOffered: DEG, notes: ["Silicon Valley powerhouse", "Entrepreneurship focus"] },
  { id: "uc-berkeley", name: "University of California, Berkeley", country: "US", city: "Berkeley, CA", type: "university", ownership: "public", founded: 1868, website: "berkeley.edu", domains: ["engineering", "computing", "natural-sciences", "social-sciences", "business"], degreesOffered: DEG, notes: ["Top public research university"] },

  // ── United Kingdom ─────────────────────────────────────────────
  { id: "oxford", name: "University of Oxford", country: "GB", city: "Oxford", type: "university", ownership: "public", founded: 1096, website: "ox.ac.uk", domains: ["arts-humanities", "law", "medicine", "social-sciences", "natural-sciences"], degreesOffered: DEG, notes: ["Oldest English-speaking university", "Tutorial system"] },
  { id: "cambridge", name: "University of Cambridge", country: "GB", city: "Cambridge", type: "university", ownership: "public", founded: 1209, website: "cam.ac.uk", domains: ["engineering", "natural-sciences", "law", "medicine", "computing"], degreesOffered: DEG, notes: ["Renowned for sciences & engineering"] },
  { id: "imperial", name: "Imperial College London", country: "GB", city: "London", type: "university", ownership: "public", founded: 1907, website: "imperial.ac.uk", domains: ["engineering", "computing", "medicine", "natural-sciences"], degreesOffered: DEG, notes: ["STEM-focused, globally ranked"] },
  { id: "ucl", name: "University College London", country: "GB", city: "London", type: "university", ownership: "public", founded: 1826, website: "ucl.ac.uk", domains: ["medicine", "law", "business", "arts-humanities", "engineering"], degreesOffered: DEG, notes: ["Large multidisciplinary research university"] },

  // ── Canada / Australia ─────────────────────────────────────────
  { id: "toronto", name: "University of Toronto", country: "CA", city: "Toronto", type: "university", ownership: "public", founded: 1827, website: "utoronto.ca", domains: ["engineering", "computing", "medicine", "business", "arts-humanities"], degreesOffered: DEG, notes: ["Canada's top research university"] },
  { id: "ubc", name: "University of British Columbia", country: "CA", city: "Vancouver", type: "university", ownership: "public", founded: 1908, website: "ubc.ca", domains: ["engineering", "medicine", "business", "natural-sciences"], degreesOffered: DEG, notes: ["Leading Canadian research university"] },
  { id: "melbourne", name: "University of Melbourne", country: "AU", city: "Melbourne", type: "university", ownership: "public", founded: 1853, website: "unimelb.edu.au", domains: ["medicine", "engineering", "business", "law", "arts-humanities"], degreesOffered: DEG, notes: ["Australia's leading research university"] },
  { id: "sydney", name: "University of Sydney", country: "AU", city: "Sydney", type: "university", ownership: "public", founded: 1850, website: "sydney.edu.au", domains: ["medicine", "engineering", "business", "law", "arts-humanities"], degreesOffered: DEG, notes: ["Australia's first university"] },

  // ── Europe ─────────────────────────────────────────────────────
  { id: "lmu-munich", name: "Ludwig Maximilian University of Munich", country: "DE", city: "Munich", type: "university", ownership: "public", founded: 1472, website: "lmu.de", domains: ["medicine", "natural-sciences", "arts-humanities", "social-sciences"], degreesOffered: DEG, notes: ["Germany's leading research university"] },
  { id: "tu-munich", name: "Technical University of Munich", country: "DE", city: "Munich", type: "university", ownership: "public", founded: 1868, website: "tum.de", domains: ["engineering", "computing", "natural-sciences", "architecture"], degreesOffered: DEG, notes: ["Top European technical university"] },
  { id: "sorbonne", name: "Sorbonne University", country: "FR", city: "Paris", type: "university", ownership: "public", founded: 1253, website: "sorbonne-universite.fr", domains: ["natural-sciences", "arts-humanities", "medicine"], degreesOffered: DEG, notes: ["Major French research university"] },

  // ── Asia ───────────────────────────────────────────────────────
  { id: "iit-delhi", name: "Indian Institute of Technology Delhi", country: "IN", city: "New Delhi", type: "institute", ownership: "public", founded: 1961, website: "iitd.ac.in", domains: ["engineering", "computing", "natural-sciences"], degreesOffered: DEG, notes: ["India's premier engineering institute"] },
  { id: "iisc", name: "Indian Institute of Science", country: "IN", city: "Bengaluru", type: "institute", ownership: "public", founded: 1909, website: "iisc.ac.in", domains: ["engineering", "natural-sciences", "computing"], degreesOffered: DEG, notes: ["Leading Indian research institute"] },
  { id: "tsinghua", name: "Tsinghua University", country: "CN", city: "Beijing", type: "university", ownership: "public", founded: 1911, website: "tsinghua.edu.cn", domains: ["engineering", "computing", "natural-sciences", "architecture"], degreesOffered: DEG, notes: ["China's top university", "Engineering stronghold"] },
  { id: "peking", name: "Peking University", country: "CN", city: "Beijing", type: "university", ownership: "public", founded: 1898, website: "pku.edu.cn", domains: ["natural-sciences", "medicine", "arts-humanities", "social-sciences"], degreesOffered: DEG, notes: ["China's leading comprehensive university"] },
  { id: "tokyo", name: "University of Tokyo", country: "JP", city: "Tokyo", type: "university", ownership: "public", founded: 1877, website: "u-tokyo.ac.jp", domains: ["engineering", "medicine", "natural-sciences", "law"], degreesOffered: DEG, notes: ["Japan's premier university"] },

  // ── Middle East ────────────────────────────────────────────────
  { id: "uae-university", name: "United Arab Emirates University", country: "AE", city: "Al Ain", type: "university", ownership: "public", founded: 1976, website: "uaeu.ac.ae", domains: ["engineering", "medicine", "business", "agriculture"], degreesOffered: DEG, notes: ["UAE's first national university"] },
  { id: "nyuad", name: "New York University Abu Dhabi", country: "AE", city: "Abu Dhabi", type: "university", ownership: "private", founded: 2010, website: "nyuad.nyu.edu", domains: ["engineering", "computing", "business", "arts-humanities"], degreesOffered: DEG, notes: ["Global liberal arts + engineering campus"] },
  { id: "kaust", name: "King Abdullah University of Science & Technology", country: "SA", city: "Thuwal", type: "university", ownership: "private", founded: 2009, website: "kaust.edu.sa", domains: ["engineering", "natural-sciences", "computing"], degreesOffered: DEG, notes: ["Graduate research university in Saudi Arabia"] },
  { id: "kfupm", name: "King Fahd University of Petroleum & Minerals", country: "SA", city: "Dhahran", type: "university", ownership: "public", founded: 1963, website: "kfupm.edu.sa", domains: ["engineering", "natural-sciences", "business"], degreesOffered: DEG, notes: ["Top Saudi university for engineering & petroleum"] },
];

export const COUNTRY_EDUCATION_PROFILES: CountryEducationProfile[] = [
  { country: "NG", name: "Nigeria", region: "West Africa", system: "6-3-3-4: 4-year bachelor (5-6 for medicine/engineering). NUC-regulated.", bachelorDurationYears: 4, bachelorYearLabel: "Level 100/200/300/400", gradingSystem: "5-point GPA; 5.0 = A (Excellent)", academicCalendar: "Two semesters + optional harmattan/rain sessions; runs Oct–Sep", accreditation: "National Universities Commission (NUC)", notes: ["JAMB/UTME + O'Level (WAEC/NECO) for admission", "Polytechnics award ND/HND; universities award degrees"] },
  { country: "GH", name: "Ghana", region: "West Africa", system: "Bologna-aligned; 4-year bachelor (6 for medicine).", bachelorDurationYears: 4, bachelorYearLabel: "Level 100/200/300/400", gradingSystem: "0–100 marks; 4-point GPA in some universities", academicCalendar: "Two semesters; runs Aug–Jun", accreditation: "Ghana Tertiary Education Commission (GTEC)", notes: ["WASSCE + cut-off points for admission", "Universities, polytechnics, colleges of education"] },
  { country: "KE", name: "Kenya", region: "East Africa", system: "4-year bachelor; 6-year medicine.", bachelorDurationYears: 4, bachelorYearLabel: "Year 1–4", gradingSystem: "Percentage + 12-point GPA", academicCalendar: "Three terms / semesters; runs Sep–Aug", accreditation: "Commission for University Education (CUE)", notes: ["KCSE entry requirements", "Growing technical & vocational sector"] },
  { country: "ZA", name: "South Africa", region: "Southern Africa", system: "3-4 year bachelor; honours → master → doctorate.", bachelorDurationYears: 3, bachelorYearLabel: "First/Second/Third Year", gradingSystem: "Percentage + 4-point GPA", academicCalendar: "Two semesters; runs Feb–Nov", accreditation: "Council on Higher Education (CHE) / SAQA", notes: ["Matric/NSC + APS points", "Strong research universities"] },
  { country: "US", name: "United States", region: "North America", system: "4-year bachelor; associate (2yr) → bachelor; credit-based.", bachelorDurationYears: 4, bachelorYearLabel: "Freshman/Sophomore/Junior/Senior", gradingSystem: "4.0 GPA; letter grades A–F", academicCalendar: "Two semesters (Fall/Spring) + Summer; runs Aug–May", accreditation: "Regional accreditors (e.g. MSCHE, WSCUC)", notes: ["SAT/ACT + application essays", "Generous credit transfer", "Liberal-arts breadth requirement"] },
  { country: "GB", name: "United Kingdom", region: "Europe", system: "3-year bachelor (4-year sandwich); 1-year master; 3-4 year PhD.", bachelorDurationYears: 3, bachelorYearLabel: "First/Second/Final Year", gradingSystem: "Classification: First (70%+), 2:1, 2:2, Third; degree classification", academicCalendar: "Two/three terms; runs Sep–Jun", accreditation: "Quality Assurance Agency (QAA); professional bodies", notes: ["A-Levels/IB or foundation year for entry", "Honours degrees with classification", "UCAS application system"] },
  { country: "CA", name: "Canada", region: "North America", system: "4-year bachelor (3-year honours option); credit-based.", bachelorDurationYears: 4, bachelorYearLabel: "First/Second/Third/Fourth Year", gradingSystem: "4.0 GPA; letter grades", academicCalendar: "Two semesters; runs Sep–Apr", accreditation: "Provincial quality councils (e.g. QAC Ontario)", notes: ["High school grades (e.g. OSSD) for admission", "Colleges award diplomas/degrees"] },
  { country: "AU", name: "Australia", region: "Oceania", system: "3-year bachelor (4-year honours); coursework + research degrees.", bachelorDurationYears: 3, bachelorYearLabel: "First/Second/Third Year", gradingSystem: "HD/D/C/P (High Distinction→Pass)", academicCalendar: "Two semesters; runs Feb–Nov", accreditation: "TEQSA", notes: ["ATAR for admission", "Strong international-student sector"] },
  { country: "DE", name: "Germany", region: "Europe", system: "Bologna: 3-4 year bachelor, 1-2 year master.", bachelorDurationYears: 3, bachelorYearLabel: "1.-3. Semester etc.", gradingSystem: "1.0–5.0 scale (1.0 = excellent)", academicCalendar: "Two semesters (Winter/Summer)", accreditation: "Accreditation Council / state", notes: ["Abitur for entry", "Tuition-free public universities", "Strong apprenticeship (Ausbildung) system"] },
  { country: "FR", name: "France", region: "Europe", system: "LMD (Licence-Bac+3, Master-Bac+5, Doctorat-Bac+8).", bachelorDurationYears: 3, bachelorYearLabel: "Licence 1–3", gradingSystem: "0–20 scale (10 = pass)", academicCalendar: "Two semesters; runs Sep–Jun", accreditation: "HCERES / Ministry of Higher Education", notes: ["Baccalauréat for entry", "Grandes Écoles for elite engineering/business"] },
  { country: "IN", name: "India", region: "South Asia", system: "3-4 year bachelor; NEP2020 reforms.", bachelorDurationYears: 4, bachelorYearLabel: "First–Fourth Year", gradingSystem: "10-point CGPA", academicCalendar: "Two semesters; runs Jul–Jun", accreditation: "UGC / AICTE / NAAC", notes: ["Board exams + entrance tests (JEE/NEET)", "IITs for engineering"] },
  { country: "CN", name: "China", region: "East Asia", system: "4-year bachelor; 2-3 year master; 3-4 year PhD.", bachelorDurationYears: 4, bachelorYearLabel: "Year 1–4", gradingSystem: "100-point scale (60 = pass)", academicCalendar: "Two semesters; runs Sep–Jul", accreditation: "Ministry of Education (MOE)", notes: ["Gaokao national exam for entry", "Expanding international programmes"] },
  { country: "JP", name: "Japan", region: "East Asia", system: "4-year bachelor; 2-year master; 3-year PhD.", bachelorDurationYears: 4, bachelorYearLabel: "Year 1–4", gradingSystem: "Grade-point system; letter grades", academicCalendar: "Two semesters; runs Apr–Mar", accreditation: "NIAD-QE", notes: ["General entrance exams (Ippan Nyushi)", "Strong science & technology sector"] },
  { country: "AE", name: "United Arab Emirates", region: "Middle East", system: "4-year bachelor; credit-based; international campuses.", bachelorDurationYears: 4, bachelorYearLabel: "Year 1–4", gradingSystem: "4.0 GPA", academicCalendar: "Two/three semesters; runs Aug–Jun", accreditation: "CAA (Ministry of Education)", notes: ["High school (Tawjihi) + English tests", "Many branch campuses of Western universities"] },
  { country: "SA", name: "Saudi Arabia", region: "Middle East", system: "4-year bachelor (5-6 for medicine/engineering).", bachelorDurationYears: 4, bachelorYearLabel: "Level 1–8", gradingSystem: "5.0 GPA (mostly)", academicCalendar: "Two/three semesters; runs Aug–Jun", accreditation: "NCAAA (Education & Training Evaluation Commission)", notes: ["High school GPA + aptitude tests (Qiyas)", "Generous scholarship system"] },
];

export function universityByCountry(country: string): UniversityRecord[] {
  return UNIVERSITY_DIRECTORY.filter((u) => u.country.toUpperCase() === country.toUpperCase());
}

export function countryProfile(country: string): CountryEducationProfile | undefined {
  return COUNTRY_EDUCATION_PROFILES.find((c) => c.country === country);
}
