/**
 * WINDELS AI VIDEO TRANSFORMER — shared contracts.
 *
 * Natural-language, mask/track-aware selective video editing that preserves
 * original motion/timing. This module defines: the scene understanding
 * structure, structured edit instructions, masks/tracks, transformation jobs,
 * the provider capability registry + route decisions, and quality reports.
 *
 * It deliberately reuses the existing WINDELS storage/job/billing/provider
 * patterns; no parallel auth, billing or storage systems are introduced.
 */

// ── Video understanding (§4–5) ─────────────────────────────────────
export type VtxEntityKind =
  | "person" | "face" | "hair" | "body_part" | "clothing"
  | "hand" | "object_held" | "object" | "vehicle" | "furniture" | "product" | "prop"
  | "environment" | "wall" | "floor" | "ceiling" | "sky" | "background";

export interface VtxEntity {
  id: string;
  kind: VtxEntityKind;
  label: string;
  /** Stable track id that follows the entity across frames. */
  trackId: string;
  confidence: number;
  /** Human-readable spatial cues (left/right/foreground...). */
  position?: string[];
  attributes?: Record<string, string>;
}

export interface VtxMotion {
  type: "static" | "walking" | "hand_movement" | "head_movement" | "talking" | "drinking" | "sitting" | "camera_move" | "other";
  description?: string;
  intensity?: number;
}

export interface VtxCamera {
  shotType?: string;
  angle?: string;
  movement?: string;
  framing?: string;
}

export interface VtxAudio {
  hasSpeech: boolean;
  hasMusic: boolean;
  hasAmbient: boolean;
  durationSec: number;
}

export interface VtxSceneUnderstanding {
  sourceAssetId: string;
  meta: { width: number; height: number; durationSec: number; fps: number; frameCount: number; codec?: string; sizeBytes?: number };
  people: VtxEntity[];
  objects: VtxEntity[];
  environment: VtxEntity[];
  motion: VtxMotion[];
  camera: VtxCamera;
  audio: VtxAudio;
  /** Flat editable-region catalogue derived from entities (§7). */
  regions: VtxRegion[];
  analyzedAt: string;
}

export interface VtxRegion {
  id: string;
  target: EditTarget;
  label: string;
  trackId: string;
  editable: boolean;
}

// ── Edit instructions (§16–17, §20) ───────────────────────────────
export type EditTarget =
  | "identity" | "face" | "hair" | "clothing" | "body" | "hand"
  | "object_held" | "object" | "background" | "environment" | "sky" | "weather"
  | "lighting" | "vehicle" | "prop" | "full_scene" | "add_object" | "remove_object";

export type EditAction = "replace" | "transform" | "restyle" | "add" | "remove" | "adjust";

export interface VtxEdit {
  id: string;
  target: EditTarget;
  action: EditAction;
  value: string;
  /** Entity/region this edit binds to (for held objects, clothing, etc.). */
  entityId?: string;
  trackId?: string;
  referenceAssetIds?: string[];
  strength?: number;
}

export interface VtxPreserve {
  identity: boolean;
  motion: boolean;
  camera: boolean;
  audio: boolean;
  timing: boolean;
}

export interface VtxEditPlan {
  prompt: string;
  edits: VtxEdit[];
  preserve: VtxPreserve;
  style: string;
  /** Detected references the user supplied. */
  references: string[];
}

// ── Masks / tracking (§7–8) ───────────────────────────────────────
export interface VtxMask {
  id: string;
  target: EditTarget;
  regionId: string;
  trackId: string;
  /** Asset id of the animated mask/alpha (when generated by ffmpeg/provider). */
  alphaAssetId?: string;
  frames: number;
  method: "chroma" | "provider_segmentation" | "manual";
}

// ── Jobs (§43–44) ─────────────────────────────────────────────────
export type VtxStage =
  | "QUEUED" | "ANALYZING" | "SEGMENTING" | "TRACKING"
  | "GENERATING" | "COMPOSITING" | "AUDIO_PROCESSING"
  | "QUALITY_CHECK" | "RENDERING" | "COMPLETED" | "FAILED" | "CANCELLED";

export interface VtxJob {
  id: string;
  organizationId: string;
  userId: string;
  projectId: string;
  sourceAssetId: string;
  stage: VtxStage;
  percent: number;
  message: string;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  plan: VtxEditPlan;
  understandingId?: string;
  masks: VtxMask[];
  resultAssetId?: string;
  previewAssetId?: string;
  modelId?: string;
  providerId?: string;
  multiShot: boolean;
  estimatedCredits: number;
  creditsUsed: number;
  estimatedRuntimeSec: number;
  isPreview: boolean;
  previewSeconds?: number;
  qualityReport?: VtxQualityReport;
  versions: VtxVersion[];
  error?: string;
  errorCode?: string;
  retriable?: boolean;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
}

export interface VtxVersion {
  id: string;
  jobId: string;
  label: string;
  assetId: string;
  isPreview: boolean;
  qualityScore?: number;
  createdAt: string;
}

// ── Project (§61) ─────────────────────────────────────────────────
export interface VtxProject {
  id: string;
  organizationId: string;
  userId: string;
  title: string;
  sourceAssetId: string;
  prompt: string;
  understandingId?: string;
  references: string[];
  jobIds: string[];
  latestJobId?: string;
  createdAt: string;
  updatedAt: string;
}

// ── Provider registry / router (§39–41) ───────────────────────────
export interface VtxModelCapability {
  textToVideo: boolean;
  imageToVideo: boolean;
  videoToVideo: boolean;
  videoEditing: boolean;
  objectReplacement: boolean;
  clothingTransformation: boolean;
  backgroundReplacement: boolean;
  characterConsistency: boolean;
  multiReference: boolean;
  audioGeneration: boolean;
  lipSync: boolean;
  maxDurationSec: number;
  maxResolution: string;
  aspectRatios: string[];
}

export interface VtxModelDescriptor {
  providerId: string;
  modelId: string;
  label: string;
  configured: boolean;
  status: "online" | "degraded" | "offline" | "stub";
  tier: "fast" | "standard" | "high_quality";
  costCredits: number;
  estimatedSecPerSec: number;
  capabilities: VtxModelCapability;
}

export interface VtxRouteDecision {
  providerId: string;
  modelId: string;
  label: string;
  reason: string;
  estimatedCredits: number;
  estimatedRuntimeSec: number;
  multiStage: boolean;
  stages: string[];
}

// ── Quality (§38, §65) ────────────────────────────────────────────
export interface VtxQualityCheck {
  id: string;
  status: "pass" | "warn" | "fail";
  score?: number;
  message: string;
}
export interface VtxQualityReport {
  passed: boolean;
  score: number;
  checks: VtxQualityCheck[];
  retried: boolean;
  ranAt: string;
}

export interface VtxDashboard {
  projects: number;
  jobs: number;
  running: number;
  completed: number;
  failed: number;
  models: number;
  modelsConfigured: number;
  creditsUsed: number;
  ffmpegAvailable: boolean;
}
