#!/usr/bin/env node
/**
 * find-orphans.mjs — compute the API's dead-code set.
 *
 * A file is REACHABLE if the module graph can get to it from either
 *   - apps/api/src/index.ts (the server entrypoint), or
 *   - any *.test.ts / *.spec.ts file (tests exercise real code too).
 * Anything else is an ORPHAN: it ships in the repo but nothing loads it.
 *
 * The orphans are bulk-generated service scaffolds from earlier sessions. They
 * contain ~377 type errors, which is why `tsc` could never run end-to-end. We
 * exclude them from the build gate (see apps/api/tsconfig.orphans.json) instead
 * of deleting them, so the code is preserved and can be revived file-by-file.
 *
 * Usage:
 *   node scripts/find-orphans.mjs            # report only
 *   node scripts/find-orphans.mjs --write    # regenerate tsconfig.orphans.json
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const apiRoot = path.resolve(here, '..', 'apps', 'api');
const srcRoot = path.join(apiRoot, 'src');

/** Resolve a relative import specifier to an on-disk .ts file. */
function resolveSpec(spec, fromFile) {
  if (!spec.startsWith('.')) return null; // bare package import
  const base = path.resolve(path.dirname(fromFile), spec).replace(/\.js$/, '');
  for (const cand of [`${base}.ts`, `${base}.tsx`, path.join(base, 'index.ts')]) {
    if (fs.existsSync(cand)) return cand;
  }
  return null;
}

// Matches: from "x" | import("x") | import "x" (side-effect) | require("x")
const IMPORT_RE =
  /(?:\bfrom\s*|\bimport\s*\(\s*|\bimport\s+|\brequire\s*\(\s*)["']([^"']+)["']/g;

const reachable = new Set();
function walk(file) {
  if (reachable.has(file)) return;
  reachable.add(file);
  let src;
  try {
    src = fs.readFileSync(file, 'utf8');
  } catch {
    return;
  }
  for (const m of src.matchAll(IMPORT_RE)) {
    const next = resolveSpec(m[1], file);
    if (next) walk(next);
  }
}

function listFiles(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) listFiles(p, out);
    else if (/\.tsx?$/.test(e.name)) out.push(p);
  }
  return out;
}

const allFiles = listFiles(srcRoot);

// Entrypoint 1: the server.
walk(path.join(srcRoot, 'index.ts'));
// Entrypoint 2: every test file.
for (const f of allFiles) if (/\.(test|spec)\.tsx?$/.test(f)) walk(f);

const orphans = allFiles
  .filter((f) => !reachable.has(f))
  .map((f) => path.relative(apiRoot, f).split(path.sep).join('/'))
  .sort();

console.log(`source files : ${allFiles.length}`);
console.log(`reachable    : ${reachable.size}`);
console.log(`orphans      : ${orphans.length}`);

if (process.argv.includes('--write')) {
  const target = path.join(apiRoot, 'tsconfig.orphans.json');
  const body = {
    $comment: [
      'GENERATED by scripts/find-orphans.mjs --write. Do not edit by hand.',
      'These files are unreachable from src/index.ts and from every test.',
      'They are bulk-generated scaffolds that do not typecheck, so they are kept',
      'out of the build gate. To revive one: fix its types, import it from real',
      'code, then re-run `node scripts/find-orphans.mjs --write`.',
    ].join(' '),
    exclude: ['node_modules', 'dist', 'tests', ...orphans],
  };
  fs.writeFileSync(target, `${JSON.stringify(body, null, 2)}\n`);
  console.log(`wrote ${path.relative(process.cwd(), target)}`);
}
