<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Webhook_dispatcher {
 private $CI; public function __construct(){ $this->CI=&get_instance();$this->CI->load->database();}
 public function dispatch($org,$event,$data){$rows=$this->CI->db->where(array('organization_id'=>$org,'active'=>1))->get('webhook_endpoints')->result_array();$sent=0;foreach($rows as $w){$events=json_decode($w['events'],TRUE)?:array();if(!in_array('*',$events,TRUE)&&!in_array($event,$events,TRUE))continue;$body=json_encode(array('id'=>'evt_'.bin2hex(random_bytes(12)),'event'=>$event,'data'=>$data,'created'=>date('c')),JSON_UNESCAPED_SLASHES);$ts=time();$signature='v1='.hash_hmac('sha256',$ts.'.'.$body,$w['secret']);$id=$this->uuid();$base=array('id'=>$id,'webhook_id'=>$w['id'],'event'=>$event,'payload'=>json_encode($data),'attempts'=>1,'created_at'=>date('Y-m-d H:i:s'));if(!$this->safe_url($w['url'])){$this->CI->db->insert('webhook_deliveries',array_merge($base,array('response_body'=>'Blocked unsafe webhook destination')));$this->CI->db->where('id',$w['id'])->set('failure_count','failure_count+1',FALSE)->update('webhook_endpoints');continue;}list($status,$response,$error)=$this->post($w['url'],$body,$signature,$ts,$event);$ok=$status>=200&&$status<300;$now=date('Y-m-d H:i:s');$this->CI->db->insert('webhook_deliveries',array_merge($base,array('status'=>$status?:NULL,'response_body'=>substr($error?:$response,0,2000),'delivered_at'=>$status?$now:NULL,'next_retry_at'=>$ok?NULL:date('Y-m-d H:i:s',time()+120))));$this->CI->db->where('id',$w['id'])->update('webhook_endpoints',array('last_delivery_at'=>$status?$now:$w['last_delivery_at'],'last_status'=>$status?:NULL,'failure_count'=>$ok?0:$w['failure_count']+1,'updated_at'=>$now));$sent++;}return $sent;}
 public function retry_due($org,$limit=10){$rows=$this->CI->db->select('d.*,w.url,w.secret,w.organization_id')->from('webhook_deliveries d')->join('webhook_endpoints w','w.id=d.webhook_id')->where(array('w.organization_id'=>$org,'w.active'=>1))->where('d.next_retry_at IS NOT NULL',NULL,FALSE)->where('d.next_retry_at <=',date('Y-m-d H:i:s'))->where('d.attempts <',5)->order_by('d.next_retry_at')->limit($limit)->get()->result_array();$done=0;foreach($rows as $r){$payload=json_decode($r['payload'],TRUE)?:array();$body=json_encode(array('id'=>'evt_'.bin2hex(random_bytes(12)),'event'=>$r['event'],'data'=>$payload,'created'=>date('c'),'retryOf'=>$r['id']),JSON_UNESCAPED_SLASHES);$ts=time();$signature='v1='.hash_hmac('sha256',$ts.'.'.$body,$r['secret']);$attempt=(int)$r['attempts']+1;if(!$this->safe_url($r['url'])){$status=0;$response='';$error='Blocked unsafe webhook destination';}else list($status,$response,$error)=$this->post($r['url'],$body,$signature,$ts,$r['event']);$ok=$status>=200&&$status<300;$now=date('Y-m-d H:i:s');$next=$ok||$attempt>=5?NULL:date('Y-m-d H:i:s',time()+min(3600,pow(2,$attempt)*60));$this->CI->db->where('id',$r['id'])->update('webhook_deliveries',array('status'=>$status?:NULL,'response_body'=>substr($error?:$response,0,2000),'attempts'=>$attempt,'delivered_at'=>$status?$now:$r['delivered_at'],'next_retry_at'=>$next));$this->CI->db->where('id',$r['webhook_id'])->update('webhook_endpoints',array('last_delivery_at'=>$status?$now:NULL,'last_status'=>$status?:NULL,'failure_count'=>$ok?0:$attempt,'updated_at'=>$now));$done++;}return $done;}
 private function post($url,$body,$signature,$ts,$event){if(!function_exists('curl_init'))return array(0,'','PHP cURL extension is required for outbound webhooks');$ch=curl_init($url);curl_setopt_array($ch,array(CURLOPT_POST=>TRUE,CURLOPT_POSTFIELDS=>$body,CURLOPT_RETURNTRANSFER=>TRUE,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>10,CURLOPT_FOLLOWLOCATION=>FALSE,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_HTTPHEADER=>array('Content-Type: application/json','User-Agent: Windels-Webhook/1.0','Windels-Signature: '.$signature,'Windels-Timestamp: '.$ts,'Windels-Event: '.$event)));$response=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);return array($status,(string)$response,$error);}
 private function safe_url($url){$p=parse_url($url);if(!$p||!in_array(strtolower($p['scheme']??''),array('http','https'),TRUE)||empty($p['host'])||isset($p['user'])||isset($p['pass']))return FALSE;$host=strtolower($p['host']);if($host==='localhost'||substr($host,-6)==='.local')return FALSE;$ips=gethostbynamel($host)?:array();if(!$ips)return FALSE;foreach($ips as $ip)if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===FALSE)return FALSE;return TRUE;}
 private function uuid(){$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
