/**
 * Session 150 — Life Operating Principles Engine: curated rule catalog,
 * Part II (rules 51–75, "Becoming Unstoppable") and Part III (rules 76–85,
 * Relationship Rules).
 *
 * Same discipline as the Part I seed: practical principles, not absolute
 * laws — each with educational framing and, where absolutism is possible,
 * a considerations note.
 */
import type { LifeRule } from "@windels/shared";

interface RuleSeed {
  n: number;
  part: LifeRule["part"];
  title: string;
  principle: string;
  why: string;
  how: string;
  action: string;
  reflection: string;
  considerations?: string;
  tags?: string[];
}

function rule(r: RuleSeed): LifeRule {
  return {
    id: `lp.r${r.n}`,
    number: r.n,
    part: r.part,
    title: r.title,
    principle: r.principle,
    whyItMatters: r.why,
    howToApply: r.how,
    action: r.action,
    reflectionQuestion: r.reflection,
    considerations: r.considerations,
    tags: r.tags ?? [],
  };
}

/* ════════════════════════════════════════════════════════════════════════════
 * PART II — THE 25 RULES OF BECOMING UNSTOPPABLE (51–75)
 * ════════════════════════════════════════════════════════════════════════════ */

const UNSTOPPABLE: LifeRule[] = [
  rule({
    n: 51,
    part: "unstoppable",
    title: "Wake Up With a Mission",
    principle: "Have something meaningful you are working toward.",
    why: "A mission turns days into chapters of a larger story. Purpose is the engine that keeps you moving when comfort and convenience pull the other way.",
    how: "Define one meaningful goal you are building toward — a skill, a venture, a service, a family goal. Each morning, connect today's tasks to it.",
    action: "Tomorrow morning, write your mission in one sentence before checking anything else.",
    reflection: "What am I working toward that would be worth doing even if no one applauded?",
    tags: ["mission", "purpose", "direction"],
  }),
  rule({
    n: 52,
    part: "unstoppable",
    title: "Move Your Body",
    principle: "Regular physical activity supports physical and mental wellbeing.",
    why: "Movement is medicine with side effects that are almost all positive: mood, energy, sleep, focus, long-term health.",
    how: "Move daily in any form that fits — walking, sports, gym, dancing, farm work. Consistency beats intensity. Make it easy to start and hard to skip.",
    action: "Today, move your body for at least twenty minutes in a way you enjoy.",
    reflection: "How do I feel on days I move versus days I don't?",
    tags: ["exercise", "health", "energy"],
  }),
  rule({
    n: 53,
    part: "unstoppable",
    title: "Drink Enough Water",
    principle: "Maintain healthy hydration according to your individual needs.",
    why: "Dehydration quietly degrades energy, focus and mood. Hydration needs vary by body, climate and activity — the principle is to stay aware, not to hit a magic number.",
    how: "Drink water through the day, especially with meals, in heat and during activity. Let thirst and urine colour guide you. Notice how your energy responds.",
    action: "Today, drink a glass of water now, and one with each meal.",
    reflection: "Am I giving my body the basic resources it needs to run well?",
    tags: ["hydration", "health", "energy"],
  }),
  rule({
    n: 54,
    part: "unstoppable",
    title: "Read Regularly",
    principle: "Give your mind new information every day or week.",
    why: "A mind fed only on repetition stagnates. Regular reading keeps ideas flowing in — the raw material for better thinking and decisions.",
    how: "Set a sustainable rhythm: a few pages daily, a book monthly, articles weekly. Mix depth (books) with breadth (articles, reports). Note what you would use.",
    action: "Today, read something that teaches you one thing you did not know yesterday.",
    reflection: "What did I read this month that changed a decision I made?",
    tags: ["reading", "learning", "ideas"],
  }),
  rule({
    n: 55,
    part: "unstoppable",
    title: "Stay Humble",
    principle: "Never become too successful to learn.",
    why: "Success that ends learning begins declining. The moment you believe you have nothing to learn, the world starts teaching you the hard way.",
    how: "Stay in environments where you are not the expert. Invite criticism from people who will tell you the truth. Revisit fundamentals regularly.",
    action: "Today, ask someone more experienced than you for one piece of advice.",
    reflection: "What have I stopped learning because I thought I had arrived?",
    tags: ["humility", "learning", "success"],
  }),
  rule({
    n: 56,
    part: "unstoppable",
    title: "Learn High-Value Skills",
    principle: "Develop abilities that solve real problems.",
    why: "Skills that solve real problems — for employers, customers, communities — are the ones that create opportunity. Abstract knowledge without application has limited leverage.",
    how: "Ask: what problems do the people I want to serve actually have? Learn the skills that solve them. Prove skill through results, not certificates alone.",
    action: "Today, identify one real problem near you and one skill that would help solve it.",
    reflection: "What problem could I become the person who solves?",
    tags: ["skills", "value", "problem solving"],
  }),
  rule({
    n: 57,
    part: "unstoppable",
    title: "Save Money",
    principle: "Build financial resilience.",
    why: "Resilience is the ability to absorb shocks and keep going. Savings are that ability in financial form — the difference between a setback and a collapse.",
    how: "Save automatically and before spending. Grow the emergency fund, then build toward bigger goals. Small regular amounts compound.",
    action: "Today, move something — anything — into savings.",
    reflection: "What could I withstand today that I could not withstand six months ago?",
    tags: ["saving", "resilience", "finance"],
  }),
  rule({
    n: 58,
    part: "unstoppable",
    title: "Protect Your Peace",
    principle: "Choose carefully what deserves your time and emotional energy.",
    why: "Emotional energy is finite. What you spend it on determines both your mood and your momentum — and much of it is a choice.",
    how: "Audit your inputs: news, people, arguments, content. Cut what drains without informing. Protect a daily stretch of quiet for your own thinking.",
    action: "Today, remove one drain on your emotional energy (a feed, a chat, a habit).",
    reflection: "What am I letting consume my emotional energy that I could simply stop?",
    tags: ["peace", "energy", "focus"],
  }),
  rule({
    n: 59,
    part: "unstoppable",
    title: "Ignore Unproductive Criticism",
    principle: "Listen to useful feedback. Ignore criticism that exists only to destroy.",
    why: "Feedback is a signal; not all signals are worth your attention. Criticism aimed at your growth contains information; criticism aimed at your destruction contains only noise — and sometimes tells you more about the critic.",
    how: "Sort criticism by source and intent: does this person want me to improve, or to lose? Extract the useful fraction from fair critics; disregard the rest without retaliation.",
    action: "Today, take one piece of useful feedback and act on it — and ignore one piece of noise.",
    reflection: "Whose criticism do I currently treat as truth without checking their intent?",
    tags: ["feedback", "criticism", "resilience"],
  }),
  rule({
    n: 60,
    part: "unstoppable",
    title: "Build Before You Brag",
    principle: "Let your work develop before seeking applause.",
    why: "Applause sought early arrives early — and substitutes for the work. Work that matures quietly earns attention that is real and durable.",
    how: "Develop projects to a credible point before publicizing. Celebrate milestones privately or with a small circle. Let results do the announcing.",
    action: "Today, spend the time you would have spent publicizing something — on building it.",
    reflection: "What am I talking about that I should be building instead?",
    tags: ["execution", "humility", "results"],
  }),
  rule({
    n: 61,
    part: "unstoppable",
    title: "Speak With Purpose",
    principle: "Say what needs to be said. Listen before responding.",
    why: "Purposeful speech saves everyone time: it says the needed thing, no more, no less. Listening first ensures the needed thing is actually the right thing.",
    how: "Before speaking, ask: does this need to be said, does it need to be said by me, does it need to be said now? Listen fully, then respond to what was actually said.",
    action: "Today, in your next conversation, listen twice as much as you speak.",
    reflection: "How much of what I say would survive the 'need it, need me, need now' test?",
    tags: ["communication", "listening", "purpose"],
  }),
  rule({
    n: 62,
    part: "unstoppable",
    title: "Forgive Yourself for Past Mistakes",
    principle: "Accept responsibility, learn the lesson, and stop allowing yesterday to control tomorrow.",
    why: "Guilt is a useful alarm, not a permanent resident. Carrying past mistakes into every future decision taxes the present for a debt the past already paid.",
    how: "Take responsibility cleanly (no excuses), extract the lesson, make amends where possible, and then release the shame. Treat yourself the way you would treat a friend who erred.",
    action: "Today, name one past mistake you are still punishing yourself for — and consciously let the lesson stay while the shame goes.",
    reflection: "What would I do differently tomorrow if I stopped carrying yesterday?",
    considerations: "Forgiving yourself is not the same as ignoring harm — real amends and changed behaviour matter, especially where others were hurt.",
    tags: ["forgiveness", "self-compassion", "growth"],
  }),
  rule({
    n: 63,
    part: "unstoppable",
    title: "Help Without Needing Applause",
    principle: "Do good because it is valuable, not merely because people are watching.",
    why: "Help that requires an audience is marketing; help that needs no audience is character. The second builds the person you become when no one is watching.",
    how: "Do one unobserved kindness regularly. Help people who cannot repay you. Notice the difference in how it feels.",
    action: "Today, help someone in a way that no one else will know about.",
    reflection: "When did I last help someone with zero chance of recognition?",
    tags: ["service", "character", "kindness"],
  }),
  rule({
    n: 64,
    part: "unstoppable",
    title: "Trust the Process—but Check the Process",
    principle: "Patience is important, but blindly repeating a broken strategy is not.",
    why: "Process keeps you steady; checking keeps you honest. The two together distinguish persistence from stubbornness.",
    how: "Define what success looks like and review progress against it at set intervals. When the evidence says a strategy is broken, change the strategy — not just the effort level.",
    action: "Today, review one ongoing effort: is the process working, or just familiar?",
    reflection: "Am I patient with a process, or have I stopped checking whether it works?",
    tags: ["process", "evaluation", "adaptability"],
  }),
  rule({
    n: 65,
    part: "unstoppable",
    title: "Keep Trying",
    principle: "Persistence matters, but persistence should include learning and adaptation.",
    why: "Quitting early forfeits what time and iteration would have delivered. But persistence without learning is just repetition of the same mistake at higher cost.",
    how: "Keep the goal; adapt the method. After each attempt, change one variable based on what you learned. Track progress so persistence has direction.",
    action: "Today, make one more attempt at something you have been avoiding — using what you learned last time.",
    reflection: "What would persistence with adaptation achieve that persistence alone cannot?",
    tags: ["persistence", "learning", "resilience"],
  }),
  rule({
    n: 66,
    part: "unstoppable",
    title: "Choose Your Environment Carefully",
    principle: "Your surroundings can influence your habits, expectations, and decisions.",
    why: "Environment is the quiet architect of behaviour: the people, places and tools around you make some choices easy and others hard — without you noticing.",
    how: "Audit your environment: who do you spend time with, what do your spaces reward, what is within reach? Arrange your environment to make good choices the easy ones.",
    action: "Today, change one thing in your environment that makes a good habit easier.",
    reflection: "What is my environment currently making easy that I wish it made hard?",
    tags: ["environment", "habits", "influence"],
  }),
  rule({
    n: 67,
    part: "unstoppable",
    title: "Surround Yourself With People Who Challenge You to Grow",
    principle: "Good relationships can expand your perspective.",
    why: "You become a blend of the people you spend the most time with. People who challenge you — with honesty, standards and examples — quietly raise your ceiling.",
    how: "Seek out people who are where you want to be or who ask you hard questions. Invest in those relationships. Be that person for others too.",
    action: "Today, reach out to one person who challenges you to grow and ask them something real.",
    reflection: "Am I the most ambitious person in my circle, and is that a sign I need new input?",
    tags: ["relationships", "growth", "mentorship"],
  }),
  rule({
    n: 68,
    part: "unstoppable",
    title: "Don't Let One Failure Define You",
    principle: "One event is not your entire story.",
    why: "A single failure, however painful, is a data point — not a verdict on your whole life. Defining yourself by one event blinds you to every other chapter.",
    how: "Separate 'I failed at this' from 'I am a failure'. Write the event into a longer timeline of your life. Take the lesson and keep the next chapter open.",
    action: "Today, write one failure into the longer story of your life — as a chapter, not the ending.",
    reflection: "What would my story look like if I stopped letting one event narrate it?",
    tags: ["failure", "identity", "resilience"],
  }),
  rule({
    n: 69,
    part: "unstoppable",
    title: "Don't Let One Success Define You",
    principle: "Yesterday's achievement does not guarantee tomorrow's.",
    why: "Success is a photograph of one moment; life is a film. Resting on one achievement stops the momentum that produced it — and the world keeps moving.",
    how: "Enjoy achievements briefly, then set the next challenge. Stay in learning mode. Let past success fund future work rather than replace it.",
    action: "Today, name one achievement you are done resting on — and one next step it should fund.",
    reflection: "What am I still coasting on that I achieved years ago?",
    tags: ["success", "humility", "momentum"],
  }),
  rule({
    n: 70,
    part: "unstoppable",
    title: "Compete With Your Previous Self",
    principle: "Measure growth against who you were before.",
    why: "Comparing yourself to others measures the wrong variable — their starting point, luck and timing. Comparing to your past self measures what you control: your own progress.",
    how: "Track a few personal metrics (health, skills, savings, habits) over time. Review quarterly. Celebrate genuine improvement regardless of others' positions.",
    action: "Today, pick one area and write down how you are better than you were a year ago.",
    reflection: "Am I measuring my life by other people's scoreboards?",
    tags: ["growth", "self-comparison", "progress"],
  }),
  rule({
    n: 71,
    part: "unstoppable",
    title: "Make Decisions Based on Long-Term Consequences",
    principle: "Ask what today's decision could create months or years from now.",
    why: "Every decision plants a seed; short-term thinking harvests weeds. The choices that look best today are often the ones that cost most later.",
    how: "Before deciding, project the consequences at 1 month, 1 year, 5 years. Choose the option your future self would thank you for. Automate decisions that are hard in the moment (savings, health) so long-term wins are the default.",
    action: "Today, take one decision and write its likely consequences at one month, one year and five years.",
    reflection: "Which recent decision would my five-years-from-now self have wanted me to change?",
    tags: ["long-term", "decisions", "consequences"],
  }),
  rule({
    n: 72,
    part: "unstoppable",
    title: "Be Reliable",
    principle: "When you say you will do something, make a serious effort to do it.",
    why: "Reliability is the currency of trust in work, family and friendship. The person who can be counted on is the person who gets the opportunities.",
    how: "Only promise what you intend to deliver. Deliver before the deadline, not at it. When you cannot deliver, say so early — early honesty preserves trust.",
    action: "Today, deliver one commitment early or confirm one deadline you might miss.",
    reflection: "If everyone kept promises the way I do, how reliable would the world be?",
    tags: ["reliability", "trust", "character"],
  }),
  rule({
    n: 73,
    part: "unstoppable",
    title: "Respect Other People",
    principle: "Strength does not require humiliation of others.",
    why: "Strength is measured by what it protects and builds, not by who it diminishes. Humiliating others signals insecurity, not power — and it costs you allies.",
    how: "Disagree without disrespecting. Correct privately, praise publicly. Treat service workers, juniors and strangers with the same courtesy as executives.",
    action: "Today, treat one person who cannot help you with full respect.",
    reflection: "Who do I treat differently depending on what they can do for me?",
    tags: ["respect", "dignity", "character"],
  }),
  rule({
    n: 74,
    part: "unstoppable",
    title: "Leave People Better Than You Found Them",
    principle: "Use your knowledge, position, and resources constructively.",
    why: "Every interaction is a chance to add or subtract. People who leave others better — taught, encouraged, helped — compound goodwill and meaning through every relationship.",
    how: "In each interaction, look for the small constructive contribution: information, encouragement, a connection, honest feedback. Give more than you take in the aggregate.",
    action: "Today, leave one person better than you found them — deliberately.",
    reflection: "Do the people I interact with regularly become better for having met me?",
    tags: ["service", "impact", "relationships"],
  }),
  rule({
    n: 75,
    part: "unstoppable",
    title: "Keep Going—but Know When to Change Direction",
    principle: "Quitting a bad strategy is not the same as giving up on your purpose.",
    why: "Purpose is a direction; strategies are routes. Clinging to a dead route while calling it persistence is how good purposes die slowly.",
    how: "Distinguish the goal (keep) from the method (change when evidence demands). Set checkpoints that tell you honestly whether the route works. Change course without changing mission.",
    action: "Today, identify one strategy you have outgrown — and the goal it still serves.",
    reflection: "Am I persistent in my purpose, or just stubborn about one route?",
    tags: ["persistence", "adaptability", "purpose"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * PART III — RELATIONSHIP RULES (76–85)
 * ════════════════════════════════════════════════════════════════════════════ */

const RELATIONSHIPS: LifeRule[] = [
  rule({
    n: 76,
    part: "relationships",
    title: "Listen Before You Judge",
    principle: "You do not know everything about another person's situation.",
    why: "Every judgment made without listening is a guess wearing certainty's clothes. Listening first costs minutes and saves relationships.",
    how: "Before forming a verdict, ask the person for their side — fully. Reflect back what you heard. Judge behaviour after listening, not instead of it.",
    action: "Today, in one conversation, listen completely before offering any judgment.",
    reflection: "Who have I judged without ever hearing their full story?",
    tags: ["listening", "judgment", "empathy"],
  }),
  rule({
    n: 77,
    part: "relationships",
    title: "Communicate Clearly",
    principle: "Do not expect people to understand what you never explained.",
    why: "Unspoken expectations are the most common source of relationship failure. People cannot read minds — and resenting them for it is a self-inflicted wound.",
    how: "State needs, boundaries and disappointments in plain words, early and kindly. Confirm understanding ('does that make sense?'). When something bothers you, say it while it is small.",
    action: "Today, explain one expectation you have been holding silently.",
    reflection: "What am I expecting someone to know that I have never told them?",
    tags: ["communication", "expectations", "honesty"],
  }),
  rule({
    n: 78,
    part: "relationships",
    title: "Respect Boundaries",
    principle: "Your boundaries matter, and other people's boundaries matter too.",
    why: "Boundaries are how people protect their time, energy and dignity. Respecting others' boundaries — and having your own respected — is the basic grammar of trust.",
    how: "Honour stated limits without negotiating them to death. State your own limits calmly and early. When someone crosses yours, say so clearly the first time.",
    action: "Today, honour one boundary someone has set — and state one of your own if needed.",
    reflection: "Whose boundary have I been treating as optional?",
    tags: ["boundaries", "respect", "trust"],
  }),
  rule({
    n: 79,
    part: "relationships",
    title: "Choose Character Over Appearance",
    principle: "People reveal themselves through consistent behavior.",
    why: "Appearance, charm and first impressions are presentation; character is the pattern of behaviour over time. Relationships built on presentation alone collapse when the pattern shows.",
    how: "Watch what people do repeatedly, especially under pressure and with people who cannot help them. Let consistency — not charisma — earn your trust.",
    action: "Today, evaluate one relationship by behaviour patterns rather than impression.",
    reflection: "Who have I trusted for their presentation that their behaviour did not earn?",
    tags: ["character", "trust", "judgment"],
  }),
  rule({
    n: 80,
    part: "relationships",
    title: "Do Not Manipulate People",
    principle: "Build relationships through honesty and mutual respect.",
    why: "Manipulation — guilt, flattery, pressure, deceit — gets short-term compliance and pays for it with long-term trust. Once people see the pattern, the relationship is gone.",
    how: "Ask for what you want directly instead of engineering for it. Give information people can decide with. When you disagree, say so openly.",
    action: "Today, ask for something directly that you would normally try to engineer.",
    reflection: "Where do I use influence on people instead of honesty with them?",
    tags: ["honesty", "manipulation", "integrity"],
  }),
  rule({
    n: 81,
    part: "relationships",
    title: "Do Not Confuse Love With Control",
    principle: "Healthy relationships allow people to retain dignity and individuality.",
    why: "Love builds people up; control shrinks them. Demanding constant access, compliance or sameness is not care — it is possession wearing care's name.",
    how: "Support your person's growth and independence. Let them have friends, opinions and space. Express needs without policing choices.",
    action: "Today, encourage one person's independence instead of managing it.",
    reflection: "Where do I mistake my anxiety for their obligation?",
    tags: ["love", "control", "relationships"],
  }),
  rule({
    n: 82,
    part: "relationships",
    title: "Apologize When You Are Wrong",
    principle: "An apology is not weakness.",
    why: "Refusing to apologize protects an image and destroys a relationship. A genuine apology — specific, unqualified, followed by change — is one of the strongest moves a person can make.",
    how: "Apologize for the specific act, not with 'if I offended anyone'. Skip the excuses; add the correction. Apologize quickly, before pride hardens it into a grudge.",
    action: "Today, make one apology you owe — specific, sincere, without excuses.",
    reflection: "What am I carrying that a genuine apology would release?",
    tags: ["apology", "humility", "relationships"],
  }),
  rule({
    n: 83,
    part: "relationships",
    title: "Forgive Without Forgetting the Lesson",
    principle: "Forgiveness does not require repeating the same mistake.",
    why: "Forgiveness releases the debt of resentment; the lesson protects you from the next injury. The two belong together — forgiveness without learning is a revolving door.",
    how: "When forgiving, name what you learned and what boundary it created. Keep the boundary after the forgiveness. Extend trust again only as rebuilt, not automatically.",
    action: "Today, forgive one past injury — and write down the lesson you keep from it.",
    reflection: "What boundary should my forgiveness have carried that I dropped?",
    tags: ["forgiveness", "boundaries", "learning"],
  }),
  rule({
    n: 84,
    part: "relationships",
    title: "Walk Away From Destructive Relationships When Necessary",
    principle: "Protecting yourself can sometimes require distance.",
    why: "Some relationships are not fixable from your side — abuse, exploitation, chronic betrayal. Staying to 'fix' them can cost your health, safety or future.",
    how: "Distinguish hard relationships (worth work) from destructive ones (work that has not helped). For destructive ones, plan the exit: support, safety, finances, timing. Leave without a campaign.",
    action: "Today, honestly assess one relationship: is it hard, or is it destructive?",
    reflection: "What would I tell a friend in the relationship I am currently tolerating?",
    considerations: "Walking away is a serious step — in cases of abuse or danger, seek professional help and safe support networks before acting.",
    tags: ["boundaries", "safety", "relationships"],
  }),
  rule({
    n: 85,
    part: "relationships",
    title: "Celebrate Other People's Success",
    principle: "Someone else's success does not automatically reduce yours.",
    why: "Envy taxes you for other people's wins and costs you the relationships success brings. Celebrating others builds alliance and goodwill — and models the generosity you want back.",
    how: "Congratulate genuinely and specifically. Share useful praise publicly. Treat others' wins as evidence that the kind of success you want is possible.",
    action: "Today, genuinely celebrate someone else's success — out loud.",
    reflection: "Whose success have I been quietly resenting instead of learning from?",
    tags: ["generosity", "success", "relationships"],
  }),
];

export const LIFE_RULES_PART2: LifeRule[] = [...UNSTOPPABLE, ...RELATIONSHIPS];
