/**
 * Session 150 — Life Operating Principles Engine: curated rule catalog,
 * Part I (rules 1–50): Mindset & Self-Control (1–10), Discipline & Daily
 * Life (11–20), Knowledge & Skills (21–30), Money & Financial Freedom
 * (31–40), Privacy, Strategy & Personal Boundaries (41–50).
 *
 * Every rule is a PRACTICAL LIFE PRINCIPLE, not an absolute law: each
 * carries educational framing (why it matters, how to apply, a reflection
 * question, a concrete daily action) and, where an absolutist reading is
 * possible, a considerations note naming the balance. The spec's own
 * philosophy is embedded: discipline without cruelty, confidence without
 * arrogance, privacy without paranoia, and so on.
 */
import type { LifeRule } from "@windels/shared";

interface RuleSeed {
  n: number;
  part: LifeRule["part"];
  title: string;
  principle: string;
  why: string;
  how: string;
  action: string;
  reflection: string;
  considerations?: string;
  tags?: string[];
}

function rule(r: RuleSeed): LifeRule {
  return {
    id: `lp.r${r.n}`,
    number: r.n,
    part: r.part,
    title: r.title,
    principle: r.principle,
    whyItMatters: r.why,
    howToApply: r.how,
    action: r.action,
    reflectionQuestion: r.reflection,
    considerations: r.considerations,
    tags: r.tags ?? [],
  };
}

/* ════════════════════════════════════════════════════════════════════════════
 * A. MINDSET & SELF-CONTROL (1–10)
 * ════════════════════════════════════════════════════════════════════════════ */

const MINDSET: LifeRule[] = [
  rule({
    n: 1,
    part: "mindset_self_control",
    title: "Stay Alert",
    principle: "Do not assume that bad things cannot happen to you. Stay aware, prepared, humble, and adaptable.",
    why: "Complacency is how people get caught unprepared — by fraud, accidents, market shifts or personal setbacks. Awareness is cheap insurance.",
    how: "Notice your surroundings and your situation. Ask 'what could go wrong here?' before committing. Keep small buffers (time, money, plans) for surprises.",
    action: "Today, identify one risk you have been ignoring and take one small step to prepare for it.",
    reflection: "What am I assuming cannot happen to me — and what would a prepared version of me do about it?",
    tags: ["awareness", "preparedness", "humility"],
  }),
  rule({
    n: 2,
    part: "mindset_self_control",
    title: "Know Your Worth",
    principle: "Do not allow other people's opinions to determine your value.",
    why: "If your self-worth depends on everyone's approval, one harsh opinion can undo years of work. Your value comes from your character and actions, not from votes.",
    how: "Separate feedback (useful information) from verdicts (other people's judgments of your worth). Build a private record of your standards and progress. Seek feedback from people whose judgment you respect.",
    action: "Today, note one criticism you received and decide whether it is information or noise — then act only on the information.",
    reflection: "Whose opinion of me am I carrying that I never actually chose to value?",
    considerations: "Knowing your worth is not the same as ignoring feedback — the strongest version of this principle takes in useful information while keeping the final say about your value.",
    tags: ["self-worth", "approval", "identity"],
  }),
  rule({
    n: 3,
    part: "mindset_self_control",
    title: "Control Your Emotions",
    principle: "Feel your emotions, but do not automatically allow them to make your decisions.",
    why: "Emotions are information, not instructions. Decisions made in anger, fear or euphoria are consistently worse than decisions made after the wave passes.",
    how: "Name the emotion ('I am angry', 'I am scared'). Pause before acting on it — even minutes help. Decide with your values and goals, then let emotion inform, not dictate.",
    action: "Today, when you feel a strong emotion, pause and name it before you respond.",
    reflection: "Which of my recent decisions were made by an emotion that has since passed?",
    tags: ["emotions", "self-control", "decisions"],
  }),
  rule({
    n: 4,
    part: "mindset_self_control",
    title: "Think Before You React",
    principle: "A moment of anger can create consequences that last for years.",
    why: "Reactions are reversible far less often than responses. A word, a resignation, a breakup message — some moments cannot be taken back.",
    how: "Build a pause into high-stakes moments: count, breathe, sleep on it. Ask 'what will I think of this response in a year?' Write, don't send, when hot.",
    action: "Today, before replying to anything that provokes you, wait at least ten minutes.",
    reflection: "What would I do differently if I always responded as my calmest self?",
    tags: ["anger", "response", "consequences"],
  }),
  rule({
    n: 5,
    part: "mindset_self_control",
    title: "Protect Your Peace",
    principle: "Not every argument deserves your attention.",
    why: "Attention is your most limited resource. Engaging with every provocation, drama or bad-faith argument taxes your energy and time — and often gives the provocation exactly what it wanted.",
    how: "Ask before engaging: 'does this conversation need me, and do I need it?' Set response policies (no politics in group chats, no midnight replies). Learn to disengage without contempt.",
    action: "Today, decline one argument that does not deserve your energy — gracefully and without guilt.",
    reflection: "Which recurring arguments cost me the most and give me the least?",
    considerations: "Protecting peace is not the same as avoiding accountability — some arguments matter, and responsibility still requires showing up for the ones that do.",
    tags: ["peace", "attention", "conflict"],
  }),
  rule({
    n: 6,
    part: "mindset_self_control",
    title: "Stay Humble",
    principle: "Success should increase your responsibility, not your arrogance.",
    why: "Success is often a mixture of effort, timing, help and luck. Arrogance blinds you to the factors you did not control — and to the people who helped you.",
    how: "Keep a habit of acknowledging others' contributions. Stay in rooms where you are not the smartest. Let your results speak rather than your self-description.",
    action: "Today, thank someone whose contribution to your success you rarely acknowledge.",
    reflection: "What have I succeeded at that I could not have done alone?",
    tags: ["humility", "success", "gratitude"],
  }),
  rule({
    n: 7,
    part: "mindset_self_control",
    title: "Build Confidence Without Becoming Arrogant",
    principle: "Know what you can do while remaining willing to learn.",
    why: "Confidence lets you act; learning lets you improve. The combination — 'I can do this, and I can still be wrong' — is the foundation of competence.",
    how: "Back your confidence with evidence (past results, preparation). Invite challenge instead of resenting it. Say 'I don't know' comfortably when you don't.",
    action: "Today, state a confident opinion and then actively ask someone to challenge it.",
    reflection: "Where do I confuse confidence with certainty?",
    tags: ["confidence", "learning", "humility"],
  }),
  rule({
    n: 8,
    part: "mindset_self_control",
    title: "Do Not Live for Approval",
    principle: "You do not need everybody to understand your journey.",
    why: "If your direction depends on universal understanding, other people's confusion becomes your prison. Most meaningful journeys look strange from the outside.",
    how: "Decide whose understanding actually matters (a few trusted people, yourself). Communicate your path clearly to those who matter, and let the rest watch or walk away.",
    action: "Today, do one thing aligned with your goals that some people will not understand.",
    reflection: "Whose approval am I currently renting that I could stop paying for?",
    tags: ["approval", "independence", "purpose"],
  }),
  rule({
    n: 9,
    part: "mindset_self_control",
    title: "Learn From Failure",
    principle: "Failure is information. Study what went wrong, make the correction, and continue.",
    why: "Failure is the most honest feedback available — it shows exactly where the gap was between intention and result. Only unexamined failure is wasted.",
    how: "After a failure, ask three questions: what happened, why did it happen, what changes next time? Write the answers down. Make the correction, then continue — the lesson, not the shame, is the point.",
    action: "Today, revisit one past failure and write down the single correction it taught you.",
    reflection: "What did my last failure teach me that success never could?",
    considerations: "Not every failure is a lesson you caused — sometimes the market, luck or other people were decisive. Study what is yours to fix, and don't carry blame that belongs elsewhere.",
    tags: ["failure", "learning", "resilience"],
  }),
  rule({
    n: 10,
    part: "mindset_self_control",
    title: "Never Stop Growing",
    principle: "Your education should not end when school ends.",
    why: "The world changes, and so do the skills that matter. People who keep learning compound their advantage; people who stop get left behind quietly.",
    how: "Give yourself a learning budget: books, courses, mentors, projects. Learn something new each week and something deep each year. Teach what you learn to lock it in.",
    action: "Today, start (or continue) one book, course or project that grows a skill you will need in five years.",
    reflection: "What did I learn this month that changed how I think?",
    tags: ["growth", "lifelong learning", "education"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * B. DISCIPLINE & DAILY LIFE (11–20)
 * ════════════════════════════════════════════════════════════════════════════ */

const DISCIPLINE: LifeRule[] = [
  rule({
    n: 11,
    part: "discipline_daily_life",
    title: "Start Your Day With Intention",
    principle: "Wake up and know what matters most that day.",
    why: "Without intention, the day gets consumed by whoever or whatever is loudest. A clear top priority turns a scattered day into a directed one.",
    how: "The night before or first thing, pick the one task that matters most and schedule it before the noise starts. A short morning review (priorities, appointments, one focus) is enough.",
    action: "Tomorrow morning, write down the one thing that must get done and do it first.",
    reflection: "What did I do yesterday that I did not choose to do?",
    tags: ["intention", "morning", "priorities"],
  }),
  rule({
    n: 12,
    part: "discipline_daily_life",
    title: "Take Care of Your Body",
    principle: "Exercise, rest, eat responsibly, hydrate, and maintain your health.",
    why: "Your body is the platform every goal runs on. Poor sleep, poor food and no movement degrade your thinking, mood and energy faster than any other single factor.",
    how: "Move daily (even a walk counts), sleep consistently, eat mostly real food, and drink water. Get check-ups. Treat health like the infrastructure it is.",
    action: "Today, do one thing for your body that you have been postponing — movement, sleep, water or a check-up.",
    reflection: "What would my goals look like if my body were fully supported?",
    considerations: "Health advice is not one-size-fits-all — for medical conditions, consult qualified professionals rather than applying general rules.",
    tags: ["health", "exercise", "sleep", "nutrition"],
  }),
  rule({
    n: 13,
    part: "discipline_daily_life",
    title: "Read and Learn",
    principle: "Spend part of your day learning something that improves your mind or your future.",
    why: "Reading is the cheapest way to stand on the shoulders of people you will never meet. Thirty minutes a day compounds into a library of knowledge over a year.",
    how: "Carry a book or reading app. Replace dead time (queues, commutes) with pages. Read widely, and take notes on what you would actually use.",
    action: "Today, read for at least twenty minutes — and note one idea you can use.",
    reflection: "What is the best book or article I have read in the past month?",
    tags: ["reading", "learning", "knowledge"],
  }),
  rule({
    n: 14,
    part: "discipline_daily_life",
    title: "Do the Difficult Things",
    principle: "Growth often requires doing what is uncomfortable.",
    why: "The difficult thing is usually the important thing — the hard conversation, the honest accounting, the first attempt. Avoidance feels safe and costs the most.",
    how: "Identify the task you are avoiding; it is usually the one that matters. Break it into a small first step and do that step today. Reward completion, not avoidance.",
    action: "Today, do the one uncomfortable thing you have been postponing — or the first five minutes of it.",
    reflection: "Which important task am I avoiding right now, and what is it actually costing me?",
    tags: ["courage", "discomfort", "growth"],
  }),
  rule({
    n: 15,
    part: "discipline_daily_life",
    title: "Keep Promises to Yourself",
    principle: "Self-discipline begins when your actions match your decisions.",
    why: "Every promise you break to yourself trains you not to believe yourself. Every promise you keep builds self-trust — the foundation of every other discipline.",
    how: "Make small, specific promises ('I will walk for 20 minutes at 6pm'), not vague ones. Write them down. Treat them with the seriousness of promises to others.",
    action: "Today, make one small promise to yourself and keep it.",
    reflection: "What have I promised myself repeatedly and never delivered?",
    tags: ["self-trust", "commitment", "discipline"],
  }),
  rule({
    n: 16,
    part: "discipline_daily_life",
    title: "Avoid Unnecessary Distractions",
    principle: "Protect your attention from things that consume time without creating value.",
    why: "Distractions are engineered to capture attention — and attention is the raw material of every achievement. What you do not watch, you can use.",
    how: "Audit a day: what consumed time without creating value? Remove the worst offenders from reach (notifications off, apps off the home screen). Schedule focus blocks.",
    action: "Today, turn off notifications for one hour and give that hour to one task.",
    reflection: "What would I accomplish if I recovered my most distracting two hours daily?",
    tags: ["focus", "attention", "distraction"],
  }),
  rule({
    n: 17,
    part: "discipline_daily_life",
    title: "Be Consistent",
    principle: "Small actions repeated over time can produce extraordinary results.",
    why: "Consistency converts small actions into compounding results: savings, skills, fitness, trust. The daily drip beats the occasional flood.",
    how: "Choose actions small enough to repeat daily. Track streaks or a simple log. Protect the routine on bad days — a reduced version still counts.",
    action: "Today, do your key habit even in a small form — the streak matters more than the size.",
    reflection: "What would one year of daily consistency on one habit produce for me?",
    tags: ["consistency", "habits", "compounding"],
  }),
  rule({
    n: 18,
    part: "discipline_daily_life",
    title: "Do Not Wait for Motivation",
    principle: "Build systems and habits that continue working when motivation disappears.",
    why: "Motivation is weather — it changes. Systems are climate: they keep producing results regardless. Waiting for motivation is how projects die.",
    how: "Turn goals into routines (fixed time, fixed place, fixed next action). Make starting easy (prepared workspace, small first step). Use reminders and accountability.",
    action: "Today, design one system for a task you currently depend on motivation to do.",
    reflection: "Which of my goals depends on motivation I cannot guarantee?",
    tags: ["systems", "habits", "motivation"],
  }),
  rule({
    n: 19,
    part: "discipline_daily_life",
    title: "Rest Without Giving Up",
    principle: "Rest is not failure. Recovery is part of sustained performance.",
    why: "Sustained effort without recovery degrades judgment, health and results. Rest is how the work becomes sustainable — the opposite of quitting.",
    how: "Schedule rest as deliberately as work (sleep, breaks, days off). When tired, rest fully rather than half-working. Distinguish 'rest' from 'retreat'.",
    action: "Today, take one genuine rest break without guilt — and return to your task after it.",
    reflection: "Do I treat rest as a strategy or as a failure?",
    tags: ["rest", "recovery", "sustainability"],
  }),
  rule({
    n: 20,
    part: "discipline_daily_life",
    title: "Finish What Matters",
    principle: "Do not become addicted to starting things while avoiding completion.",
    why: "Starting feels like progress; finishing is where value is created. A graveyard of half-finished projects produces excitement and nothing else.",
    how: "Before starting something new, close or consciously pause one open thing. Define 'done' before you begin. Finish the last 10% — that is where most of the value lives.",
    action: "Today, finish one small open task completely, or define what 'done' means for your biggest project.",
    reflection: "What would change if I finished half of what I start?",
    tags: ["completion", "follow-through", "focus"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * C. KNOWLEDGE & SKILLS (21–30)
 * ════════════════════════════════════════════════════════════════════════════ */

const KNOWLEDGE: LifeRule[] = [
  rule({
    n: 21,
    part: "knowledge_skills",
    title: "Learn Valuable Skills",
    principle: "Develop skills that create value for yourself and others.",
    why: "Skills are portable assets no one can take from you. The most valuable ones solve real problems — communication, money, technology, trade, care.",
    how: "Pick skills the world pays for and you can sustain interest in. Learn by doing (projects beat courses alone). Revisit and deepen them over time.",
    action: "Today, list your three most valuable skills and one skill worth adding this year.",
    reflection: "What problem can I solve that makes me valuable to others?",
    tags: ["skills", "value", "career"],
  }),
  rule({
    n: 22,
    part: "knowledge_skills",
    title: "Learn How Money Works",
    principle: "Understand income, expenses, saving, debt, investing, taxes, risk, and business.",
    why: "Money literacy is a life skill, not a luxury. People who understand interest, risk and cash flow make calmer, better financial decisions than people who avoid the subject.",
    how: "Learn the basics deliberately: income vs expenses, compound interest, debt costs, emergency funds, tax obligations, risk. Read one good personal-finance book; practice with your own numbers.",
    action: "Today, calculate your actual monthly income and expenses — know the gap.",
    reflection: "What money concept do I avoid because I never learned it?",
    considerations: "Financial decisions are personal and regulated — for large sums, investments or taxes, professional advice is appropriate.",
    tags: ["money", "finance", "financial literacy"],
  }),
  rule({
    n: 23,
    part: "knowledge_skills",
    title: "Learn to Communicate",
    principle: "Your ability to explain, listen, negotiate, and understand people is a powerful life skill.",
    why: "Almost every outcome passes through communication: jobs, deals, relationships, leadership. Clear communicators convert ideas into results.",
    how: "Practice explaining complex things simply. Listen fully before responding. Learn to ask good questions and to disagree without hostility. Write regularly — writing clarifies thinking.",
    action: "Today, explain something you know well to someone else in plain language.",
    reflection: "Where has unclear communication cost me something I wanted?",
    tags: ["communication", "listening", "negotiation"],
  }),
  rule({
    n: 24,
    part: "knowledge_skills",
    title: "Ask Questions",
    principle: "Never be ashamed to say, 'I don't know.'",
    why: "Pretending to know closes the only door to learning. Asking questions is how you get the information everyone else assumes you have.",
    how: "Make 'I don't know — can you explain?' a normal sentence. Ask follow-ups until you actually understand. Write down answers you will need again.",
    action: "Today, ask one question you have been pretending to know the answer to.",
    reflection: "What am I pretending to know that I could simply ask about?",
    tags: ["questions", "curiosity", "humility"],
  }),
  rule({
    n: 25,
    part: "knowledge_skills",
    title: "Learn From People",
    principle: "Everyone you meet can teach you something.",
    why: "Every person carries experience you do not have — a craft, a place, a mistake, a lesson. Curiosity about people is a lifelong curriculum.",
    how: "Ask people about their work, their history and their lessons. Listen for what they learned the hard way. Thank them and apply what fits.",
    action: "Today, have one real conversation with someone and learn one thing from them.",
    reflection: "Who have I spent years around without ever asking the right questions?",
    tags: ["mentorship", "people", "learning"],
  }),
  rule({
    n: 26,
    part: "knowledge_skills",
    title: "Learn From History",
    principle: "Study what happened before you make decisions about what comes next.",
    why: "Patterns repeat: markets, politics, personal finance, organizations. History is the largest dataset of human decisions available — and it is free.",
    how: "Read history around your field (business, money, your country, your industry). Before a big decision, ask 'has this happened before, and what happened next?'",
    action: "Today, read one short history of something you are currently dealing with.",
    reflection: "What pattern in my life is repeating because I never studied its history?",
    tags: ["history", "patterns", "decisions"],
  }),
  rule({
    n: 27,
    part: "knowledge_skills",
    title: "Learn to Think Critically",
    principle: "Do not believe something simply because someone said it confidently.",
    why: "Confidence is not evidence. The most confidently repeated claims are often the least examined — and believing them costs real decisions.",
    how: "Ask: who says this, what do they gain, what evidence exists, what would change my mind? Look for the other side's strongest argument, not its weakest.",
    action: "Today, examine one confident claim you believe — and find one piece of evidence against it.",
    reflection: "What do I believe mainly because someone said it with confidence?",
    tags: ["critical thinking", "evidence", "judgment"],
  }),
  rule({
    n: 28,
    part: "knowledge_skills",
    title: "Verify Important Information",
    principle: "Check evidence before making important decisions.",
    why: "Important decisions — money, health, contracts, big moves — deserve verified information. A single unverified source can cost what verification would have saved.",
    how: "For anything high-stakes, find the primary source or official record. Cross-check at least two independent sources. Check dates: old information is often wrong information.",
    action: "Today, verify one important fact you have been relying on without checking.",
    reflection: "Which of my important decisions rest on information I have never verified?",
    tags: ["verification", "evidence", "decisions"],
  }),
  rule({
    n: 29,
    part: "knowledge_skills",
    title: "Become Adaptable",
    principle: "The world changes. Your ability to learn and adapt is an advantage.",
    why: "Industries, tools and circumstances change faster than ever. Adaptability — the willingness to update skills and strategies — is the skill that protects all others.",
    how: "Practice small adaptations regularly (new tools, new routes, new methods). When the environment shifts, update the plan without abandoning the goal. Keep skills broad enough to pivot.",
    action: "Today, do one familiar task a new way and notice what changes.",
    reflection: "What am I doing the same way purely out of habit that the world has already changed?",
    tags: ["adaptability", "change", "resilience"],
  }),
  rule({
    n: 30,
    part: "knowledge_skills",
    title: "Teach What You Learn",
    principle: "Knowledge becomes more valuable when you use it to help others.",
    why: "Teaching forces clarity, reveals gaps in your own understanding, and multiplies your knowledge's impact. The best way to learn deeply is to explain.",
    how: "Share what you know — explain to colleagues, mentor juniors, write it down. When teaching exposes a gap, go learn the missing piece.",
    action: "Today, teach one thing you know to someone who needs it.",
    reflection: "What do I know that someone around me is struggling to learn?",
    tags: ["teaching", "sharing", "growth"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * D. MONEY & FINANCIAL FREEDOM (31–40)
 * ════════════════════════════════════════════════════════════════════════════ */

const MONEY: LifeRule[] = [
  rule({
    n: 31,
    part: "money_financial_freedom",
    title: "Spend Less Than You Earn",
    principle: "A foundation of financial stability is controlling the gap between income and expenses.",
    why: "The gap between income and spending is where financial freedom is built. Spend more than you earn and the gap grows in the wrong direction — debt, stress, dependence.",
    how: "Track spending for a month to see the real numbers. Build a simple budget that spends less than income by design. Automate the difference into savings.",
    action: "Today, review your last month's spending and identify one category to reduce.",
    reflection: "Where is my money going that does not reflect my priorities?",
    tags: ["budget", "spending", "finance"],
  }),
  rule({
    n: 32,
    part: "money_financial_freedom",
    title: "Save Before You Spend Everything",
    principle: "Build financial reserves for emergencies and future opportunities.",
    why: "Emergencies are certain; their timing is not. Reserves turn emergencies from crises into inconveniences — and let you act when opportunities appear.",
    how: "Pay yourself first: move savings out of reach the moment income arrives. Build an emergency fund (a few months of essential expenses) before other goals. Treat savings as a bill.",
    action: "Today, set up (or add to) an automatic transfer into savings.",
    reflection: "How many months of expenses could I survive without income today?",
    tags: ["saving", "emergency fund", "finance"],
  }),
  rule({
    n: 33,
    part: "money_financial_freedom",
    title: "Avoid Unnecessary Debt",
    principle: "Understand the cost and consequences before borrowing.",
    why: "Debt is a promise about the future — you borrow today's money against tomorrow's income. Unnecessary or expensive debt (consumer loans, high-interest credit) quietly taxes your future.",
    how: "Before borrowing, write down the total cost (interest, fees) and the repayment plan. Borrow for assets or genuine emergencies, rarely for consumption. Pay high-interest debt first.",
    action: "Today, calculate the real total cost of any debt you currently carry.",
    reflection: "Which of my debts was worth its cost — and which was not?",
    considerations: "Some debt — mortgages, student loans, business credit — can be a reasonable tool when understood; the principle is about unnecessary debt, not all debt.",
    tags: ["debt", "interest", "finance"],
  }),
  rule({
    n: 34,
    part: "money_financial_freedom",
    title: "Build Multiple Sources of Value",
    principle: "Develop skills, businesses, investments, or other legitimate sources of income where appropriate.",
    why: "One income stream is one point of failure. Multiple legitimate sources — skills, side work, investments, a business — spread risk and accelerate progress.",
    how: "Start where you are: a marketable skill, a side service, small investments you understand. Reinvest gains. Keep everything lawful, transparent and within your capacity.",
    action: "Today, list your current income sources and one realistic additional source you could build.",
    reflection: "What would happen to my finances if my main income disappeared for six months?",
    considerations: "The phrase 'where appropriate' matters — not everyone needs multiple businesses, and chasing too many streams can dilute the one that matters.",
    tags: ["income", "business", "investing"],
  }),
  rule({
    n: 35,
    part: "money_financial_freedom",
    title: "Do Not Chase Quick Money",
    principle: "If something sounds too good to be true, investigate before committing your money.",
    why: "Guaranteed returns, secret systems and 'act now' pressure are the signature of fraud. Quick-money schemes transfer money from the impatient to the patient.",
    how: "Treat 'too good to be true' as a stop sign, not a green light. Investigate: who is behind it, what is the actual product, what are the risks, is it regulated? Never send money under time pressure.",
    action: "Today, investigate one 'opportunity' you have been tempted by — or write down the warning signs you now recognize.",
    reflection: "What promises have I almost believed because they flattered my desire for speed?",
    tags: ["fraud", "scams", "risk"],
  }),
  rule({
    n: 36,
    part: "money_financial_freedom",
    title: "Protect Your Money",
    principle: "Use secure financial practices and understand financial risks.",
    why: "Money is easier to lose than to earn: theft, fraud, careless deals, unmanaged risk. Security practices are cheap; recovery is expensive.",
    how: "Use strong, unique passwords and two-factor authentication on financial accounts. Review statements regularly. Read contracts before signing. Keep insurance appropriate to your risks.",
    action: "Today, enable two-factor authentication on your most important financial account.",
    reflection: "What would happen to my accounts if my phone or password were compromised?",
    tags: ["security", "risk", "finance"],
  }),
  rule({
    n: 37,
    part: "money_financial_freedom",
    title: "Invest in Yourself",
    principle: "Skills, education, health, relationships, and experience can produce long-term value.",
    why: "You are the asset behind every other asset. Skills, health and relationships compound — and unlike most investments, no one can seize them.",
    how: "Spend deliberately on things that increase your capability: training, tools, health, mentors, experiences. Measure by what you become, not what you consume.",
    action: "Today, spend time or money on one investment in yourself — a skill, a session, a book, a workout.",
    reflection: "What is the highest-return investment I could make in myself this year?",
    tags: ["self-investment", "skills", "growth"],
  }),
  rule({
    n: 38,
    part: "money_financial_freedom",
    title: "Make Your Money Serve Your Goals",
    principle: "Money is a tool. Define what you want it to accomplish.",
    why: "Without a defined purpose, money gets spent on whatever is loudest. With a purpose — security, freedom, family, a cause — every naira or dollar has a job.",
    how: "Write down what money is FOR in your life (protection, goals, people, giving). Align spending and saving with that list. Review quarterly.",
    action: "Today, write down three things your money is supposed to accomplish for you.",
    reflection: "If money were purely a tool, what am I using it to build?",
    tags: ["goals", "money", "purpose"],
  }),
  rule({
    n: 39,
    part: "money_financial_freedom",
    title: "Do Not Compare Your Wealth to Someone Else's",
    principle: "You rarely know another person's full financial situation.",
    why: "What you see of others' wealth is a curated highlight reel — debt, family money and luck are invisible. Comparison distorts your own decisions and peace.",
    how: "Compare yourself only to your past self. Measure by your goals and obligations, not by appearances. Remember that visible wealth is rarely the full picture.",
    action: "Today, notice one comparison that costs you peace — and drop it.",
    reflection: "Whose financial picture am I comparing myself against without knowing the full story?",
    tags: ["comparison", "contentment", "money"],
  }),
  rule({
    n: 40,
    part: "money_financial_freedom",
    title: "Pursue Financial Freedom Responsibly",
    principle: "Build wealth without sacrificing integrity, health, relationships, or lawful conduct.",
    why: "Wealth built on broken trust, health or the law is wealth with a demolition bill attached. The goal is freedom — and freedom includes freedom from guilt and ruin.",
    how: "Set boundaries on what you will not trade for money. Keep promises, pay debts, file taxes honestly. Rebalance when wealth starts costing health or relationships.",
    action: "Today, name one line you will not cross for money — and write it down.",
    reflection: "What would I regret trading for money?",
    tags: ["integrity", "wealth", "balance"],
  }),
];

/* ════════════════════════════════════════════════════════════════════════════
 * E. PRIVACY, STRATEGY & PERSONAL BOUNDARIES (41–50)
 * ════════════════════════════════════════════════════════════════════════════ */

const PRIVACY: LifeRule[] = [
  rule({
    n: 41,
    part: "privacy_strategy_boundaries",
    title: "You Do Not Have to Announce Every Plan",
    principle: "Some goals are better developed before they are publicly announced.",
    why: "Announcements create pressure and invite noise. Early publicizing can drain a project's energy into explanation before it has results.",
    how: "Keep early-stage goals to a small circle. Share when there is something to show or when input is genuinely needed. Let the work create the announcement.",
    action: "Today, identify one goal you will keep quiet about until it has results.",
    reflection: "Do I announce things to build momentum or to borrow approval?",
    tags: ["strategy", "privacy", "focus"],
  }),
  rule({
    n: 42,
    part: "privacy_strategy_boundaries",
    title: "Protect Sensitive Information",
    principle: "Not everyone needs access to your personal, financial, business, or private information.",
    why: "Information is power, and once shared it cannot be unshared. Routine oversharing — of finances, plans, personal details — hands leverage to people who have not earned it.",
    how: "Sort information by sensitivity and share accordingly: personal details with friends, finances with trusted advisers, business plans with partners under agreement. Pause before sharing anything that could embarrass or harm you later.",
    action: "Today, review what you share routinely and identify one thing to stop sharing.",
    reflection: "Who has access to my sensitive information who has never needed it?",
    considerations: "Privacy without paranoia: protecting information is not the same as hiding from everyone — trust and connection still require sharing with the right people.",
    tags: ["privacy", "information", "boundaries"],
  }),
  rule({
    n: 43,
    part: "privacy_strategy_boundaries",
    title: "Do Not Display Every Weakness Publicly",
    principle: "Vulnerability can be healthy, but sensitive information should be shared with people you trust.",
    why: "Vulnerability builds intimacy with people who have earned it — and ammunition with people who have not. The audience for your struggles should be chosen, not random.",
    how: "Choose your audience deliberately: trusted friends, mentors, professionals. Share struggles in contexts designed for support, not in public feeds. Distinguish honesty from exposure.",
    action: "Today, share one real struggle with one trusted person — and not with everyone.",
    reflection: "Which of my vulnerabilities has earned trust, and which has only been displayed?",
    tags: ["vulnerability", "trust", "boundaries"],
  }),
  rule({
    n: 44,
    part: "privacy_strategy_boundaries",
    title: "Let Results Speak",
    principle: "You do not have to prove every plan before it becomes reality.",
    why: "Arguments about what you will do are cheap; evidence of what you did is expensive — and far more persuasive. Proving plans in advance wastes the energy the plan needs.",
    how: "Put the energy into execution, not explanation. When questioned, point to progress rather than promises. Let the finished work answer.",
    action: "Today, choose action over explanation for one plan you keep defending verbally.",
    reflection: "How much time do I spend describing things I have not yet done?",
    tags: ["results", "execution", "humility"],
  }),
  rule({
    n: 45,
    part: "privacy_strategy_boundaries",
    title: "Think Strategically",
    principle: "Before making a major move, consider the consequences, alternatives, risks, and timing.",
    why: "Major moves — jobs, business, money, relationships — have long tails. A few hours of strategic thinking before them can save years of aftermath.",
    how: "Before a big move, write down: what happens if it works, what happens if it fails, what are the alternatives, and is the timing right? Sleep on it. Consult a trusted adviser.",
    action: "Today, apply the four questions (consequences, alternatives, risks, timing) to one decision you are facing.",
    reflection: "What major move did I make without considering its long tail?",
    tags: ["strategy", "planning", "decisions"],
  }),
  rule({
    n: 46,
    part: "privacy_strategy_boundaries",
    title: "Set Boundaries",
    principle: "Learn to say 'no' without hatred and 'yes' without resentment.",
    why: "Unclear boundaries produce a life full of resentful yeses and hostile noes. Clean boundaries protect your time and energy while keeping relationships honest.",
    how: "Decide in advance what you will and will not do. Say no simply and kindly ('I can't take that on'). Say yes only when you mean it. Enforce boundaries calmly, repeatedly.",
    action: "Today, say no to one request you would have resented accepting.",
    reflection: "What am I saying yes to that I actually want to say no to?",
    tags: ["boundaries", "assertiveness", "relationships"],
  }),
  rule({
    n: 47,
    part: "privacy_strategy_boundaries",
    title: "Be Careful Who You Trust",
    principle: "Trust should be built through consistent behavior, not words alone.",
    why: "Words are cheap and persuasive; behavior is evidence. Trusting promises without a track record is how people get exploited financially, emotionally and professionally.",
    how: "Watch what people do with small responsibilities before giving them large ones. Trust incrementally — more access as consistency is demonstrated. Listen when someone shows you who they are.",
    action: "Today, review one relationship and check whether the behavior matches the words.",
    reflection: "Who have I trusted on words alone that I should have trusted on evidence?",
    tags: ["trust", "character", "judgment"],
  }),
  rule({
    n: 48,
    part: "privacy_strategy_boundaries",
    title: "Do Not Confuse Privacy With Isolation",
    principle: "Protecting your privacy does not mean refusing all meaningful relationships.",
    why: "Privacy is about choosing who enters; isolation is about locking everyone out. The first protects you, the second starves you.",
    how: "Keep your close circle small and real. Share deeply with people who have earned it. Guard your information without guarding your heart.",
    action: "Today, reach out to one person you trust and share something real.",
    reflection: "Have I been protecting myself — or hiding from connection?",
    tags: ["privacy", "connection", "balance"],
  }),
  rule({
    n: 49,
    part: "privacy_strategy_boundaries",
    title: "Protect Your Reputation",
    principle: "Your character and credibility can take years to build and moments to damage.",
    why: "Reputation is the shortcut other people use to decide whether to trust you. It is built in years of small consistent actions and lost in one public one.",
    how: "Act as if your behavior will be visible — because increasingly it is. Keep your word, own mistakes, treat people well even when no one is watching (especially then).",
    action: "Today, do one small thing that builds your reputation — quietly.",
    reflection: "What would a year of my behavior say about me to someone who never met me?",
    tags: ["reputation", "integrity", "character"],
  }),
  rule({
    n: 50,
    part: "privacy_strategy_boundaries",
    title: "Keep Your Next Move Purposeful",
    principle: "Privacy should serve strategy—not deception.",
    why: "Strategic privacy protects legitimate work in progress; deception hides intentions others have a right to know. The difference is whether the hidden thing is fair.",
    how: "Be private about plans in development, transparent about commitments and obligations. When privacy would mislead people who rely on you, disclose. Ask: is this protection or concealment?",
    action: "Today, check one thing you keep private: is it protection or concealment?",
    reflection: "Is there anything I keep hidden that people who rely on me deserve to know?",
    tags: ["strategy", "integrity", "privacy"],
  }),
];

export const LIFE_RULES_PART1: LifeRule[] = [...MINDSET, ...DISCIPLINE, ...KNOWLEDGE, ...MONEY, ...PRIVACY];
